### ISSUE TITLE
git rebase does not work

### ISSUE THREAD

**Issue by AlexeySinushkin** [shiftkey/desktop#1005]
### The problem

some non-github repo - rebase does not work

### Release version

Version 3.3.5-linux2 (x64)

### Operating system

kubuntu 22.10

### Steps to reproduce the behavior

some non-github repo
create branch "b" based on branch "a"
switch to branch "a" , fetch, pull -> some new commits appeared
switch back to branch "b" and  rebase to "a" -> message already up to date, there are not new commits etc

if you will reproduce the same using git (console)
git rebase a -> Successfully rebased and updated refs/heads...

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/7188665/887a7d4d-d6e9-4c0e-bdf5-fe0391aa7959)

**Comment by shiftkey** [comment]
> switch back to branch "b" and rebase to "a" -> message already up to date, there are not new commits etc

I don't have the time currently to walk through and try to reproduce this, and I wonder if the logs will have any details about unexpected behaviour and why it ended up here.

Ultimately I don't believe this is OS-specific behaviour, and may need the attention of the main project if it can be reproduced on other OSes.
