### ISSUE TITLE
Authentication Error on Push Origin

### ISSUE THREAD

**Issue by LewisRye** [shiftkey/desktop#1006]
### The problem

Installed Docker Desktop for Ubuntu [Signing in with Docker Desktop for Linux](https://docs.docker.com/desktop/get-started/#signing-in-with-docker-desktop-for-linux), which involved some GPG key stuff, I believe this has messed with the authentication key used by GitHub Desktop, I now cannot push any commits and keep getting an authentication error.
I have tried `sudo apt remove github-desktop` and reinstalling but nothing is working, does anyone know if this is a bug with the app or if I need to sort it on my side? It is worth noting that when I uninstall and reinstall, I am still signed in so I assume it is not uninstalling properly.

### Release version

3.3.8-linux1 (x64)

### Operating system

Ubuntu

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/86835910/18a291de-e0f7-4de0-9bc3-56f1b841aece)

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by LewisRye** [comment]
Log states:
`Error: Although you appear to have the correct authorization credentials, the 'xxxxxxxxx' organization has enabled OAuth App access restrictions...`
There seems to be no way to add the OAuth app to the organisation unblock list, so temporarily I have completely removed the OAuth restriction on my org and the app seems to now be working again...
