### ISSUE TITLE
[BUG] Error "The name org.freedesktop.secrets was not provided by any .service files" while signing in for Github.com

### ISSUE THREAD

**Issue by Krr0ptioN** [shiftkey/desktop#1007]
### The problem

Once I logined and authenticated from browser and went back to the application, I face a pop error which says:

`The name org.freedesktop.secrets was not provided by any .service file`

### Release version

 github-desktop-bin-3.3.8_linux2-1

### Operating system

Linux 6.1.55-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 16:57:15 +0000 x86_64 GNU/Linux

### Steps to reproduce the behavior

1. Settings (Ctrl+Comma)
2. Click on Accounts Section in Settings(or Options) dialog.
3. Click on Sign In to Github.com
4. Click on Continue with Browser
5. <Sign in and authenticate>
6. Once the browser asked you to get back to the browser click and move back to the application
7. End - The pop will show up and says the authentications was not successful because there is no 'serviec' file.

### Log files

error: [ui] Error adding account 'UserName'
Error: The name org.freedesktop.secrets was not provided by any .service files

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/54506351/96e7abf0-7d2e-4831-925a-d72d759c513b)

### Additional context

- Archlinux
- No password manager or Keepassac is installed

**Comment by shiftkey** [comment]
> * No password manager or Keepassac is installed

This is required to store the token in a way that is persisted after closing the app.

**Comment by Krr0ptioN** [comment]
> This is required to store the token in a way that is persisted after closing the app.

![image](https://github.com/shiftkey/desktop/assets/54506351/4899189d-3313-4daf-84bd-4fc73df5675e)
Thanks I installed Keepass although now I am facing this vague error, that I don't know what does it mean by name? or how can I make it activatable, is it refering to Github API and tokens?

**Comment by shiftkey** [comment]
@Krr0ptioN I've not seen that error before. It's probably something configuration-related with the local machine, and Google might yield you more context.

**Comment by Krr0ptioN** [comment]
Yes apparently it has something to do with DBUS. Thanks anyway.
