### ISSUE TITLE
Stuck on "You are being redirected to the authorized application" page

### ISSUE THREAD

**Issue by YukiXXL** [shiftkey/desktop#1011]
### The problem

Everytime after singing-in and re-authorizing the app, I am stuck on a page that simply sas:

You are being redirected to the authorized application.

If your browser does not redirect you back, please visit [this setup page] to continue.

Nothing is happening. No open dialogue pop-up. Clicking the link does nothing.
The link is: x-github-desktop-dev-auth://oauth?code=<numbers/letters>&state=<numbers/letters>

### Release version

3.3.8 Linux RC2

### Operating system

Debian 12 Stable

### Steps to reproduce the behavior

1. Download the "GitHubDesktop-linux-amd64-3.3.8-linux2.deb"
2. Install it.
3. Select "Sign in to Github.com"
4. Authorize the app
5. ...

### Additional context

Using Firefox ESR 115.7. Tried on Firefox 122.0.1 and still the same problem.

Tried using mimetype fix that I found here and didn't help. Tried the AppImage workaround that said to run the app in terminal as 'github-desktop "URL" ' and it didn't help.

**Comment by enobis-dev** [comment]
Same exact problem on EdeavourOS using the AppImage

**Comment by shiftkey** [comment]
> The link is: x-github-desktop-dev-auth://oauth?code=<numbers/letters>&state=<numbers/letters>

This is the schema that the app registers to acknowledge it can handle this protocol handler:

https://github.com/shiftkey/desktop/blob/6768ab50c03a08a3f6d57707c73045fb37d81ac6/script/package-debian.ts#L85-L86

I'm not sure how this is broken for your machine, but I've heard some anecdotes about Firefox having issues that I've not been able to fully understand given this is part of the package. 

> Same exact problem on EdeavourOS using the AppImage

I also configure these the same for AppImage but I don't seem to understand how to resolve these issues from within the package:

https://github.com/shiftkey/desktop/blob/6768ab50c03a08a3f6d57707c73045fb37d81ac6/script/electron-builder-linux.yml#L11-L12

Various folks have suggested workarounds and hacks to the package itself, and if there's a fix that I can incorporate I'd be open to figuring that out.

**Comment by YukiXXL** [comment]
I have found a solution. I needed to associate github.desktop application with 'x-scheme-handler/x-github-desktop-dev-auth'. I used the command:
`xdg-mime default github-desktop.desktop x-scheme-handler/x-github-desktop-dev-auth`
