### ISSUE TITLE
Cannot Fetch origin on repository

### ISSUE THREAD

**Issue by cjanua** [shiftkey/desktop#1012]
### The problem

using gh CLI, I can easily clone, push, and sync; however, on GitHub Desktop I get prompted with an error

`The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.`

GitHub Desktop allows me to see the recent changes; however, actions consistently error out likely do to a bug in determining my access.

### Release version

Version 3.3.8-linux2 (x64)

### Operating system

Arch Linux

### Steps to reproduce the behavior

1. Get invited and legitimately added to work on a collaborated repo
2. Use an Arch Linux Machine with the specified version
3. Successfully clone repo into local repository
4. After a change to the repo from external system, attempt to pull changes via GitHub desktop

### Log files

Error
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### Additional context

GitHub via VSCode works, GH CLI works, git command does not (Kind of expected due to 2F Auth), and GitHub Desktop does not.

**Comment by shiftkey** [comment]
> GitHub Desktop allows me to see the recent changes; however, actions consistently error out likely do to a bug in determining my access.

Is this repository associated with an organization? I suspect you're encountering [this known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization).
