### ISSUE TITLE
Error when sign in

### ISSUE THREAD

**Issue by ronniefuertes** [shiftkey/desktop#1013]
### Laptop

Processors: 12 × AMD Ryzen 5 4600H with Radeon Graphics
Memory: 11,1 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 82EY
System Version: IdeaPad Gaming 3 15ARH05

### Operating System/Distribution

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.6.16-2-MANJARO (64-bit)
Graphics Platform: Wayland

### Installer

Which version of the app?
Github desktop app - latest version
Which installer type?
via terminal: 
- flatpak install flathub io.github.shiftey.Desktop
- pamac build github-desktop-bin 

### What happened?

Popup error message: "The name is not activatable"

I can't recall what version I installed first, but it was arround January 15, 2024.
Everything worked fine and I successfylly loged in, and I clone a repository on my computer.

Last week asked me to update and today I updated the app, and when I wanted to update a file on a repository asked me to log in again and the error appear.
The first time that I installed was via terminal using flatpack.
I remove it, restarted the pc, deleted the github folder and installed again using flatpack. Still the same error.
Then I remove it again, restarted the pc, but this time I installed using pamac. Still the same error.

**Comment by shiftkey** [comment]
> Popup error message: "The name is not activatable"

This is a generic `dbus` error from the keychain, as we need somewhere to store the token received from the browser sign-in flow so it persists after closing the app. I suspect that you may not have a libsecret-compatible package like `gnome-keyring`  installed or configured correctly.

**Comment by ghost** [comment]
Here is the fix:

install `gnome-keyring` via pacman

create `keyrings` folder at `.local/share` it shall look like this `.local/share/keyrings/`

Then just login via GitHub Desktop.

And it's fixed!

@shiftkey You can fix this issue, if you want to.
