### ISSUE TITLE
Cannot sign in on Kali Linux

### ISSUE THREAD

**Issue by maurana** [shiftkey/desktop#1025]
### The problem

Cannot sign in even though it has been authenticated

### Release version

Github Dekstop v3.1.5  > github-desktop_3.1.5-linux2_amd64.deb

### Operating system

Kali Linux 2024.1 amd64

**Comment by shiftkey** [comment]
@maurana I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
