### ISSUE TITLE
webauth failed to share secrets with github desktop

### ISSUE THREAD

**Issue by Enfraguance** [shiftkey/desktop#1032]
### The problem

The name org.freedesktop.secrets was not provided by any .service files ; error when trying to sign into github desktop from steamdeck desktop

### Release version

3.3.6-linux3

### Operating system

6.1.52-valve16-1-neptune-61 (64-bit)

### Steps to reproduce the behavior

go to github desktop, options, accounts, github.com sign in, attempt.

**Comment by Enfraguance** [comment]
I just switched to SmartGit, works fine

**Comment by shiftkey** [comment]
> The name org.freedesktop.secrets was not provided by any .service files ; error when trying to sign into github desktop from steamdeck desktop

This is related to `libsecret` (what the app uses for credential storage) and not being able to find a compatible backend.

I'm not familiar with what SteamDeck has installed, but without a compatible backend like `gnome-keyring` installed this is likely to be an ongoing issue.

**Comment by Enfraguance** [comment]
even after assuring there's a backend, (kwallet) the auth fails after reaching chrome, prompting for launch of github desktop, with no auth, continuing to ask for a sign in

**Comment by Enfraguance** [comment]
I will say, this isnt your fault, this encrption sysyem is a bit buggered on steamdeck and usually if i deny it's pull for encryption it just goes through, but with github desktop, the github desktop application is idle upon hitting cancel, taunting me with the signin būtton i just pressed

**Comment by shiftkey** [comment]
There are log files the app generates which might help understand what the app receives when it is launched, but it's mostly obscured (to avoid leaking secrets into logs). The logs are at `~/.config/GitHub\ Desktop/logs/` on disk and might yield some more context.

**Comment by Enfraguance** [comment]
All you're gonna get from the logs is Kwallet throwing a fuss, trust me.
