### ISSUE TITLE
[Packages] `packages.shiftkey.dev` feeds will be temporarily unavailable April 10-12

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#1044]
Just wanting to add a link here for visibility.

The package feeds that I maintain on `apt.packages.shiftkey.dev` and `rpm.packages.shiftkey.dev` served ~1.3 TB in the past 30 days, most of which was during the last update at the start of the month:

![Image](https://github.com/shiftkey/desktop/assets/359239/011e5f04-f318-47ad-9b8e-70f6d197277d)

Unfortunately this means it's going to exceed the assigned credits in the next day or so, so it will likely not be accessible for a couple of days until the billing cycle ends:

![](https://github.com/shiftkey/desktop/assets/359239/bb4b9382-b8be-49a0-822e-2356d6a4e9d1)

I plan to look into CDN options to better cache this data once the billing period resets and I have time to explore this. An interim fix that I explored required DNS changes which wasn't possible to introduce without breaking what's currently deployed.

Side note: newer users may not be familiar with this, but the previous hosting solution cost about the same as these credits, but only support 50 GB of bandwidth. So it's neat to see this setup squeezes so much more out for the same infrastructure costs.

**Comment by shiftkey** [comment]
This is back live, apologies for the disruption!

**Comment by TIJBRAND1996** [comment]
Open
