### ISSUE TITLE
publish packages to unofficial PPA

### ISSUE THREAD

**Issue by dvergeylen** [shiftkey/desktop#105]
As the release page always provides some `.deb` files, maybe would it be interesting to deploy them to a launchpad ppa?

Automated deploy from travis-ci is a no brainer as it is supported out-of-the-box: [Doc](https://docs.travis-ci.com/user/deployment/launchpad/)

`travis.yml` contains encrypted access tokens (see [here](https://docs.travis-ci.com/user/deployment/launchpad/#encrypting-your-oauth-tokens))

Would be happy to help :smiley:

**Comment by krisives** [comment]
Where are the `debian/control` and similar files located?

**Comment by shiftkey** [comment]
This is interesting, but I'm not sure when I'll get around to it.

> Automated deploy from travis-ci is a no brainer as it is supported out-of-the-box:

I've actually been moving my deployment tasks over to Azure Pipelines, but I'm sure there's alternative ways to achieve the same result.

**Comment by shiftkey** [comment]
I started to look around at alternatives to Travis deploys but I'm a bit confused about the differences between [source packages](https://help.launchpad.net/Packaging/PPA/Uploading) and the `.deb` files that I already generate as part of the build.

I was hoping it would be easy to upload, like [https://packagecloud.io](packagecloud.io) but perhaps I'm missing some context.

**Comment by KaKi87** [comment]
Hello,

Any news on this ?

I would love to have automated updates instead of downloading DEBs.

Thanks !

**Comment by shiftkey** [comment]
@KaKi87 no - the last bunch of research I did didn't yield something I could pull into my build infrastructure. I'm open to proposals if others have things that have worked for them, but I'm not willing to pay for something like PackageCloud currently.

**Comment by KaKi87** [comment]
What about just uploading your DEBs on launchpad.net ? It seems a lot easier.

**Comment by shiftkey** [comment]
> What about just uploading your DEBs on launchpad.net ? It seems a lot easier.

Mostly just being unfamiliar with packaging and having to jump through a lot of hoops:

 - setting up PGP and finishing account creation
 - [converting the DEB into the "source package" that launchpad needs](https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage)
 - [uploading over SFTP or FTP](https://help.launchpad.net/Packaging/PPA/Uploading)
 - doing all of this in a hosted environment (so that releases are not tied to anything machine-specific)

**Comment by jfgordon2** [comment]
@shiftkey I found an article that may help with turning your github hosted solution into a proper repo - https://pmateusz.github.io/linux/2017/06/30/linux-secure-apt-repository.html (setting up a repo in github starts about halfway down the page)

**Comment by shiftkey** [comment]
I've ended up trialling PackageCloud in #278 as it supports both `deb` and `rpm` feeds, and will handle the release packages I'm already generating.

Instructions for setting up your machine are in this comment https://github.com/shiftkey/desktop/issues/278#issuecomment-627642533 which I'll convert some documentation once I've got the corresponding `rpm` instructions ready.

**Comment by shiftkey** [comment]
Instructions for installing are now in the README: https://github.com/shiftkey/desktop#packagecloud

**Comment by KaKi87** [comment]
Hi,

A few months ago, I started developing a tool named [dynapt](https://git.kaki87.net/KaKi87/dynapt) to automatically fetch updates through APT for packages that don't provide an APT repository (or, in this case, an up-to-date one).

As I've been upgrading GitHub Desktop through it for quite some time now, I just published my first pre-release of it, which you can download and set up from [this tutorial](https://gist.github.com/KaKi87/f620788e9901abbfef4978eb7ad358b4).

For GitHub Desktop specifically, replace the following configuration line :

```json
    "apps": []
```

With the following :

```json
    "apps": [
        {
            "name": "GitHub Desktop",
            "github": {
                "repo": "shiftkey/desktop",
                "filter": "*amd64*"
            }
        }
    ]
```

But also change `amd64` to `aarch64` if applicable.

For questions or issues, please submit a comment on the tutorial page.

Thanks

---

cc. @sarim (#1117)
