### ISSUE TITLE
Add certificate issue, upon installing ZScalar

### ISSUE THREAD

**Issue by v-yeddula** [shiftkey/desktop#1052]
### Operating System/Distribution
Ubuntu 22.04

### Installer
Github-Desktop 3.3.12
GitHubDesktop-linux-amd64-3.3.12-linux2.deb

### What happened?
![image](https://github.com/shiftkey/desktop/assets/157407626/7246e6d3-1d5a-4d56-9a5b-540a025f292d)

upon clicking AddCertificate nothing happens. As soon as I open desktop this appears. It used to work fine before, but I started using Zscalar certificate, since it's mandatory, got my browsers running, but not this. Any solutions? would love to get my github-desktop running

**Comment by TIJBRAND1996** [comment]
"/home/nate/Documents/GitHub/Mythora_Dev"

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

I don't believe the "Add certificate" behaviour will change anything currently (it needs Electron APIs to install the certificate which I don't believe have been implemented on Linux) so any context on the behaviour leading up to this error would be great.

Also, is it ZScal*e*r or ZScal*a*r? I'm not familiar with this product so understanding what it's trying to do that's causing issues for Desktop would be great...
