### ISSUE TITLE
Error Object does not exist at path “/org/freedesktop/secrets/collection/login”

### ISSUE THREAD

**Issue by ckir** [shiftkey/desktop#1055]
### The problem

WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.3527
Distro: Ubuntu 24.04
Kernel: 5.15.146.1-microsoft-standard-WSL2

Running from within WSL getting error Object does not exist at path “/org/freedesktop/secrets/collection/login” when trying to connect to Github.com from options.

### Release version

3.3.12-linux2

### Operating system

WSL version: 2.1.5.0

### Steps to reproduce the behavior

1. Go to: File / Options
2. Click: Sign into Github.com
3. Click: Continue with browser
4. See the error

### Screenshots

![dterror](https://github.com/shiftkey/desktop/assets/1611731/7169c4a9-37bd-4ff2-9446-524ba0924712)

**Comment by stevenhowes** [comment]
Install gnome-keyring and then run:

dbus-update-activation-environment --systemd DISPLAY

Before launching. This will then allow the prompt for setting up the keyring password to display.

**Comment by shiftkey** [comment]
Closing this out as secret storage has lots of machine specific quirks that I don't have the bandwidth to support, and thanks @stevenhowes for suggesting the workaround here...

**Comment by rahil627** [comment]
hmmm, dang. I'm running into this on v3.4.3, but it is indeed a weird machine: chromebook linux container (via lxc?)...

whenever I try to push, it asks to auth via browser, comes back, default keyring dialog, then the error. however, the push works, so I can just press cancel early on. ;)

good enough for me, until I learn how to magit! :D
