### ISSUE TITLE
Push - The remote disconnected

### ISSUE THREAD

**Issue by LeoLomardo** [shiftkey/desktop#1065]
### The problem

I have internet and when i try to push, it gives me that error message: "The remote disconnected. Check your Internet connection and try again."

### Release version

Version 3.3.12-linux2 (x64)

### Operating system

Arch Linux

### Steps to reproduce the behavior

1-Go to reppository
2-Click push origin
3-error

### Log files

[2024-05-19.desktop.production.log](https://github.com/shiftkey/desktop/files/15370121/2024-05-19.desktop.production.log)

### Screenshots

![Captura de tela de 2024-05-19 13-47-33](https://github.com/shiftkey/desktop/assets/80079076/0588a4e1-36c8-44ec-b5a6-ed1a45ab33ba)

**Comment by clxadmin** [comment]
I have the same issue since today

**Comment by clxadmin** [comment]
Writing objects: 100% (127/127), 1.74 MiB | 1.99 MiB/s, done.
Total 127 (delta 16), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 5: The remote disconnected. Check your Internet connection and try again.)

**Comment by LeoLomardo** [comment]
> I have the same issue since today
> 

I just made a backup of the most recent files, and cloned the repository again, now its working with no problem

**Comment by shiftkey** [comment]
@clxadmin this appears to be the underlying issue:

```
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
```

This seems to be occurring on `git push`, and it seems like the server is rejecting the request (or a request during this process). I would see if you can push from the command line.

If it fails there try and run the operation with the `GIT_CURL_VERBOSE=2` environment variable set to see if you can flush out more details around why this is being rejected.

**Comment by shiftkey** [comment]
This looks very similar to #1050, please have a read of the details there and see if setting a higher limit for determining when to buffer  during push operations will help:

```
git config http.postBuffer 524288000
```

**Comment by clxadmin** [comment]
> > I have the same issue since today
> 
> I just made a backup of the most recent files, and cloned the repository again, now its working with no problem

I try the same.. deleted whole repository and cloned it new -- still the same issue.
I'm wondering if this is a know issue with repositories from Gitlab ? Can anyone confirm the same ?

**Comment by clxadmin** [comment]
> This looks very similar to #1050, please have a read of the details there and see if setting a higher limit for determining when to buffer during push operations will help:
> 
> ```
> git config http.postBuffer 524288000
> ```

I'm using GitHub Desktop on Mint - the question is how to do this (git config http.postBuffer 524288000) with that?

**Comment by TIJBRAND1996** [comment]
No speak ingles

**Comment by shiftkey** [comment]
> I'm using GitHub Desktop on Mint - the question is how to do this (`git config http.postBuffer 524288000`) with that?

@clxadmin This is the Git command to run within your problem repository, so you'll need the Git command line installed to then `cd` into your repository on disk and then run that command.

**Comment by shiftkey** [comment]
Closing this out due to inactivity, now that we understand the area better
