### ISSUE TITLE
Error logging into GitHub

### ISSUE THREAD

**Issue by j-f1** [shiftkey/desktop#107]
## Description

Logging into GitHub Desktop by entering my username, password, 2FA token directly into the app produces an error message:

> Unknown or unsupported transport 'disabled' for address 'disabled:'

![screenshot 2018-12-05 at 13 50 35](https://user-images.githubusercontent.com/25517624/49536541-c80ddc80-f894-11e8-85d3-7a3bbb5b21d4.png)

## Version

* GitHub Desktop: 1.5.0-linux5

* Operating system: Chrome OS 11151.45.0 (Official Build) beta-channel celes
  (using Chrome OS’s beta Linux support)

## Steps to Reproduce

1. On a Chromebook, go to Settings → Linux (Beta) and enable it.
1. Download the latest `.deb` from GitHub
1. Move it into “Linux Files” in the file manager
1. Open the terminal and run `sudo dpkg -i GitHubDesktop-linux-1.5.0-linux5.deb`
1. Open GitHub Desktop from the launcher (🔍 key)
1. “Sign in with GitHub.com” and try to log in

### Expected Behavior

Successfully logged in

### Actual Behavior

Error message and not logged in.

### Logs

(Where are the logs for Linux stored? That should proably be added to this template)

**Comment by j-f1** [comment]
<details><summary>DevTools trace</summary>

```

error @ install.ts:23
addAccount @ accounts-store.ts:95
async function (async)
addAccount @ accounts-store.ts:78
_addAccount @ app-store.ts:3415
signInStore.onDidAuthenticate @ app-store.ts:363
emitter.on @ sign-in-store.ts:211
e.exports.e.simpleDispatch @ emitter.js:26
e.exports.e.emit @ emitter.js:144
emitAuthenticate @ sign-in-store.ts:197
setTwoFactorOTP @ sign-in-store.ts:586
async function (async)
setTwoFactorOTP @ sign-in-store.ts:539
_setSignInOTP @ app-store.ts:3354
setSignInOTP @ dispatcher.ts:782
onSubmit @ sign-in.tsx:81
onSubmit @ dialog.tsx:330
r @ react-dom.production.min.js:15
[more react-dom stuff here]
```

</details>

Looks like the secure store isn’t working properly.

**Comment by j-f1** [comment]
I eventually got prompted to add a keychain somewhere else and logging in works now.

**Comment by shiftkey** [comment]
> I eventually got prompted to add a keychain somewhere else and logging in works now.

@j-f1 I haven't had a chance to look at how Desktop works in ChromeOS, but if you can provide any additional context about what component is asking you to add details to the keychain that'd be great.

**Comment by j-f1** [comment]
I think the API token is stored in a keychain. When I pushed a commit to GitHub without logging in, I was prompted for my username and auth token. After the push was successful, a system dialog popped up and asked me to create a password for my keychain. I was able to successfully log in after that. The log in with browser option doesn’t work unfortunately.

**Comment by shiftkey** [comment]
> The log in with browser option doesn’t work unfortunately.

Yeah, there's some changes to the installer that need to be added: https://github.com/shiftkey/desktop/issues/10#issuecomment-412350162

**Comment by DanTup** [comment]
@shiftkey this is the other error I mentioned I got right after signing in. As far as I can tell, it hasn't stopping anything from working (though I haven't done much yet).

**Comment by DanTup** [comment]
@shiftkey actually, turns out it didn't work - when I came to push a change, I got an auth failure again. I haven't installed anything additional like gnome-keyring mentioned above - lmk if that's something I should do!

**Comment by shiftkey** [comment]
@DanTup could you try with `gnome-keyring` installed? I haven't made it an explicit dependency for the `deb` package but maybe I should?

https://github.com/shiftkey/desktop/blob/dd9308d94c2a8bea2a4700df9105818800f18e3c/script/electron-builder-linux.yml#L18-L29

EDIT: but if you're trying this in ChromeOS then the problem in #138 remains a blocker on being able to retrieve the token

**Comment by DanTup** [comment]
Isn't #138 only blocking the Signin via browser flow?

Anyway, I installed `gnome-keyring` with `apt get install gnome-keyring` and then set it as the credential helper with `git config --global credential.helper /usr/bin/gnome-keyring`. I then restarted the container and tried to push from GH Desktop and I got a dialog asking me to set a password for a new keyring (it looked terrible, presumably it was gnome-keyring related). I set a password, however GH Desktop still claims to fail to authenticate when I pushed.

I tried signing in from the File->Options entry, and this time it asked for 2FA. That seemed to work well, and in the logs I see:

```
2019-04-07T16:08:31.685Z - info: [ui] [AppStore] adding account DanTup (Danny Tuppeny) to store
2019-04-07T16:08:33.611Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Dart-Code - DanTup (has token)
2019-04-07T16:08:41.861Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Dart-Code - DanTup (has token)
2019-04-07T16:08:42.993Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin foo:foo --progress (took 1.088s)
```

However it then shows this error in the UI (nothing in logs):

![image](https://user-images.githubusercontent.com/1078012/55686357-2983ac00-5958-11e9-8144-3e5c77010f37.png)

This user definitely has access to that organisations repos, so I'm not sure what to make of that. The Options dialog does now show me as logged in.

![Screenshot 2019-04-07 at 17 13 57](https://user-images.githubusercontent.com/1078012/55686398-9008ca00-5958-11e9-8e38-04baead0b7f4.png)

**Comment by DanTup** [comment]
Hmm, seems I can see all other repos, including my private ones, but nothing from the Dart-Code org in the Clone list. When signing in directly in the app (not using the browser flow), is there something you need to do for the organisation repos to show up?

**Comment by shiftkey** [comment]
> Isn't #138 only blocking the Signin via browser flow?

It is, but this issue itself touches on two flow:

 - originally signing in from the browser - this is mostly covered by #138 
 - different sign-in flows (manual username/password to sign in, or basic authentication when the push fails)

Both of these depend on having a working credential store, but how the authentication is setup is different. I'll come back and tidy up these when I have some time.

> then set it as the credential helper with `git config --global credential.helper /usr/bin/gnome-keyring`

This config value is unnecessary, as Desktop uses the `GIT_ASKPASS` environment variable to handle the authentication. This will spawn a Desktop script to read the credential store for details about the given account and remote.

Ensure you've signed in _after_ installing `gnome-keyring` to ensure that your token is persisted. If you  keep an eye on the logs when you then try and do a fetch/push/pull, you'll likely see this message:

https://github.com/shiftkey/desktop/blob/2b74ea83d28b564e2f05410179d8cc77a137631e/app/src/lib/stores/app-store.ts#L4156-L4163

<img width="643" src="https://user-images.githubusercontent.com/359239/55686487-342e4900-5938-11e9-8015-97dea4381a45.png">

**Comment by shiftkey** [comment]
> When signing in directly in the app (not using the browser flow), is there something you need to do for the organisation repos to show up?

I get the feeling this is related to #126 and in particular https://github.com/shiftkey/desktop/issues/126#issuecomment-467459745

**Comment by DanTup** [comment]
> This config value is unnecessary

Ah yeah, I removed it and it still seems to work (well, other than the other bit!).

> I get the feeling this is related to #126 and in particular #126 (comment)

Aha, that sounds likely. I noticed it had "dev" on the end of the name when I revoked it to try forcing a new login. Is there any workaround?

**Comment by shiftkey** [comment]
> Is there any workaround?

Short of building the package with your own OAuth client/secret and trusting those, not currently. https://github.com/shiftkey/desktop/issues/72 has more context on the underlying reasons why, and if we get to a point where we decide to tackle "official support" then we'll revisit it.
