### ISSUE TITLE
Error: The name is not activatable

### ISSUE THREAD

**Issue by isFermi** [shiftkey/desktop#1078]
### The problem

Does not let me sign in through github website, when i authenticate it says Error: The name is not activatable. I am unsure what to do here. 

### Release version

3.3.18-1

### Operating system

Arch Linux

### Steps to reproduce the behavior

1. Click file
2. Options
3. Accounts -> Sign into Github.com
4. Press continue
5. Boom
6. I have tried logging out and back in

### Log files

[100026:0607/191748.048045:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[100026:0607/191748.048061:ERROR:select_file_dialog_linux_portal.cc(285)] Failed to read portal version property
error: [ui] Error adding account 'isFermi'
Error: The name is not activatable

(The error was parsed as 4: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

**Comment by shiftkey** [comment]
> `Error: The name is not activatable`

This is related to secret storage on the local machine, and I wish I had more context on how to fix these as the steps are very setup-specific. See https://github.com/shiftkey/desktop/issues/1020 for some additional context on folks who have dug into the issue from their experiences.
