### ISSUE TITLE
Snap missing from Snapcraft.io?

### ISSUE THREAD

**Issue by dfrankland** [shiftkey/desktop#108]
Is it just me or is the snap pack no longer available on Snapcraft?

https://snapcraft.io/github-desktop

**Comment by shiftkey** [comment]
I'm not sure. I've been on holidays for the last few weeks so I'm not sure what's lurking in my inbox, but a quick glance shows nothing recent that might explain it 🤷‍♂️

**Comment by shiftkey** [comment]
Looks like it's good - something had set the snap to "private" so it wasn't visible in the store. I've flipped it back to "public" now.

**Comment by ipkpjersi** [comment]
@shiftkey Has any progress been made on this? I miss seeing it on the snapcraft store, it was really convenient having it on there.

**Comment by Foorack** [comment]
Any status update on this? Having it on the snapstore would significantly simply installation.

**Comment by shiftkey** [comment]
@ipkpjersi @Foorack please follow along with #116 as I'm blocked on what I can do as a package distributor

**Comment by shiftkey** [comment]
With the help of the Snapcraft team, I've now been able to publicize the app again on the Snapcraft store now the enclosures are migrated. It is recommended to install the `beta` channel currently if you are working from a fresh install.

For existing installs the `edge` channel will remain using the `strict` enclosure for the moment, and refreshing to the latest version there will ask you to install the `beta` channel, which is using the `classic` enclosure and requires a manual upgrade:

<img width="929" src="https://user-images.githubusercontent.com/359239/55685440-adc03a00-592c-11e9-830e-32b6f429831d.png">
