### ISSUE TITLE
AppImage for linux debian amd64 disappear ?

### ISSUE THREAD

**Issue by flagoda** [shiftkey/desktop#1088]
### The problem

Hi, AppImage doesn't exist anymore for linux amd64 ?

### Release version

3.3.18

### Operating system

Xubuntu 22

### Steps to reproduce the behavior

https://github.com/shiftkey/desktop/releases AppImage for linux amd64 doesn't exist anymore

**Comment by shiftkey** [comment]
I would have to dig into what's changed but I think the `x86_64` release is the equivalent architecture e.g. `GitHubDesktop-linux-x86_64-3.3.18-linux1.AppImage`.

This change appears to have occurred back in July 2023 with [`3.2.7`](https://github.com/shiftkey/desktop/releases/tag/release-3.2.7-linux1) when we introduced the ARM architectures:

![Image](https://github.com/user-attachments/assets/0a858781-d7c9-4a61-84f8-a3ed9cb2ea6a)

Please confirm this latest version works for your setup.

**Comment by flagoda** [comment]
I'm really sorry, oversight, on the latest version i have to click on "Show all 20 assets"... (shame on me)
![Capture d’écran_2024-06-27_10-33-36](https://github.com/shiftkey/desktop/assets/28236550/d4a38282-6886-43ae-a453-90ce85195360)
