### ISSUE TITLE
Build for ARM?

### ISSUE THREAD

**Issue by Vacant0mens** [shiftkey/desktop#1091]
### The feature request

A build for ARM processors would be awesome for using on Raspberry Pi's, Windows on ARM (for those who use it), and other ARM-based systems.

### Proposed solution

Git repositories would be easier to access on Raspberry Pi's/on Raspbian and developing on other ARM-based systems (i.e. other ARM-based development boards/mini computers, the upcoming Windows compatibility for ARM architecture, possibly even Risk V -based systems.)

**Comment by shiftkey** [comment]
> A build for ARM processors would be awesome for using on Raspberry Pi's, Windows on ARM (for those who use it), and other ARM-based systems.

ARM32 and ARM64 build have been available since [3.2.7](https://github.com/shiftkey/desktop/releases/tag/release-3.2.7-linux1) - please check out the latest releases https://github.com/shiftkey/desktop/releases

**Comment by Vacant0mens** [comment]
Then could someone update the documentation to show the options for how those can get installed?
The "Install via package manager" section only shows examples for Debian and RedHat. I tried the same process on Raspbian, and it said there wasn't a package available for Arm64.

**Comment by Vacant0mens** [comment]
```
Hit:5 https://apt.packages.shiftkey.dev/ubuntu any InRelease
...
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository
'https://apt.packages.shiftkey.dev/ubuntu any InRelease' doesn't support architecture 'arm64'
```
@shiftkey Is there an apt repository for the Arm builds?

**Comment by shiftkey** [comment]
Not currently, as it requires me rejigging how the package feed is configured.

https://github.com/shiftkey/desktop/issues/1004 is tracking that request.
