### ISSUE TITLE
Apt key file not downloadable

### ISSUE THREAD

**Issue by punk-t** [shiftkey/desktop#1099]
### Operating System/Distribution

Which distribution of Linux are you using?
Mint 21.3

### Installer

Which version of the app?
itHubDesktop-linux-amd64-3.4.2-linux1.deb

Which installer type?
*.deb package

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.
When following install instructions one have to visit/wget https://apt.packages.shiftkey.dev/ in order to get gpg.key. This doesn't work due to HTTPS certificate issue (wrong DNS names). Since the server has HSTS enabled users cannot make or add an exception to this.

To reproduce:
  - visit https://apt.packages.shiftkey.dev/ in any browser
  - see browser error

or: 
  - try `wget -o - https://apt.packages.shiftkey.dev/gpg.key`
  - see warning

----

This is not really an installer problem itself, but I had no other idea issuing that, sorry :)

**Comment by shiftkey** [comment]
This should be working again:

![Image](https://github.com/user-attachments/assets/a5de579e-e353-4e1f-9aee-23a7a1fec570)

**Comment by punk-t** [comment]
cofirmed :)
Thank you
