### ISSUE TITLE
it works very slowly

### ISSUE THREAD

**Issue by malik233222** [shiftkey/desktop#1100]
### The problem

fetching takes 3-5 minutes 

### Release version

2.9.0

### Operating system

Ubuntu

**Comment by shiftkey** [comment]
> 2.9.0

This release is from mid-2021. Please update to something more recent.

> ### Log files
> _No response_

I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
