### ISSUE TITLE
"Unable to locate Git" with Flatpak installation

### ISSUE THREAD

**Issue by AlexanderRitter02** [shiftkey/desktop#1103]
### Operating System/Distribution

Linux Mint 21.3

### Installer

Which version of the app?
3.3.18-linux1 (x64)

Which installer type?
Flatpak from Mint Software store

### What happened?

When trying to open the Gnome Terminal using "Repository > Open in GNOME Terminal" I get the following dialog popup:
> **Unable to locate Git**
> We were unable to locate Git on your system. This means you won't be able to execute any Git commands in the command prompt.
> To help you get Git installed and configured for your operating system, we have some external resources available.

Git is installed and available in my terminal:
```
git --version
git version 2.34.1
```
I suspect this may be because of Flatpak isolations and whatever it does, so I'll just use the APT package feeds. I have no clue about how to configure Flatpaks properly, but maybe someone here can throw in his advice or experience installing Github Desktop as a Flatpak.
Since this issue didn't seem to be reported before, I thought I may as well be the first one, so a solution can be presented for others that might search.

**Comment by shiftkey** [comment]
I think https://github.com/flathub/io.github.shiftey.Desktop/issues/255 is what you're interested in.
