### ISSUE TITLE
Stupid question, But. What port does this application use for outbound pushes?

### ISSUE THREAD

**Issue by TheRealFame** [shiftkey/desktop#1104]
### Operating System/Distribution

Which distribution of Linux are you using?
Zorin-OS
### Installer
.deb (Latest Release.)
### What happened?
Cannot push to repo's on my signed in account. With speculation being. It is not whitelisted by my firewall.

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by TheRealFame** [comment]
> I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

It seems to have been that i shouldn't have used git credential manager 😅

**Comment by shiftkey** [comment]
Closing this out as I'm not sure what's actionable here. If there's anything else to add to help troubleshoot please open a fresh issue.
