### ISSUE TITLE
Shiftkey apt repo broken 

### ISSUE THREAD

**Issue by itiligent** [shiftkey/desktop#1124]
### The problem

The shiftkey apt repo is recently broken.
In just the past few days running apt update gives :
`Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 13.107.246.31 443]`

It is also no longer possible to download th gpg key to set up a new apt based install. Browsing to https://apt.packages.shiftkey.dev is blocked due to certificate errors.

 

### Release version

any

### Operating system

Debian

### Steps to reproduce the behavior

sudo apt update with the shiftkey repo configured
or
browse to https://apt.packages.shiftkey.dev
or 
try to install the gpg key
`wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/shiftkey-packages.gpg > /dev/null`

### Log files

n/a

### Screenshots

n/a

### Additional context

n/a

**Comment by DAK404** [comment]
Same thing here, but instead of `apt`, its `rpm` for me.

Shiftkey said in #1109 (which was opened in august):

> Closing as duplicate of https://github.com/shiftkey/desktop/issues/1062
>
> This is working now, but I'll use that issue to do a brain-dump when I have bandwidth.

**Comment by kitswas** [comment]
Some more info for diagnosis.

The certificate is not valid for apt.packages.shiftkey.dev.  
The certificate is only valid for the following names: *.azureedge.net, *.media.microsoftstream.com, *.origin.mediaservices.windows.net, *.streaming.mediaservices.windows.net

> https://apt.packages.shiftkey.dev/ubuntu
> 
> Unable to communicate securely with peer: requested domain name does not match the server’s certificate.
> 
> HTTP Strict Transport Security: true
> HTTP Public Key Pinning: false
>

**Comment by shiftkey** [comment]
This has been restored. #1062 is the tracking the underlying issues (bandwidth used -> credits consumed -> services suspended)
