### ISSUE TITLE
Cloning Problem

### ISSUE THREAD

**Issue by adil-2bx** [shiftkey/desktop#1136]
### The problem

I can not seem to clone repositories from the internet, it is very irritating.

### Release version

Version 3.3.12-linux2 (x64)

### Operating system

Ubuntu 24.04.1 LTS

### Steps to reproduce the behavior

Install Github Desktop on Ubuntu

Click clone a repo from the internet,

Nothing shows up

### Screenshots

![Screenshot from 2024-09-30 10-02-54](https://github.com/user-attachments/assets/7b17a690-f6fd-4a40-b5c6-41c85517b8c4)

**Comment by shiftkey** [comment]
https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

See https://github.com/shiftkey/desktop/issues/72 for more context
