### ISSUE TITLE
My files are not visible 

### ISSUE THREAD

**Issue by Bhumika-00** [shiftkey/desktop#1139]
### The problem

all the repo are dissappear b ut when i try to clone them it shows non empty folder

### Release version

latest

### Operating system

linux ubuntu

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
