### ISSUE TITLE
menu bar in linux

### ISSUE THREAD

**Issue by kerolloz** [shiftkey/desktop#114]
## Version

* GitHub Desktop: GitHubDesktop-linux-1.5.1-linux2.deb

* Operating system: Ubuntu 18.10

### Expected Behavior

menu bar doesn't seem to be working properly

### Actual Behavior

menu bar should appear with the names for each menu

## Additional Information

![image](https://user-images.githubusercontent.com/36763164/50730208-56a1a200-1150-11e9-8137-384148fc8791.png)

### Logs

I have no idea how to access logs in linux!

**Comment by vitalkanev** [comment]
I believe this is an issue with the _Yaru_ theme. See https://github.com/ubuntu/yaru/issues/969

**Comment by kerolloz** [comment]
@vitalkanev 
Okay this solves the issue when I change the theme to _Yaru Dark_. but I really like the light one.

**Comment by shiftkey** [comment]
@kerolloz thanks for the feedback. I actually think switching to use the in-app menu that Windows supports here is the best thing to do here.

Here's an example of it in action:

<img width="1286" src="https://user-images.githubusercontent.com/359239/50736784-fd5d6100-1197-11e9-8ba6-ea454d2e494b.png">

With this change we should make it a chromeless window, but maybe that's not the best idea.

**Comment by kerolloz** [comment]
@shiftkey I'm sorry. I didn't get what Windows has to do with my Ubuntu. 
> we should make it a chromeless window

How would that help me fix my problem?

**Comment by shiftkey** [comment]
@kerolloz it would address the problem by not using the OS default menu (it would also blend in nicer on OSes with light themes)

**Comment by kerolloz** [comment]
@shiftkey Thanks, I got it. 
Does that have to do with Electron(or its version)? :electron:
cause I got the same issue with Atom! :atom:
but surprisingly Slack is working properly :smiley:.

**Comment by shiftkey** [comment]
> Does that have to do with Electron(or its version)?

It's related to Electron and it trying to show a default menu that fits with the OS theme. https://github.com/electron/electron/pull/15878 seems to be the fix but I think it's only just made it into `4.0.1` - maybe it'll be backported to earlier versions in time.

> but surprisingly Slack is working properly 😃

I'm not sure what Slack is doing here - I haven't tested it out on Linux.
