### ISSUE TITLE
allow to override the open in the browser url

### ISSUE THREAD

**Issue by mtariqsajid** [shiftkey/desktop#1144]
### The feature request

If the Git repository is hosted outside of GitHub, the "Open in Browser" feature is disabled. To improve user experience, consider allowing users to manually set the browser URL. This will make it easier for them to view the repository directly.

### Proposed solution

Allow users to override the repository URL in File -> Options.

**Comment by shiftkey** [comment]
This is probably something worth talking about with the upstream project, as I'm not interested in maintenance of features that are scoped specifically to the Linux ecosystem.

It likely needs some thought about the design and how this would work within the application, but I fear it's something that may not fit the workflows that they want the Desktop client to support...
