### ISSUE TITLE
Linux GitHub desktop 3.4.3 -  at login "user interaction failed"

### ISSUE THREAD

**Issue by kcnypmek** [shiftkey/desktop#1146]
### The problem

login at website with my passkey. Allow desktop application
ERROR MESSAGE : "user interaction failed"

### Release version

3.4.3

### Operating system

Linux Debian 12

### Steps to reproduce the behavior

1. Open Github desktop app
2. Go to Options/Accounts
3. Click on button " Sign into GitHub.com"
4. Open web browser Chrome
5. Sign in at github.com - succeeded
6. return to Github desktop app
7. see error "user interaction failed"

### Screenshots

![login_website](https://github.com/user-attachments/assets/3d5ae6db-8004-4984-a2dc-3ba97322a6c8)
![error_github_desktop](https://github.com/user-attachments/assets/514c60bf-fcf2-4bc6-9841-0d74dc51d753)

**Comment by shiftkey** [comment]
This message is often related to keychain setup issues, but sadly I don't have much bandwidth these days to support troubleshooting each situation.

Some previous issues to look at:

 - https://github.com/shiftkey/desktop/issues/702#issuecomment-1105478800
 - https://github.com/shiftkey/desktop/issues/759#issuecomment-1493969877

**Comment by lorods** [comment]
> ### The problem
> 
> login at website with my passkey. Allow desktop application ERROR MESSAGE : "user interaction failed"
> ### Release version
> 
> 3.4.3
> ### Operating system
> 
> Linux Debian 12
> ### Steps to reproduce the behavior
> 
>     1. Open Github desktop app
> 
>     2. Go to Options/Accounts
> 
>     3. Click on button " Sign into GitHub.com"
> 
>     4. Open web browser Chrome
> 
>     5. Sign in at github.com - succeeded
> 
>     6. return to Github desktop app
> 
>     7. see error "user interaction failed"
> 
> 
> ### Log files
> 
> _No response_
> ### Screenshots
> 
> ![login_website](https://github.com/user-attachments/assets/3d5ae6db-8004-4984-a2dc-3ba97322a6c8) ![error_github_desktop](https://github.com/user-attachments/assets/514c60bf-fcf2-4bc6-9841-0d74dc51d753)
> ### Additional context
> 
> _No response_

Are you using KWallet?
