### ISSUE TITLE
Arch Linux installer support?

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#115]
The ways to package this are explained here: https://github.com/immackay/github-desktop-aur/pull/4#issuecomment-450646833

But I've got no clue how to properly distribute it. Thoughts @immackay?

**Comment by immackay** [comment]
I think we could merge `github-desktop-bin` and `github-desktop`, then have the PKGBUILD for that package point to the package which I assume would be on the releases page of this repository? I believe with Travis CI we could also have the PKGBUILD/.SRCINFO updated automatically through use of a SSH key.

After having support from GitHub for a while, it may be worthwhile to see if an Arch Trusted User would be willing to take on maintenance of the package. This would move the package from the AUR to the [Community] repository.

**Comment by heavysink** [comment]
Hi,
I am a maintainer of ArchlinuxCN and I have included both github-desktop and github-desktop-git in Archlinuxcn repository. An automatic buildbot will watch the release and automatically build it. To simply install, you can follow the instruction of 

https://wiki.archlinux.org/index.php/Unofficial_user_repositories#archlinuxcn

and just do

pacman -S github-desktop

The PKGBUILD is here, directly from AUR, added dependency on openssl-1.0 on the error given by extra-x86_64-build of lacking the dependencies.

https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/github-desktop

**Comment by shiftkey** [comment]
Closing this out as I'd prefer to contribute to https://github.com/immackay/github-desktop-aur whenever new releases are available, e.g. https://github.com/immackay/github-desktop-aur/pull/6

**Comment by insign** [comment]
I'm a lil bit confuse about what is the right AUR... github-desktop or github-desktop-bin?

**Comment by shiftkey** [comment]
`github-desktop` is built from source, `github-desktop-bin` is derived from the Debian package (to save on building from scratch). Both are valid and up-to-date as of today...
