### ISSUE TITLE
Github Desktop No Longer Provides Authentication When Using Git in the Terminal

### ISSUE THREAD

**Issue by EliasTDam** [shiftkey/desktop#1154]
### The problem

When trying to use either "git clone xxxx" or "vcs import" I get prompted for a login to Github. I really appreciated that Github Desktop used to fix that in the background for me, but suddenly it no longer works. I have tried signing out and in again of the Desktop application, but with no success.

### Release version

Version 3.3.12-linux2 (x64)

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

Unsure. Happened for the first time today.

### Log files

[2024-11-07.desktop..log](https://github.com/user-attachments/files/17664385/2024-11-07.desktop.log)

**Comment by shiftkey** [comment]
Can you share a screenshot of the prompt you see here? GitHub Desktop shouldn't be integrating with the command line `git` that a user has installed (a decision made back in 2017 https://github.com/desktop/desktop/issues/340) so I'm curious which tool you're seeing here...
