### ISSUE TITLE
All uses xwayland even tho its running on a wayland system

### ISSUE THREAD

**Issue by Twig6943** [shiftkey/desktop#1166]
### The problem

https://github.com/desktop/desktop/issues/19570

### Release version

latest

### Operating system

linux

### Steps to reproduce the behavior

.

### Screenshots

 .

### Additional context

.

**Comment by shiftkey** [comment]
Have you used the opt-in behaviour for Wayland? It's not enabled by default currently because I've not looked into how to do that:

```
github-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by Twig6943** [comment]
> Have you used the opt-in behaviour for Wayland? It's not enabled by default currently because I've not looked into how to do that:
> 
> ```
> github-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland
> ```

Yea I have I've made this issue cuz its not enabled by default. Just put this flag `--ozone-platform-hint=auto` to the .desktop file and it should work (talking about the flatpak pkg) 

Similiar issue:
https://github.com/flathub/com.heroicgameslauncher.hgl/pull/171
