### ISSUE TITLE
Package feed outdated

### ISSUE THREAD

**Issue by YukiXXL** [shiftkey/desktop#1170]
### The problem

Using the package feed shows outdated version in the Package Manager. It is version 3.3.12-linux2 while the latest available is 3.4.8 Linux RC1.

### Release version

-

### Operating system

Linux Mint 22

### Steps to reproduce the behavior

1. Add Debian/Ubuntu package feed.
2. Do "sudo apt update".
3. Search for the packages and check the version ( I am using Synaptic Package Manager).

**Comment by shiftkey** [comment]
Duplicate of #1117
