### ISSUE TITLE
Sprache von github desktop auf deutsch einstellen

### ISSUE THREAD

**Issue by Raihir** [shiftkey/desktop#1173]
Raspberry 5

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

Version 3.4.8

Provide as much detail as possible. Error messages or output are extremely useful.

Hallo, wo kann ich die Sprache auf deutsch einstellen?
Danke

**Comment by shiftkey** [comment]
To quote from the upstream project:

> At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
