### ISSUE TITLE
[Wayland] GPU error 8704 on app startup, unable to connect to dbus

### ISSUE THREAD

**Issue by AAM1075** [shiftkey/desktop#1177]
### The problem

Github Desktop has stopped launching properly under Wayland (still works just fine with X11 on the same machine). No window appears but there is an icon on the taskbar (clicking the icon does nothing). When the app starts, I get the following errors in the console (in order):
* `[2:1218/234944.495683:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`
* `LaunchProcess: failed to execvp: xdg-settings`
* `[54:1218/234944.817475:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT`
* `[54:1218/234944.817548:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ`
* `[54:1218/234944.817608:ERROR:shared_image_factory.cc(999)] CreateSharedImage: could not create backing.`
* `[54:1218/234944.817704:ERROR:shared_image_factory.cc(765)] DestroySharedImage: Could not find shared image mailbox`
* `[54:1218/234944.817790:ERROR:gpu_service_impl.cc(1124)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.`
* `[2:1218/234356.689364:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=8704`

These errors are thrown three times before it gives up and hangs. These errors also persist after several restarts/reinstalls.

**-- EDIT --**
I forgot to mention in the original message that launching from the pinned taskbar icon results in the same issue. It's link is configured to run `run --branch=stable --arch=x86_64 --command=start-github-desktop --file-forwarding io.github.shiftey.Desktop @@u %U @@`.

### Release version

3.4.8-linux1

### Operating system

Kubuntu 24.04

### Steps to reproduce the behavior

1. Install via flatpak: `flatpak install flathub io.github.shiftey.Desktop`
2. Run Github Desktop in a terminal using either of the following commands: `flatpak run io.github.shiftey.Desktop --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`, `flatpak run io.github.shiftey.Desktop`

3. Restart the computer
4. Observe the error

### Log files

I didn't find any log files in `$HOME/.var/app/io.github.shiftey.Desktop/config/GitHub\ Desktop/logs/`.

### Screenshots

Console output:
![image](https://github.com/user-attachments/assets/90c24b22-fecf-45a0-aae0-a3ee788d8e5f)

Taskbar icon:
![image](https://github.com/user-attachments/assets/d58ce29b-3be2-4419-b6cc-7648ee85588e)

### Additional context

I haven't had this problem with any other Electron applications, even discord (mostly) works just fine. I'm thinking a recent Kubuntu update may have broken something. I've tried it on another computer that is also running the same OS, and the problem persists (both systems are up-to-date and had linux installed around the same time).

**Comment by shiftkey** [comment]
https://github.com/flathub/io.github.shiftey.Desktop/ currently handles the Flatpak packages, please report this there
