### ISSUE TITLE
authorization looping between chrome and githubdesktop

### ISSUE THREAD

**Issue by buffalobillhuang** [shiftkey/desktop#1180]
### The problem

Stuck at authorization step in githubdesktop, it jumps to chrome, and chrome with signed in github.com, prompts back, and it jumps to chrome....

### Release version

3.3.12 linux2(x64)

### Operating system

Linux p1ubuntu 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by buffalobillhuang** [comment]
after apt update and apt upgrade, this problem disappears. Thx!

**Comment by buffalobillhuang** [comment]
Therefore closing it now.
