### ISSUE TITLE
Link in `Merge branch 'master' of LINK` does not link right.

### ISSUE THREAD

**Issue by 9p4** [shiftkey/desktop#119]
## Version

* GitHub Desktop: 1.5.1linux2

* Operating system: Linux fibonacci-4k 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

## Steps to Reproduce

1. Create a repository and a branch in the repository
2. Commit to branch and merge branch
3. Go to "History" tab and click on merge
4. When clicking on link `Merge branch 'master' of LINK` if link is long enough, you can see the link overflow. Ex: https://github.com/randomrep/jdsjfdsfasdk…
5. When clicking on the link, the ellipses are included in the link and the https://github.com/randomrep/jdsjfdsfasdk… is opened in Firefox or Chrome as opposed to the correct link.

### Expected Behavior

The full link opens

### Actual Behavior

Truncated link is opened

## Additional Information

![image](https://user-images.githubusercontent.com/17993169/51419321-645c1c00-1b81-11e9-855d-874a7c3f7e29.png)

![image](https://user-images.githubusercontent.com/17993169/51419330-82298100-1b81-11e9-8cbe-604bdb79f4ea.png)

### Logs

[2019-01-19.desktop.production.log](https://github.com/shiftkey/desktop/files/2774941/2019-01-19.desktop.production.log)

**Comment by shiftkey** [comment]
@sambhavsaggi thanks for the report! 

Are you able to share a public commit that reproduces the issue? I've found https://github.com/BotsBurgh/BOTSBURGH-FTC-2018-19/commit/754ce5b27a4066a208df4d4293d2aa194a1787ce which might be the one we're talking about here

What's interesting about this is that the split is visible on the GitHub website, and the commit summary isn't a clickable link (but overflowing into the description, which is clickable):

<img width="762" src="https://user-images.githubusercontent.com/359239/51427105-00117a80-1bca-11e9-8fcf-3cfa7b84afc6.png">

Viewing the commit in Git shows the unmodified URL on one line (with no description)

```shellsession
$ git show 754ce5b --format=medium
commit 754ce5b27a4066a208df4d4293d2aa194a1787ce
Merge: 968a86a 17403d7
Author: nitsl <niteshramanathan@gmail.com>
Date:   Fri Jan 18 19:05:10 2019 -0500

    Merge branch 'master' of https://github.com/BotsBurgh/BOTSBURGH-FTC-2018-19
```

**Comment by j-f1** [comment]
The gray text in the summary is clickable for me.

**Comment by shiftkey** [comment]
I've been able to reproduce this on macOS, so I'm going to open an issue again the main project to track it there.

**Comment by shiftkey** [comment]
Moved to the main project. Please follow along with https://github.com/desktop/desktop/issues/6690
