### ISSUE TITLE
[AppImage] git does not work due to missing libcurl-gnutls.so.4

### ISSUE THREAD

**Issue by simoniz0r** [shiftkey/desktop#12]
### Description

When trying to use any of the built in git operatins (clone, fetch, etc), an error pops up saying that `libcurl-gnutls.so.4` cannot be opened.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** OpenSUSE Tumbleweed

### Steps to Reproduce

Sign in
Try to clone a repo or use the fetch option on a local repo
See error that `libcurl-gnutls.so.4` is missing.

**Expected behavior:** git operations should work

**Actual behavior:** Error displayed about missing `libcurl-gnutls.so.4`

**Reproduces how often:** 100%

### Logs
```
/tmp/.mount_githubbZudXq/app/resources/app/git/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```

![image](https://user-images.githubusercontent.com/16279904/34066970-eed9b8e8-e1de-11e7-9434-4cd548b1b72c.png)

**Comment by shiftkey** [comment]
This is related to the embedded Git we ship in Desktop. The discussion about statically linking Git is here https://github.com/desktop/dugite-native/issues/42 but we haven't figured it out yet.

As a workaround mentioned here https://github.com/desktop/desktop/issues/1525#issuecomment-351720433, you can symlink `libcurl.so.4` to `libcurl-gnutls.so.4` which should get it working.

**Comment by simoniz0r** [comment]
If you're using a build of `git` from a Debian based distro, you should be able to package `libcurl3-gnutls` in your AppImage to solve this issue.  I've done this for an AppImage that I've made myself, and it has worked on all of the distros I've been able to test it on.  

Simply packaging `libcurl3-gnutls` itself should be enough if your build of `git` is from a Debian based distro.  `libcurl3-gnutls` is relatively small in size, so this would make for an easy quick fix, IMO.

**Comment by probonopd** [comment]
Statically linking Git may be even better a solution.

**Comment by shiftkey** [comment]
I'm not sure the best fix for this is in the packaging process of Desktop (the mentions in the documentation talk about adding dependencies for the Electron app, which is separate to our version of `git` that is distributed in the app). I'm going to close this out in favour of the ongoing discussion in https://github.com/desktop/dugite-native/issues/42 - if you have any bright ideas, please sound out over there.

If we can figure a way out of that, this will become available with an update to the Git distributed in Desktop.

**Comment by probonopd** [comment]
cc @TheAssassin

**Comment by TheAssassin** [comment]
See https://github.com/desktop/dugite-native/issues/42#issuecomment-352253495.

**Comment by probonopd** [comment]
By the way, the AppImage developers are happy to support, we are on #AppImage on irc.freenode.net.
