### ISSUE TITLE
[Feature Request] Vue, Edit and Comment on Issues and PRs

### ISSUE THREAD

**Issue by zero77** [shiftkey/desktop#121]
Can you please add support to vue, edit and comment on Issues and PRs, like you can in the web browser.
Thanks

**Comment by shiftkey** [comment]
@zero77 thanks, but the place to ask about this is on the [main project](https://github.com/desktop/desktop).

Here are some previous discussions which are relevant to your request:

 - https://github.com/desktop/desktop/issues/1866
 - https://github.com/desktop/desktop/issues/2376
 - https://github.com/desktop/desktop/issues/295

**Comment by zero77** [comment]
@shiftkey 
Thanks, i will have a look.
