### ISSUE TITLE
Can't install snap package

### ISSUE THREAD

**Issue by adam-birds-test** [shiftkey/desktop#122]
**Please describe the problem you think should be solved**
When I try to install the snap package I get an error about can't find signatures with metadata for snap, full error below:

```
snap install GitHubDesktop-linux-1.6.1-linux1.snap 
error: cannot find signatures with metadata for snap
       "GitHubDesktop-linux-1.6.1-linux1.snap"
```

**Comment by shiftkey** [comment]
@adam-birds-hwt I need more information to try and reproduce the issue:

 - what distro you are installing to
 - what version of `snap`

**Comment by shiftkey** [comment]
@adam-birds-hwt I think you'll need to pass in `--dangerous` to install this snap locally, because it's not signed when packaging - https://askubuntu.com/questions/822765/snap-install-failure-error-cannot-find-signatures-with-metadata-for-snap has some more details

**Comment by joshirio** [comment]
I can confirm it installs with `snap install GitHubDesktop-linux-1.6.1-linux1.snap --dangerous`

Ubuntu 18.04 and 19.04

**Comment by shiftkey** [comment]
Closing this out because I believe the `--dangerous` is needed here to install locally, at least until we can address #116
