### ISSUE TITLE
Organisation Repos not able to be cloned.

### ISSUE THREAD

**Issue by adam-birds-test** [shiftkey/desktop#126]
## Description
My organisation repositories aren't showing in the list to clone. They also don't let me clone them directly using the URL.

## Version
* GitHub Desktop: Version 1.6.2-linux1
* Operating system: Ubuntu 18.04 4.18.0-15-generic

## Steps to Reproduce
1. Install GitHubDesktop using the latest .deb package.
2. Sign in with a GitHub Account that has access to an organisation.
3. Try to clone a repo from that organisation. (None appear in the list)

### Expected Behavior
1. You should see a list like the below including your organisation repos to include:
![image 1](https://user-images.githubusercontent.com/36477553/53419377-afafe880-39d1-11e9-934d-23a434e0c749.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/36477553/53419537-f7cf0b00-39d1-11e9-857f-d37a96ac88fd.png)

**Comment by shiftkey** [comment]
@adam-birds-hwt thanks for the report! 

I'm pretty sure this is related to #72. Because the Linux installer currently uses the development OAuth app details it gets caught by [third party application restrictions](https://help.github.com/en/articles/enabling-oauth-app-access-restrictions-for-your-organization) that some organizations have enabled.

**Comment by adam-birds-test** [comment]
@shiftkey looks like it worked back in 1.2.0 on Fedora though as my colleague uses that. When looking at the dev tools, the bearer token that it provides to the api doesn't return the full list. Tested it separately in Postman, whereas the token my colleague got in 1.2.0 does provide the full organisation list.

Also not that we aren't using GitHub Enterprise, but just connected to a normal github.com organisation.

**Comment by wordsoup** [comment]
👋 I received the same issue: cloning (or even viewing an accurate list of my org's private repositories, same as screenshot above 👆) in both 1.6.2 and 1.6.3 on a fresh Sabayon (Gentoo-based) install for a new laptop. I can verify that removing third party restrictions from the org and restarting Desktop did the trick. Afterwards I was immediately able to view the org's list of private repositories in the "Clone a repository" dialog, pull and push as expected.

While removing app restrictions isn't ideal, glad it works. @adam-birds-hwt this fix seems to work for non-Enterprise orgs, if that helps.

**Comment by shiftkey** [comment]
Closing this out in favour of #72, which I've updated to reflect that it's both related to GitHub Enterprise and orgs which have Third Party App restrictions enabled.
