### ISSUE TITLE
Desktop for Raspbian

### ISSUE THREAD

**Issue by Matt-the-Marxist** [shiftkey/desktop#130]
There is no actual way of running this on raspbian. Is there any way this can be fixed?

**Comment by Serkan-devel** [comment]
Electron isn't supported on arm and will drop 32-bit support. Might be hard to port github desktop onto that platform unfortunately

**Comment by shiftkey** [comment]
I think we're limited by what Electron itself can do - `3.0.13` seems to be the last good version that works on Raspbian Stretch based on this comment https://github.com/electron/electron/issues/16205#issuecomment-464098197

That issue also suggests when Raspbian 10 is out (with a more recent `glibc`) later versions of Electron apps might also work, but with [32-bit Linux support for Electron](https://electronjs.org/blog/linux-32bit-support) being deprecated for Electron 4 the future options are also limited.

This isn't something that I have bandwidth to explore further, but the signs and winds seem to be pointing to 64-bit ARM support being the future.
