### ISSUE TITLE
client installation not detect on GitHub website

### ISSUE THREAD

**Issue by prascher** [shiftkey/desktop#131]
I am on Ubuntu 18.04 and for some reason GitHub does not seem to recognize that I have the desktop client.

**Comment by shiftkey** [comment]
Not currently - there needs to be some backend changes to GitHub to support this. I'm not sure when this will happen.

**Comment by shiftkey** [comment]
Closing this out for now as this depends on upstream support from the team, and this is something that I can't contribute to them for the foreseeable future...
