### ISSUE TITLE
No snap please fix.

### ISSUE THREAD

**Issue by Saladin1812** [shiftkey/desktop#136]
Please update the readme there is no snap package
snap install --beta github-desktop
It says not found also there is no github desktop on snapcraft. 
And other thing is that is the rpm for fedora,CentOS,SUSE or for what distro ?

**Comment by shiftkey** [comment]
> Please update the readme there is no snap package

Please follow along with this tracking issue #116 - the Snapcraft listing has been disabled while I figure out how to implement the in-app migration guide.

> And other thing is that is the rpm for fedora,CentOS,SUSE or for what distro ?

I'm not aware of any distro-specific dependencies about it - I've tested the package on at least Fedora and CentOS in the past.

**Comment by Saladin1812** [comment]
ok thanks :)
