### ISSUE TITLE
unable to invoke protocol handlers in ChromeOS

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#138]
Extracting this feedback from @DanTup in #134:

> Actually, it was this bit on the page before where I saw the URL.
> 
> ![Screenshot 2019-04-07 at 12 47 25](https://user-images.githubusercontent.com/1078012/55683062-57a2c500-5933-11e9-942f-97d1f640215b.png)
> 
> Clicking the big green button just leads to the error in the screenshot above.
>
> ...
> 
> I immediately get the error now when it spawns the browser:
> 
> ![Screenshot 2019-04-07 at 12 42 53](https://user-images.githubusercontent.com/1078012/55683018-bfa4db80-5932-11e9-83cf-dba634dbb222.png)
>

I suspect there's some limitation involved here that might block Linux apps from registering protocol handlers in ChromeOS, but I don't have the bandwidth currently to research further:

> Note: On Chrome OS, the Linux world and the Chrome OS world are somewhat separate - I don't know whether it's possible for Linux apps to register protocol handlers that work in the main Chrome browser (though note that I know almost nothing about this setup, I just enabled it on a Pixelbook and decided to see what worked and what doesn't).

**Comment by DanTup** [comment]
> I suspect there's some limitation involved here that might block Linux apps from registering protocol handlers in ChromeOS

I did have a look around, but couldn't find much info on this (there's a little info on some restrictions [here](https://support.google.com/chromebook/answer/9145439?hl=en)). My understanding is that the Linux apps are running in a container on ChromeOS (for ex. Chrome can't access ports bound to localhost in the container using `localhost` except for [some specifically mapped ones](https://www.reddit.com/r/Crostini/comments/99s3t9/wellknown_ports_are_now_autoforwarded_to_the/)).

I also don't know if there's a way to detect this (eg. to hide the browser sign-in option) - so far the only sign I've seen that you're running on Chrome OS is that the hostname is "penguin" in the container, but I'm not sure I'd toggle things based on that.

**Comment by shiftkey** [comment]
#292 is another report of the sign-in process not working on Chrome OS

**Comment by shiftkey** [comment]
I don't see any indication this will be supported as part of the Crostini effort to get Linux apps working on ChromeOS:

 - https://support.google.com/pixelbook/thread/32323061?hl=en
 - https://support.google.com/chromebook/thread/33348240?hl=en

I'll also point out that GitHub is planning to [remove basic authentication support in November](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/), so we'll be stuck without an option here for ChromeOS users to authenticate because of the lack of support for protocol handlers.

**Comment by shiftkey** [comment]
Closing this out as I have no plans to revisit this, and I don't think this will be supported on Chrome OS based on another cursory search of the internet
