### ISSUE TITLE
About GitHub Desktop Error Message occurs on Ubuntu 17.10

### ISSUE THREAD

**Issue by AluminiumTech** [shiftkey/desktop#14]
Summary of the issue: Going to "About GitHub Desktop" throws an error message regarding update checking.

Description:

An error message appears saying "Couldn't determine the last time an update check was performed. You may be running an old version. Please try manually checking for updates and contact GitHub Support if the problem persists. "

![Screenshot](https://user-images.githubusercontent.com/14107316/34096279-bc0e739e-e40f-11e7-848c-e2ea14684d85.png)

GitHub Desktop Version: 1.0.11 RC1 for Linux

OS Version: Ubuntu 17.10 with the latest updates installed.

### Steps to Reproduce

1. Open GitHub Desktop app
2. Click on "Help" and "About GitHub Desktop".

**Expected behavior:** Show that it's the latest version.

**Actual behavior:** Error message suggesting it's an outdated version.

**Reproduces how often:** 100% of the time.

**Comment by shiftkey** [comment]
Yep, we definitely don't check for updates with these builds. 

The code for that is [here](https://github.com/desktop/desktop/blob/master/app/src/ui/lib/update-store.ts#L158-L174), and for now we should probably just display a more friendly message and disable updates, like we do [here](https://github.com/desktop/desktop/blob/master/app/src/ui/about/about.tsx#L185-L195).

**Comment by AluminiumTech** [comment]
Still encountering this issue... even in RC3.

![relnotes](https://user-images.githubusercontent.com/14107316/34158560-dbc59df6-e500-11e7-8cb1-abaf97f887bf.png)

**Comment by shiftkey** [comment]
@AluminiumTech ah yes, I missed one code path

**Comment by AluminiumTech** [comment]
Still having this issue.......

![Github 1.0.12](https://user-images.githubusercontent.com/14107316/34763873-8982d2bc-f5e4-11e7-8196-4af8cb949632.png)

**Comment by AluminiumTech** [comment]
I'm using the .deb package btw.

**Comment by shiftkey** [comment]
> Still having this issue.......

Which version?

**Comment by AluminiumTech** [comment]
>> Which version?

Linux 1.0.12 RC

**Comment by shiftkey** [comment]
@AluminiumTech thanks, I'll test it out and see if I can understand what's happening

**Comment by shiftkey** [comment]
@AluminiumTech oh, actually, this is because `release-1.0.12` doesn't contain the upstreamed original fixes - https://github.com/desktop/desktop/pull/3732 was merged after that. I was planning to put out a new build in the next day or so that now has those fixes. I'll leave this open to track that.

**Comment by shiftkey** [comment]
This should be fixed in https://github.com/shiftkey/desktop/releases/tag/release-1.0.12-linux1
