### ISSUE TITLE
Arch can not log in

### ISSUE THREAD

**Issue by CanftIn** [shiftkey/desktop#143]
## Description
I downloaded the [AUR github-desktop-bin](https://aur.archlinux.org/packages/github-desktop-bin/) and installed, and I follow the step: select `File` > `Options` > `Accounts` then log in, with correct user name and password I can not log in github desktop.

## Version

* GitHub Desktop: Version 1.6.5-linux6

* Operating system: ArchLinux(Kernel: x86_64 Linux 5.0.7-arch1-1-ARCH)

## Steps to Reproduce

1. open github-desktop and add my local exist repository.
2. add new file in my local repo.
3. go in github-desktop and add file then commit
4. after commit this happens：
![2019-04-23-201620_581x452_scrot](https://user-images.githubusercontent.com/26135447/56580327-e5a1cf80-6604-11e9-8361-0ed6587b0d5a.png)
5. after inputting correct name and password:
![2019-04-23-201639_660x260_scrot](https://user-images.githubusercontent.com/26135447/56580328-e63a6600-6604-11e9-9169-9341beb2094e.png)
6. I try to follow the step: select `File` > `Options` > `Accounts` then log in, the
situation still happen. Error message:
```
No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login.
```

### Expected Behavior
Logging in github desktop and can commit files.

### Actual Behavior
Authentication failure and
```
No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login.
```

### Logs
[2019-04-23.desktop.production.log](https://github.com/desktop/desktop/files/3107457/2019-04-23.desktop.production.log)

**Comment by shiftkey** [comment]
@CanftIn thanks for the report.

This error feels like it's related to lacking a credential store that the app can communicate with. GitHub Desktop communicates using `libsecret` APIs, so a `libsecret`-compatible store is required to be installed to respond to those requests. `gnome-keyring` is one that I know works, and I think that corresponds with the [`gnome-keyring`](https://www.archlinux.org/packages/extra/x86_64/gnome-keyring/) package.

Can you confirm that is installed? I'm not sure if there is additional configuration required after that...

**Comment by CanftIn** [comment]
I think I'v installed `gnome-keyring` package.
![2019-04-24-222042_590x155_scrot](https://user-images.githubusercontent.com/26135447/56667498-85805b80-66e0-11e9-8e0a-4b3d95472f07.png)

I am thinking about whether it is possible to relate about `.gitconfig` file.
`cat ~/.gitconfig` output is:
```
[user]
	name = canftin
	email = wwc7033@gmail.com
[credential]
	helper = store
[color]
	ui = true
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

**Comment by immackay** [comment]
Hmm. Would you be able to provide more information about your Arch installation?

**Comment by immackay** [comment]
This is my mistake. libsecret is an additional requirement along with gnome-keyring.
The package has been updated to 1.6.6 RC2 and includes this change.

Thanks for the report!

**Comment by shiftkey** [comment]
@CanftIn can you test the updated package and confirm this is resolved?

**Comment by CanftIn** [comment]
@shiftkey @immackay I update to 1.6.6-linux2 but still can not sign in. And the gnome-keyring3.31.91-1 and libsecret0.18.8-2 all have been installed.

**Comment by immackay** [comment]
Okay, I will try to reproduce the issue this weekend.

Would you be willing to give more information about your setup? The output of `pacman -Qqe` in particular would be great.

**Comment by CanftIn** [comment]
@immackay Of course, thanks for your enthusiasm.
this is output file:
[output.txt](https://github.com/shiftkey/desktop/files/3123680/output.txt)

**Comment by immackay** [comment]
Hi @CanftIn,

This error is due to the gnome-keyring-daemon not being started. Normally this is handled by a display manager, but you can follow the steps [here](https://wiki.archlinux.org/index.php/GNOME/Keyring#Without_a_display_manager) to start it with xinit. I personally recommend the settings they list for i3 users 😉

Package has been updated again though as I found two missing libraries, nss and nspr.

**Comment by CanftIn** [comment]
@immackay Well, awesome help! You're right, gnome-keyring-daemon not being started, my bad for not clearly reading the archwiki.
Adding the setting to the `.xinitrc` and I can log in.
```sh
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
```
Thanks for helping. Then I close this issue.
