### ISSUE TITLE
Github Desktop doesn't recognise atom as being installed on the machine

### ISSUE THREAD

**Issue by astrolemonade** [shiftkey/desktop#147]
When I want to open a repo in an external editor from within the Github Desktop app a notification is telling me I need to install Atom, even if I have it installed already.
I tried to change the settings in the preferences, but no success.
Note: Atom editor was not installed from flatpak

**Comment by shiftkey** [comment]
@cata0309 please tell me which version/installer of Desktop you're using, and where Atom was installed to.

The app is looking at this location, and I'm not sure if we need to do additional checks if there are other standard locations:

https://github.com/shiftkey/desktop/blob/58a7331bfba0b29b133b2bad2890613d1831e2a4/app/src/lib/editors/linux.ts#L49-L50

**Comment by astrolemonade** [comment]
I understand, that was my problem, I had it installed from snap, but after I installed from their site all good.It is recognisable now

**Comment by tsutterley** [comment]
I know this issue is closed, but something similar to the following in linux.ts might fix it for future releases
`return getFirstPathIfAvailable(['/snap/bin/atom', '/usr/bin/atom'])`
(not that a symbolic link from the snap install location doesn't work)

**Comment by shiftkey** [comment]
@tsutterley if someone wanted to PR that change in I'd be happy to review it
