### ISSUE TITLE
use default chrome instead of integrated app menu

### ISSUE THREAD

**Issue by null-von-sushi** [shiftkey/desktop#149]
**Please describe the problem you think should be solved**

Github desktop uses Windows 10 style window controls on Linux, which looks very out of place. In addition, this also prevents shadows from showing when using KDE. 

This is what it normally looks like:
![Screenshot_20190519_010339](https://user-images.githubusercontent.com/13616397/57976187-ffe78700-79d1-11e9-9501-9bcbbbf229dc.png)

**[Possible Solution] Allow people to enable native titlebars**
Just using native titlebars (and menu bars too) should be relatively easy to implement I believe, as that's the default. 

I force-enabled them just to add some screenshots to demonstrate how much more consistent it would look. Also notice how the window now has shadows properly showing. I cannot disable the built in windows 10-style window controls Github-desktop shows though, hence this issue.  
![Screenshot_20190519_005908](https://user-images.githubusercontent.com/13616397/57976134-53a5a080-79d1-11e9-986c-0ca1fdc76160.png)

Just as a side note, KDE can set per-window color schemes, so this is what it would look like with a custom color scheme for Github-desktop:

![Screenshot_20190519_005835](https://user-images.githubusercontent.com/13616397/57976132-412b6700-79d1-11e9-90f9-55705e164976.png)

**EDIT:** Offtopic, but I just realized this is not the official repository. Does that mean microsoft does not actually support Running github desktop Linux?

**Comment by shiftkey** [comment]
@null-von-sushi thanks for the feedback! I added this in #139 because I wasn't happy with how the app looked with the default chrome:

![](https://user-images.githubusercontent.com/359239/55687540-5ded6d00-5944-11e9-92d4-91a088f674ae.png)

I don't have strong feels either way on this, but if others would like it to go back to showing the default frame (and leave it up to users to make Desktop fit better with their theme) then I'm fine with reverting that PR.

**Comment by shiftkey** [comment]
> Offtopic, but I just realized this is not the official repository. Does that mean microsoft does not actually support Running github desktop Linux?

Not currently. I'm a maintainer on GitHub Desktop but this Linux fork is something that I try and keep up to date in my spare time. Please follow along with the upstream discussion about this https://github.com/desktop/desktop/issues/1525

**Comment by null-von-sushi** [comment]
> I don't have strong feels either way on this, but if others would like it to go back to showing the default frame (and leave it up to users to make Desktop fit better with their theme) then I'm fine with reverting that PR.

It'd be nice if this could be a user configurable action, I don't think there's any solution that is perfect for all use cases honestly.


> Not currently. I'm a maintainer on GitHub Desktop but this Linux fork is something that I try and keep up to date in my spare time. Please follow along with the upstream discussion about this [desktop#1525](https://github.com/desktop/desktop/issues/1525)

Interesting. Thanks for the link, I'll keep an eye on the upstream issue...

**EDIT:** It might be worth considering mentioning your fork on the main desktop website (if you want that amount of traffic for this project that is). I only found this thanks to the AUR, most people search the web for software though.

**Comment by trxcllnt** [comment]
@shiftkey +1 for reverting #139. Ubuntu's default Gnome theme is indeed awful, but the install base mostly consists of people who a. don't care what Gnome looks like, or b. are going to customize Gnome anyway (like me and @null-von-sushi :joy:).

Here's a comparison with VSCode, which also uses their own menu by default, but has an option to use native menus:

![Screenshot from 2019-06-20 18-47-09](https://user-images.githubusercontent.com/178183/59891892-d5e80280-938b-11e9-80b4-e959e6eecd5d.png)

If you're interested, here's my setup:

* [User Themes](https://extensions.gnome.org/extension/19/user-themes/) applies your user theme to gnome-shell controls
* [Activity Configurator](https://extensions.gnome.org/extension/358/activities-configurator/) lets you clean up the top panel
* The [Gnome GlobalAppMenu](https://extensions.gnome.org/extension/1250/gnome-global-application-menu/) and `appmenu-gtk3-module` to move app menus into the Gnome panel. This project was abandoned by its author but still works great on Ubuntu 18.04.2 w/ a few JSON edits.
* OS X [cursors](https://www.gnome-look.org/p/1084939/), [High Sierra theme](https://github.com/vinceliuice/Sierra-gtk-theme), and fonts:
  <details><summary>(font install instructions)</summary><pre>
  wget -O mac-fonts.zip http://drive.noobslab.com/data/Mac/macfonts.zip
  sudo unzip mac-fonts.zip -d /usr/share/fonts; rm mac-fonts.zip
  sudo fc-cache -f -v</pre></details>

**Comment by trxcllnt** [comment]
Sweet #139 was clean to rebase out. Here's the new (or old) look:

![Screenshot from 2019-06-20 20-41-07](https://user-images.githubusercontent.com/178183/59896170-5878be00-939c-11e9-990d-743b4d2897d9.png)

I'd love to submit a PR that adds native menu bars back as an option. I had a bit of trouble running the snap packager on 18.04:

1. `yarn package` on my host eventually throws an error trying to exec `gtk-update-icon-cache-3.0`
2. `yarn package` in the  [`azure-pipelines.yml`](https://github.com/shiftkey/desktop/blob/8e533a99d4ab17539b1d948b66a52bab0f321979/azure-pipelines.yml#L71) containers fails at the `workaroundForSnapPackage()` function in `scripts/package.ts`
    * `unsquashfs` isn't in the `snapcore/snapcraft` base
    * after installing `squashfs-tools`, `/src/dist/unsquashfs-root/meta/snap.yaml` doesn't exist

Any ideas how to run the packaging steps (preferably containerized)?

**Comment by shiftkey** [comment]
> 1. `yarn package` on my host eventually throws an error trying to exec `gtk-update-icon-cache-3.0`

Yeah, I've only been able to get this working inside the Snapcraft docker container.

> * `unsquashfs` isn't in the `snapcore/snapcraft` base

This was working fine when I shipped the last update a week ago: https://brendanforster.visualstudio.com/desktop-linux/_build/results?buildId=381

> Any ideas how to run the packaging steps (preferably containerized)?

This stuff was working fine for me up until a couple of days ago but something in the docker setup is blowing up because of some change with the Docker images, and it's having a problem parsing this version string:

<img width="618" src="https://user-images.githubusercontent.com/359239/59920456-f0a88e80-9400-11e9-934f-53ad584ff4fa.png">

**Comment by trxcllnt** [comment]
Yeah that's the same error I was seeing in the snapcraft image. Glad to know it's not just me! Looks like [their containers](https://hub.docker.com/r/snapcore/snapcraft/tags) were updated recently. [This commit](https://github.com/snapcore/snapcraft/pull/2591/files#diff-145349882cd29d495f2e5bae003cb14cR18) looks related to the version check issue, and the one before that they moved the [squashfs-utils](https://github.com/snapcore/snapcraft/commit/c326d7ef0275957ac2f74eecfcd97ed54707ba0c#diff-4addbde244d0316411b17f6e6a53b48dR1) into a prior build step. So it could be as easy as copying the [original install process](https://github.com/snapcore/snapcraft/commit/512c54488e148b4b9778f2fe62640f6eee4b2a2b#diff-4addbde244d0316411b17f6e6a53b48dR1) into the build container here and giving it a go.

**Comment by trxcllnt** [comment]
@null-von-sushi heads up, if you want to build yourself a version of github desktop with the native menubar, you can check out https://github.com/trxcllnt/desktop/tree/revert-139 and run `docker-build-and-package.sh`. The only prerequisite is docker, and you shouldn't need to build or install anything in the project itself. Once it's done you can install `dist/GitHubDesktop-linux-2.0.4-linux1.deb` like normal.

**Comment by null-von-sushi** [comment]
> @null-von-sushi heads up, if you want to build yourself a version of github desktop with the native menubar, you can check out https://github.com/trxcllnt/desktop/tree/revert-139 and run `docker-build-and-package.sh`. The only prerequisite is docker, and you shouldn't need to build or install anything in the project itself. Once it's done you can install `dist/GitHubDesktop-linux-2.0.4-linux1.deb` like normal.

I once tried to run a docker thing and couldn't get it to work, so I am not having high expectations. Oh, and I am not even using Debian/Ubuntu. I will probably just wait for this to be fixed properly. For now I just have a kwin override to show the native titlebar. Having 2 titlebars is annoying, but I don't use github THAT often.

Thanks though :)

**Comment by alitajelsir** [comment]
Any update on the issue?. Is reverting the code still an option?

**Comment by shiftkey** [comment]
> Any update on the issue?. 

Not really. Been unwell this week and I see there's a new release available and so after I've caught up with that I'm going to open a PR for this change.

> Is reverting the code still an option?

Totally. I've only heard feedback against this change, and while I did get some ❤️ reactions on the original PR I also appreciate that some on this issue would like it reverted. I have no strong feelings, but I'd like to confirm that more people prefer reverting so I'll leave the PR open for a bit to gather feedback.

**Comment by alitajelsir** [comment]
> Not really. Been unwell this week and I see there's a new release available and so after I've caught up with that I'm going to open a PR for this change.
>  

The most important thing is your health. Don't overwork yourself. Stay healthy 😁.

**Comment by shiftkey** [comment]
I've opened #237 to propose this change. If you're interested in seeing the app use the default chrome, please leave a reaction or approval on that PR.

**Comment by shiftkey** [comment]
This shipped as part of [`2.4.0 RC1`](https://github.com/shiftkey/desktop/releases/tag/release-2.4.0-linux1).
