### ISSUE TITLE
Ubuntu 18.04 LTS build error

### ISSUE THREAD

**Issue by wanjizheng** [shiftkey/desktop#154]
Hi, followed the instruction to set up the Linux environment and start the build process.  However, the `yarn run package` returns the below error:
https://gist.github.com/wanjizheng/38ef1a7b4af5833a182a351f5d2d8791

**Comment by shiftkey** [comment]
@wanjizheng can you run the script with `DEBUG=electron-builder` set? That will provide some extra details about why `electron-builder` is failing (leading to these other failures)...

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of context about reproducing the issue.
