### ISSUE TITLE
Editors installed via snap are not detected

### ISSUE THREAD

**Issue by ziggy42** [shiftkey/desktop#155]
## Description
I have visual studio code installed:
```bash
➜  ~ whereis code
code: /var/lib/snapd/snap/bin/code /var/lib/snapd/snap/bin/code.url-handler
```
but it's not detected:
![Screenshot from 2019-06-18 11-25-47](https://user-images.githubusercontent.com/4258550/59670243-e77ab000-91bb-11e9-865e-64f717c79862.png)

## Version
* GitHub Desktop: 2.0.4-linux1
* Operating system: Fedora 29

## Steps to Reproduce
1. install [visual studio code via snap](https://snapcraft.io/code) 
2. try to set it as default editor

### Expected Behavior
Visual Studio Code should be detected.

### Actual Behavior
Visual Studio Code is not detected.

I'll look into this in a near future if no one has time to fix it :+1:

**Comment by shiftkey** [comment]
I only think we detect the regular installed version, not the Snap-based one:

https://github.com/shiftkey/desktop/blob/735628de54c70da4731aaaf55cf598de607a3d3a/app/src/lib/editors/linux.ts#L47-L54

There's an example further down for checking multiple paths, feel free to borrow that:

https://github.com/shiftkey/desktop/blob/735628de54c70da4731aaaf55cf598de607a3d3a/app/src/lib/editors/linux.ts#L59-L72

**Comment by ziggy42** [comment]
What if both versions are installed? :smile: 
I'd just take the snap version first if available.

**Comment by shiftkey** [comment]
> What if both versions are installed? 😄

It should return the first found path, so prioritizing the Snap before the default install seems fine here
