### ISSUE TITLE
Sign-in with browser launches seperate profile

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#157]
## Description
Once beta snap is installed any attempts to login using the browser option launch the default browser as expected. While I did see the login loop as in #134, the snap opened and entirely new profile under my browser( Vivaldi latest stable 2.5). This new profile is odd because its like i had just fresh installed vivaldi.

## Version
* GitHub Desktop: 2.0.4-linux1
 Vivaldi: 2.5.1525.48

* Operating system:
Pop!_OS 19.04

## Steps to Reproduce

1. Install github desktop and vivaldi
2. Setup test profile on vivaldi
3. Launch github desktop and clikc the sign in with browser

### Expected Behavior
Launched browser was expected to be a new tab of my current opened profile with access to my password manager and accounts

### Actual Behavior
The browser launched seems to create a temporary new profile that cannot see or access any profiles, extensions, or any other data avaliable to the normal profiles.

## Additional Information
Normal Browser
![Screenshot from 2019-06-18 23-56-11](https://user-images.githubusercontent.com/46433725/59737952-2729b200-9225-11e9-890b-ad7abe7afe1e.png)
Browser made by Github Desktop
![Screenshot from 2019-06-18 23-55-32](https://user-images.githubusercontent.com/46433725/59737960-301a8380-9225-11e9-980a-fc5a7debfa78.png)
Found where the snap is pulling the profile from
![Screenshot from 2019-06-19 00-10-32](https://user-images.githubusercontent.com/46433725/59738400-c00cfd00-9226-11e9-9f43-a0febb08070e.png)
seems to make its own configuration folder for vivaldi from within its own snap folder?

### Logs
heres log idk if important
[2019-06-19.desktop.production.log](https://github.com/shiftkey/desktop/files/3304473/2019-06-19.desktop.production.log)

**Comment by shiftkey** [comment]
> The browser launched seems to create a temporary new profile that cannot see or access any profiles, extensions, or any other data avaliable to the normal profiles.

I'm not quite sure what sort of sandboxing the runtime is doing here, but I'm not sure this is an easy fix for Desktop to do 🤔

**Comment by ghost** [comment]
> > The browser launched seems to create a temporary new profile that cannot see or access any profiles, extensions, or any other data avaliable to the normal profiles.
> 
> I'm not quite sure what sort of sandboxing the runtime is doing here, but I'm not sure this is an easy fix for Desktop to do

Yep. I just wanted to put it the issue somewhere. It doesn't really bother me since I never use the view on github button

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps like this one. Please follow along with #203 in the meantime.
