### ISSUE TITLE
Warning/Information about publishin the repo when the repo is published.Is it normal?

### ISSUE THREAD

**Issue by astrolemonade** [shiftkey/desktop#158]
## Version

* GitHub Desktop:
2.0.4-linux1

* Operating system:
Solus 4 Fortitude linux

## Steps to Reproduce

Open the app and you will see a notification flash about publishing the repo
*Other notes:
App installed via snap store

I managed to record the screen when the notification appear and go to Vlc and play the video at slow speed and took a screenshot of it.
![image](https://user-images.githubusercontent.com/35623921/59978304-bb0fcb00-95e3-11e9-9b42-90ee2844726d.png)

Is this behavior normal ?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35623921/59978381-61f46700-95e4-11e9-943e-c2f4e049f5c9.gif)

**Comment by shiftkey** [comment]
@cata0309 thanks for the feedback!

That animation shouldn't be necessary (the "Fetch origin" header seems to indicate it knows about a remote repository), and I'm going to leave this open to see if I can reproduce it on my side.

**Comment by astrolemonade** [comment]
If you need more information let me know ! I will do anything I can to help

**Comment by shiftkey** [comment]
@cata0309 I think that animation was an unfortunate side-effect of launching the app and how it was animating the transition.

Is this still occurring for you on the latest version? I couldn't see this on `2.3.1`, so I'm going to close this out as I don't know of other users (here or on the main project) which have encountered this issue.
