### ISSUE TITLE
On Kubuntu 18.04 "the name org.freedesktop.secrets was not provided by any service."

### ISSUE THREAD

**Issue by Xtigyro** [shiftkey/desktop#159]
## Description
On Kubuntu 18.04 `the name org.freedesktop.secrets was not provided by any service.` when you try to login into the standard `GitHub`.

## Version
2.0.4-linux1 (installed through `snap install github-desktop --beta --classic`)

* Operating system: Kubuntu 18.04, KDE neon 5.16.1

## Additional Information
Can be workarounded through: `apt install -y gnome-keyring`

**Comment by shiftkey** [comment]
@Xtigyro thanks for the feedback!

The snap itself contains the `libsecret` base package the app requires, but it also needs something to be registered to listen to and respond to requests for credentials.

The only working implementation I'm aware of is `gnome-keyring`, but some users dislike that being specified on KDE systems. I'm not sure of an alternative at this point, but I'll keep this in mind.

**Comment by KaKi87** [comment]
Hello there, I had the same issue on KDE Neon and installing `gnome-keyring` fixed it, as expected.
But, I would like to bump this issue in order to get rid of this dependancy.
Thanks !
