### ISSUE TITLE
Missing curl / libcurl.so dependency in snap package

### ISSUE THREAD

**Issue by miyconst** [shiftkey/desktop#160]
Continuation from - [Missing some libraries in Snap package #71](https://github.com/shiftkey/desktop/issues/71).

- OS: Fresh installation of **Ubuntu 18.04.01**.
- GitHub Desktop: `2.0.4-linux1-beta`.

```
sudo apt update
sudo apt upgrade
sudo snap install github-desktop --beta --classic
```

Trying to clone any repository results in the following error:

![](https://user-images.githubusercontent.com/6418433/46950527-8abc7800-d0b7-11e8-9d66-554dac77f788.png)

The following comman solves the problem:

```
sudo apt-get install curl
```

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps like this one. Please follow along with #203 in the meantime.
