### ISSUE TITLE
Login doesn't use account when commiting

### ISSUE THREAD

**Issue by binkiklou** [shiftkey/desktop#168]
## Description

Hello, I've logged in with the app on my github account, but the only account I see when making a commit, is my OS/Linux account.(I don't really know what it is). But when I go into Options->Settings, I see my github account.

## Version
* GitHub Desktop:
2.10 Linux RC1
* Operating system:
Pop!_OS 18.04 LTS

## Steps to Reproduce
1. Install github desktop
2.Log in to you Github.com account(doesn't matter if you are using log in with the browser, or inside the app)
### Expected Behavior
The profile picture to the left of the Commit Summary input should be the one from your github account, and when pushing a commit, if you go to the repo where you made the commit you should see that there is a new commit by your github account.
### Actual Behavior
The profile picture to the left of the Commit Summary input, is a placeholder profile picture, and when you hover it it gives the email of your pop_os! os account. When pushing a commit, the app will either give an authentification error or push to the repo without your github account. If you look in the repo, the commit will be made by no user.

## Additional Information

The profile picture in the commit section:

![Screenshot from 2019-07-11 14-30-13](https://user-images.githubusercontent.com/19596443/61076557-845ef080-a3ea-11e9-8986-4b3044a93816.png)

The profile picture in the options:

![Screenshot from 2019-07-11 14-39-45](https://user-images.githubusercontent.com/19596443/61076579-90e34900-a3ea-11e9-9c61-8b34461f4a31.png)

Example commit(with an old version, i think. because now it creates authentification errors)

![Screenshot from 2019-07-11 14-40-35](https://user-images.githubusercontent.com/19596443/61076601-99d41a80-a3ea-11e9-94f6-e68f73314e8b.png)
:

Authentification error:

![Screenshot from 2019-07-11 14-43-51](https://user-images.githubusercontent.com/19596443/61076609-9fc9fb80-a3ea-11e9-99f0-d72db1a74674.png)

An example of a commit with 

### Logs

I couldn't find the log files. I will put them here, if anyone can help me on that.

**Comment by immackay** [comment]
Hi there, some additional information would be great.

How have you installed GitHub Desktop?
With a standard install, I believe the log files are stored under `~/.config/GitHub\ Desktop/logs/`

You can try setting your git name and email using
```
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
```
Additionally I believe if you unset these variables, GitHub Desktop *should* use its internal configuration. Not sure about this, but the commands are:
```
git config --global --unset user.name
git config --global --unset user.email
```

**Comment by immackay** [comment]
Additionally, if you've installed via the snap package, it seems to be borked for version 2.1.0.

See #163 for more details.

**Comment by binkiklou** [comment]
@immackay I've run the commands and it seems to work again thanks!
