### ISSUE TITLE
Not able to login on Chrome OS

### ISSUE THREAD

**Issue by mcmuffindk** [shiftkey/desktop#170]
## Description

When trying to login, you will receive an error saying "Unknown or unsupported transport 'disabled' for address 'disabled:'" 

## Version

* GitHub Desktop: 2.1.0-linux1

* Operating system: Chrome OS 75.0.3770.144
* Sub system: Linux 4.19.34-04457-g5b63d4390e96

## Steps to Reproduce

1. Login
2. Error

### Expected Behavior

Succesfull login

### Actual Behavior

Unsuccesfull login resulting in error

### Logs

[2019-08-06.desktop.production.log](https://github.com/shiftkey/desktop/files/3473873/2019-08-06.desktop.production.log)

**Comment by tsinis** [comment]
run
`sudo apt install gnome-keyring`
from terminal, then reboot

**Comment by shiftkey** [comment]
I believe the comment from @tsinis here is the needed resolution.

@mcmuffindk please retest against the latest version if you're still encountering issues.
