### ISSUE TITLE
undefined symbol: g_date_copy

### ISSUE THREAD

**Issue by thenetimp** [shiftkey/desktop#171]
Fresh install of Ubuntu 18.04LTS

Followed install instructions, click on icon it doesn't open, run at CLI and get the following.

```
/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
```

**Comment by thenetimp** [comment]
bother didn't see the closed issue, but also didn't see that it was fixed in the closed issue, should really leave tickets open until they are actually fixed.

**Comment by immackay** [comment]
See #163
