### ISSUE TITLE
Cannot launch, failed to verfiy SELinux context

### ISSUE THREAD

**Issue by LanTenDragon** [shiftkey/desktop#172]
## Description
I have installed GitHub Desktop and tried to launch in from GUI. It did not launch at all and thus I launched from terminal, but it gave the following error.

## Version

* GitHub Desktop: 2.1.0-linux1
* Operating system: Ubuntu 19.04

## Steps to Reproduce
1. Install GitHub Desktop from Snapcrafters
2. Launch from terminal `github-desktop`

### Expected Behavior
GitHub Desktop launches normally

### Actual Behavior
Terminal shows output as shown in the logs

## Additional Information
None

### Logs

> dragon@dragon:$ snap install github-desktop --beta --classic
> github-desktop (beta) 2.1.0-linux1 from Snapcrafters installed

> dragon@dragon:$ github-desktop 
> 2019/08/12 13:27:40.692909 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/dragon/snap: exec: "matchpathcon": executable file not found in $PATH

> dragon@dragon:$ github-desktop -strace
> 2019/08/12 13:30:05.907274 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/dragon/snap: exec: "matchpathcon": executable file not found in $PATH
> /home/dragon/Documents was removed, reassigning DOCUMENTS to homedir

**Comment by immackay** [comment]
#163

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps like this one. Please follow along with #203 in the meantime.
