### ISSUE TITLE
Failed to start in Ubuntu 18.04

### ISSUE THREAD

**Issue by Techtiger255** [shiftkey/desktop#173]
Does not start under `ubuntu 18.04.3 LTS bionic`. When the icon is pressed nothing happens, whatsoever.

**Comment by ramonivandy** [comment]
do you fix it ?

**Comment by saurabhrathour** [comment]
any fix on this?

**Comment by ramonivandy** [comment]
> any fix on this?

for now, I use the old version. and its work.

**Comment by saurabhrathour** [comment]
> > any fix on this?
> 
> for now, I use the old version. and its work.

With private repo aswell?
Actually I am getting error while pushing code to private repo with previous version of it!

**Comment by Techtiger255** [comment]
After a full system reset, it worked... Not sure what the issue was...
