### ISSUE TITLE
lubuntu 19.04 segmentation fault from running snap

### ISSUE THREAD

**Issue by rendorHaevyn** [shiftkey/desktop#174]
## Description

When attempting to run github-desktop snap on lubuntu 19.04 I received a segmentation fault error, and the program failed to run.

## Version

* GitHub Desktop:

github-desktop (beta) 2.1.0-linux1 from Snapcrafters installed

* Operating system:

Linux 5.0.0-13-generic #14-Ubuntu SMP

lubuntu 19.04

## Steps to Reproduce

Steps for getting this problem:
1. `snap install github-desktop --classic --beta`
2. `github-desktop`
3. Segmentation fault (core dumped)

I should note that I tried this a couple of times to confirm (uninstall/reinstall). 

I also gave the install a crack with `--edge` (rather than `--classic --beta`) - github-desktop actually launched and I could create a local repo, however, I could not sign in, was presented with an AppArmor error message, and I was also prompted to uninstall this version (`--edge`, I guess), and install the package listed in step 1 above.

### Expected Behavior

Github desktop to load.

### Actual Behavior

Jack all.

**Comment by immackay** [comment]
I imagine this is #163

**Comment by veeshi** [comment]
Was originally working fine however same error now occurs on Lubuntu 19.04 `Segmentation fault (core dumped)`

**Comment by immackay** [comment]
Would you be willing to downgrade to 2.0.4 to see if that fixes the issue? See #163 for instructions.

**Comment by veeshi** [comment]
Works! Thanks :+1:

**Comment by rendorHaevyn** [comment]
@immackay Thank you - your suggestion was successful, per: [https://github.com/shiftkey/desktop/issues/163#issuecomment-525140265](url)

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps like this one. Please follow along with #203 in the meantime.
