### ISSUE TITLE
snap failed to start "GLIBC_2.18 not found"

### ISSUE THREAD

**Issue by zypA13510** [shiftkey/desktop#176]
## Description

Snap failed to start. Running `snap run --strace github-desktop` returns the following message at the end:
> writev(2, [{"/snap/github-desktop/x1/app/gith"..., 42}, {": ", 2}, {"/lib64/libc.so.6", 16}, {": ", 2}, {"version \`GLIBC_2.18' not found ("..., 103}, {"\n", 1}], 6/snap/github-desktop/x1/app/github-desktop: /lib64/libc.so.6: version \`GLIBC_2.18' not found (required by /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)
) = 166
> exit_group(1)                           = ?
> +++ exited with 1 +++
> error: exit status 1

## Version

* GitHub Desktop: 2.0.4-linux1

* Operating system: CentOS 7 (3.10.0-957.27.2.el7.x86_64)

## Steps to Reproduce

1. `snap install downloads/GitHubDesktop-linux-2.0.4-linux1.snap --dangerous --classic`
2. `github-desktop`

### Expected Behavior

It starts.

### Actual Behavior

It did not. Output:
> /snap/github-desktop/x1/usr/sbin/update-icon-caches: line 16: gtk-update-icon-cache-3.0: command not found
> WARNING: icon cache generation failed for /home/dmnleozu/snap/github-desktop/x1/.local/share/icons/default
> /snap/github-desktop/x1/app/github-desktop: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6)

## Additional Information

Not installing 2.1.0 due another issue: [missing libpcre.so](https://github.com/shiftkey/desktop/issues/163#issuecomment-508294680). Not sure if this is fixed in 2.1.0.

**Comment by zypA13510** [comment]
Seems like a CentOS7-specific issue because CentOS 7 is built with glibc 2.17. Just searching glibc 2.18 and all issues seem to concern CentOS 7.

Despite this being a CentOS7-specific issue, the rpm version works nonetheless.

**Comment by zypA13510** [comment]
For those who wish to use the snap version on CentOS 7, the last working version without requiring glibc 2.18 is 1.6.5-linux2. But due to the various bugs with strict enclosure, <del>the last "stable" version is probably 1.5.0-linux3</del>(not working now), it's probably better to stick to rpm.

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps in general. Please follow along with #203 in the meantime.
