### ISSUE TITLE
Push to multiple remotes NOT really possible?

### ISSUE THREAD

**Issue by kematzy** [shiftkey/desktop#177]
I am unable to choose the remote repo I wish to push to via GUI.  

I'm unsure if this is a bug or a local installation error or just a missing feature.

## Description
In a project with three (3) remotes: 

-  **GitHub**  - my own repository.
-  **heroku**  - the deployment repository.
-  **Hasura**  - the original repository forked from (originally '_origin_').

**In the app GUI the "Push/Fetch" button only shows the "heroku" repository, so I am unable to push to "GitHub" via the app.**

## Version

* GitHub Desktop:   2.1.0-linux1

* Operating system:  Linux Mint Mate 19.1

## Steps to Reproduce

1.  Fork an existing repository from Github (such 
2.  Add a remote git repository "aka GitHub"
3.  Add another remote repository "aka heroku"
4. Try to choose which remote you wish to push to. 

### Expected Behavior

Ability to choose a remote to push to / fetch from, either via Menu or GUI button.

### Actual Behavior

The app have chosen the "heroku" remote and provides no ability to change this.

## Additional Information
None

### Logs

The log files contains nothing relating to the above repository and/or remotes, and contains no error messages or similar.

**Comment by shiftkey** [comment]
This is a limitation of how Desktop uses tracking branches. There's more context in the main project, and I recommend following along with that discussion https://github.com/desktop/desktop/issues/1442
