### ISSUE TITLE
github-desktop snap fails to start on Fedora 30 - missing libpcre.so.3

### ISSUE THREAD

**Issue by tmlgcq** [shiftkey/desktop#179]
## Description
github-desktop fails to start on Fedora 30. Errors with
/snap/github-desktop/63/app/github-desktop: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

In any case, would there be any chance of adding libpcre to the snap to address this?

## Version

* GitHub Desktop: 2.1.0-linux1
* Operating system: Fedora 30 

## Steps to Reproduce

1. Launch github-desktop snap from ui or cli
2. Error Displays

### Expected Behavior
Expected desktop to launch.

### Actual Behavior
Desktop fails to load and the following error displays
$ github-desktop 
/snap/github-desktop/63/app/github-desktop: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

## Additional Information
None

### Logs
No application logs are found.

Entry from journalctl:
Sep 15 15:41:02 host github-desktop_github-desktop.desktop[11573]: /snap/github-desktop/63/app/github-desktop: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory

**Comment by immackay** [comment]
#163

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps in general. Please follow along with #203 in the meantime.
