### ISSUE TITLE
GNOME keyring not installed as dependency

### ISSUE THREAD

**Issue by jeffdgr8** [shiftkey/desktop#180]
## Description
GNOME keyring is not installed as a dependency for GitHub Desktop on Linux. So if it's not installed already, logging in to GitHub results in the error: `Unknown or unsupported transport 'disabled' for address 'disabled:'`. I ran into [this issue](https://github.com/desktop/desktop/issues/5678) previously and wanted to let you know it is still happening on `release-2.1.0-linux1`.

## Version
* GitHub Desktop: 2.1.0 Linux RC1
* Operating system: Chrome OS 77.0.3865.93 / Debian GNU/Linux 9 (stretch)

## Steps to Reproduce
1. Linux without GNOME keyring installed
2. Install GitHub desktop
3. Login to GitHub account

### Expected Behavior
Successful login

### Actual Behavior
Error: Unknown or unsupported transport 'disabled' for address 'disabled:'

## Additional Information
Run `sudo apt install gnome-keyring` in order to install the dependency manually.

**Comment by shiftkey** [comment]
@jeffdgr8 to help prevent this in the future, would you be interested in submitting a PR to add it to the list here? https://github.com/shiftkey/desktop/blob/linux/script/electron-builder-linux.yml

I think you were using a `deb`, right?

**Comment by jeffdgr8** [comment]
@shiftkey https://github.com/shiftkey/desktop/pull/186
