### ISSUE TITLE
Remove an old version

### ISSUE THREAD

**Issue by alexanderadam** [shiftkey/desktop#181]
## Description

It seems that I have an old version installed and I don't know how I installed it. I always used the Debian packages as far as I remember.
It doesn't seem to interfere with newer versions but I obviously want to have the old version gone.

It is located in `/opt/GitHubDesktop` but I guess there are still some `.desktop` files etc that have to be removed so I guess there must be some kind of uninstalling progress?

## Version
* GitHub Desktop: `1.1.1`
* Operating system: Ubuntu 18.04.3 LTS

## Steps to Reproduce
1. Well, if I would know where it comes from I could write this down. But I simply can't remember. Please tell me if I can give you more information.

### Expected Behavior
There should be a way to remove that old version

### Actual Behavior
I don't know how to remove it properly :wink: 

PS: thank you **so** much for your work! I still hope that your fork will find it's way into master.

**Comment by shiftkey** [comment]
Given it should be installed through `apt-get` I think this is all you need to do:

```
sudo apt-get remove github-desktop
```

**Comment by alexanderadam** [comment]
Ah sorry: I probably misformulated it.

It doesn't seem to be related to `apt`. I can even install the Debian package and then I have _both_ versions installed: the apt version and the version in `/opt/GitHubDesktop`.

Thus, when I uninstall the `apt` package again I still have the directory `/opt/GitHubDesktop` and a corresponding menu entry for it.

There's also no snap package for GitHub Desktop installed (or at least `snap list` won't return anything related).

**Comment by shiftkey** [comment]
I tested this again with `2.4.0-linux1` and I can't seem to find which installer would be using `/opt/GitHubDesktop`. The `deb` and `rpm` packages live under `/opt/GitHub Desktop/` so I think this folder was leftover from before I changed the root directory.

```
$ dpkg-deb -c ~/Downloads/GitHubDesktop-linux-2.4.0-linux1.deb
drwxr-xr-x 0/0               0 2020-03-26 17:20 ./
drwxr-xr-x 0/0               0 2020-03-26 17:20 ./opt/
drwxr-xr-x 0/0               0 2020-03-26 17:20 ./opt/GitHub Desktop/
-rw-r--r-- 0/0          701056 2020-01-08 16:49 ./opt/GitHub Desktop/v8_context_snapshot.bin
-rw-r--r-- 0/0          280392 2020-01-08 16:48 ./opt/GitHub Desktop/snapshot_blob.bin
-rw-r--r-- 0/0          316984 2020-01-08 16:33 ./opt/GitHub Desktop/chrome_200_percent.pak
-rw-r--r-- 0/0            1060 2020-01-08 15:41 ./opt/GitHub Desktop/LICENSE
-rwxr-xr-x 0/0         5581136 2020-01-08 16:51 ./opt/GitHub Desktop/chrome-sandbox
-rw-r--r-- 0/0         4675743 2020-01-08 16:15 ./opt/GitHub Desktop/LICENSES.chromium.html
drwxr-xr-x 0/0               0 2020-03-26 17:20 ./opt/GitHub Desktop/resources/
...
$ rpm -qlp ~/Downloads/GitHubDesktop-linux-2.4.0-linux1.rpm
/opt/GitHub Desktop/LICENSE
/opt/GitHub Desktop/LICENSES.chromium.html
/opt/GitHub Desktop/chrome-sandbox
/opt/GitHub Desktop/chrome_100_percent.pak
/opt/GitHub Desktop/chrome_200_percent.pak
/opt/GitHub Desktop/github-desktop
...
```

@alexanderadam I'd recommend just deleting the folder, as I think it's now orphaned from whatever package that was previously installed.

**Comment by shiftkey** [comment]
Closing this out as I'm not going to investigate this further.

**Comment by alexanderadam** [comment]
> I think this folder was leftover from before I changed the root directory.

Probably. I'm not sure how trustworthy the timestamp is, but it says the folder is from 2018.

Now I also have the current version installed (so `/opt/GitHub Desktop/` and `/opt/GitHubDesktop/` are present).

Do you have any advice how to _fully_ remove this version?
So what should I remove (apart from `/opt/GitHubDesktop`)?

**Comment by shiftkey** [comment]
> So what should I remove (apart from `/opt/GitHubDesktop`)?

The only other files in the installer creates are these, but these are probably being overwritten by recent versions of the app and should be safe to leave:

```
/usr/share/doc/github-desktop/changelog.gz
/usr/share/applications/github-desktop.desktop
/usr/share/icons/hicolor/1024x1024/apps/github-desktop.png
/usr/share/icons/hicolor/256x256/apps/github-desktop.png
/usr/share/icons/hicolor/512x512/apps/github-desktop.png
```

**Comment by alexanderadam** [comment]
Awesome, thank you for helping me Brendan!

Stay healthy and thank you so much for maintaining the :penguin: Linux fork!
I'm also very sorry that all the folks are permanently asking for official releases in issue 1525. :see_no_evil: 


**EDIT:** Just in case somebody else stumbled about this: there was also a menu entry for GitHub Desktop in `~/.local/share/applications/desktop.desktop`.
