### ISSUE TITLE
symbol lookup error: ...libgobject-2.0.so.0: undefined symbol: g_date_copy

### ISSUE THREAD

**Issue by Lateralus138** [shiftkey/desktop#182]
## Description

GitHub-Desktop doesn't start at all and produces an error.

## Version

* GitHub Desktop: 2.1.0-linux1

* Operating system: Ubuntu 18.04.3 LTS 64 Bit Gnome 3.28.2

## Steps to Reproduce

1. `Ran from cli`
2. `Ran from ui`

### Expected Behavior

Expected the gui to start.
### Actual Behavior

Nothing happens and it throws the before mentioned error: 
`/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy`

## Additional Information

Error thrown:
`/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy`

I found this link with the exact same issue and someone there suggests that the snap author should provide the missing library:
[GitHub-Desktop Snap Issue](https://forum.snapcraft.io/t/undefined-symbol-g-date-copy-problem/12235 "GHDS Issue")

### Logs

Can't find the log anywhere in Linux. I have used the find and locate commands (after updatedb of course) and nothing.

**Comment by immackay** [comment]
#163 
There's instructions there for downgrading to 2.0.4 (or you can use the latest .deb)

**Comment by Lateralus138** [comment]
Much appreciated. There was nothing to revert to, but I was able to get it running with the .snap. I did search through open issues, but forgot to look through closed and I know better so I'm sorry I wasted your time...
