### ISSUE TITLE
Pull Origin Action got no response, at least from GUI

### ISSUE THREAD

**Issue by darrentsuei** [shiftkey/desktop#184]
## Description

RT, pull origin action through mouse click got no response, no info indicating if the pull works or not

## Version

* GitHub Desktop: 2.1.0-linux1

* Operating system: Ubuntu 16.04 LTS

**Comment by shiftkey** [comment]
@darrentsuei unfortunately there's not much for me to work with currently.

Please open the **Help** | **Show logs in your File Manager** menu item and find the logs from the relevant day - there might be more information to help me understand what you saw.

**Comment by shiftkey** [comment]
Closing this out due to inactivity.
