### ISSUE TITLE
Not Working On the Raspberry Pi 4

### ISSUE THREAD

**Issue by varlevi** [shiftkey/desktop#187]
### Describe the feature or problem you’d like to solve

I was searching for Linux-compatible versions of GitHub Desktop when I found this, but when I downloaded the Debian Package onto my Pi 4 (I'm running Raspbian, which is a version of Debian), it said the package could not download onto this computer.

### Proposed solution

The solution would be to change the Debian package so it works on Raspian as well, or to create a separate package for Raspian. I feel this is an important problem, because Raspberry Pis are actually the third most popular computer, and the most popular linux computer, in the world.

**Comment by ghost** [comment]
I'm experimenting with getting this running on Raspberry Pi 4, I'll tell you when I'm finished and give the files to you.

**Comment by varlevi** [comment]
Great! Keep me posted!

**Comment by ghost** [comment]
> The solution would be to change the Debian package so it works on Raspian as well

That would not work.

>  or to create a separate package for Raspbian

Yes, only that would be possible because if you would change the .deb, it would not work on normal computers

**Comment by ghost** [comment]
Got keytar, registry-js, fs-admin and electron building with some custom patches.

**Comment by ghost** [comment]
Necessary packages are installed now, compiling right now.

**Comment by RaspberryPiFan** [comment]
build finished

**Comment by ghost** [comment]
Debug build finished !

**Comment by ghost** [comment]
I'll give you a .deb file later, this is just a debug build

**Comment by ghost** [comment]
If you get the build and you think it doesn't work, just wait, it takes about 5 minutes to start.

**Comment by ghost** [comment]
I can't make a deb file, but I'll help you to compile it.

**Comment by ghost** [comment]
`sudo apt install gconf2 gconf-service libnotify4 libappindicator1 libxtst6 libnss3  libsecret-1-0 gnome-keyring` Run this to prepare

**Comment by ghost** [comment]
It works now on my Raspberry Pi, but it's not easy to get it work on every Raspberry Pi by just installing a package

**Comment by varlevi** [comment]
Hmm... I tried running the 'sudo' command in the command line and it said it would take up almost 10,000 kB of space. Does that sound right to you? Looks like a lot to me, but I am certainly not an expert on builds and things like that!

**Comment by ghost** [comment]
Yes, that's normal. 10,000 kB are just 10 MB

**Comment by ghost** [comment]
The packages are not the full GitHub desktop, only needed packages.

**Comment by varlevi** [comment]
Okay. Thanks. Now that I've downloaded the packages, can you tell me where can I find the full GitHub desktop? Like I said, I'm not very bright when it comes to software and builds, so thank you so much for your help.

**Comment by ghost** [comment]
I'm creating a package for easy self building now, it will be finished soon.

**Comment by varlevi** [comment]
Awesome. Will it be in a separate fork?

**Comment by ghost** [comment]
Yes, https://github.com/RaspberryPiFan/desktop-rpi4. Do not download this now, it's not a working build, the working build is only on my RPi now.

**Comment by varlevi** [comment]
Alright. I'll keep my eye out for the working build.

**Comment by ghost** [comment]
@varlevi Final build! I'll tell you how to compile.

**Comment by varlevi** [comment]
Do you mean that it is ready?

**Comment by ghost** [comment]
Oh no, found 1 bug right now, fix coming later

**Comment by ghost** [comment]
1. Boot up your Raspberry Pi 4 with Raspbian.
2. Open 2 terminal windows.
3. Type `git clone https://github.com/RaspberryPiFan/desktop-rpi4.git` in one of the windows.
4. Type `cd desktop-rpi` in both windows.
5. type `./patch.sh` in one windows
6. type `yarn && yarn build:dev` in the other one.
7. After that's finished, click in the window where you entered `./patch.sh` and press crtl and c.
8. type `yarn start-server` in one window.
9. type `dist/github-desktop-dev-linux-armv7l && ./github-desktop` in the other window

**Comment by ghost** [comment]
works now
(hopefully)

**Comment by varlevi** [comment]
does ./patch.sh need sudo rights? Its giving me a permission denied error. I looked it up online and couldn't find any info.

**Comment by ghost** [comment]
you need to add the execute permission

**Comment by ghost** [comment]
do
```
chmod +x ./patch.sh
chmod +x ./do-patch.sh
```

**Comment by ghost** [comment]
Did it work?

**Comment by varlevi** [comment]
Yes. The chmod commands worked! Unfortunately, after running the yarn-build command it gives me the error Failed to find Electron v5.0.6 for linux-arm at https://github.com/electron/electron/releases/download/v5.0.6/electron-v5.0.6-linux-arm.zip

**Comment by varlevi** [comment]
Does this mean I need to install electron for this to work?

**Comment by ghost** [comment]
No.
Can you make a Screenshot of the error please?

**Comment by varlevi** [comment]
Sure. Here it is:

![2019-11-02-100656_1360x768_scrot](https://user-images.githubusercontent.com/53223556/68072886-aa711d80-fd58-11e9-81ea-61853a6d7af7.png)

the error line is about fifteen lines down and is explained more around line 22.

**Comment by ghost** [comment]
Fix coming soon...

**Comment by varlevi** [comment]
Great! Thank you for all your help. Walking me through this is not something one usually does on GitHub, but it has been super helpful to me, and hopefully your answers to my questions can help others!

**Comment by ghost** [comment]
Stop the `./patch.sh` script and type the following in the window you use for patch.sh:
```
rm ./do-patch.sh
wget https://raw.githubusercontent.com/RaspberryPiFan/desktop-rpi4/linux/do-patch.sh
chmod +x ./do-patch.sh
./patch.sh
```
After you done that, run `yarn && yarn build:dev` in the other windows again

**Comment by ghost** [comment]
If you'll later get an error with git not found in a folder  called dugite (you'll probably get that) make an screenshot again.

**Comment by varlevi** [comment]
Hmm... When I run the last patch command it starts running this in an endless loop (I had to quit the terminal so that my computer didn't crash):

![2019-11-02-131602_1360x768_scrot](https://user-images.githubusercontent.com/53223556/68075241-26785f00-fd73-11e9-9c76-ea08a22b973f.png)

**Comment by ghost** [comment]
That's normal, do the other things in another window

**Comment by ghost** [comment]
It doesn't crashes the Raspberry Pi

**Comment by ghost** [comment]
I did it on my Pi, and it worked great

**Comment by ghost** [comment]
How much RAM do you have? It worked on a 4GB Pi

**Comment by varlevi** [comment]
I have 4GB as well, but after running all the commands, yarn build:dev is still giving me the same response. I opened up the file the error references, do you see any problems on the throw err line or a line around there?
![2019-11-02-132535_1360x768_scrot](https://user-images.githubusercontent.com/53223556/68075331-4d836080-fd74-11e9-968f-a957d5263ca7.png)

**Comment by ghost** [comment]
Is patch.js running **while** yarn is running?

**Comment by ghost** [comment]
In a separate window?

**Comment by varlevi** [comment]
I tried it both ways. With patch.js running, the yarn command wouldn't even finish, and without it running it gave me the error.

**Comment by varlevi** [comment]
I'm trying it again with patch.js running... Maybe I was just being impatient.

**Comment by ghost** [comment]
Yes, yarn takes really long

**Comment by ghost** [comment]
But it will work.

**Comment by ghost** [comment]
I tried it.

**Comment by varlevi** [comment]
Great, I'll let it load for a while.

**Comment by varlevi** [comment]
Okay, so it got past the electron part :), however the command did not finish still and gave me a 'Command failed with exit code 1' error.

**Comment by ghost** [comment]
Screenshot?

**Comment by varlevi** [comment]
![2019-11-02-135311_1360x768_scrot](https://user-images.githubusercontent.com/53223556/68075614-2038b180-fd78-11e9-962e-9a8fd37d7bb4.png)


It's down at the bottom.

**Comment by ghost** [comment]
Have you  done `sudo apt install gconf2 gconf-service libnotify4 libappindicator1 libxtst6 libnss3 libsecret-1-0 gnome-keyring`?

**Comment by varlevi** [comment]
I did, but that was before I installed yarn, so I'll try again.

**Comment by varlevi** [comment]
Hmm... That didn't seem to work either. However, the command took much less time, so I think the last part is the only part that did not work.

**Comment by ghost** [comment]
No, do `sudo apt install libsecret-1-dev -y`

**Comment by ghost** [comment]
Now try yarn again.
You'll get an error later, but I need to compile a fix, this wi ll take around 15 mins

**Comment by varlevi** [comment]
Got it.

**Comment by ghost** [comment]
It will take longer, I need to recompile parts of git for the RPi, there are only prebuilts for PC

**Comment by varlevi** [comment]
Okay. That's fine. Thank you for taking time to do this project. I'm sure it will be very helpful to me and others.

**Comment by ghost** [comment]
Can take 1 hour

**Comment by ghost** [comment]
I'm finished. Are you still online?

**Comment by varlevi** [comment]
Yes.

**Comment by varlevi** [comment]
Should I try running the yarn command again?

**Comment by ghost** [comment]
No, wait, I'm uploading something

**Comment by varlevi** [comment]
:+1:

**Comment by ghost** [comment]
Download this: https://github.com/RaspberryPiFan/desktop-rpi4/raw/linux/dugite-native-armv7l.tar.gz
Extract the content into <folder with github desktop>/app/node_modules/dugite/git

**Comment by varlevi** [comment]
Do I need to create the git folder? I don't see it in the dugite folder.

**Comment by ghost** [comment]
Yes, create it.

**Comment by ghost** [comment]
Run the yarn command again: `yarn && yarn build:dev`
patch.sh must be running

**Comment by ghost** [comment]
If you didn't start it

**Comment by varlevi** [comment]
Okay. Now something really weird is happening. I extracted the new folder to the git folder, which worked fine, but then (as soon as I ran the yarn command) the same error came up, and the git file was _deleted._ I tried extracting the files and running the command multiple times with the same results. Watching the dugite folder in the file manager, the git folder disappears right before the error shows up in the console.

**Comment by ghost** [comment]
Ok. I'll fix this.

**Comment by ghost** [comment]
Create a new folder called `git` in the main dir and extract the content of the zip file there

**Comment by varlevi** [comment]
You mean desktop-rpi4?

**Comment by ghost** [comment]
No, zip was wrong, I meant that file where you copied dugite/git from

**Comment by ghost** [comment]
Then stop patch.sh and update and restart it in the patch.sh window with
```
rm ./do-patch.sh
wget https://raw.githubusercontent.com/RaspberryPiFan/desktop-rpi4/linux/do-patch.sh
chmod +x ./do-patch.sh
./patch.sh
```

**Comment by ghost** [comment]
Now try `yarn && yarn build:dev` again.

**Comment by varlevi** [comment]
Alright. So after doing those commands, ./patch.sh is not being recognized again, and unfortunately I won't have access to my computer for a while. I will try this again when I can access my computer again. Thank you again for your time preparing this fork and helping my through the process. I hope my questions are helping probe for bugs, etc.

**Comment by ghost** [comment]
ok.

**Comment by ghost** [comment]
Deleted the repo, will re-upload it soon

**Comment by ghost** [comment]
Moved there: https://github.com/RaspberryPiFan/desktop

**Comment by ghost** [comment]
Final build coming soon...

**Comment by ghost** [comment]
Did you try it?

**Comment by varlevi** [comment]
Just got around to this! It's working on running the yarn command right now.

**Comment by lachlan-00** [comment]
can you bring this back into a list of commands to build for https://github.com/RaspberryPiFan/desktop/tree/2.2.2-Pi?

The patch.sh is also pointing outside the source directory
![image](https://user-images.githubusercontent.com/1305249/72037120-bcd37e80-32e8-11ea-9055-a99044ab2630.png)

**Comment by shiftkey** [comment]
This is neat to see unfold. Similar to #86, I can't support Raspberry Pi distributions currently without a version of Git that can be used there. If there are changes I can take in to help with building the project for your situation, please let me know (or just open a PR to start the discussion).
