### ISSUE TITLE
Immediately segfaults on debian 9.

### ISSUE THREAD

**Issue by seanmorris** [shiftkey/desktop#189]
### Describe the bug

It immediately segfaults on debian 9.

### Version & OS

github-desktop (beta) 2.1.0-linux1 from Snapcrafters installed

Linux the-altar 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

### Steps to reproduce the behavior

1. $ sudo snap install github-desktop --beta --classic
2. $ github-desktop
3. Segmentation fault

### Expected behavior

It doesn't segfault.

### Actual behavior

segfault

### Screenshots

![image](https://user-images.githubusercontent.com/640101/68439248-dd6e4380-0194-11ea-86be-0fa666d1ef92.png)

### Logs

Segmentation fault

### Additional context

Segmentation fault

**Comment by szszoke** [comment]
It is also happening on Kubuntu 19.10 on the `5.0.0-36-generic` kernel.

**Comment by shiftkey** [comment]
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps like this one. Please follow along with #203 in the meantime.
