### ISSUE TITLE
undefined symbol: g_date_copy

### ISSUE THREAD

**Issue by AAYamoldin** [shiftkey/desktop#190]
hello
I am using Linux Mint 19.2 Cinnamon and after I install GitHub desktop as
`sudo snap install github-desktop --beta --classic
`
and after `github desktop
`
I have an error
`/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
`

Could you explane me how to solve it?

**Comment by EricGrahamMacEachern** [comment]
I have the same problem. I am on Ubuntu 18.04 with kernel 4.15.0-72-generic. Did you install it with a snap using these instructions? I did. 

[How to install GitHub Desktop on Ubuntu](https://snapcraft.io/install/github-desktop/ubuntu)


```
eric@custom:~$ github-desktop
/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
eric@custom:~$ 

```

**Comment by jonasmoeller** [comment]
Try installing the .deb package, that worked for me instead of the snap version.

**Comment by iNewLegend** [comment]
> Try installing the .deb package, that worked for me instead of the snap version.

where is the .deb package?

**Comment by doktorfysik** [comment]
> > Try installing the .deb package, that worked for me instead of the snap version.
> 
> where is the .deb package?

There is one here that I got to work on Ubuntu 18.04:
https://github.com/shiftkey/desktop/releases/tag/release-2.1.0-linux1

**Comment by jonasmoeller** [comment]
@iNewLegend try the package @doktorfysik linked, it should work without any problems.

**Comment by iNewLegend** [comment]
@y3kth0 works.

**Comment by AAYamoldin** [comment]
I didn´t solve the podlem with 2.1.0 version and install 2.0.4 
all works ok.
