### ISSUE TITLE
/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy

### ISSUE THREAD

**Issue by Alessio-Rigoli** [shiftkey/desktop#192]
### Describe the feature or problem you’d like to solve
Good morning how are going,
I recently installed the GitHub desktop application via SNAP and recieved the following error when trying to launch the application and was wondering if this was a known bug or a solution exists.
Thanks

**Comment by immackay** [comment]
Hi there, gonna point you towards #163 - there's instructions for downgrading the snap there, alternatively you can install the .deb

**Comment by Alessio-Rigoli** [comment]
Thank you, I'll give that a try.

**Comment by shiftkey** [comment]
Closing this out as a duplicate of #163
