### ISSUE TITLE
Some repositories are missing / cannot commit to

### ISSUE THREAD

**Issue by mem48** [shiftkey/desktop#194]
### Describe the bug

In the list of repositories that can be cloned from GitHub, some are missing. It seems that not all organisations (and their repositories) are listed. This is different to how GitHub desktop works on Windows. It is possible to clone these repositories using the URL manually, but I cannot commit to the repositories as I get the error message "Authentication Failed."

### Version & OS

Version 2.1.0-linux on Linux Mint 19.3 Cinnamon 64 Bit.

### Steps to reproduce the behaviour
1. Go to clone a repository
2. On the GitHub.com tab
3. See the list of repositories listed

### Expected behaviour

All repositories associated with my account should be listed, this is what happens with GitHub desktop on Windows.

### Actual behaviour

Personal repositories and some organisations are listed, but most organisations and their repositories are missing.

**Comment by shiftkey** [comment]
This is because this is an unofficial distribution of Desktop, and some organizations are configured to restrict the OAuth apps that they trust. #72 has more details.
