### ISSUE TITLE
timeout on signin due to querying for libsecret backend

### ISSUE THREAD

**Issue by Meetem** [shiftkey/desktop#195]
### Describe the bug
SignIn doesn't work while using wayland with plasma desktop (works fine in X11 with plasma)
Not application SignIn, nor browser one works.

After a while applications reports an error with following text:
"Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached"

### Version & OS
Kubuntu 20.04
Linux 5.4.7-050407-generic
GitHub Desktop version 2.1.0-linux1

### Steps to reproduce the behavior
1. Install GitHub Desktop via AppImage in Kubuntu with X11 session. 
2. SignIn with your account via app
3. Change WM to Wayland
4. Get error "Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached"
5. Try to SignIn again

### Logs
[2020-01-03.desktop.production.log](https://github.com/shiftkey/desktop/files/4019981/2020-01-03.desktop.production.log)

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by hholst80** [comment]
It's unlikely that it's a wayland specific problem. Rather it is connected to the dbus magic. How do you launch wayland?

This works for me:

```
QT_QPA_PLATFORM=wayland XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
```

**Comment by shiftkey** [comment]
Seeing `org.freedesktop.secrets` mentioned here makes me think there's a missing backend to handle the request for credentials that we do during the sign in process.

Currently `gnome-keyring` is the only supported backend for `libsecret` that I'm aware of, but I hear recent versions of `keepassxc` might also support it in recent versions: https://github.com/atom/node-keytar/issues/74#issuecomment-595249207

@Meetem can you confirm that you have `gnome-keyring` installed? KWallet does not support the `libsecret`-based API that we use to store and retrieve credentials that are critical to the sign-in flow.

**Comment by shiftkey** [comment]
Closing this out due to inactivity.
