### ISSUE TITLE
Ignores Git credential helper setting, making it incompatible with GCM4ML entries in GNOME Keyring

### ISSUE THREAD

**Issue by bviktor** [shiftkey/desktop#197]
### Describe the bug

[GCM4ML](https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux) adds entries for HTTP remotes in the form of

```
git:https://git.foobar.com
```

The credential helper is:

```
credential.helper=!/etc/alternatives/java -Ddebug=false -Djava.net.useSystemProxies=true -jar /usr/local/bin/git-credential-manager.jar
```

That works fine from the command line, i.e. if I `git pull`, it works just fine, no credentials are asked for.

However, GitHub Desktop for Linux seems to ignore these entries and asks for a username and password.

Could Desktop please rely on the `credential.helper` entry first, attempt to use it, and only ask for credentials if that fails?

### Version & OS

GitHub Desktop 2.1.0-linux1 on Ubuntu 18.04.

### Steps to reproduce the behavior

Install Ubuntu Desktop 18.04, then

```
sudo apt install default-jre-headless gnome-keyring seahorse libgnome-keyring-dev
``` 

Obtain GCM4ML:

```
sudo wget https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux/releases/download/git-credential-manager-2.0.4/git-credential-manager-2.0.4.jar -o /usr/local/bin/git-credential-manager.jar
```

Set the credential helper:

```
git config --global 'credential.helper' '!/etc/alternatives/java -Ddebug=false -Djava.net.useSystemProxies=true -jar /usr/local/bin/git-credential-manager.jar'
```

Then push/pull a repo via HTTP origin that requires authentication. This adds a new entry to GNOME Keyring (Seahorse) under the **Passwords / Login** key. Further pull/push actions should work without asking for credentials.

Then install Desktop, e.g.

```
wget https://github.com/shiftkey/desktop/releases/download/release-2.1.0-linux1/GitHubDesktop-linux-2.1.0-linux1.deb
sudo dpkg -i GitHubDesktop-linux-2.1.0-linux1.deb
```

Open the same repo, and try to push/pull.

### Expected behavior

GitHub Desktop authenticates properly using the set credential helper.

### Actual behavior

GitHub Desktop not only ignores the credential helper, it forcefully removes any entry, at least according to log entries like this:

```
2020-01-08T10:29:45.464Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 3.519s)
```

### Screenshots

N/A

### Logs

See above.

### Additional context

N/A

**Comment by shiftkey** [comment]
> Could Desktop please rely on the `credential.helper` entry first, attempt to use it, and only ask for credentials if that fails?

This is not something I can currently support because of how GitHub Desktop authenticates - it uses the `GIT_ASKPASS` environment variable to invoke itself and retrieve credentials that are stored by this app. This helps us support GitHub authentication and things like 2FA, and it should fallback to username and password for non-GitHub remotes.

If you successfully authenticate there, it should remember those credentials if it can access your keyring. It should a different pattern to other programs, but sadly interop with GCM hasn't been on my radar for a while.
