### ISSUE TITLE
在路径org.freedesktop.secret.collection的对象上没有/org/freedesktop/secrets.collection.login接口

### ISSUE THREAD

**Issue by dangxusheng** [shiftkey/desktop#199]
When I log in, this error pops up. 

error detail : 
  在路径org.freedesktop.secret.collection的对象上没有/org/freedesktop/secrets.collection.login接口

environment info: ubuntu 18.04 LTS, install by .deb,  GitHubDesktop-linux-2.0.4-linux1.deb

**Comment by shiftkey** [comment]
I believe this is related to the lack of `gnome-keyring` being installed. #186 was merged and is now available in the newer versions - please retest and confirm whether this resolves the issue for you.
