### ISSUE TITLE
Appimage Update

### ISSUE THREAD

**Issue by vctrro** [shiftkey/desktop#200]
### Describe the feature or problem you’d like to solve

Add update functionality to the Appimage assembly. 
https://github.com/AppImage/AppImageUpdate

### Proposed solution

This will make it easier for users to update the program.

### Additional context

![image](https://user-images.githubusercontent.com/14020725/73748357-ad721480-4772-11ea-8b73-284eebb4d07e.png)

**Comment by shiftkey** [comment]
This is a problem currently because of how we leverage `electron-builder`:

https://docs.appimage.org/packaging-guide/optional/updates.html#using-electron-builder

> `electron-builder` promotes its own updater scheme rather than the update information described in this documentation, in order to have the same mechanism on Linux as is used on Windows. **Unfortunately this means that AppImages generated by `electron-builder` cannot be updated using the usual tools.**

I've been planning to move away from `electron-builder` for multiple reasons, but for now the workaround proposed is also non-trivial:

> One way to inject the update information into the AppImage created with `electron-builder` nevertheless is to extract the AppImage generated with electron-builder to an AppDir using the `–appimage-extract` command line option of the AppImage, and then re-packing it as an AppImage by using `appimagetool -u`.

**Comment by shiftkey** [comment]
Closing this out to signal that I don't have bandwidth to support this, but if someone wants to explore this they are welcome to take a shot at it.
