### ISSUE TITLE
[Snap] re-enable Snap installer once we have a working build again

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#202]
It looks like 2.1.0 doesn't work because of changes to the packaging process for Snap - probably related to changes to the docker tooling and what electron-builder needs. 

#163 is the big issue, but it mentions a lot of unrelated thing so I plan to use this issue to track how to properly package the app for distribution in the Snap store (which I've unlisted for the moment to prevent more bad installs).

**Comment by shiftkey** [comment]
I wanted to see if I could get this working again but after installing the latest version of snapcraft and enabling KVM on this machine I just can't seem to build even a trivial package:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"

$ snap --version
snap    2.44.1
snapd   2.44.1
series  16
ubuntu  19.10
kernel  5.3.0-45-generic

$ snapcraft --version
snapcraft, version 3.10.2

$ less snap/snapcraft.yaml
name: github-desktop
version: 2.4.0
summary: Simple collaboration from your desktop
description: |
  App description
grade: stable
confinement: classic
apps:
  github-desktop:
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - unity7
      - x11
      - browser-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    command: bin/electron-launch '$SNAP/github-desktop/GitHub Desktop'

parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
  github-desktop:
    after:
      - gnome
    plugin: dump
    source: dist/github-desktop-linux-x64
    stage-packages:
      - fcitx-frontend-gtk3
      - gvfs-libs
      - libasound2
      - libgconf-2-4
      - libglib2.0-bin
      - libgnome-keyring0
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxss1
      - libxtst6
      - zlib1g

base: core18

$ snapcraft snap --config snap/snapcraft.yaml 
Using config file: snap/snapcraft.yaml
Configuration file is experimental and is subject to change.
Launching a VM.
error: no changes of type "auto-refresh" found                                  
snap "snapd" has no updates available
Could not find snap/snapcraft.yaml. Are you sure you are in the right directory?
To start a new project, use `snapcraft init`
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.

$ snapcraft init
snap/snapcraft.yaml already exists!
```

**If anyone more familiar with packaging snaps would be able to help get to the bottom of this, it'd be greatly appreciated. But currently I cannot revisit this support and would rather spend my time elsewhere.**

**Comment by cjp256** [comment]
@shiftkey  That `--config` option slipped in unnoticed and is not what you would expect. I opened a PR to remove that in snapcraft.

Nonetheless, there appears to be another issue here.  Do you by chance have ecryptfs enabled on your home directory (or wherever the project data is)?

I'll continue looking into it and see if we can get this fixed up :)

**Comment by shiftkey** [comment]
Closing this out as I don't have the bandwidth to revisit this in the short or medium term. If someone else wants to have a shot at this there are notes earlier in the issue about what's changed. 

Getting this building and working again is the first step for us to be able to support this again, and someone willing to step up and support this who has more familiar than myself about this is essential.
