### ISSUE TITLE
Build failed on Fedora 31

### ISSUE THREAD

**Issue by jfclere** [shiftkey/desktop#215]
### Describe the bug

Build failed with:
Error: Could not detect abi for version 7.1.8 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
### Version & OS

Master and fedora 31.
### Steps to reproduce the behavior

1. check out repo
2. yarn
3. get the error
+++
error /home/jfclere/TMP/desktop/app/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/jfclere/TMP/desktop/app/node_modules/keytar
Output:
/home/jfclere/TMP/desktop/app/node_modules/node-abi/index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 7.1.8 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/home/jfclere/TMP/desktop/app/node_modules/node-abi/index.js:30:9)
+++

### Expected behavior

build without problem.

### Actual behavior

not able to  build.

### Additional context

I have tried npm too: same problem.

**Comment by jfclere** [comment]
[jfclere@pc-7 desktop]$ node -v
v12.13.1

**Comment by shiftkey** [comment]
@jfclere do you have the additional dependencies for building on Linux? There's some instructions for Fedora in https://github.com/shiftkey/desktop/blob/linux/docs/contributing/setup-linux.md#electron-dependencies which should ensure that keytar falls back to being built from source if `prebuild-install` doesn't find the right version.

**Comment by jfclere** [comment]
missing libsecret-devel was the problem, sorry for the noise.
