### ISSUE TITLE
yarn build:dev failed on fedora31

### ISSUE THREAD

**Issue by jfclere** [shiftkey/desktop#216]
### Describe the bug

yarn build:dev
gives:
+++
WEBPACK] Finished building highlighter.js within 3.413 seconds
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Checking started in a separate process...
✖ ｢atl｣: Checking finished with 1 errors
(node:541637) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Build failed after 23.603 seconds
(node:541637) Warning: a promise was rejected with a non-error: [object Object]
(node:541637) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Errors building cli.js
[at-loader] ./app/src/main-process/main.ts:445:18 
    TS2345: Argument of type '{ window: BrowserWindow | null; }' is not assignable to parameter of type 'PopupOptions'.
  Types of property 'window' are incompatible.
    Type 'BrowserWindow | null' is not assignable to type 'BrowserWindow | undefined'.
      Type 'null' is not assignable to type 'BrowserWindow | undefined'.
error Command failed with exit code 1.
+++

### Version & OS

master

### Steps to reproduce the behavior

1. run: yarn build:dev
2. See error

### Expected behavior

successful build.

### Additional context

window: BrowserWindow makes me think that I missed something related to configuration but I can't find where.. I have used strace -f but can't find missing libraries neither decide for a missing file.

**Comment by shiftkey** [comment]
@jfclere can you confirm that `yarn` passes before running `yarn build:dev` and that it's not trying to use an old version of Electron and this error is related to using the older type declarations?

**Comment by jfclere** [comment]
yarn passes:
[jfclere@dhcp-144-218 desktop]$ yarn
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ ts-node -P script/tsconfig.json script/post-install.ts
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 3.91s.
yarn run v1.17.3
$ tsc -P tslint-rules
Done in 3.29s.
yarn run v1.17.3
$ tsc -P script/tsconfig.json
Done in 5.15s.
Done in 14.17s.
[jfclere@dhcp-144-218 desktop]$ echo $?
0

**Comment by shiftkey** [comment]
Also, the `master` branch doesn't exist on this repository. Can you share the specific commit you're using?

```
$ git rev-parse HEAD
```

**Comment by jfclere** [comment]
jfclere@dhcp-144-218 desktop]$ git rev-parse HEAD
be51c6b7f87804ab20c0bbc2517c3e87baa0b40e

**Comment by shiftkey** [comment]
@jfclere I don't see that commit on this repository:

```
$ git show be51c6b7f87804ab20c0bbc2517c3e87baa0b40e
fatal: bad object be51c6b7f87804ab20c0bbc2517c3e87baa0b40e
```

Are you able to test using the `linux` branch which reflects a known commit that's currently passing CI:

```
$ git checkout linux
```

**Comment by jfclere** [comment]
I have restarted from scratch:
git clone https://github.com/shiftkey/desktop
git checkout linux
yarn
yarn build:dev
yarn start
so it is working.
Next using sign in using you browser doesn't work :-(
![Screenshot from 2020-02-12 18-19-16](https://user-images.githubusercontent.com/316679/74413417-a8325b00-4e3f-11ea-9ee8-76a771086c62.png)

**Comment by shiftkey** [comment]
I'm glad you got this working!

> Next using sign in using you browser doesn't work :-(

#134 and #72 are relevant to this, and are not going to be resolved in the near term
