### ISSUE TITLE
Debian package still named "desktop"

### ISSUE THREAD

**Issue by mitar** [shiftkey/desktop#22]
Using 1.0.12 Linux RC1 .deb file. You can see in the `DEBIAN/control` file inside it that package is still named `desktop` and not `github-desktop` or something like that. I think this name is way to generic to be useful as a package name.

**Comment by shiftkey** [comment]
Yeah, I had a go at this in #20 but all roads lead back to the `app/package.json` `name` entry.

**Comment by shiftkey** [comment]
I _think_ this is associated with `electron-packager`'s behaviour, and either needs to be addressed there or in the application itself.
