### ISSUE TITLE
How to open/run on Linux?

### ISSUE THREAD

**Issue by szafranski** [shiftkey/desktop#223]
Hello, which file to run to open the software on Linux? Thanks

**Comment by shiftkey** [comment]
Please check out the [releases page](https://github.com/shiftkey/desktop/releases) for the installers, and the instructions for your distribution about how to install the package.

**Comment by szafranski** [comment]
I haven’t seen assets. Thanks!

**Comment by szafranski** [comment]
Is it possible to run this software on 32bit Linux?

**Comment by shiftkey** [comment]
> Is it possible to run this software on 32bit Linux?

Only 64-bit is currently supported. No plans for 32-bit.

**Comment by szafranski** [comment]
K. Thanks!
