### ISSUE TITLE
Button 'Open in Visual Studio Code' does not open visual studio code on ubuntu

### ISSUE THREAD

**Issue by JvGldr** [shiftkey/desktop#224]
### Describe the bug

Button 'open in visual studio' does not open visual studio on ubuntu. Message in logfile: 
2020-03-06T14:44:40.312Z - info: [ui] Current tutorial step is NotApplicable

### Version & OS

Version 2.3.1-linux1
Ubuntu 18.04.4 LTS

### Steps to reproduce the behavior

1. Go to 'Main screen of yhe client app'
2. Click on 'Open in Visual Studio Code''
3. Nothing happens

### Expected behavior

I expect Visual Studio Code to open the local GitHub folder containing the repo. (just like the windows version does)

### Actual behavior

Nothing happens, no feedback, no error message.

### Screenshots

n.a.

### Logs

2020-03-06T14:44:40.312Z - info: [ui] Current tutorial step is NotApplicable

### Additional context

similar to other issues, but the editor is detected, it just doesn't start

**Comment by shiftkey** [comment]
@JvGldr thanks for the report.

We look for VSCode in these locations:

https://github.com/shiftkey/desktop/blob/5d21312a1704e7d93ac029f31ad42c6668f6452a/app/src/lib/editors/linux.ts#L69

I gather those are working fine, but as the problem seems to be related to launching the editor can you confirm that there's no problems with launching `code` from a shell on your local machine (using the full path)?

**Comment by JvGldr** [comment]
@shiftkey Yes, I can confirm that: /snap/bin/code from a shell launches the editor.

**Comment by shiftkey** [comment]
@JvGldr if you open **View**  | **Toggle Developer Tools** and try the steps again does it show any interesting errors in the Console tab?

**Comment by JvGldr** [comment]
@shiftkey I've checked the console, but I do not see any errors. I've also tried the other two buttons (Show in Explorer and View Github) The only message that pop up (in all three cases) in the console is this infor message:  info: [ui] Current tutorial step is NotApplicable, but that is after the command has been executed e.g. after going to GitHub on the web.

**Comment by ankurkotwal** [comment]
@shiftkey I'm having the same issue on Ubuntu 19.10 as well. I tried the things you listed here and have the same results as @JvGldr

**Comment by shiftkey** [comment]
> I've also tried the other two buttons (Show in Explorer and View Github)

@JvGldr do these work too? I want to confirm we're focused on just the editor issue.

I don't have anything obvious to poke at right now after testing again on Ubuntu 19.10 (works here, and I have VSCode installed via snap), but I'll provide some context while I think and make time to dig into it. We use the NodeJS [`spawn`](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html) API to launch the editor, but we don't do any inspection of the `ChildProcess` returned by `spawn` to see if it exits or whether it emits some errors.

https://github.com/shiftkey/desktop/blob/dcfafa35b4033edee7c966b9901c2e06bf6e1935/app/src/lib/editors/launch.ts#L26-L30

I thought these would error out and put something into the main app, but maybe we need better tracing in here.

**Comment by JvGldr** [comment]
@shiftkey : The other two buttons work fine! The issue only concerns the open in 'Visual Studio Code' button.

**Comment by ankurkotwal** [comment]
This is now working for me in 2.4.0-linux1 RC1.

**Comment by JvGldr** [comment]
Works fine now in Version 2.4.0-linux1! @shiftkey: Thanx for fixing!

**Comment by shiftkey** [comment]
@JvGldr @ankurkotwal thanks for verifying - I'm not sure I did anything specific so it must have been fixed upstream! 

Closing this out as resolved, but please comment if anyone else spots this in the latest version.
