### ISSUE TITLE
I don't see .deb

### ISSUE THREAD

**Issue by Matyu9** [shiftkey/desktop#226]
Je suis un utilisateur de DÉBIAN mais je ne trouve pas la sortie .deb où est elle???

**Comment by shiftkey** [comment]
Please check the Releases page: https://github.com/shiftkey/desktop/releases

Each release lists the corresponding installers at the bottom, along with the checksums for each installer:

<img width="838" src="https://user-images.githubusercontent.com/359239/76355894-d5b1dd80-62f3-11ea-9f7c-0669d57cfa09.png">
