### ISSUE TITLE
Debian package installed into /opt/GitHubDesktop

### ISSUE THREAD

**Issue by mitar** [shiftkey/desktop#23]
This is not really a standard path on Debian/Ubuntu. I think it should just go under `/usr/lib`.

**Comment by shiftkey** [comment]
This is a convention from [`electron-builder`](https://github.com/electron-userland/electron-builder/blob/fd2a1f0794d6f4ded47baa7091fe70fc1628f1b5/packages/electron-builder-lib/src/targets/LinuxTargetHelper.ts#L12) which I believe is aliased to `/usr/local/bin` [after install](https://github.com/electron-userland/electron-builder/blob/4ea9f03882945f320b8c5cef330444ea0b8daad0/packages/electron-builder-lib/templates/linux/after-install.tpl#L4).

**Comment by mitar** [comment]
Yes, I can confirm that there is a symlink in `/usr/local/bin`.

To me it is just surprising that it goes into `/opt` for Debian package. I can understand custom install scripts putting things there, but for Debian package, I am more used to `/usr`.

Anyway, not a major thing.

**Comment by shiftkey** [comment]
Please raise this against the upstream `electron-builder` project if it's a thing that you think should be changed. I'm going to close this out because it's something we're stuck with unless we move away from `electron-builder` to something else.
