### ISSUE TITLE
Provide an option to disable Client Side Decoration (CSD) for GitHub Desktop window

### ISSUE THREAD

**Issue by alitajelsir** [shiftkey/desktop#232]
### Describe the feature or problem you’d like to solve

There is no way to disable CSD for GitHub desktop window (it doesn't work with [gtk3-nocsd](https://github.com/ZaWertun/gtk3-nocsd)). The app can't use the system title bar. 

### Proposed solution

Provide an option to disable CSD for GitHub desktop window. This will provide uniform look for apps in KDE.

### Additional context

Chromium with no CSD vs GitHub Desktop:
![github-nocsd](https://user-images.githubusercontent.com/26362874/77156415-00e0bd80-6aa8-11ea-8dc6-d5fdd8c36fff.png)

**Comment by shiftkey** [comment]
I think this might be related to #149

**Comment by alitajelsir** [comment]
Thanks I'll continue posting in #149 and close this issue. Thanks for your efforts.
