### ISSUE TITLE
Scrollbar remains white in dark mode

### ISSUE THREAD

**Issue by khvorov45** [shiftkey/desktop#236]
### Describe the bug

Scrollbar remains white in dark mode.

### Version & OS

Version: 2.3.1-linux1
OS: Linux Mint 19.3 Cinnamon

### Screenshots

![Screenshot from 2020-03-27 12-37-57](https://user-images.githubusercontent.com/44919476/77712699-abb52680-7028-11ea-8c52-aa6bf871700a.png)

**Comment by shiftkey** [comment]
I wonder if we need to do the same thing for Linux as we do on Windows:

https://github.com/shiftkey/desktop/blob/63a27d2f40edc0b82d01ca936da80f1ca7793187/app/styles/ui/_scroll.scss#L3-L28

https://github.com/shiftkey/desktop/blob/63a27d2f40edc0b82d01ca936da80f1ca7793187/app/styles/themes/_dark.scss#L39-L53
