### ISSUE TITLE
Ditch the CSD

### ISSUE THREAD

**Issue by codic12** [shiftkey/desktop#243]
The CSD is meant for windows and looks out-of-place on linux. It'd be nice to let the window manager handle the decorations instead ;)

**Comment by codic12** [comment]
(CSD==Client Side Decorations, aka the custom window decorations)

**Comment by shiftkey** [comment]
@gsbhasin123 thanks for the suggestion. This was previously reported in #232 and I have an earlier issue open #149 to track this - please follow along with that discussion.

The work to do this is in #237 and I want to confirm this is what the community prefers.

**Comment by codic12** [comment]
Oh, thank you! Did not know.
