### ISSUE TITLE
Support Linux ARM

### ISSUE THREAD

**Issue by hmsjy2017** [shiftkey/desktop#245]
I think that it is a good choice to support machines that runs Linux ARM32/ARM 64 like Raspberry  Pi and Orange Pi. In this case, some beginners can use git more conveniently.

**Comment by shiftkey** [comment]
@hmsjy2017 thanks for your interest.

A while ago the Desktop team stopped distributing an ARM64 version of Git in the `dugite-native` package that would be necessary to support running on these platforms, so without an alternative way of invoking Git and the engineering work to incorporate it into our builds, this isn't going to happen.

https://github.com/desktop/dugite-native/pull/315 has more context behind the change.

**Comment by hmsjy2017** [comment]
Why not use its old version?I think it still works, although it is no longer officially supported.

**Comment by shiftkey** [comment]
> Why not use its old version?

For me, not receiving security updates to Git is the biggest concern about staying on an old version. ([Here's an example from December of several CVEs that would affect users if we stayed on older version.](https://lore.kernel.org/git/xmqqr21cqcn9.fsf@gitster-ct.c.googlers.com/T/#u)).

**Comment by shiftkey** [comment]
Closing this out in favour of #251 which outlines what I think are the blockers to being able to achieve this. Please follow along with that issue.
