### ISSUE TITLE
GitHub Desktop doesn't open on my LMDE [SOLVED]

### ISSUE THREAD

**Issue by caiomtls** [shiftkey/desktop#250]
### Operating System/Distribution

Linux Mint Debian Edition 4

### Installer

2.4.0 Linux RC2
Terminal dpkg

### What happened?

I install the .deb, but after  installing it doesn't open, but the version 2.1.0 Linux RC1 works fine and the others below.

**Comment by shiftkey** [comment]
Given Linux Mint is Debian based I wonder if this isn't similar to #222. 

@CaioMatheu5 any error messages or output when launching `github-desktop` that might indicate whether it's related?

**Comment by caiomtls** [comment]
@shiftkey I didn't received any error messages or output when launching github-desktop. So, I don't think is that similar to #222. 

And thank you very much @shiftkey for supporting GNU/Linux.

**Comment by shiftkey** [comment]
@CaioMatheu5 what about the output from this command - any interesting clues about missing shared libraries?

```
$ ldd /usr/bin/github-desktop
```

**Comment by caiomtls** [comment]
I got this output. And as I'm a noob, I don't know what this means.

        linux-vdso.so.1 (0x00007fffd39ef000)
	libffmpeg.so => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc25eb25000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc25eb04000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc25eafa000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fc25eaa5000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fc25e986000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fc25e7c6000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fc25e685000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fc25e680000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fc25e656000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fc25e453000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fc25e446000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fc25e43f000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fc25e22d000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fc25e027000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fc25de17000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fc25dc0d000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007fc25da07000)
	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007fc25d8b7000)
	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007fc25d885000)
	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007fc25d856000)
	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007fc25d815000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fc25d7ef000)
	libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007fc25d0fe000)
	libgdk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007fc25d000000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fc25cff0000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fc25cfa5000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fc25cf7c000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fc25ce5c000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fc25ce09000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fc25cdca000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fc25cdc1000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fc25cbb6000)
	libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007fc25cbb1000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fc25cab0000)
	libatk-bridge-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007fc25ca7b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc25c8f6000)
	libatspi.so.0 => /usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x00007fc25c8c2000)
	libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007fc25c82f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc25c815000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc25c654000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc265a3c000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fc25c64a000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fc25c5d4000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fc25c5ce000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc25c3b0000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fc25c351000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fc25c129000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fc25c10f000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fc25bf09000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fc25bd03000)
	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007fc25bcfc000)
	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007fc25bcf7000)
	libcairo-gobject.so.2 => /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007fc25bceb000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fc25bca7000)
	libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fc25bc9d000)
	libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fc25bc98000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fc25bc87000)
	libepoxy.so.0 => /usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007fc25bb55000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fc25ba5a000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fc25ba3f000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fc25b9f9000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fc25b93d000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fc25b938000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fc25b92d000)
	libfribidi.so.0 => /usr/lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007fc25b90e000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fc25b868000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fc25b82f000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fc25b82a000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fc25b81b000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fc25b778000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fc25b72b000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fc25b57f000)
	libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007fc25b571000)
	libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007fc25b55e000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fc25b509000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fc25b4ed000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fc25b4c0000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fc25b4b6000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fc25b48e000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fc25b46f000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fc25b34f000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fc25b26f000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fc25b23b000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fc25b235000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fc25b226000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fc25b21f000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fc25b0ee000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fc25b0cf000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fc25af4b000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fc25ad38000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fc25ad00000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007fc25acc7000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fc25ac42000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fc25ac1f000)

**Comment by caiomtls** [comment]
Now I'm getting this message on the terminal we I run $ github-desktop

**Comment by caiomtls** [comment]
I managed to make it run by using:
$ github-desktop --no-sandbox

But this message it's shown:
[22437:0408/193712.660679:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(electron) 'getZoomFactor function' is deprecated and will be removed. Please use 'zoomFactor property' instead.

**Comment by jfgordon2** [comment]
@CaioMatheu5 have you tried setting the user ID of the chrome-sandbox executable?

`sudo chmod 4755 '/opt/GitHub Desktop/chrome-sandbox'`

**Comment by shiftkey** [comment]
@CaioMatheu5 

>But this message it's shown:
> ```
> [22437:0408/193712.660679:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
> (electron) 'getZoomFactor function' is deprecated and will be removed. Please use 'zoomFactor property' instead.
> ```

These messages are just warnings once the application is running. Feel free to ignore them.

**Comment by caiomtls** [comment]
@jfgordon2 Yep, I've tried this solution. But when I attempted to run GitHub Desktop, I received this message on the terminal: 

`trace/breakpoint trap (core dumped)` 

And it stopped to work at all. If a reinstall and use `--no-sandbox` it works. 
The version 2.1.0 it's working fine to me, so I just accepted it for now. 
Thanks for the suggestion @jfgordon2.

**Comment by jfgordon2** [comment]
@CaioMatheu5 it might be worth trying [enabling user name spaces](https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel) - my suspicion is that this is related to #222:
`sudo sysctl -w kernel.unprivileged_userns_clone=1`

**Comment by caiomtls** [comment]
YES! IT WORKS!
Thank you so much guys! @jfgordon2 @shiftkey 
You are amazing!
