### ISSUE TITLE
Could not install on Linux debian

### ISSUE THREAD

**Issue by ivan-vitenko** [shiftkey/desktop#252]
### Operating System/Distribution
Debian GNU/Linux 10 (buster)

### Installer
GitHubDesktop-linux-2.4.0-linux2.deb
dpkg -i GitHubDesktop-linux-2.4.0-linux2.deb

### What happened?
unlink: не вдалося вилучити посилання '/usr/bin/github-desktop-dev': Немає такого файла або каталогу
I have a message in the terminal in Ukrainian. It can be translated as "unlink: failed to remove link '/usr/bin/github-desktop-dev': No such file or directory"

**Comment by shiftkey** [comment]
Thanks for opening this up @ivan-vitenko!

> "unlink: failed to remove link '/usr/bin/github-desktop-dev': No such file or directory"

cc @jfgordon2 as it looks like it's related to this part of removing the previous version

https://github.com/shiftkey/desktop/blob/ef558fd74d51352ab0d3e4857ec7cbf8871e4958/script/linux-after-remove.sh#L11-L14

**Comment by ivan-vitenko** [comment]
@shiftkey  Thanks for the answer!
Please tell me what steps I need to take to make the installation successful?

**Comment by jfgordon2** [comment]
I'm running this on a Debian distro and don't see this, but perhaps I need to take another tactic on this, so I'll download buster and take a look!

@ivan-vitenko you can either build this locally, or (more simply) just download the previous release which didn't include the new symlinks.  I'll try to get a simple solution over to @shiftkey ASAP

**Comment by jfgordon2** [comment]
@ivan-vitenko I replicated the error message, but just an FYI it doesn't look like it stopped the installation.  The issue running GitHub Desktop on Debian 10 seems to be related to #222 and I posted a few commands that got it running for me at the bottom.  I'll post a fix to prevent this error from showing up in the terminal, however.
