### ISSUE TITLE
Dear Brendan Forster, I am Brazilian and I want to thank you for making GitHub desktop available for GNU / Linux. Me and some other people got to know your profile through a class on the Curso em Vídeo channel, which is a free project to teach online programming. I'm sorry for using the google translator, I can't speak English.

### ISSUE THREAD

**Issue by adriano-mendonca** [shiftkey/desktop#255]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@adrianomendoncaa you're very welcome!

![](https://media.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif)
