### ISSUE TITLE
Thank you for your amazing job.

### ISSUE THREAD

**Issue by FilipeMGaspar** [shiftkey/desktop#257]
I want to thank you for your amazing job in GitHub Desktop for linux.
I'm learning how to use git in a youtube channel [CursoEmVideo](https://www.youtube.com/cursosemvideo) with teacher **Gustavo Guanabara** @gustavoguanabara. And he show us how to install and use the GitHub Desktop for linux from your repository. 
I'm using Linux Ubuntu 19.10, and it works great. Thank you for your amazing job

**Comment by shiftkey** [comment]
@FilipeMGaspar you're welcome!

![](https://media.giphy.com/media/el7VG1XOOvi24oRXFt/giphy.gif)
