### ISSUE TITLE
lazy login option

### ISSUE THREAD

**Issue by atherdon** [shiftkey/desktop#27]
### Description

Hi @shiftkey, thanks again for your work/teamwork. Appreciate it.

sign in via website at 1.0.11 Linux RC3 not working. callback is not going back and button state is 'loading'.
Ubuntu 16.04, 64-bit 
But I can login using login form only. just want to contribute.

Have a good day and please hug somebody at desktop team, cause it makes(Linux version) me so happy!
[Description of the issue]

### Version

**GitHub Desktop version:** 1.0.11 Linux RC3 
I use this version cause it was pointed from this issue desktop/desktop#1525
Maybe it'll be great if you can update link on your comment: https://github.com/desktop/desktop/issues/1525#issuecomment-351598630

Shall I try the latest release(1.0.13 Linux RC)?

**OS version:** Ubuntu 16.04, 64-bit 

### Steps to Reproduce

1. Install on Ubuntu, open an app
1. Sign in screen
1. Tried to login via OAuth link(Sign in via browser) and after authorizing at website I think callback is not going back.

**Expected behavior:** github oauth page must be closed. desktop app must login me into my account

**Actual behavior:** github oauth page not closed and blank. desktop app sign in form not sumbitted. submit button is loading.

**Reproduces how often:** only first time when you login. not critical.

**Comment by shiftkey** [comment]
@atherdon I believe this is the same issue as #10, which should be resolved once we update to Electron 1.8.x.
