### ISSUE TITLE
Empty repository list and unable to push

### ISSUE THREAD

**Issue by diegojserrano-alumno** [shiftkey/desktop#270]
### Describe the bug
I am starting to use Github classroom but after accepting the assignment and logging in to github desktop as a student the repository list is empty. I am able to clone the assignment repo via URL when I try to push and authentication error is thrown. Pushing via command line works ok so it is not an authentication problem.

### Version & OS

version 2.4.1-linux1
using Kubuntu 19.10

![Screenshot_20200427_122544](https://user-images.githubusercontent.com/64422425/80391134-b828db00-8883-11ea-81c5-7afeb4a5ebf7.png)
![Screenshot_20200427_122612](https://user-images.githubusercontent.com/64422425/80391147-bc54f880-8883-11ea-8473-1fd672db8a6a.png)
![Screenshot_20200427_122629](https://user-images.githubusercontent.com/64422425/80391151-bd862580-8883-11ea-9972-683a54c05562.png)
![Screenshot_20200427_122745](https://user-images.githubusercontent.com/64422425/80391161-c119ac80-8883-11ea-8434-f6bce2a7ac43.png)
[2020-04-27.desktop.production.log](https://github.com/shiftkey/desktop/files/4540587/2020-04-27.desktop.production.log)

**Comment by shiftkey** [comment]
@diegojserrano-alumno thanks for the report!

I think you're also caught up in the OAuth app restrictions that are enabled by default for organizations on GitHub. This port does not have the same privileges as the main application, for reasons that are outlined in https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547.

**Comment by diegojserrano** [comment]
All right, I understand. Since my students are still using Windows this is not an issue for me. I will use the linux port and push via cli.
I am very grateful for your effort in this port.
Please close the issue.
