### ISSUE TITLE
PackageCloud Trial for Debian and RPM users

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#278]
If you're using a Debian or RPM-based distro I've started evaluating [PackageCloud](https://packagecloud.io/) as a way of distributing updates. The trial lasts for 2 weeks.

The details are up at https://packagecloud.io/shiftkey/desktop including setup instructions, and the current release is listed there. I'm aiming to get automated releases in place for the 2.5 release of GitHub Desktop that's coming up, but no promises (and I can manually upload anyway if I don't get time).

This is not a free service (starts at $75 a month) but if you get value out of it and would love to sponsor to assist with the expenses please get in touch (either here or via email).

**Comment by shiftkey** [comment]
Some teething problems to resolve, will dig into these later:

```
$ sudo apt-get install github-desktop             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package github-desktop is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'github-desktop' has no installation candidate
$ sudo apt-get install github-desktop=2.4.1-linux2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gconf-service gconf-service-backend gconf2 gconf2-common libappindicator1
  libdbusmenu-gtk4 libgconf-2-4
Suggested packages:
  gconf-defaults-service gir1.2-gnomekeyring-1.0 libgnome-keyring0
  indicator-application
E: Can't find a source to download version '2.4.1-linux2' of 'github-desktop:amd64'
```

**Comment by shiftkey** [comment]
Looks like I need to use the API or a client SDK as the web portal requires you to choose the specific distribution this works for:

https://github.com/atom/atom-release-publisher/blob/1dc92fbaa3b06b3d64f4ef09c38e468d6dc66f6f/src/linux-package-uploader.js#L28-L43

```js
  async _uploadDebPackage (version, filePath, reportProgress) {
    // NOTE: Not sure if distro IDs update over time, might need
    // to query the following endpoint dynamically to find the right IDs:
    //
    // https://{this.apiToken}:@packagecloud.io/api/v1/distributions.json
    await this._uploadPackage({
      version,
      filePath,
      type: 'deb',
      arch: 'amd64',
      fileName: 'atom-amd64.deb',
      distroId: 35 /* Any .deb distribution */,
      distroName: 'any',
      distroVersion: 'any'
    }, reportProgress)
  }
```

**Comment by shiftkey** [comment]
Works On My Machine:tm: 

```
$ sudo apt update      
Hit:1 http://ca.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://ca.archive.ubuntu.com/ubuntu focal-updates InRelease [107 kB]     
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]      
Get:4 http://ca.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]  
Hit:5 https://deb.nodesource.com/node_12.x focal InRelease                     
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [16.6 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [208 B]
Get:6 https://packagecloud.io/shiftkey/desktop/ubuntu focal InRelease [23.2 kB]
Get:9 https://packagecloud.io/shiftkey/desktop/ubuntu focal/main amd64 Packages [788 B]
Fetched 353 kB in 2s (169 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

$ sudo apt-get install github-desktop             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gconf-service gconf-service-backend gconf2 gconf2-common libappindicator1
  libdbusmenu-gtk4 libgconf-2-4
Suggested packages:
  gconf-defaults-service gir1.2-gnomekeyring-1.0 libgnome-keyring0
  indicator-application
The following NEW packages will be installed:
  gconf-service gconf-service-backend gconf2 gconf2-common github-desktop
  libappindicator1 libdbusmenu-gtk4 libgconf-2-4
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.4 MB of archives.
After this operation, 250 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 gconf2-common all 3.2.6-6ubuntu1 [698 kB]
Get:3 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 libgconf-2-4 amd64 3.2.6-6ubuntu1 [84.8 kB]
Get:4 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 gconf-service-backend amd64 3.2.6-6ubuntu1 [58.6 kB]
Get:5 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 gconf-service amd64 3.2.6-6ubuntu1 [17.4 kB]
Get:6 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 gconf2 amd64 3.2.6-6ubuntu1 [83.0 kB]
Get:7 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 libdbusmenu-gtk4 amd64 16.04.1+18.10.20180917-0ubuntu6 [27.5 kB]
Get:8 http://ca.archive.ubuntu.com/ubuntu focal/universe amd64 libappindicator1 amd64 12.10.1+20.04.20200408.1-0ubuntu1 [22.8 kB]
Get:2 https://packagecloud.io/shiftkey/desktop/ubuntu focal/main amd64 github-desktop amd64 2.4.1-linux2 [63.4 MB]
Fetched 64.4 MB in 20s (3,299 kB/s)                                                                                                  
Selecting previously unselected package gconf2-common.
(Reading database ... 195671 files and directories currently installed.)
Preparing to unpack .../0-gconf2-common_3.2.6-6ubuntu1_all.deb ...
Unpacking gconf2-common (3.2.6-6ubuntu1) ...
Selecting previously unselected package libgconf-2-4:amd64.
Preparing to unpack .../1-libgconf-2-4_3.2.6-6ubuntu1_amd64.deb ...
Unpacking libgconf-2-4:amd64 (3.2.6-6ubuntu1) ...
Selecting previously unselected package gconf-service-backend.
Preparing to unpack .../2-gconf-service-backend_3.2.6-6ubuntu1_amd64.deb ...
Unpacking gconf-service-backend (3.2.6-6ubuntu1) ...
Selecting previously unselected package gconf-service.
Preparing to unpack .../3-gconf-service_3.2.6-6ubuntu1_amd64.deb ...
Unpacking gconf-service (3.2.6-6ubuntu1) ...
Selecting previously unselected package gconf2.
Preparing to unpack .../4-gconf2_3.2.6-6ubuntu1_amd64.deb ...
Unpacking gconf2 (3.2.6-6ubuntu1) ...
Selecting previously unselected package libdbusmenu-gtk4:amd64.
Preparing to unpack .../5-libdbusmenu-gtk4_16.04.1+18.10.20180917-0ubuntu6_amd64.deb ...
Unpacking libdbusmenu-gtk4:amd64 (16.04.1+18.10.20180917-0ubuntu6) ...
Selecting previously unselected package libappindicator1.
Preparing to unpack .../6-libappindicator1_12.10.1+20.04.20200408.1-0ubuntu1_amd64.deb ...
Unpacking libappindicator1 (12.10.1+20.04.20200408.1-0ubuntu1) ...
Selecting previously unselected package github-desktop.
Preparing to unpack .../7-github-desktop_2.4.1-linux2_amd64.deb ...
Unpacking github-desktop (2.4.1-linux2) ...
Setting up gconf2-common (3.2.6-6ubuntu1) ...
Setting up libdbusmenu-gtk4:amd64 (16.04.1+18.10.20180917-0ubuntu6) ...
Setting up libappindicator1 (12.10.1+20.04.20200408.1-0ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for sgml-base (1.29.1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up libgconf-2-4:amd64 (3.2.6-6ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Setting up gconf-service-backend (3.2.6-6ubuntu1) ...
Setting up gconf-service (3.2.6-6ubuntu1) ...
Setting up gconf2 (3.2.6-6ubuntu1) ...
Setting up github-desktop (2.4.1-linux2) ...
Processing triggers for libc-bin (2.31-0ubuntu9) ...
```

**Comment by shiftkey** [comment]
The default don't work as expected because we want to advertise support for any Debian-ish distro (rather than republish for every version) so here's the script that worked for me:

```
wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
sudo apt-get update
```

For the RPM feed, this is the minimum to add the feed:

```
$ sudo rpm --import https://packagecloud.io/shiftkey/desktop/gpgkey
$ sudo sh -c 'echo -e "[shiftkey]\nname=GitHub Desktop\nbaseurl=https://packagecloud.io/shiftkey/desktop/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/shiftkey/desktop/gpgkey" > /etc/yum.repos.d/shiftkey-desktop.repo'
```

**Comment by jfgordon2** [comment]
@shiftkey I'll throw in a bit, as I'd love to see this thrive - perhaps this would be worthwhile to setup a few tiers on github sponsors? not sure what the obligation is, though, nor the credit card fees, etc

**Comment by shiftkey** [comment]
@jfgordon2 I need to go through a whole process (after being accepted into the program of course) but more info about sponsoring is here: https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/sponsoring-an-open-source-contributor

**Comment by shiftkey** [comment]
Installation instructions are now in the README: https://github.com/shiftkey/desktop#packagecloud

**Comment by shiftkey** [comment]
So the trial is about to expire and here's some quick stats from the less-than-two-weeks of having this open:

 - 560+ downloads - 94% for deb, 6% for RPM
 - 33GB bandwidth used

Extrapolating to a full month looks like we'd need ~75GB a month of bandwidth at the current popularity, which would fall into the $150.00 per month billing. So there's two action items for me over the next few days:

 - apply to GitHub Sponsors so that others can help contribute to these costs
 - explore alternative hosting options that could cache better and reduce costs without abusing the platform

**Comment by shiftkey** [comment]
Well that forecasting was way off the mark. I just got the notification that we've already used 50% of the allocated bandwidth in the space of a week, so it looks like people are using it more than I anticipated :tada:. 

I started the application process for GitHub Sponsors early in the week but that's going to take some time (and the first payout won't occur until 90 days from when that completes, [based on the ToS](https://help.github.com/en/github/site-policy/github-sponsors-additional-terms#43-payment-timing)).

**Comment by shiftkey** [comment]
My application to GitHub Sponsors was approved just now, so I've added the relevant details to the repository to make this visible:

<img width="1011" src="https://user-images.githubusercontent.com/359239/83353281-d4f37b00-a327-11ea-9ba3-78448ce4676f.png">

If you want to help out with these costs it'd be greatly appreciated.

**Comment by shiftkey** [comment]
I gather this repository is being shared around the place recently because I just got the 90% warning overnight, and am now at 99% of bandwidth used.

I've upgraded us to the Medium plan (now it's $150 per month for 3x the bandwidth) so it'll continue to work, but if you can chip in with these costs it'd be greatly appreciated.

**Comment by shiftkey** [comment]
I'm a bit confused about how they're crunching the numbers after I upgraded, so after downloading 167GB of bandwidth for this month the account has been suspended (rather continuing to pay overages):

<img width="635" src="https://user-images.githubusercontent.com/359239/85202298-cd4a4500-b2db-11ea-8b7b-f4485f37b0d7.png">

I believe this will reset on the 22nd of June, so if you're continuing to try and install the app and its failing it should come good on Monday.

**Comment by Saladin1812** [comment]
why don't use OBS (Open build service) instead its free and you can build for all the distros..

**Comment by adamsmd** [comment]
@jatin-cbs In a comment at https://github.com/shiftkey/desktop/issues/337#issuecomment-689021690, shiftkey says that he needs an alternative to do all the following.  I can't tell from the webpage, does OBS do all of these?

- hosted infrastructure
- accepts .deb directly
- handles GPG signing natively
- also supports RPM hosting

**Comment by Saladin1812** [comment]
@adamsmd  Yes OBS supports debian and rpm packages and gpg signing keys too ! Many packages are hosted on OBS.. You can host packages for any major linux distro and its free :) 
https://openbuildservice.org/

**Comment by nektro** [comment]
+1 on using OBS as PackageCloud is still erroring for updates.

```
Err:3 https://packagecloud.io/shiftkey/desktop/any any InRelease                                                                                                                                                  
  429  Too Many Requests [IP: REDACTED 443]
```

```
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: REDACTED 443]
```

**Comment by dragonBall561** [comment]
Try Launchpad. I (think) it is free!

**Comment by TopView** [comment]
+1 also getting: W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 54.183.38.243 443]

By chiming in here, will i hear when this is moved/fixed?  Hope so.

**Comment by shiftkey** [comment]
> By chiming in here, will i hear when this is moved/fixed? Hope so.

I've opened #363 to explore OBS but I haven't had time to understand how to integrate without throwing away my build and deployment infrastructure

**Comment by Star-Tube** [comment]
Was about to install using this. Could the readme be updated to reflect that this may not always be available and explain an alternative? (Not sure if this needs to be a seperate issue or if here is fine... I'm fairly new to github)

**Comment by Saladin1812** [comment]
@Star-Tube No need to open a new issue for this, however shiftkey is still maintaining the packagecloud repository. And people who don't use packagecloud actually come back to git releases to get the updated package So they will probably be aware once a good alternative is found.

**Comment by khawkins98** [comment]
I know there are a lot of issues on this and that it's a know thing, but just noting that the PacakgeCloud seems to have he exceeded its quota and it's only the 12th.

https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease

![image](https://user-images.githubusercontent.com/928100/110905528-e6cc6a80-830a-11eb-81a5-b9020c40cf09.png)

---

If [OBS isn't a good fit](https://github.com/shiftkey/desktop/issues/363#issuecomment-796852273) and PacakgeCloud can't offer a free/discounted tier, perhaps it's worth changing the readme to encourage usage of the GitHub releases?

**Comment by Saladin1812** [comment]
I recommended OBS however if that is not a fit, I will recommend to use native services like 

Fedora copr for  RPMs for CentOS Stream/ RHEL/ Fedora
These fulfill all requirements that shiftkey needs, its free but its only for RPM packages.

PPAs for ubuntu/ ubuntu based deb packages
Again this one but for deb packages.

**Comment by hwittenborn** [comment]
If all you need is distribution of binaries(not sure of PackageCloud auto-builds or anything), [Gemfury](https://gemfury.com/) looks like it would do the job. Seems to be free for any public project with no cap on bandwidth(just says average use in their terms)

It doesn't support GPG signing(i.e. a Release file) but I don't see any harm in that when the repo's being served over HTTPS.

**Comment by hwittenborn** [comment]
Just saw the thing about shiftkey needing GPG signing.

Not to push down anyone's opinion, but is GPG signing needed for HTTPS repos? Google isn't giving me anything in it's favor(correct me if I'm wrong though).

**Comment by shiftkey** [comment]
Just wanting to let you all know that I've been thinking about this again this weekend, and while it required some hacking on code today I think I've got an alternative approach here that will allow me to move away from PackageCloud to a solution that:

 - supports RPM/DEB hosting on a single host
 - should enable GPG (if I can figure out the right steps to run)
 - after publishing a new release on GitHub, I run a script on the appliance and it does the consuming/signing/metadata work to add the new release to each feed
 - HTTPS enabled using Let's Encrypt

Here's a quick demo, working on CentOS using an RPM feed (with GPG disabled currently):

<img width="1680" src="https://user-images.githubusercontent.com/359239/111075410-ab769b00-84c6-11eb-9bb2-ef8fe2a22d6e.png">

Once I have the equivalent working for APT and it's less hard-coded I'll share the code and start gathering feedback on what's missing for users.

I have $150 USD/month Azure credits to spend on whatever I feel like, and I think we could go far with a cheap VM that can support the network bandwidth for serving releases that goes far beyond the 165GB/month I'm getting from PackageCloud. But the approach that I'm taking doesn't tie it to Azure, and only assumes it's working on an Ubuntu setup.

**Comment by TommyTran732** [comment]
That is awesome if you could set it up. However, if it ends up costing you so much money ($165/month is a lot, even when you get the $150 credit every month - you can spend it on something else), why not just use COPR for Fedora based Distro and PPAs for Ubuntu based distro? 

I haven't tested, but I am pretty sure openSUSE can use Fedora's COPR as well. Zypper handles the repos just like DNF does. The only thing that could be a problem is Debian.

**Comment by shiftkey** [comment]
@tommytran732 I looked at PPAs initially but it seems "source packages" mentioned [here](https://help.launchpad.net/Packaging/PPA/Uploading) don't match up with the generated installers I already have. COPR feels also the same with the mentions of SRPMs instead of RPMs in [their docs](https://docs.pagure.org/copr.copr/user_documentation.html#build-source-types).

**Comment by soredake** [comment]
https://saveriomiroddi.github.io/Building-a-debian-deb-source-package-and-publishing-it-on-an-ubuntu-ppa/

**Comment by hwittenborn** [comment]
@shiftkey Would [Cloudsmith](https://cloudsmith.com/) work?

**Comment by shiftkey** [comment]
@hwittenborn perhaps, but bandwidth-wise it seems more expensive than PackageCloud

**Comment by hwittenborn** [comment]
It should be completely free for open source projects afaik -- I found this on the pricing page:
![image](https://user-images.githubusercontent.com/74838472/111392745-38ffe980-8685-11eb-9392-0c8c8c0efef2.png)

**Comment by shiftkey** [comment]
@hwittenborn we're using up 165GB+ bandwidth a month currently, so that's not gonna suit this situation

**Comment by hwittenborn** [comment]
I also found this on the pricing page -
![image](https://user-images.githubusercontent.com/74838472/111399448-65bafd80-8693-11eb-87a1-ae126a76aea9.png)

That's my bad though, should've had it in my previous comment

**Comment by lskillen** [comment]
Cloudsmith is (at least) 50GB for storage and 200GB for bandwidth, for OSS:
> Every Cloudsmith plan has support for zero-cost Open-Source repositories, with a generous 50 GB+ storage and 200 GB+ bandwidth allowance. As long as your repository is public and has a valid Open-Source license, it will be free to use forever.

**Comment by hwittenborn** [comment]
@shiftkey Just looking around - if you're looking for something selfhosted, [Sonatype Nexus](https://www.sonatype.com/products/repository-oss?topnav=true) looks pretty good.

I'm currently using it for some of my own projects, and everything works great(except for the UI that's not too modern, but it's still functional). It supports GPG, DEBs and RPMs, and can run under Docker if that would help out at all.

As long as you're fine uploading prebuilt binaries to it(doesn't look like it works with source packages), it looks like it would work.

**Comment by mwt** [comment]
I've created a mirror of the Debian repo. It has IPv4/IPv6 and supports both http and https. It uses the same gpg as the official repo. So, you shouldn't have to trust me or add another gpg key. You can test it by running:

~~~sh
sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
~~~

or just manually edit the file yourself. I'm open to hosting an rpm mirror as well, but this seems to be impossible in Debian without an rpm-based chroot or seprate server. If someone else has an rpm based VPS, I encourage you to mirror. If you don't have the bandwidth, I can rsync from you.

My goal with this mirror is to reduce @shiftkey's bandwidth usage. I'm hoping we can:
1. Prevent the original server from going down.
2. Eventually get @shiftkey onto a cheaper plan.

**Update:** I setup an rpm mirror at <https://mirror.mwt.me/ghd/rpm> as well. I created a separate issue, #647, so as not to derail the discussion here.

**Comment by mwt** [comment]
I currently have a script that regenerates a Debian repo upon receiving new .deb files. It detects their versions, renames them, generates all those package files, etc. It wouldn't be difficult to wrap this up in a PHP script (or even cgi-bash) so that you could POST new deb files to an endpoint. The endpoint could be protected with basic auth and a password stored as a secret for GH actions. Debs could be sent via curl.

I don't have a decent solution for RPM though. I just raise this in case someone has a good RPM solution that can resolve the other half of the problem.

**Comment by theofficialgman** [comment]
are there plans of ever updating the debian repo past version 2.9.6? This is quite out of date now and the other package distribution methods are up to date and automated

**Comment by mwt** [comment]
> are there plans of ever updating the debian repo past version 2.9.6? This is quite out of date now and the other package distribution methods are up to date and automated

Btw, I can't update packages on the mirror myself (because of gpg). Updates will automatically get copied from PackageCloud once they're pushed there.

**Comment by shiftkey** [comment]
> are there plans of ever updating the debian repo past version 2.9.6? This is quite out of date now and the other package distribution methods are up to date and automated

This is on my list for the coming week.

**Comment by mwt** [comment]
> I don't have a decent solution for RPM though. I just raise this in case someone has a good RPM solution that can resolve the other half of the problem.

I figured out the RPM repos. I am testing [a script](https://github.com/mwt/desktop-makerepo) that checks your releases at 3am each day, downloads rpm/deb files if the latest release changes, and constructs [repos](https://mirror.mwt.me/github-desktop/) out of them. This seems to be working well. I've tested it on Ubuntu, Debian, and Oracle Linux (redhat based).

It could also be adapted to work some other way (eg. rsync files after building) or to add updates only when some condition is met (using variables from [this endpoint](https://api.github.com/repos/shiftkey/desktop/releases/latest)).

This would remove the need for PackageCloud and the expense associated with it. Do you think that this is a good solution?

**Comment by theofficialgman** [comment]
@shiftkey looks like you either need to switch plans at packagecloud or up your storeage/bandwidth limit
I get 429 errors when apt updating on my install
```
Ign:9 https://packagecloud.io/shiftkey/desktop/any any InRelease
Ign:9 https://packagecloud.io/shiftkey/desktop/any any InRelease
Err:9 https://packagecloud.io/shiftkey/desktop/any any InRelease                                                                                                  
  429  Too Many Requests [IP: 2600:1f1c:2e5:6900:ea2f:7c61:44d4:731c 443]
```
 and goes to the webpage directly redirects with this
 ```
 Bandwidth or Storage Limit Exceeded
 ```

**Comment by jfgordon2** [comment]
> @shiftkey looks like you either need to switch plans at packagecloud or up your storeage/bandwidth limit
> 
> I get 429 errors when apt updating on my install
> 
> ```
> 
> Ign:9 https://packagecloud.io/shiftkey/desktop/any any InRelease
> 
> Ign:9 https://packagecloud.io/shiftkey/desktop/any any InRelease
> 
> Err:9 https://packagecloud.io/shiftkey/desktop/any any InRelease                                                                                                  
> 
>   429  Too Many Requests [IP: 2600:1f1c:2e5:6900:ea2f:7c61:44d4:731c 443]
> 
> ```
> 
>  and goes to the webpage directly redirects with this
> 
>  ```
> 
>  Bandwidth or Storage Limit Exceeded
> 
>  ```

@theofficialgman I know it's not exactly the deb package, but I do highly recommend the [flatpak](https://flathub.org/apps/details/io.github.shiftey.Desktop).  You can also download the debs in the releases on this repo.

While the packaging solution is being worked out, I believe he's personally out-of-pocket on the majority of these bandwidth costs.  I'd rather see him get out of package cloud entirely at this point than double-down.

**Comment by theofficialgman** [comment]
> @theofficialgman I know it's not exactly the deb package, but I do highly recommend the [flatpak](https://flathub.org/apps/details/io.github.shiftey.Desktop). You can also download the debs in the releases on this repo.

ngl, thats probably the worst reason to use a flatpak. LOL, never.
shiftkey can just make a github debian repo with github pages to host the debs on for free if he wants. I know plenty of projects that do that.

for ubuntu, a launchpad PPA is always a free option as well

**Comment by mwt** [comment]
You could use the mirror mentioned in the README or try the new script I mentioned that doesn't rely on PackageCloud by running:

```sh
wget -qO- "https://mirror.mwt.me/github-desktop/install.sh" | sudo sh
```

I have been using the above on Ubuntu 22.04 since I made it last week. It should work fine. It got the 3.0.0 update automatically during this time. It's essentially the same script that I've been using for a while with RStudio. So, I don't expect issues.

This should work on Debian/Ubuntu, RHEL/Fedora, and (Open)SUSE. Though, I haven't tested it on that last one.

**Comment by jfgordon2** [comment]
> > @theofficialgman I know it's not exactly the deb package, but I do highly recommend the [flatpak](https://flathub.org/apps/details/io.github.shiftey.Desktop). You can also download the debs in the releases on this repo.
> 
> ngl, thats probably the worst reason to use a flatpak. LOL, never. shiftkey can just make a github debian repo with github pages to host the debs on for free if he wants. I know plenty of projects that do that.
> 
> for ubuntu, a launchpad PPA is always a free option as well

I'm not suggesting that as a reason to try, but as a suitable alternative.  If using flatpaks doesn't work for your specific situation, there's a mirror on the README that should be a swap-in replacement for the current apt repo.

I think what it comes down to is somebody has to do the work.  Keep in mind when there's an open source project like this, people are volunteering their time and money to make it available for you.  Hosting on github (beyond just basic artifact download availability) is almost certainly an abuse of this platform, if not a ToS violation, and Launchpad [has been investigated](https://github.com/shiftkey/desktop/issues/465) but found incompatible with the current build script.  If you'd like to contribute your expertise to make the switch to Launchpad happen, I'm sure it would be welcomed.  I'm not an expert on packaging, but I know this sort of change would be a fair amount of work.

**Comment by lskillen** [comment]
This was mentioned previously, but there's always [Cloudsmith](https://cloudsmith.com) as well, which is mostly compatible with the current setup, offers significant open-source storage/bandwidth (up to and beyond 1TB for sponsored projects), is fully managed with no quirks or otherwise usage restrictions, etc. :-) (I work there, happy to help with questions!)

**Comment by jfgordon2** [comment]
I just checked out the documentation @lskillen and it looks pretty straightforward to integrate as a couple steps in the [GA pipeline](https://help.cloudsmith.io/docs/integrating-with-github-actions#push-debian-package) pipeline.  I presume to go beyond the standard 1GB of free bandwidth listed in the pricing, there's some approval process to go through?  It might be helpful to orient @shiftkey on next steps if this is a direction he wants to take this project.  

@shiftkey I'm happy to submit a PR or if you just want a second set of eyes along with @lskillen.

**Comment by lskillen** [comment]
Yep, it is just an approval process, and tbh the team is pretty flexible/helpful/supportive in general. Usually someone asks for a bump, and we say OK. The minimum we ask for is attribution that we're providing it for free, but I'd imagine thst is probably several magnitudes less onerous than @shiftkey paying out of their own pocket. :)

**Comment by aywi** [comment]
Hi, it looks like the package repository has not been updated for two months.

**Comment by mwt** [comment]
> Hi, it looks like the package repository has not been updated for two months.

Yes. Packages are currently uploaded to PackageCloud manually. So nothing is broken.

---

As an update, in the last two months, I have built out the mirroring infrastructure for [`mirror.mwt.me`](https://mattwthomas.com/mirrors/) considerably. There are now three origin servers (US East, US West, and Europe) with a tiered CDN that pulls from the closest origin. There is also a failover server that is used if the node near you goes down.

I mirror all of the files from PackageCloud each day to `/ghd/` which is the second link in the readme.

I also have been using an alternative at `/github-desktop/` which updates each day using the latest release from GitHub. This is automated, works well, and does not depend on PackageCloud.

@shiftkey so, if you stopped paying for PackageCloud today, you'd still have a working deb/rpm repo at `/github-desktop/` which I could propose instructions for in the readme. I want to clarify that you could stop using PackageCloud at any time without major consequences or effort on your part.

My goal in making this mirror was to fix the bandwidth issue and I'd like to help fix this $160 issue as well. Maintaining this shouldn't cost you money. Let me know if you think this is good or if you think there's something missing. You can also do this and try out Cloudforge at the same time.

**Comment by shiftkey** [comment]
@mwt thanks for the help with the mirror here, but there's clearly enough users here that we're still getting slammed each month (without even shipping new updates to PackageCloud).

I've opened https://github.com/shiftkey/desktop/issues/834 to start testing my alternative feed, which no longer depends on anything PackageCloud-related to allow for hosting of these releases. I'm aiming for https://apt.packages.shiftkey.dev/ to become the canonical channel for debian packages, and I'll spin up a corresponding `rpm.packages.shiftkey.dev` for RPM packages once the APT feed is stable (as that's the more popular package currently).

**Comment by shiftkey** [comment]
https://github.com/shiftkey/desktop/issues/835 has the relevant instructions for the new RPM feed, and I've opened https://github.com/shiftkey/desktop/pull/836 to refresh the README so we can move away from PackageCloud.

**Comment by shiftkey** [comment]
The PackageCloud feed will continue to operate for a while, but will not receive updates.

For anyone still looking for discussions on this let's move to the new issues for each feed:

 - https://github.com/shiftkey/desktop/issues/834
 - https://github.com/shiftkey/desktop/issues/835
