### ISSUE TITLE
option to use Windows title bar on Linux

### ISSUE THREAD

**Issue by Heath123** [shiftkey/desktop#285]
https://github.com/shiftkey/desktop/pull/139 added this, but was reverted (https://github.com/shiftkey/desktop/issues/149). 

### Proposed solution

Personally I (and probably some others) prefer the Windows-style title bar, so it would nice if there was a configuration option of some kind.

**Comment by shiftkey** [comment]
@Heath123 thanks for opening this up.

For the moment this is a low-priority for me as I initially thought this would be straight-forward but #149 showed how many people tweaked their setups (and I'd inadvertently affected). I also heard in #243 that these client-side decorations didn't fit with their setup.

I'd like to hear from others why the Windows-style theme here is preferred for them - others shared their setups in #149, like https://github.com/shiftkey/desktop/issues/149#issuecomment-504261558, so I'm curious if we can avoid having to juggle multiple options.

**Comment by Heath123** [comment]
Personally I like it because I think custom title bars look quite nice and professional, it saves a tiny bit of space (not really a big deal) and it's sort of funny to see a Windows-like window on Ubuntu, I don't know about other people, though. This is a really small thing and I don't care that much, so it makes sense that it's low-priority. I wonder if many other people want this or if it's mostly just me?

**Comment by harry-cpp** [comment]
I personally prefer the CSD, I use Ubuntu 20.04 + GNOME.

**Comment by GrahamSH-LLK** [comment]
This would be so awesome. Leaving it up to the OS is not my favorite choice as some Linux dists are absolutely ugly.

**Comment by GrahamSH-LLK** [comment]
One idea is to not put the close/minimize/maximize there and leave that up to the OS. That way we minimize annoyance on both sides. A less "windowsy" one would be better also.

**Comment by mon-jai** [comment]
Wanted this feature too. The current one is ugly on Ubuntu.

**Comment by Miqueas** [comment]
> Wanted this feature too. The current one is ugly on Ubuntu.

Is ugly on ANY distro/desktop environment

**Comment by Miqueas** [comment]
@shiftkey the best solution here is to provide an option to enable/disable CSD and ship the app as-is (like vs code)

**Comment by Miqueas** [comment]
From my point of view, this is a waste of space, since everything in the server-side decorated title bar can be in the same place as the app menu bar

![image](https://user-images.githubusercontent.com/31262466/163733988-b9756cf5-b9e0-47fc-8a86-077e4fdc5d46.png)

**Comment by Miqueas** [comment]
Still no changes? :(

**Comment by shiftkey** [comment]
> Still no changes? :(

The relevant code is linked in the other pull requests, but I've marked this as "help wanted" as I'd like someone to take a shot at making it configurable.

**Comment by Miqueas** [comment]
> > Still no changes? :(
> 
> The relevant code is linked in the other pull requests, but I've marked this as "help wanted" as I'd like someone to take a shot at making it configurable.

Oh, that makes sense

**Comment by mon-jai** [comment]
@shiftkey Maybe we could just additionally, make another build with Windows titlebar?

**Comment by mon-jai** [comment]
@shiftkey Did a quick look.

Seems that their configuration stores lies within [the browser side of the boundary](https://github.com/shiftkey/desktop/blob/linux/app/src/lib/stores/app-store.ts). But if we will need the config value before the browser window is even created,

https://github.com/shiftkey/desktop/blob/5d1d4b781c2a30f53728ab0147f9bce5490765a8/app/src/main-process/app-window.ts#L62-L67

Maybe we could write the config value to a file? (like <code>&#96;${app.getPath('userData')}/electron-config.json&#96;</code>)
