### ISSUE TITLE
GLIBCXX_3.4.21 not defined in file libstdc++.so.6

### ISSUE THREAD

**Issue by alex-rokabilis** [shiftkey/desktop#29]
### Description

App fails to starts. Due to `GLIBCXX_3.4.21 not found`
![bug1](https://user-images.githubusercontent.com/10569451/36817175-e77a6706-1ce8-11e8-9216-cd16d87e9d1f.png)

*This can be solved.* By installing `libstdc++6`. Refer to this [answer](https://askubuntu.com/a/582910/450598)

After the lib's installation I can confirm that the app starts normally.
But it **fails to login** to github account.

1) By the fetch origin button
![bug2](https://user-images.githubusercontent.com/10569451/36817418-cc7ea844-1ce9-11e8-90ec-ad3eec3bf631.png)

2) By the sign-in from the options menu (crashes the whole process)
![bug3](https://user-images.githubusercontent.com/10569451/36817672-a93b337e-1cea-11e8-8eed-3d586dc42979.png)

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** Ubuntu 14.04

### Steps to Reproduce

1. Install the app in ubuntu with `GLIBCXX < 3.4.21`

**Expected behavior:** Spawn the app and sign-in flawless 

**Actual behavior:** App crashes. Fails to sign-in with any way.

**Reproduces how often:** Every time

**Comment by probonopd** [comment]
Please see https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by shiftkey** [comment]
Related issue about `electron-builder`-specific issue: https://github.com/electron-userland/electron-builder/issues/1985

**Comment by alex-rokabilis** [comment]
After an hour of downloading manual `node_modules`, I built the app using the updated `libstdc++6` and I can confirm it's working fine now! Thanks for the help! :smile:

**Comment by probonopd** [comment]
__CAUTION:__ __Bundling `libstdc++.so.6` however will in most cases break compatibility with distros that have a newer library version installed into their system than the bundled one. So blindly bundling the library is not reliable.__  Please see https://github.com/electron-userland/electron-builder/issues/1985#issuecomment-372018791

**Comment by alex-rokabilis** [comment]
@probonopd As I understand you are telling that now that I have bundled an older version of `libstdc++` in my executable, this one will not run I an newer distro (or run with issues). But it will be ok in the system that it was built. Correct?

**Comment by probonopd** [comment]
Correct. And the link above describes a solution for this problem.

**Comment by shiftkey** [comment]
Reopening this to track the underlying issue with `node-keytar` - if I can update the [`binding.gyp`](https://github.com/atom/node-keytar/blob/master/binding.gyp) file to hint about using an earlier version of `GLIBCXX` then that's probably the ideal solution here.

**Comment by shiftkey** [comment]
For anyone monitoring this issue, `1.3.3` has the necessary fix: https://github.com/shiftkey/desktop/releases/tag/release-1.3.3
