### ISSUE TITLE
local path issue

### ISSUE THREAD

**Issue by muhammad-danish1998** [shiftkey/desktop#290]
this directory appear to git repository

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system and distribution you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@muhammad-danish1998 thanks for the report!

Unfortunately I don't have much information to investigate the issue. I've updated the body to include our bug report template - are you able to fill it out as best you can about how you were able to find the issue, and any additional information that is helpful for us?

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@muhammad-danish1998 if you're able to complete the issue template to help with investigating, please open a new issue.
