### ISSUE TITLE
"Google Chrome OS can't open this page" when trying to log in using browser link

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#292]
### Describe the bug

After reinstalling Linux on my Chromebook I installed GH Desktop and got the error "Google Chrome OS can't open this page" when I used the "Sign in to GitHub.com" link in Desktop. I was able to log in fine using the "Sign in to GitHub.com using your username and password" link. I got the same error after logging out and then trying to log back in using the "Sign in using your browser" link in the options menu.

### Version and OS

Version 2.5.2-linux1, Debian 10.2 on an Acer Chromebook 15 (CB515-1HT-C2AE)

### Steps to reproduce the behavior

1. Run GitHub Desktop
2. Click on "Sign in to GitHub.com" or "Sign in using your browser"
3. See error

### Expected behavior

1. Chrome opens GitHub OAuth login tab
2. Log into GitHub
3. Redirected to GH Desktop

### Actual behavior

1. Chrome opens new tab named "Untitled", URL: "https://github.com/login/oauth/authorize?client_id=..."
2. Black screen with pop-up "Google Chrome OS can't open this page."
3. Click "Close", pop-up closes, tab stays open, not redirected to GH Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/32821049/84126983-db56b680-a9fb-11ea-9fcb-31f4b636f0bd.png)
![image](https://user-images.githubusercontent.com/32821049/84127101-07723780-a9fc-11ea-91b4-d4fbd44218c6.png)
![image](https://user-images.githubusercontent.com/32821049/84127697-d47c7380-a9fc-11ea-8ef5-4436a48123fd.png)
Link is greyed out in GH Desktop, I wasn't redirected back to the app.

### Logs

[hastebin](https://hastebin.com/gavojimesu.sql)

### Additional context

I removed what followed "client_id=" in the URL, I'm not entirely sure if I should have. I can provide it if needed.

**Comment by ghost** [comment]
I get the same error using the Username/email and password fields shown in the screenshots. Same behavior, opens new "Untitled" Chrome tab with the same pop-up and buttons grayed out in GHD.

Edit: I emptied the fields in the "Git" section of options and I still get the exact same behavior. I now have essentially no way to log in. ._.

Edit 2: I reinstalled Linux because that was the only way I could find that would get me back to the first welcome page with the "Sign in to GitHub.com using your username and password" link. I'm now logged in without any issues.

**Comment by shiftkey** [comment]
@Airrocket thanks for the report. I believe this is the same problem as #138 but I'm not sure how to fix it as this seems to be related to how protocol handlers work.

I'm going to bump this thread with that information but I'm not aware of an easy solution in this situation currently.
