### ISSUE TITLE
missing tilde interpolation for local paths

### ISSUE THREAD

**Issue by brainchild0** [shiftkey/desktop#294]
# Describe the bug

When prompting for  a path for a local repository , the  the application performs no interpolation of a leading tilde character. 

# Version & OS

GHD: 2.5.2; OS: Linux Mint 19.3

# Steps to reproduce the behavior

1. Using standard Git client,  clone a GitHub repository into home directory.
1. In application, select *File* / *Add Local Repository*.
1. Enter local path to repository, beginning with `~` to represent  home directory.

# Expected behavior

Application accepts entry.

# Actual behavior

Application does not accept entry

**Comment by shiftkey** [comment]
@brainchild0 thanks for the report!

I was able to reproduce this but the fix itself isn't quite clear. We have this method here that uses [`untildify`](https://github.com/sindresorhus/untildify) to convert `~` to your home directory:

https://github.com/shiftkey/desktop/blob/9b0e80e9ce98cf39230b1eb6e0164938c0ac0c1f/app/src/ui/add-repository/add-existing-repository.tsx#L194-L196

But if you're typing out the path manually, we don't do any conversion before checking it's a valid Git repository (so it likely fails here):

https://github.com/shiftkey/desktop/blob/9b0e80e9ce98cf39230b1eb6e0164938c0ac0c1f/app/src/ui/add-repository/add-existing-repository.tsx#L167-L171

There could be some history here about why we do that, or it might have just been an oversight in testing. But making a change in there is where I'd start with trying to fix this.

**Comment by shiftkey** [comment]
This has been fixed in #317 and will be available in the next update
