### ISSUE TITLE
Packagecloud 429 Failure

### ISSUE THREAD

**Issue by vicw0ng-hk** [shiftkey/desktop#297]
When running `sudo apt update`, I get the following failure:
`W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 54.183.113.236 443]`
`W: Some index files failed to download. They have been ignored, or old ones used instead.`

Probably reached bandwidth limit on packagecloud.io.

**Comment by shiftkey** [comment]
@vicw0ng-hk Yep. More context in https://github.com/shiftkey/desktop/issues/278#issuecomment-646991072, should reset tomorrow.
