### ISSUE TITLE
Merged pull requests still listed

### ISSUE THREAD

**Issue by shgysk8zer0** [shiftkey/desktop#30]
### Description

After merging a pull request, it is still shown in the pull requests list. I cannot confirm at the moment, but I do not believe that new PRs are shown. This is not specific to a single installation, as I see the same thing on my Fedora laptop.

The specific PR is shgysk8zer0/awesome-rss#64

I will be updating the issue soon with observations of my next PR.

**Update:**

After opening another pull request, I noticed that the merged PR had vanished and the new PR was visible. After merging, the now closed PR was still listed in the Pull requests tab.

I also noticed that the PR listed on my Fedora laptop was different from what was shown currently and initially on my Ubuntu desktop. The laptop was not on when the PR was created and merged.

My best guess is that PR data is only being updated if there is an open PR, and any closed / merged PRs are being ignored. This would cause the differences between laptop and desktop and also explain why merging PRs does not cause the PR tab to update. If my assumption is correct, having an un-merged / open PR is does trigger an update to the PR tab, which is why the old PR disappeared on desktop, but not on the laptop (GitHub app was not opened until after the merge).

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** Ubuntu 17.10 (.deb), Fedora 27 (.rpm)

### Steps to Reproduce

1. Go to Branch -> Create pull request
1. Create PR in browser
1. Merge PR
1. View Pull request in branch tab
1. Wait several days and repeat previous step with same results

**Expected behavior:** Merged/closed pull requests should not be shown

**Actual behavior:** At least one merged pull request is still visible

**Reproduces how often:** Unknown. Happened once

![](https://i.imgur.com/KN4h0TU.png)
![](https://i.imgur.com/loQSCZ4.png)

### Logs

Logs contain no info that seems to relate. But, the `ISSUE_TEMPALTE` should be updated to say that the logs directory can be found using Help -> Show logs in your File Manager, which opens `~/.config/GitHub Desktop/logs/`

#### Additional Information

I use `git@github.com`... for remotes, but the open PR remains even after deleting/removing and cloning again from `https://`...

**Comment by j-f1** [comment]
Looks like this is the same as https://github.com/desktop/desktop/issues/4122, which has an open PR which should be included in the next release.

**Comment by shgysk8zer0** [comment]
Ah, somehow didn't think of checking issues there.

**Comment by shiftkey** [comment]
Thanks @j-f1 for the reply, and @shgysk8zer0 yes, please follow along with the upstream issue!
