### ISSUE TITLE
inotify / directory watcher not working?

### ISSUE THREAD

**Issue by sarim** [shiftkey/desktop#301]
### Describe the bug

With the repo open in github desktop, I go to vscode, edit files. Add files. Then I come back to github desktop, Modifications doesn't show up in `Changes` tab. Or sometimes it shows up partially, as in the modified files, not added files. I have to click on "history" tab, then click on "changes" tab again to trigger a refresh it seems, then all files show up.

### Version & OS

Version 2.5.2-linux1
Ubuntu 18.04 LTS

### Steps to reproduce the behavior

1. From terminal, in a git repo folder, type `github` command to open.
2. Repo shows up, Alt+Tab to vscode, make changes, modify/add/delete files.
3. Come back to github desktop. 
4. See changes in "Changes (n)" tab.

### Expected behavior

All changes make to the repo. AKA all files listed in `git status`

### Actual behavior

Not all changes show up. Sometimes no changes show up - Changes(0).

### Question
Does linux version make use of inotify or similiar technology to watch the repo directory for changes? If yes, can anyone point me to the package name / module etc.. so I can debug? I searched the repo for "inotify" but nothing shows up.

**Comment by shiftkey** [comment]
> Does linux version make use of inotify or similiar technology to watch the repo directory for changes?

There is no support in any version of the app for watching the directory for changes. I thought we might have had a discussion about this but I can't find it currently.

What should be happening is that the status refreshes when the app regains focus (to reflect the "other app" -> "return to Desktop" flow). If that's not working as expected, there might be some clues in the log about potential Git exceptions.

**Comment by sarim** [comment]
Here is the today's log file , I don't see any relevant error msg ....
[2020-06-24.desktop.production.log](https://github.com/shiftkey/desktop/files/4826999/2020-06-24.desktop.production.log)

Do I need to enable a debug flag or something?

**Comment by shiftkey** [comment]
> Do I need to enable a debug flag or something?

No, error codes that we don't need to handle from Git will appear both there and in the Developer Tools, so that all seems fine.

If you can [build the app from source](https://github.com/shiftkey/desktop/blob/c4058531328c9c6f96c74fc640e7b8a783b71f3b/docs/contributing/setup-linux.md) and run it locally you'll get a more verbose output of the Git commands (including timings).

There might be something repository specific here, but I'm not sure of the specific things to ask:

> Not all changes show up. Sometimes no changes show up - Changes(0).

Can you elaborate on the details here and what you're comparing Desktop to? Is it Git itself, or some other tool?

**Comment by sarim** [comment]
> If you can [build the app from source](https://github.com/shiftkey/desktop/blob/c4058531328c9c6f96c74fc640e7b8a783b71f3b/docs/contributing/setup-linux.md) and run it locally you'll get a more verbose output of the Git commands (including timings).

Okey, I'll try that. Without the detailed log there's just not enough information. No point in speculating. I'll report back when I managed to compile from source and reproduce it.


> Can you elaborate on the details here and what you're comparing Desktop to? Is it Git itself, or some other tool?

git itself. `git status`

**Comment by sarim** [comment]
OK, So it seems to be working as intended. I'm actually using a pretty complex setup with github-desktop running over a remote Xserver connection. I guess sometimes "returned focus to window" event is not being send to the app from Xserver. At the time of opening the issue I thought github-desktop uses inotify and I thought it as an issue specific to github-desktop.

**Comment by shiftkey** [comment]
@sarim thanks for taking the time to describe your setup and dig into the behaviour.

I'm going to close this as we don't support anything related to file watching currently on Linux (either in Git or GitHub Desktop).
