### ISSUE TITLE
Arch executable problem

### ISSUE THREAD

**Issue by m4rocks** [shiftkey/desktop#304]
### Operating System/Distribution

Arch Linux

### Installer

Latest 2.5.3-1
AUR github-desktop-bin

### What happened?

Executable in `/usr/bin` points to `/opt/github-desktop/github-desktop` which is a directory. It should point at `/opt/github-desktop/github-desktop/github-desktop` (A mouthful, isn't it?)

**Comment by shiftkey** [comment]
@clandestinz thanks for reporting this!

This repository doesn't handle the Arch Linux package, but I submitted a PR to fix this over on https://github.com/immackay/github-desktop-aur/pull/8 last week. Hopefully @immackay has some time available to publish a fix to the AUR in the coming days.

**Comment by m4rocks** [comment]
alright thanks for your time

**Comment by shiftkey** [comment]
The fix appears to have been published to the AUR - thanks @immackay!
