### ISSUE TITLE
Issue with installation - Error | .deb & PackageCloud

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#306]
### Operating System/Distribution

Which distribution of Linux are you using?
Ubuntu LTS 18
### Installer

Which version of the app? 2.5.3
Which installer type? Deb & PackageCloud

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.
When trying to install deb I just get a error but when doing PackageCloud at 2% I get this message.
`Hit:1 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:2 https://deb.debian.org/debian buster InRelease                                            
Ign:3 https://storage.googleapis.com/cros-packages/85 buster InRelease                          
Ign:4 http://ppa.launchpad.net/atareao/telegram/ubuntu groovy InRelease                         
Hit:5 https://storage.googleapis.com/cros-packages/85 buster Release                            
Hit:6 https://download.sublimetext.com apt/stable/ InRelease                                    
Ign:8 http://ppa.launchpad.net/ubuntu-desktop/ubuntu-make/ubuntu groovy InRelease               
Hit:9 https://deb.debian.org/debian-security buster/updates InRelease
Err:10 http://ppa.launchpad.net/atareao/telegram/ubuntu groovy Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Get:7 https://packagecloud.io/shiftkey/desktop/any any InRelease [23.2 kB]
Err:11 http://ppa.launchpad.net/ubuntu-desktop/ubuntu-make/ubuntu groovy Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Get:13 https://packagecloud.io/shiftkey/desktop/any any/main amd64 Packages [1,859 B]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/atareao/telegram/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/ubuntu-desktop/ubuntu-make/ubuntu groovy Release' doe  gir1.2-gnomekeyring-1.0 libgnome-keyring0
The following NEW packages will be installed:
  github-desktop
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
19 not fully installed or removed.
Need to get 0 B/63.7 MB of archives.
After this operation, 241 MB of additional disk space will be used.
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 50231 files and directories currently installed.)
Preparing to unpack .../github-desktop_2.5.3-linux1_amd64.deb ...
Unpacking github-desktop (2.5.3-linux1) ...
dpkg: error processing archive /var/cache/apt/archives/github-desktop_2.5.3-linux1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/lib/github-desktop/github-desktop' to '/usr/lib/github-desktop/github-desktop.dpkg-new': failed to write (No space left on device)
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/github-desktop_2.5.3-linux1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by shiftkey** [comment]
@zionthedev this seems to be the issue: "No space left on device" when installing

```
cannot copy extracted data for './usr/lib/github-desktop/github-desktop' to '/usr/lib/github-desktop/github-desktop.dpkg-new': failed to write (No space left on device)
```

**Comment by ghost** [comment]
Oh Thanks for letting me know. I'll install more storage.
