### ISSUE TITLE
RPM installer conflicts with Discord (libnotify dependency)

### ISSUE THREAD

**Issue by Lunarequest** [shiftkey/desktop#307]
### Fedora 32
Which distribution of Linux are you using?

### Installer
RPM
### What happened?
installing both discord and github desktop throws and error as they have a dependency conflict. 
```
Total size: 68 M
Installed size: 230 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  file /usr/lib/.build-id/43/403913e1ccc0475b5e2d1d2ddca551b8815a99 from install of github-desktop-2.5.3.linux1-1.x86_64 conflicts with file from package discord-0.0.10-2.fc32.x86_64
```

**Comment by Lunarequest** [comment]
the same issue happens when you use the packagecould repo

**Comment by shiftkey** [comment]
@advaithm thanks for the report!

> installing both discord and github desktop throws and error as they have a dependency conflict.

The `/usr/lib/.build-id/43/403913e1ccc0475b5e2d1d2ddca551b8815a99` doesn't seem to be part of the application, so I'm curious what it represents and why both apps have it in their metadata.

> the same issue happens when you use the packagecould repo

This makes sense, as they are the same source.

**Comment by shiftkey** [comment]
Additional links about the `.build-id` directory:

 - Fedora docs: https://fedoraproject.org/wiki/Releases/FeatureBuildId
 - StackExchange answer: https://unix.stackexchange.com/a/411736

**Comment by Lunarequest** [comment]
Thanks for the response. I really moved to fedora yesterday

**Comment by Lunarequest** [comment]
@shiftkey after some research it's libnotify. Both require different versions which causes the conflict

**Comment by Lunarequest** [comment]
@shiftkey how do you compile the unpacked desktop too a rpm?

**Comment by shiftkey** [comment]
@advaithm 

```
$ yarn
$ yarn build:prod
$ yarn run package
```

There may be some additional dependencies you need installed, and the package step will warn you if it cannot find them.

**Comment by Lunarequest** [comment]
@shiftkey i have tried building it on my laptop and there is still a issue with github-desktop installing. Not sure why tho. If you need me to run anything please do send me the things you need me to run

**Comment by shiftkey** [comment]
> i have tried building it on my laptop and there is still a issue with github-desktop installing. 

Without more context about what is failing as well as the relevant error messages you're seeing I really can't help out much.

**Comment by Lunarequest** [comment]
@shiftkey nothing fails. when i try and install github-desktop there is a conflict between libnotify version

**Comment by brenoferreiralima** [comment]
same problem here...

Error: Transaction test error:
  file /usr/lib/.build-id/43/403913e1ccc0475b5e2d1d2ddca551b8815a99 from install of github-desktop-2.5.3.linux1-1.x86_64 conflicts with file from package discord-0.0.11-1.fc32.x86_64

![Screenshot from 2020-08-20 23-25-04](https://user-images.githubusercontent.com/4742411/90845478-8a890580-e33c-11ea-8eb2-1f9f35eb9145.png)

**Comment by Lunarequest** [comment]
I no longer use Fedroa Linux so I can not attest to any changes feel free to keep the issue open

**Comment by Saladin1812** [comment]
Error: Transaction test error:
  file /usr/lib/.build-id/43/403913e1ccc0475b5e2d1d2ddca551b8815a99 from install of github-desktop-2.5.2.linux1-1.x86_64 conflicts with file from package discord-0.0.11-1.fc32.x86_64

same issue here.. Tried multiple versions of github desktops as well..

**Comment by Saladin1812** [comment]
@advaithm  I am actively looking and testing this issue thread on my fedora machine :+1:

**Comment by Lunarequest** [comment]
based on what i understood discord uses a older version of libnotify which conflicts with github-desktop

**Comment by Saladin1812** [comment]
@advaithm so can we have an rpm with the libnotify that fedora has ? There should be no problem as fedora has almost the latest libnotify..

**Comment by Saladin1812** [comment]
Or just don't specify libnotify version in the rpm spec itself ?

**Comment by Lunarequest** [comment]
I don't use fedora any more so I can't really say anything

**Comment by shiftkey** [comment]
> so can we have an rpm with the libnotify that fedora has ?
> ...
> Or just don't specify libnotify version in the rpm spec itself ?

@jatin-cbs we inherit the libnotify version from the `electron-installer-redhat` package we use to generate the RPM installer:

https://github.com/electron-userland/electron-installer-redhat/blob/060071451a5859a01eaf0724a685aed21bf0762f/src/dependencies.js#L18

```js
  notify: '(libnotify or libnotify4)',
```

The idea that I was going to take another shot at was adding `%define _build_id_links none` to the spec file, based on https://access.redhat.com/discussions/5045161, which should stop the `/usr/lib/build-id/` files from being added to the RPM.

This requires passing in a new template to `electron-installer-redhat` which I didn't seem to get right when I last looked at this.

**Comment by Saladin1812** [comment]
@shiftkey I will look at the spec file using rpmrebuild in the packagecloud repo probably its the same rpm on github releases page.. Will try my best if i can solve this..

**Comment by Saladin1812** [comment]
Discord just had a new update to 0.0.12 and is present in rpm fusion koji so till it doesn't arrive in rpm fusion stable you can just upgrade it using 

sudo dnf upgrade http://koji.rpmfusion.org/kojifiles/packages/discord/0.0.12/1.fc32/x86_64/discord-0.0.12-1.fc32.x86_64.rpm

Upgrading it to the latest discord fixes the issue with this libnotify conflict :) You can wait for it to arrive in stable rpm fusion as well..

**Comment by Lunarequest** [comment]
@jatin-cbs  can i close this issue

**Comment by Saladin1812** [comment]
Yes you can close this will reopen this if it breaks in future update.. @advaithm
