### ISSUE TITLE
Visual studio code is not opening from Git hub desktop where as i can open terminal ..i am using ubuntu and github version is 2.3.1 and visual studio code version is 1.47.1

### ISSUE THREAD

**Issue by Subodhchalke** [shiftkey/desktop#308]
### Describe the bug
I am facing issue when m clicking open visual studio code button in Github desktop

### Version & OS

Github Desktop version = 2.3.1-linux1
Visual Studio Code version = 1.47.1
OS =Ubuntu 18.04.4

### Expected behavior

Visual studio code should be open

### Actual behavior

Visual studio code is not opening when clicking on open visual studio code 

### Screenshots

Add screenshots to help explain your problem, if applicable.
### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@Subodhchalke please fill out the issue template

**Comment by shiftkey** [comment]
You are also using an old version of GitHub Desktop - `2.5.3` is the latest version, and from https://github.com/shiftkey/desktop/issues/224 I know of other users who had their problem with VSCode resolved after upgrading to `2.4.0` or later.

**Comment by Subodhchalke** [comment]
ok @shiftkey  will try to upgrade thanx

**Comment by Subodhchalke** [comment]
@shiftkey thanx it is working fine in 2.5.0

**Comment by shiftkey** [comment]
Closing as resolved
