### ISSUE TITLE
Can't install GitHub Desktop and Discord

### ISSUE THREAD

**Issue by zagdrath** [shiftkey/desktop#309]
### Operating System/Distribution

Which distribution of Linux are you using?
**Fedora Workstation 32**

### Installer

Which version of the app?
**Version 2.5.3**
Which installer type?
**using the .rpm installer**

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.
So when I have discord installed i cant install Github desktop, i get a error that says it has conflicts with file from another package which is Discord.

**Comment by shiftkey** [comment]
@zagdrath thanks for the report.

This is the same issue which was reported in #307 so please follow along with that.

**Comment by zagdrath** [comment]
Hm, alright #307 seems to never have been solved really.

**Comment by shiftkey** [comment]
@zagdrath that's correct, as I'm unsure of the appropriate change, but I want to avoid having to track the same problem in multiple places.

**Comment by zagdrath** [comment]
Alright, I did not see #307, I should have looked but the title was
different than I thought what it was about.
