### ISSUE TITLE
Doesn't start on CentOS-7 behind firewall

### ISSUE THREAD

**Issue by aloysbaillet** [shiftkey/desktop#31]
### Description

When attempting to run GH desktop on CentOS 7 (from the launcher) nothing appears to happen. No processes exist for electron or desktop when I check and if I attempt to launch from the command line it hangs with no output.

I did manage to get it to launch one time (double clicking the icon in the file explorer) but when it launched I only had the chrome and the menu bar. Clicking entries in the menu bar did nothing (visible).

Our environment has a self signed cert for our GH enterprise install, and applies a self signed cert to all external https connections.

### Version

**GitHub Desktop version:** 1.1.0 (could not check in-app)

**OS version:** centos-release-7-4.1708.el7.centos.x86_64

### Steps to Reproduce

1. Attempt to launch desktop from the command line or launcher
2. Then attempt to launch desktop from the file manager

**Expected behavior:** The application should launch and display something

**Actual behavior:**
After (1): Nothing appears.
After (2): The chrome and menu appears but nothing is functional and the inner window area is blank.

**Reproduces how often:** All of the time

### Logs

These only appeared *after* the window opened with nothing in it. When the window did not appear, none of the logs (or config folder) were generated.
```
2018-02-28T23:27:42.105Z - info: [main] Received possible protocol arguments: 1
```

#### Additional Information
I also tried to delete any pref/settings files that I could find to try from the beginning but that didn't help (just deleting `.config/GitHub Desktop/` which gets recreated everytime I start the app).
FYI @quandtm

**Comment by shiftkey** [comment]
I'm not aware of any CentOS-specific issues with Electron or Desktop, but I'll try and install it on a VM and see if I can trigger this issue

> Our environment has a self signed cert for our GH enterprise install, and applies a self signed cert to all external https connections.

I think this might bite you later on once we get the application running, but I'm not going to worry about that for the moment.

**Comment by shiftkey** [comment]
I can reproduce this on a vanilla CentOS build - `7.4.1708 (Core)` with the AppImage install - and when I could get to the dev tools I can see this error:

<img width="819" src="https://user-images.githubusercontent.com/359239/37064425-c5e2a8a2-2151-11e8-9ee5-24a5df7c5578.png">

This is already tracked in #29, so I'm going to close this issue in favour of that. I'm not sure of the CentOS-specific fix for this, despite trying a few common things.

Please open another issue if you encounter a problem with connecting to a the GitHub Enterprise which has a self-signed certificate after you get the required version of `GLIBCXX` on your machine.

**Comment by probonopd** [comment]
The `GLIBCXX` usually means that some ingredient of the AppImage or some ingredient for it was built on a system newer than the target system on which the AppImage is being executed. Building all ingredients on an older system is usually the best fix for this kind of issue. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for more information.
