### ISSUE TITLE
packagecloud.io Bandwidth or Storage Limit Exceeded

### ISSUE THREAD

**Issue by tonyp7** [shiftkey/desktop#310]
Hello,

I tried running 

```bash
wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -
```

But i got the error:
```
gpg: no valid OpenPGP data found.
```

I thought that was odd because it has installed flawlessly in the past. The issue seems to be with https://packagecloud.io/shiftkey/desktop/gpgkey which gives the error message "Bandwidth or Storage Limit Exceeded"

EDIT -- I understand this is because packagecloud is quite an expense. I see you have the deb files attached to each release so Ill go this way!

**Comment by shiftkey** [comment]
Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.

It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

**Comment by tonyp7** [comment]
Thanks for the reply. Why not just submit it to the store? https://snapcraft.io

That’s how a lot of apps get distributed nowadays and it wouldn’t cost you anything

**Comment by shiftkey** [comment]
> Why not just submit it to the store? https://snapcraft.io

This is an additional format to DEB/RPM support, and while I had this working before I had to pull it because it stopped working. #202 is tracking that work, not sure when I'll get back to it.
