### ISSUE TITLE
No valid OpenPGP data found (Issue while installing)

### ISSUE THREAD

**Issue by sonuishaq67** [shiftkey/desktop#311]
### Tried installing it but fails on the first step
```wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -```
Output: ```gpg: no valid OpenPGP data found.```
Verbose for this ``` wget -vO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -```
Output:
```--2020-07-20 16:19:14--  https://packagecloud.io/shiftkey/desktop/gpgkey
Resolving packagecloud.io (packagecloud.io)... 54.193.34.251, 2600:1f1c:2e5:6901:10ad:ff59:b50e:2773, 2600:1f1c:2e5:6900:dbad:ab75:d3df:6840
Connecting to packagecloud.io (packagecloud.io)|54.193.34.251|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2020-07-20 16:19:18 ERROR 429: Too Many Requests.

gpg: no valid OpenPGP data found.
```

**Comment by shiftkey** [comment]
> `429: Too Many Requests`

As I mentioned in #310 yesterday:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

This should renew in a couple of days.

**Comment by sonuishaq67** [comment]
Oh thanks , I didn't know there were deb file releases .
