### ISSUE TITLE
RPM requires libcurl but libcurl4 is provided (openSUSE 15.2)

### ISSUE THREAD

**Issue by larsvilhuber** [shiftkey/desktop#312]
### Operating System/Distribution

openSUSE 15.2

### Installer

- github-desktop-2.5.3.linux1-1.x86_64
- zypper-1.14.37-lp152.2.3.1.x86_64

### What happened?

```
$ sudo zypper in github-desktop
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libcurl needed by github-desktop-2.5.3.linux1-1.x86_64
 Solution 1: do not install github-desktop-2.5.3.linux1-1.x86_64
 Solution 2: break github-desktop-2.5.3.linux1-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2
```
Application installs, and seems to run. The likely issue is that openSUSE 15.2 provides "libcurl4", not "libcurl":
```
$ sudo zypper search libcurl
Loading repository data...
Reading installed packages...

S  | Name                | Summary                                 | Type
---+---------------------+-----------------------------------------+--------
i+ | libcurl-devel       | Development files for the curl library  | package
   | libcurl-devel-32bit | Development files for the curl library  | package
   | libcurl-mini-devel  | Development files for the curl library  | package
i+ | libcurl4            | Library for transferring data from URLs | package
   | libcurl4-32bit      | Library for transferring data from URLs | package
   | libcurl4-mini       | Library for transferring data from URLs | package
```

**Comment by shiftkey** [comment]
@larsvilhuber thanks for the heads up on this. I was initially hoping that it'd be as easy as doing what we do in the debian package - specifying a fallback package if it's not available:

https://github.com/shiftkey/desktop/blob/1627b22a7b4daa1f680108db8e36ee3a84879bc1/script/package-debian.ts#L55

The relevant section here for RPM packages:

https://github.com/shiftkey/desktop/blob/1627b22a7b4daa1f680108db8e36ee3a84879bc1/script/package-redhat.ts#L44-L54

I tested out this patch locally to see if the same thing was possible:

```
diff --git a/script/package-redhat.ts b/script/package-redhat.ts
index dbd4af683..6eec5497c 100644
--- a/script/package-redhat.ts
+++ b/script/package-redhat.ts
@@ -47,7 +47,7 @@ const options: RedhatOptions = {
     'libX11-xcb',
     'alsa-lib',
     // dugite-native dependencies
-    'libcurl',
+    'libcurl | libcurl4',
     // keytar dependencies
     'libsecret',
     'gnome-keyring',
```

However I see this error, so it looks like that's not possible:

```
error: line 9: Dependency tokens must begin with alpha-numeric, '_' or '/': Requires: gtk3, (libnotify or libnotify4), (nss or mozilla-nss), libXScrnSaver, (libXtst or libXtst6), xdg-utils, at-spi2-core, (libuuid or libuuid1), (kde-cli-tools or kde-cli-tools5 or kde-runtime or trash-cli or glib2 or gvfs-client), libX11-xcb, alsa-lib, libcurl | libcurl4, libsecret, gnome-keyring
```

I guess an alternative here would be to publish a RPM specific for openSUSE, which isn't too hard, but for a one-line change feels very heavy-handed...

**Comment by larsvilhuber** [comment]
One way to address this is in the RPM build specs to have distro-specific lines. That can break, but distros don't change that often. 
```
%if %{suse_version} >= 1502
BuildRequires: libcurl
%endif 
```
but that might only work on the openSUSE build service (BTW, free for building and distributing multi-platform RPMs)

**Comment by larsvilhuber** [comment]
PS: re-reading your posted error message seems to already have the solution embedded:
```
(libnotify or libnotify4)
```
where does that come from? You would seem to need to do the same for libcurl:
```
(libcurl or libcurl4)
```

**Comment by shiftkey** [comment]
@larsvilhuber aha, didn't notice that - thanks!

I've opened #315 now and will publish a release later this week with the changes.
