### ISSUE TITLE
Installation instructions for openSUSE

### ISSUE THREAD

**Issue by larsvilhuber** [shiftkey/desktop#313]
### Describe the feature or problem you’d like to solve

The README provides solution for installing to Redhat-based distros, but doesn't work as-is for openSUSE.

### Proposed solution

Add instructions allowing for copy-paste to openSUSE terminal. Less experienced users will be able to copy-paste. 

### Additional context

README will be edited.

**Comment by shiftkey** [comment]
@larsvilhuber thanks for opening this up.

I'm going to close this out in favour of #314 which is tracking the docs changes themselves, but I'd love to figure out a better solution for #312 so we don't need to explain that warning - let's chat about that over there...
