### ISSUE TITLE
Redirect after browser authentication does not open application

### ISSUE THREAD

**Issue by subversivo58** [shiftkey/desktop#318]
### Describe the bug

Authentication using the browser does not return to the application because it uses an unregistered mime-type scheme by the application.

### Version & OS

* **Source**: [GitHubDesktop-linux-2.5.3-linux1.deb](https://github.com/shiftkey/desktop/releases/tag/release-2.5.3-linux1)
* **Version**: 2.1.0-linux1
* **OS**: Linux Mint 20 Cinnamon | Cinnamon v4.6.6 | Linux Kernel 5.4.0-42-generic | 64bits
* **Processor**: AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G × 2
* **Tested Browsers**: Chrome 84.0.4147.105 | Firefox 79.0

### Steps to reproduce the behavior

1. Download package from [GitHubDesktop-linux-2.5.3-linux1.deb](https://github.com/shiftkey/desktop/releases/tag/release-2.5.3-linux1) and install
2. Open application and go to: "Sign in to GitHub.com" (button) or **File > Options > Accounts** and sign in "GitHub.com" with "**Sign in using your browser**"
3. Sign in to GitHub.com if you have not done so before ... authorize the application and confirm using username/email and password or use the security key

### Expected behavior

In https://github.com/login/oauth/authorize is expected to redirect to the application through its own protocol (x-github-desktop-dev-auth) that the application must recognize.

### Actual behavior

The redirect does not occur after confirming the "xdg-open" prompt ... the application does not recognize the schema.

```none
x-github-desktop-dev-auth://oauth?code=xxxxxxxxxxxxxxxxxxxxx&state=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```

### Screenshots

![github-005](https://user-images.githubusercontent.com/6475273/89330087-1d9c1d00-d666-11ea-8ee3-4a8ae6acd0dc.png)
![github-006](https://user-images.githubusercontent.com/6475273/89330088-1e34b380-d666-11ea-87ab-9124b839ab72.png)

### Additional context

This behavior has been observed in new installations on both Linux Mint 19.3 and 20.

When viewing the application's "github-desktop.desktop" file, the protocol used in the browser was missing from the MimeTypes list of the file.

![github-007](https://user-images.githubusercontent.com/6475273/89330091-1ecd4a00-d666-11ea-8749-fdec8cd1144e.png)

**Comment by subversivo58** [comment]
Palliative editing of the `github-desktop.desktop` file and adding the schema mime-type used in the redirect and updating the mime-type database solves the problem and in future attempts, the redirection returns to the application.


**Steps**:

1- Open `/usr/share/applications/github-desktop.desktop` with the text editor of your choice

```none
sudo -H subl /usr/share/applications/github-desktop.desktop
```

2 - Add the scheme ("x-scheme-handler/x-github-desktop-dev-auth;") in the "MimeType" list and save

```none
[Desktop Entry]
Name=GitHub Desktop
Comment=Simple collaboration from your desktop
Exec="/opt/GitHub Desktop/github-desktop" %U
Terminal=false
Type=Application
Icon=github-desktop
StartupWMClass=GitHub Desktop
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;x-scheme-handler/x-github-desktop-dev-auth;
Categories=GNOME;GTK;Development;
```

3 - Update mime types database

```none
sudo update-desktop-database 
```

4 - Redo the authentication by the browser ... now the redirect should open the application completing the authorization


------

Note: after performing steps 1 to 3, it is no longer possible to reproduce the problem even if you uninstall and reinstall the package.

**Comment by bovlb** [comment]
I have the same problem, but this fix does not work for me.

Update: Using the latest version, the suggested workaround is already in place, but I still cannot login.  I was able to get Firefox to return control to Github Desktop by installing gnome-tweak-tool but Github Desktop just spins.

Update 2: I have fixed the problem by running Github Desktop as a non-root user.  (Previously I was using `--no-sandbox`.) 
 Unfortunately, this required me to use `--cap-add=SYS_ADMIN` on `docker run`.

Update 3: Ignore the bit above about `gnome-tweak-tool`.  That seems to be a red herring.

**Comment by shiftkey** [comment]
@subversivo58 thanks for opening this up.

> * **Source**: [GitHubDesktop-linux-2.5.3-linux1.deb](https://github.com/shiftkey/desktop/releases/tag/release-2.5.3-linux1)
> * **Version**: 2.1.0-linux1

This bit is confusing to me, as if you are actually on version `2.1.0` then you don't have the packaging changes in https://github.com/shiftkey/desktop/pull/273 (which have been available since [`2.4.1-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-2.4.1-linux2)).

This is important because of this section:

https://github.com/shiftkey/desktop/blob/052fa1404560bc7cb10e3e18537fc3291b9af633/script/package-debian.ts#L68-L76

So if your installation doesn't have that added to your `.desktop` file I suspect you're on an older version. Can you confirm **with the latest release** that the `.desktop` entry looks correct?

**Comment by subversivo58** [comment]
Hi @shiftkey 

I am in the latest version [GitHubDesktop-linux-2.5.3-linux1.deb](https://github.com/shiftkey/desktop/releases/tag/release-2.5.3-linux1)

![github-000](https://user-images.githubusercontent.com/6475273/89665937-db661c00-d8af-11ea-933a-224a5e393917.png)


As I said earlier:

> Note: after performing steps 1 to 3, it is no longer possible to reproduce the problem even if you uninstall and reinstall the package.

--------

PS: I will try to virtualize a clean installation ... return in a few hours with the print of the `.desktop` file of this installation.


-------

> This bit is confusing to me, as if you are actually on version 2.1.0 then you don't have the packaging changes in #273 (which have been available since 2.4.1-linux2).

PS2: My mistake: when I opened the issue I was using **GitHubDesktop-linux-2.1.0-linux1.deb** aversion and had not yet installed the latest release that I had just downloaded. I will confirm this.

**Comment by guidezpl** [comment]
Same issue is occurring for me with the latest version.

Update: I was able to sign in using Firefox 
<img width="508" alt="Screen Shot 2020-09-30 at 6 45 37 PM" src="https://user-images.githubusercontent.com/6655696/94715042-3b77bc80-034d-11eb-992e-20f3c5b0e560.png">

**Comment by bala** [comment]
The reason could be because of javascript in your browser. when github desktop opens default browser for login access, copy the url to another browser like chrome, opera or vivaldi and try login. Also check the same step in private window of firefox.

Now if it opens, Then check  the browser add-ons.

**Comment by shiftkey** [comment]
I'm going to close this out as I think I've configured everything right in the Debian installer as of version `2.4.1-linux2`
