### ISSUE TITLE
Unable to install on Raspberry OS (Raspbian 10 Buster)

### ISSUE THREAD

**Issue by jimbiscuit** [shiftkey/desktop#319]
Hello,

I try to install github desktop on my raspberry pi with Rasbian 10 Buster.
I try the way explain in the readme.md but I have got this issues :
```
pi@raspberrypi:~ $ sudo apt install github-desktop
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package github-desktop
```

Next I try the way explain [here](https://packagecloud.io/shiftkey/desktop?filter=debs) and I have the same error.

after that when I make an update I have got this :

```
pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                                            
Ign:4 https://packagecloud.io/shiftkey/desktop/raspbian buster InRelease                                   
Hit:3 https://packagecloud.io/shiftkey/desktop/any any InRelease       
Err:5 https://packagecloud.io/shiftkey/desktop/raspbian buster Release
  404  Not Found [IP: 54.193.34.251 443]
Reading package lists... Done                    
E: The repository 'https://packagecloud.io/shiftkey/desktop/raspbian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by shiftkey** [comment]
Linux ARM support is not available at the moment.

I've opened https://github.com/shiftkey/desktop/issues/251 to track the blockers on this, but I don't have a timeline for it.

Please follow along with that issue in the meantime.

**Comment by leecollings** [comment]
I just stumbled on this when trying to install on a 64-bit Raspberry Pi... so it doesn't support the latest Raspberry Pis then I take it?

**Comment by shiftkey** [comment]
> I just stumbled on this when trying to install on a 64-bit Raspberry Pi... so it doesn't support the latest Raspberry Pis then I take it?

I haven't published any of these packages to the feed yet because I want to ensure these are solid packages first.

I also suspect I'll need to reconfigure the feeds to allow users to subscribe to the right architecture.
