### ISSUE TITLE
add `github` command line interface as part of Linux installation

### ISSUE THREAD

**Issue by Epskampie** [shiftkey/desktop#32]
### Description

When opening github desktop from the terminal on osx like this: `github A_REPO_PATH` it opens the app with either
* That directory open (if already added)
* The "add local repository" popup open and filled in.

This is useful when working primarily from the command line.

The linux version so far doesn't seem to support this, I think it's just a matter of passing along command line parameters.

### Version

**GitHub Desktop version:** GitHubDesktop-linux-x86_64-1.1.0.AppImage

**OS version:** Ubuntu 16.04

**Comment by Serkan-devel** [comment]
Is the issue on OSX or on Ubuntu?

**Comment by Epskampie** [comment]
The issue is on Ubuntu, I just mentioned OSX to indicate how it works on the other platforms.

**Comment by shiftkey** [comment]
@Epskampie thanks for the feedback. The CLI integration is a bit different depending on the platform:

 - on Windows, we'll update the `PATH` after installation or updating - [this is the relevant code](https://github.com/desktop/desktop/blob/master/app/src/main-process/squirrel-updater.ts#L47-L56)
 - on macOS, the user needs to enable this - but [this is the relevant code](https://github.com/desktop/desktop/blob/master/app/src/ui/lib/install-cli.ts) that happens.

I gather we need to do something like the latter for Linux, but I'm interesting in pointers from others about best practices. I had a peek at what VSCode does around this and they don't seem to support installing a CLI currently, so that has me a bit nervous...

**Comment by Epskampie** [comment]
Just to be clear, I'm absolutely not asking for automatic installation of a command into the `PATH`, I can easily add it myself. 

I'm just asking that you can open/add a repo from the commandline, like it works on osx/windows: `/path/to/github /path/to/repo`

**Comment by shiftkey** [comment]
@Epskampie the external shims are important because there's a bit of work required to be able to launch Electron from the command line and pass arguments in - [look at the `github.sh` script](https://github.com/desktop/desktop/blob/master/app/static/darwin/github.sh) to see this work.

We do the `PATH` updating automagically on Windows because it's install location will contain the version information, so we manage that to ensure the user doesn't have to. macOS doesn't have this constraint, so once the shim is installed it's good to go.

What I need to understand is the best way to manage this shim for Linux users. If we're not able to write to `/usr/local/bin` as a regular user, what other options are there? Are we left with bundling a shim in the package and getting the user to update `PATH`?

**Comment by Epskampie** [comment]
Ah, I see. I looked into how vscode does this. By default no shim is installed, like you found out. They have [an option in the interface](https://code.visualstudio.com/docs/editor/command-line) called `Install 'code' command in PATH`. When this is selected the user must enter root credentials and [the code shim](https://github.com/Microsoft/vscode/blob/master/resources/linux/bin/code.sh) is copied to /usr/bin/

Not ideal, but it works.

**Comment by shiftkey** [comment]
@Epskampie there's also this mention in the docs:

> Note: Windows and Linux installations should add the VS Code binaries location to your system path.

**Comment by asianjakepaul** [comment]
Looks like you can open a repository from command line using:
 ```bash 
/path/to/github-desktop open REPO_PATH
```
See: https://github.com/shiftkey/desktop/blob/d1ffc6a5749816725bc567224f21bbb345ca026d/app/src/cli/commands/open.ts#L26 and https://github.com/shiftkey/desktop/blob/d1ffc6a5749816725bc567224f21bbb345ca026d/app/src/cli/open-desktop.ts#L12

Looks like they only implemented this command on OSX and Windows so far?
Would this fix it?
```ts
if (__DARWIN__) {
    return ChildProcess.spawn('open', [url], { env })
} else if (__WIN32__) {
    return ChildProcess.spawn('cmd', ['/c', 'start', url], { env })
} else if (__LINUX__) {
    return ChildProcess.spawn('xdg-open', [url], { env })
} 
```

**Comment by shiftkey** [comment]
@asianjakepaul we also include a [`github.bat`](https://github.com/desktop/desktop/tree/master/app/static/win32/github.bat) or [`github.sh`](https://github.com/desktop/desktop/blob/master/app/static/darwin/github.sh) shell script that gets added to the PATH, so you can call `github [path]` and it'll launch the app and pass the arguments through correctly. We'd need one of those for Linux, that knows where to find the installed `github-desktop` program.

The `xdg-open` line is a part of the solution, but on macOS we also need to elevate to symlink the `github.sh` into `/usr/local/bin/github` -  I suspect we'd need to do something similar for Linux too.

**Comment by asianjakepaul** [comment]
@shiftkey is `github.sh` automatically added to `PATH` when installing using the .deb files?

I just installed https://github.com/shiftkey/desktop/releases/tag/release-1.4.0 on Ubuntu 16.04 and `/opt/GithubDesktop/desktop` is not in in `PATH`, output of `which github` is `github not found`

Also the `xdg-open` part when signing in using "Sign in with browser" does not work for me (might be related to this)

**Comment by shiftkey** [comment]
@asianjakepaul 

> is github.sh automatically added to PATH when installing using the .deb files?

It is not - I haven't spotted a hook for doing that yet, it might be a limitation of `electron-builder`

> Also the `xdg-open` part when signing in using "Sign in with browser" does not work for me (might be related to this)

To launch a browser? Or is this for the callback to Desktop at the end of the browser signin process?

I'm not very familiar with `xdg-open`, but it seemed mainstream enough that it should work for most users. Are you aware of other options?

**Comment by asianjakepaul** [comment]
Opening the browser works, the callback fails, I get the xdg-open dialog and when I click "open" nothing happens, browser stays open on a blank screen.

I think the protocol scheme doesn't register correctly, I don't see a `MimeType` in the `.desktop` file.

I think there is a `postInstall` hook in electron-builder, see https://github.com/electron-userland/electron-builder/issues/2050
Maybe we can add it to `PATH` or symlink to `/usr/local/bin` in that hook.

**Comment by asianjakepaul** [comment]
I will try to get `xdg-open` working on my system and report back here when something changes.

I will also try installing the snap package and see if that makes a difference.

**Comment by jfgordon2** [comment]
> @Epskampie thanks for the feedback. The CLI integration is a bit different depending on the platform:
> 
> * on Windows, we'll update the `PATH` after installation or updating - [this is the relevant code](https://github.com/desktop/desktop/blob/master/app/src/main-process/squirrel-updater.ts#L47-L56)
> * on macOS, the user needs to enable this - but [this is the relevant code](https://github.com/desktop/desktop/blob/master/app/src/ui/lib/install-cli.ts) that happens.
> 
> I gather we need to do something like the latter for Linux, but I'm interesting in pointers from others about best practices. I had a peek at what VSCode does around this and they don't seem to support installing a CLI currently, so that has me a bit nervous...

I don't know if you're still looking at making a shim, I've got a little bit of a start, though it seems like the cli.js file is coded to error out on linux


`#!/bin/sh`
`# this github.sh file exists in same directory as github-desktop`

`if [ ! -L $0 ]; then`
`	# if path is not a symlink, find relatively`
`	GITHUB_PATH="$(dirname $0)"`
`else`
`	if command -v readlink >/dev/null; then`
`		# if readlink exists, follow the symlink and find relatively`
`		SYMLINK=$(readlink -f "$0")`
`		GITHUB_PATH=$(dirname "$SYMLINK")`
`	else`
`		# else use the standard install location`
`		GITHUB_PATH="/opt/GitHub Desktop"`
`	fi`
`fi`

`ELECTRON="$GITHUB_PATH/github-desktop"`
`CLI="$GITHUB_PATH/resources/app/cli.js"`

`ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"`

`exit $?`

Then I just added it to my command line by executing:
`sudo chmod +x /opt/GitHub\ Desktop/github.sh`
Then
`alias github="/opt/GitHub\ Desktop/github.sh"`

**Comment by shiftkey** [comment]
@jfgordon2 this is a pretty decent start. There's a bit more to the discussion about ensuring it's on `PATH` when installing/uninstalling but that might need to be handled by packaging.

> though it seems like the cli.js file is coded to error out on linux

The source for this file is from [`app/src/cli`](https://github.com/shiftkey/desktop/tree/linux/app/src/cli) and maybe it needs some changes too.

If you wanted to take a shot at adding the script to [`app/static/linux`](https://github.com/shiftkey/desktop/tree/linux/app/static/linux) we can see how far this can get us.
