### ISSUE TITLE
unable to install with yum due to use of "or" in dependencies

### ISSUE THREAD

**Issue by sujitp81** [shiftkey/desktop#320]
### Operating System/Distribution

Which distribution of Linux are you using?
CentOS 7.8
### Installer
 **sudo yum install GitHubDesktop-linux-2.5.3-linux1.rpm  --nogpgcheck -y python-elasticsearch-curator**

Which version of the app?
Latest version  (**2.5.3-linux1**) has the error, so does all versions above (and including) **2.5.0-linux2**
_Note:linux-2.5.0-linux1 does not have this problem._

Which installer type?
**yum**
### What happened?

[username@ussd-dev-dev01 Downloads]$ sudo yum install GitHubDesktop-linux-2.5.3-linux1.rpm  --nogpgcheck -y python-elasticsearch-curator
Loaded plugins: fastestmirror, langpacks
Examining GitHubDesktop-linux-2.5.3-linux1.rpm: github-desktop-2.5.3.linux1-1.x86_64
Marking GitHubDesktop-linux-2.5.3-linux1.rpm as an update to github-desktop-2.5.0_linux1-1.x86_64
Loading mirror speeds from cached hostfile
No package python-elasticsearch-curator available.
Resolving Dependencies
--> Running transaction check
---> Package github-desktop.x86_64 0:2.5.0_linux1-1 will be updated
---> Package github-desktop.x86_64 0:2.5.3.linux1-1 will be an update
Error: Invalid version flag: or
[username@ussd-dev-dev01 Downloads]$

**Comment by shiftkey** [comment]
@sujitp81 thanks for the report. I'm not familiar with this error but I feel it's related to #273 where we reworked the packaging side of things.

**Comment by shiftkey** [comment]
With the change in #273 the generated package tries to resolve dependencies in a more general way:

https://github.com/electron-userland/electron-installer-redhat/blob/060071451a5859a01eaf0724a685aed21bf0762f/src/dependencies.js#L7-L26

```js
const dependencyMap = {
  atspi: 'at-spi2-core',
  drm: 'libdrm',
  gbm: 'mesa-libgbm',
  gconf: 'GConf2',
  glib2: 'glib2',
  gtk2: 'gtk2',
  gtk3: 'gtk3',
  gvfs: 'gvfs-client',
  kdeCliTools: ['kde-cli-tools', 'kde-cli-tools5'],
  kdeRuntime: 'kde-runtime',
  notify: '(libnotify or libnotify4)',
  nss: '(nss or mozilla-nss)',
  trashCli: 'trash-cli',
  uuid: '(libuuid or libuuid1)',
  xcbDri3: 'libxcb',
  xdgUtils: 'xdg-utils',
  xss: 'libXScrnSaver',
  xtst: '(libXtst or libXtst6)'
}
```

We also did this in #315 for `libcurl` for an SUSE-related issue, so I'm now curious why this `or` syntax isn't supported on CentOS (or is this a yum-specific issue?)

**Comment by shiftkey** [comment]
Also found this community thread but no clear resolution: https://github.community/t/linux-centos-error-msg-invalid-version-flag-or/122215

**Comment by shiftkey** [comment]
Looks like this is related to "rich dependencies" support and isn't supported by `yum`: https://bugzilla.redhat.com/show_bug.cgi?id=1317481

You might be able to install the latest version using `dnf` but the recommendations I've seen about properly supporting `yum` is to avoid using `or`, which feels like a lot of change to how packages are made currently.

**Comment by paleozogt** [comment]
btw, this also happens with Amazon Linux 2

**Comment by shiftkey** [comment]
Closing this out as something that I don't plan to support. The alternative approach here could be to generate distro-specific packages but I'm not willing to take that on - it'd likely also need some changes to how we invoke `electron-installer-redhat` in this script:

https://github.com/shiftkey/desktop/blob/7da1ff5f19a7e765f7861d5b53415c8c34f0ef34/script/package-redhat.ts#L36-L100
