### ISSUE TITLE
404 error with GitHub Enterprise on CentOS7.8 with version: 2.5.0.linux1 "Sign in using your browser"

### ISSUE THREAD

**Issue by sujitp81** [shiftkey/desktop#321]
### Describe the bug

I am unable to **sign in** to GitHub Enterprise. Browser launches and goes to GitHub enterprise site, but with 404 error.
I also installed Chrome (not Chromium) browser to see if this is a browser issue, but it too has same problem.
Note: I was already logged into GitHub Enterprise in browser. If I logout from browser and then try "Sign in using your browser", then browser launches and brings up GitHub Enterprise login page, and after logging in, I have the same 404 error.
### Version & OS
OS: **CentOS 7.8**
Github Desktop version: **2.5.0.linux1**
GitHub Enterprise Version: **2.20.10**

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Options'
3. Click 'Sign in' next to 'GitHub Enterprise Server'
4. Enter "https://git.mycompanyname.com", click 'Continue'
5. Click "Sign in using your browser"

### Expected behavior

I should go to my github enterprise site on browser and get signed in to GitHub Desktop.

### Actual behavior
Browser launches and and loads my github enterprise site, but with a **404 error** and the GitHub desktop UI's "Sign in" text has the two curved arrows keeps circling.

### Screenshots
![image](https://user-images.githubusercontent.com/5796826/89720434-c42e4800-d9ef-11ea-96ef-8292c4a6194b.png)

### Logs
The above screenshot also contain content of the log file.

**Comment by shiftkey** [comment]
@sujitp81 thanks for the report. Unfortunately GitHub Enterprise is not supported currently due to #72.

I don't have an timeline for when this will be supported currently as it depends on official support from GitHub, and the workarounds I've explored require manual setup for GitHub Enterprise users...
