### ISSUE TITLE
RPM on opensuse Leap 15.2 Broken

### ISSUE THREAD

**Issue by insiderow** [shiftkey/desktop#322]
### Operating System/Distribution

 Leap 15.2 

### Installer

desktop-release-2.5.3-linux1

Which version of the app?

desktop-2.5.3.

Which installer type?

RPM

### What happened?

Unsuccessful install, with message "nothing provides libX11-xcb needed by github-desktop-2.5.3.linux1-1x86_64"

Checked files in the system. System has libX11-xcb1, but not libX11-xcb.

Thank you!

**Comment by shiftkey** [comment]
@insiderow thanks for the report!

Looks like we need to do something similar to https://github.com/shiftkey/desktop/pull/315 for this dependency...

**Comment by NNowakowski** [comment]
Same issue happening here on OpenSUSE Tumbleweed.
You can ignore the broken dependency in OpenSUSE and the application still seems to work just fine, but there should probably still be a fix for this.
