### ISSUE TITLE
Repositories bug

### ISSUE THREAD

**Issue by TogoFire** [shiftkey/desktop#324]
### Describe the bug

Organizations do not appear to clone the repository.

I tested it on Windows 10, and it appears normally, but on Linux it doesn't.

### Version & OS
Github Desktop Version 2.5.3-linux1

$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana

**Comment by shiftkey** [comment]
> Organizations do not appear to clone the repository.
> 
> I tested it on Windows 10, and it appears normally, but on Linux it doesn't.

This is a known limitation currently - see #281 for more details and the root cause #72.
