### ISSUE TITLE
Repository from github organization not found

### ISSUE THREAD

**Issue by AlexanderHD27** [shiftkey/desktop#325]
### Describe the bug

If I want to clone a Repository from a organization where I'm a member
Github Desktop cannot find it! 

### Version & OS

2.3.1-linux1

### Steps to reproduce the behavior

1. Open Github Desktop
2. Click on Clone Repository
3. Search for a Repository to clone from a organization
4. And nothing found!

### Additional context

This Bug only accured only Linux!

**Comment by shiftkey** [comment]
> This Bug only accured only Linux!

This is a known limitation currently - see #281 for more details and the root cause #72.
