### ISSUE TITLE
Cloning problem

### ISSUE THREAD

**Issue by ForhadCU** [shiftkey/desktop#327]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@ForhadCU please fill out the template with more details about your issue

**Comment by shiftkey** [comment]
Closing this out due to lack of information
