### ISSUE TITLE
Cloning organization repos

### ISSUE THREAD

**Issue by Marki-dev** [shiftkey/desktop#330]
### Describe the feature or problem you’d like to solve
When i try to clone my private org repos i get auth errors, even though i am the owner of the repo
### Proposed solution
N/A

### Additional context

try cloning a organization private repo

**Comment by timhsanchez1** [comment]
I'm having the same problem, I think. At the starting page, my private repos from my organization do not show up in the list of repos in Github Desktop. If I try to clone directly from the URL, it asks for my authentication, and when I enter that it doesn't work.

The repos show up automatically on Github Desktop on my Windows computer, so the error is specific to this linux version.

Thanks for your help!

**Comment by shiftkey** [comment]
Please see #281 which provides more context about this limitation
