### ISSUE TITLE
Commits are too slow [2.5.4-linux1]

### ISSUE THREAD

**Issue by rpereira-tae** [shiftkey/desktop#333]
### Bug Description

When I try to commit any change I press the button `Commit to <branch>` and it takes more than 1 minutes loading to commit. For some reason, if I commit, and quickly click on the History or Changes tabs, the commit takes effect without having to wait any longer.

### Version & OS

Version 2.5.4-linux1
Ubuntu 18.04

### Steps to reproduce the behavior

1. Make any changes on any repository
2. Write commit message
3. Press `Commit to <branch>` button

### Expected behavior

The commit is effective immediately.

### Actual behavior

The commit is effective but it takes a long time loading, from 1 minute to 5 minutes.

**Comment by shiftkey** [comment]
@rpereira-tae thanks for the report. 

This feels very similar to #329 - can you confirm that switching between apps causes the commit to complete for you as well?

**Comment by rpereira-tae** [comment]
Thanks for answering!!

I just tried and actually switching between apps makes the commit effective, also the bug happens with the Undo button. But when I exchange between apps these operations are effective immediately

**Comment by shiftkey** [comment]
Excellent - I'll close this out in favour of that.

This is my theory about what's happening, but I'm not sure when I'll identify the required fix...

> I believe something's change with how Electron (or NodeJS) uses `child_process.execFile` on Linux when a command needs to provide `stdin`. It seems to be just these types of operations that delay until _something else happens_ (like onblur/onfocus of the app) to cause the callbacks to fire.
> 
> The fact that this has been seen on 2.5.3 (Electron 7) and 2.5.4 (Electron 9) makes me wonder if we need to revisit the handling of processes inside `dugite` (which contains our Git plumbing work relevant to this area) for this situation.
