### ISSUE TITLE
Too many Request Issue while installing

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#334]
Here is the error  Details : 

> Err:1 https://packagecloud.io/shiftkey/desktop/any any/main amd64 github-desktop amd64 2.5.4-linux1
  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:10ad:ff59:b50e:2773 443]
> E: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/pool/any/main/g/github-desktop/github-desktop_2.5.4-linux1_amd64.deb  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:10ad:ff59:b50e:2773 443]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

And when I tried to check "https://packagecloud.io/shiftkey/desktop/any/pool/any/main/g/github-desktop/github-desktop_2.5.4-linux1_amd64.deb" in browser  &It returns : 
> "Bandwidth or Storage Limit Exceeded"

**Comment by shiftkey** [comment]
This is not a new issue. From #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle should reset around the 22nd of the month. In the meantime the installers are available with each release on the [Releases](https://github.com/shiftkey/desktop/releases) page.
