### ISSUE TITLE
Problem gpgkey "Bandwidth or Storage Limit Exceeded" 

### ISSUE THREAD

**Issue by luizhanauer-eai** [shiftkey/desktop#337]
### Operating System/Distribution

Which distribution of Linux are you using?
 Ubuntu 20.04

### What happened?
========================
# Terminal
usr@usr:~$ sudo wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -
gpg: nenhum dado OpenPGP válido encontrado.

# Url
https://packagecloud.io/shiftkey/desktop/gpgkey
return "Bandwidth or Storage Limit Exceeded"

**Comment by LGR3** [comment]
May be helpful,

As I update Linux Ubuntu 18.04 with `sudo apt-get update` , I'm getting :

```
Err:11 https://packagecloud.io/shiftkey/desktop/any any InRelease                                                    
429  Too Many Requests [IP: 54.183.57.83 443]

W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease
429  Too Many Requests [IP: 54.183.57.83 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by shiftkey** [comment]
As I said in #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, so I'd recommend the manual install in the meantime from the [Releases](https://github.com/shiftkey/desktop/releases) page. But if you are able to help with sponsorship costs (currently only 20% is covered by the community), it'd be neat to take this up to the next subscription level so it's available to more users, which is $300 per month.

**Comment by LGR3** [comment]
Is packagecloud indeed needed? There are simpler and free solutions for this intent. Best regards,

**Comment by shiftkey** [comment]
@LGR3 I've talked more about this over in https://github.com/shiftkey/desktop/issues/278 but I haven't found an alternative that does all of these things I need:

 - hosted infrastructure
 - accepts `.deb` directly 
 - handles GPG signing natively
 - also supports RPM hosting

But I'm open to other ideas if others know of a similar solution that satisfies this list.

**Comment by adamsmd** [comment]
@shiftkey In a comment at https://github.com/shiftkey/desktop/issues/278#issuecomment-695334021, @jatin-cbs claims openbuildservice.org supports all four things you listed as needing.
