### ISSUE TITLE
Cannot setup package repository on Fedora 32

### ISSUE THREAD

**Issue by liabutt** [shiftkey/desktop#338]
### Operating System/Distribution

Fedora 32
Kernel: 5.8.4-200.fc32.x86_64

### Installer

Newest version as of 10th of September 2020. (I think 2.5.5 beta 1)

### What happened?
When I run: "sudo rpm --import https://packagecloud.io/shiftkey/desktop/gpgkey" I get the following error message:

"curl: (22) The requested URL returned error: 429 
error: https://packagecloud.io/shiftkey/desktop/gpgkey: import read failed(2)."

I get the error when running it as the user with sudo and when running it as root.

**Comment by shiftkey** [comment]
At the moment the PackageCloud feed is disabled, as it's exceeded the bandwidth associated with the current plan.

From an earlier discussion #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, so I'd recommend the manual install in the meantime from the [Releases](https://github.com/shiftkey/desktop/releases) page. But if you are able to help with sponsorship costs (currently only 20% is covered by the community), it'd be neat to take this up to the next subscription level so it's available to more users, which is $300 per month.
