### ISSUE TITLE
[Feature] Hide menu bar

### ISSUE THREAD

**Issue by wyqydsyq** [shiftkey/desktop#34]
I generally use most programs with the top menu bar to be hidden to maximize screen space until I actually need it, in which case I press Alt to reveal it. This behaviour is available in other Electron apps (namely Atom) so should be easy enough to implement in this as well

**Comment by shiftkey** [comment]
@wyqydsyq thanks for the feedback. This is already being tracked in the upstream repository, so please follow along with that issue which has some previous discussion: https://github.com/desktop/desktop/issues/3151

**Comment by probonopd** [comment]
...but please don't hide the menu bar by default ([why?](https://medium.com/@probonopd/make-it-simple-linux-desktop-usability-part-1-5fa0fb369b42)).

**Comment by j-f1** [comment]
To me, it looks like @wyqydsyq was asking for an option to hide the menu bar until the user presses <kbd>Alt</kbd>, not to have it that way by default.
