### ISSUE TITLE
Ability to change display name of repository

### ISSUE THREAD

**Issue by webmasterlv** [shiftkey/desktop#340]
### Describe the feature or problem you’d like to solve

When you have multiple repositories with same names from different projects, there is no clear way to differentiate among them.

I have repositories that happen to have same names such as _foo/bar_ and _baz/bar_ and they look the same. You can hover over it and it shows tooltip, but it takes time switching between projects.

Also, the naming scheme that is now requires to remember what project this repository belongs to. It can at least display full repository name, like _foo/bar_, not just _bar_.

### Proposed solution

A possibility to change display name for repository that is saved locally. When you add new repository, it can use default name as it is now, but in right-click context menu there can be _Rename..._ or _Set title..._ where you can type name that suits you. 

### Additional context

Here is a screenshot: [https://imgur.com/a/2YQSrKF](https://imgur.com/a/2YQSrKF)

**Comment by shiftkey** [comment]
@webmasterlv thanks for the feedback!

Unfortunately this repository is mostly for Linux-specific issues, and I don't have the bandwidth to invest in feature work currently. The upstream project is where I'd recommend to go for these sorts of requests, but I believe #1929 is the most relevant discussion about this request so I'll link to this over there.

**Comment by webmasterlv** [comment]
@shiftkey Ok, thanks for pointing out the direction!
