### ISSUE TITLE
AppImage on RHEL8.2 failed with 404 not found error when attempting enterprise login

### ISSUE THREAD

**Issue by kmarf** [shiftkey/desktop#341]
### Describe the bug

When using latest AppImage release on RHEL8.2 after attempting to sign into an enterprise instance I got a 404 error with Firefox, although when copying the relevant URL to a different non-default Chrome browser it logged me in via SSO successfully but did not update anything in the Github Desktop application (I think as that called Firefox not Chrome). 

### Version & OS

Latest pre-release on fully patched RHEL 8.2 with Firefox as default browser

### Steps to reproduce the behavior

1. Go to sign on using Github enterprise 
2. Default (Firefox) browser opens 
3. See 404 error

### Expected behavior

Perhaps better error-handling in the application saying SSO attempt via default browser failed? 

### Actual behavior

404 not found error in default (Firefox) browser 

### Screenshots

N/A 

### Logs

N/A

**Comment by shiftkey** [comment]
> after attempting to sign into an enterprise instance

This is related to OAuth setup and GitHub Enterprise Server not being aware of the development app.

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547

> > What you suggest to do then? On windows and Mac is working properly.
> 
> This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in [desktop#1525](https://github.com/desktop/desktop/issues/1525) (please upvote if you care) but #72 is tracking this known limitation.
> 
> As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.
> 
> Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.
> 
> The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.
