### ISSUE TITLE
Bandwidth or Storage Limit Exceeded

### ISSUE THREAD

**Issue by edgars-cirulis** [shiftkey/desktop#345]
### Operating System/Distribution

Which distribution of Linux are you using?

Neon KDE - Ubuntu Based

### Installer

Which version of the app? latest
Which installer type? via repo

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

I did: wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -
and got error: gpg: no valid OpenPGP data found / Bandwidth or Storage Limit Exceeded

**Comment by larsvilhuber** [comment]
You might consider switching to https://build.opensuse.org/ which is free, and provides (I think) the same functionality.

**Comment by Sakib-Ar-Rahman** [comment]
I had the same issue. I also tried downloading the .deb package from packagecloud.io website and got the _Bandwidth or Storage Limit Exceeded message._

**Comment by Derkades** [comment]
Also during apt update:
```
Err:12 https://packagecloud.io/shiftkey/desktop/any any InRelease
  429  Too Many Requests [IP: 54.183.28.111 443]
```

**Comment by Sakib-Ar-Rahman** [comment]
I was just able to install Github Desktop after downloading the .deb package (2.5.3) from https://packagecloud.io/shiftkey/desktop/packages/any/any/github-desktop_2.5.3-linux1_amd64.deb .

I am assuming it should be possible to download and install via repo as well.

**Comment by shiftkey** [comment]
The billing cycle reset yesterday, so this is available again for installation and updates.
