### ISSUE TITLE
Request: make available in elementary OS's AppCenter

### ISSUE THREAD

**Issue by grandeljay** [shiftkey/desktop#346]
### Describe the feature or problem you’d like to solve

As somebody who heavily relies on GUIs I would very appreciate if this was available in the elementary OS AppCenter.

### Proposed solution

Since people who use GitHub Desktop are probably also very fond of GUIs, I think that making it available in App stores (in particular elementary OS's AppCenter) would be very appreciated.

**Comment by Vashi1** [comment]
Willing to work on it

**Comment by nerve-hawthorne** [comment]
Unfortunately, this can't be done. :disappointed: 
Github Desktop is build upon `electron`, which is [against elementary's appcenter guidelines](https://docs.elementary.io/develop/appcenter/publishing-requirements#technical-requirements).

**Comment by shiftkey** [comment]
Well that's unfortunate. Thanks for the context @type-xl!

Here's the relevant section:

> Your app may be written in any language, but the front-end must be a native Gtk3 app. Web, Electron, Qt, Java, and other non-native app front-ends will be rejected during the review process. A game may be excepted from this requirement so long as it uses native window decorations and is generally usable on both loDPI and HiDPI displays.
