### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mnznz** [shiftkey/desktop#352]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by shiftkey** [comment]
@mnznz please complete the template

**Comment by mnznz** [comment]
> ### Operating System/Distribution
> Which distribution of Linux are you using?
> 
> ### Installer
> Which version of the app?
> Which installer type?
> 
> ### What happened?
> Provide as much detail as possible. Error messages or output are extremely useful.

tq
