### ISSUE TITLE
I am not able to clone the repository assigned to me.

### ISSUE THREAD

**Issue by surajknkumar** [shiftkey/desktop#357]
### Operating System/Distribution

Which distribution of Linux are you using?
Ubuntu 20.04

### Installer

Which version of the app?
#github-desktop (2.5.4-linux1)

Which installer type?
$ wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -
$ sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
$ sudo apt-get update

### What happened?
I am not able to clone the repository assign to me.
there is a window pop up for authentication 
![image](https://user-images.githubusercontent.com/19522169/95523031-3c62bb00-09eb-11eb-93ae-6515ddb98b71.png)

If I created a new repository of my own then it's working fine.

Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by shiftkey** [comment]
Please check out https://github.com/shiftkey/desktop/issues/281 as there are some limitations with accessing organization repositories currently
