### ISSUE TITLE
429 (Too many requests) error from packagecloud.io

### ISSUE THREAD

**Issue by bduffany** [shiftkey/desktop#358]
### Operating System/Distribution

Ubuntu 20.04

### Installer

DEB

### What happened?

Getting a 429 error from packagecloud.io when running `apt-get update`:

```
Err:10 https://packagecloud.io/shiftkey/desktop/any any InRelease              
  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:10ad:ff59:b50e:2773 443]
```

**Comment by bryangreen** [comment]
Same issue here

**Comment by shiftkey** [comment]
From #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
>
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

**Comment by bryangreen** [comment]
Got it! Here's $5/mo! When does the acct reset?

**Comment by sahil-3011** [comment]
facing same issue

**Comment by shiftkey** [comment]
> When does the acct reset?

@bryangreen the billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.

**Comment by onlycs** [comment]
MOVE TO LAUNCHPAD!!!!
IS FREE I THINK!
Got 2 GiB

**Comment by ryanbranch** [comment]
> Got it! Here's $5/mo! When does the acct reset?

Great idea, thanks for sharing! Until you posted this, I didn't realize how easy it was to set up a monthly donation through GitHub.

Thank you @shiftkey for everything you've done with this project! As an Ubuntu newbie it's been immensely helpful for me at my new job, and I hope you're eventually able to source the entire cost through community contributions.

**Comment by shiftkey** [comment]
Just bumping this to indicate the billing cycle has reset
