### ISSUE TITLE
Committing is very slow

### ISSUE THREAD

**Issue by tamas646** [shiftkey/desktop#362]
I've updated to the latest version of Github Desktop on my linux machine, and I've noticed that every commit takes more than (or nearly) a minute for me.

My Github version is 2.5.4-linux1.

Here are my logs from the last two commits. (Older commits were also very slow)
[2020-10-24.desktop.production.log](https://github.com/shiftkey/desktop/files/5432756/2020-10-24.desktop.production.log)

**Comment by shiftkey** [comment]
@tamas646 I think you're encountering #329

**Comment by tamas646** [comment]
@shiftkey Yes, you are right. I tested it, and it seems I'm facing the same issue.
