### ISSUE TITLE
Long named branches to break into another line

### ISSUE THREAD

**Issue by vinnom** [shiftkey/desktop#364]
### Describe the feature or problem you’d like to solve

Long named branches just collapses into "..."

### Proposed solution

Long named branches on browser breaks into another line, which makes it easier to read (even if github-desktop displays the full name when hovering the cursor over the branch name). Maybe this could be applied to the "Current branch" box too - or make them resizable.

### Additional context
![Captura de tela de 2020-10-30 09-21-53](https://user-images.githubusercontent.com/11577103/97706429-711add00-1a94-11eb-92e7-24b012eb3a3e.png)
![Captura de tela de 2020-10-30 09-15-40](https://user-images.githubusercontent.com/11577103/97706432-71b37380-1a94-11eb-8964-9975dd636187.png)

**Comment by shiftkey** [comment]
@vinnom thanks for the feedback.

Unfortunately this isn't something that I plan to address, and should be proposed on the main project: https://github.com/desktop/desktop
