### ISSUE TITLE
Unable to sign in with enterprise account

### ISSUE THREAD

**Issue by Brin-o** [shiftkey/desktop#366]
### Describe the bug
When trying to log into an enterprise server, it is impossible to connect to it. I get error 402 if not using a browser and a 404 page if I do use the browser for log in. On Windows this works perfectly.

### Version & OS

Version 2.5.4-linux1 & Pop OS 20.04

### Steps to reproduce the behavior
1. Log in with enterprise
2. Use any of the sign in options

### Expected behavior

Being able to normally follow the log in procedure

### Actual behavior

Getting an error 402

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/49071768/98184293-515b3d00-1f0a-11eb-9405-e0aed29b6d27.png)
![image](https://user-images.githubusercontent.com/49071768/98184308-5cae6880-1f0a-11eb-96a3-d5b513962383.png)

### Logs
https://pastebin.com/zF6k0z8g

**Comment by shiftkey** [comment]
This is related to OAuth setup and GitHub Enterprise Server not being aware of the development app.

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547

> > What you suggest to do then? On windows and Mac is working properly.
> 
> This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in [desktop#1525](https://github.com/desktop/desktop/issues/1525) (please upvote if you care) but #72 is tracking this known limitation.
> 
> As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.
> 
> Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.
> 
> The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.
