### ISSUE TITLE
GPG Key page seems to be down. 

### ISSUE THREAD

**Issue by hffaust** [shiftkey/desktop#374]
Trying to pull the gpg key from https://packagecloud.io/shiftkey/desktop/gpgkey gives a page with the message "Bandwidth or Storage Limit Exceeded". This is preventing the gpg from being added in APT and installed on debian based linux systems.

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.

**Comment by hffaust** [comment]
Cool, I did a manual install from the release page. Just wanted to make you aware in case you weren't already. Thank you.

**Comment by shiftkey** [comment]
> Just wanted to make you aware in case you weren't already. 

No problem. I get email notifications as this bandwidth gets used up, all the way up to when it finally gets disabled.

**Comment by lskillen** [comment]
@shiftkey We'd be happy to help with this over at @cloudsmith-io; OSS repositories get upto 1TB of bandwidth for exactly $0. :-) Shouldn't this project have qualified for the OSS tier at Packagecloud though?
