### ISSUE TITLE
sudo apt update throws error report saying too many requests

### ISSUE THREAD

**Issue by basuparth** [shiftkey/desktop#377]
### Operating System/Distribution

Ubuntu 18.04
### Installer

The present version of the app. I was successfull in the installation 10-12 days back but now I am running into error. Also the official page does not allow to download the package saying "bandwidth exceded".

Error Report
Unable to update with “apt-get” getting “429 too many requests” error

**Comment by Roger-ZRZ** [comment]
Same error here: 
Err:8 https://packagecloud.io/shiftkey/desktop/any any InRelease        
  429  Too Many Requests 
Reading package lists... Done                     
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests

**Comment by Shade1996** [comment]
Same error:
https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests 

kubuntu 20.04

**Comment by andvenancio** [comment]
The same problem...
![image](https://user-images.githubusercontent.com/25935569/99298536-9c3d5480-2828-11eb-8194-e6e87a5347eb.png)

I use **Linux Mint 20 Cinnamon**.

**Comment by ketilBed** [comment]
Hi 

I'm getting the same error. It looks like we have run out of bandwidth on the hosting site (packagecloud.io). Either we find new hosting or we wait a month.

**Comment by cbtek** [comment]
I ran into this issue as well on Ubuntu 20.04.  Had to download and install the .deb directly from releases page.

**Comment by sylle-dev** [comment]
Same here on KDE Neon

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
