### ISSUE TITLE
Use OpenSUSE's build service instead of packagecloud

### ISSUE THREAD

**Issue by saltedcoffii** [shiftkey/desktop#378]
Packagecloud is, as the project author has stated, not cheap. OpenSUSE's build service aids in building software for APT and RPM based linux distros, and is free for open source software.

Here's an example of what a package download page would look like:
[https://software.opensuse.org//download.html?project=home%3AIBBoard%3Acawbird&package=cawbird](https://software.opensuse.org//download.html?project=home%3AIBBoard%3Acawbird&package=cawbird) 
The project home page:
[https://build.opensuse.org/](https://build.opensuse.org/)
The FAQ:
[https://en.opensuse.org/openSUSE:Build_Service_FAQ](https://en.opensuse.org/openSUSE:Build_Service_FAQ)

Hopefully, if this platform is usable, it will help with the financial constraints. <3

**Comment by shiftkey** [comment]
Please follow along with #363
