### ISSUE TITLE
Debian Packaging: Executable name 'desktop' and package name 'desktop' are ambiguous

### ISSUE THREAD

**Issue by teward** [shiftkey/desktop#38]
*This is not really a full issue or bug report, but as an Ubuntu developer, I am acutely aware of the evils of package naming.  This is a suggestion on the basis of my experience as a Packager.*

The current binaries built for GitHub Desktop for Linux (RCs) are generated so that the package itself in the `debian/control` files and others is named `desktop`.

This is extremely ambiguous and unclear what it actually is, and makes understanding what is actually installed or usable or not equally more difficult.

If possible, I would suggest that you adjust the packaging so that the binary for GitHub Desktop is installed as `github-desktop`, and that the package name be adjusted as well.  It currently installs as `desktop` and that is very ambiguous as to what it actually is.

**Comment by shiftkey** [comment]
@teward thanks for the report. We're already tracking this in #22, so please follow along with that issue.
