### ISSUE TITLE
"Open in Visual Studio Code" from Github Desktop

### ISSUE THREAD

**Issue by Daggerpov** [shiftkey/desktop#380]
### Describe the feature or problem you’d like to solve

Adding this button to Github Desktop will allow users to open their repositories from Github Desktop with their IDE (not sure if it works with other IDEs other than VSC). I've had this feature on Mac and Windows. 

### Proposed solution

Similarly to how there is currently a "view on Github" button, this would be added right above just like in the Native Mac/Windows Github Desktop applications. 

### Additional context
This is what it looks like on the Native Github Desktop application (on Mac):

![image](https://user-images.githubusercontent.com/53918934/100609721-75792680-32dc-11eb-8566-e8690b390e5e.png)

and this is what it looks like on Shiftkey's (on Pop! OS 20.10: 

![image](https://user-images.githubusercontent.com/53918934/100609757-86299c80-32dc-11eb-8b93-dd0af0143b35.png)

**Comment by shiftkey** [comment]
@Daggerpov this should already be supported in the app, with this being the component that decides what to display:

https://github.com/shiftkey/desktop/blob/5f7bf50ba153d4cf1258a6a16643081bcffe4172/app/src/ui/repository.tsx#L395-L404

Have you selected VSCode in your preferences dialog? These are the paths we check on disk for the executable:

https://github.com/shiftkey/desktop/blob/5f7bf50ba153d4cf1258a6a16643081bcffe4172/app/src/lib/editors/linux.ts#L73-L74

**Comment by Daggerpov** [comment]
Oh, the issue was with the Flatpak version of Visual Studio Code. When I switched over to the Debian one, I just discovered that it now works fine! I don't know if this is an issue on your application's part of theirs, though, in terms of compatibility.

**Comment by shiftkey** [comment]
I haven't checked in with the Flatpak builds in a while but that's not something I maintain.

#265 is the tracking issue for that discussion.

**Comment by shiftkey** [comment]
Closing this out as we're using #265 to discuss general Flatpak support
