### ISSUE TITLE
Can't start AppImage on Debian 10 due to setuid/sandbox issue

### ISSUE THREAD

**Issue by MakiWolf** [shiftkey/desktop#383]
### Operating System/Distribution

Which distribution of Linux are you using?
Debian 10

### Installer

Which version of the app? 2.5.7
Which installer type? AppImage

### What happened?
not opening AppImage

![grafik](https://user-images.githubusercontent.com/73300633/101258845-8800bf00-3725-11eb-9469-806a3f022dbd.png)

I have also tried it on Ubuntu 20.10, there it opened with no problems
Running -no-sandbox also solved that on Debian 10

**Comment by shiftkey** [comment]
This is not a new issue, and was something specific to Debian defaults that we investigated as part of an earlier issue. Here's the context: https://github.com/shiftkey/desktop/issues/222#issuecomment-622962431

**Comment by ghost** [comment]
why not use the .deb or package repo?
probably faster

**Comment by shiftkey** [comment]
Closing this out due to inactivity, and I want to signal that this is something that I probably won't fix without more context. 

I'm not a user of the AppImage package these days and I don't know if I can fix this given the constraints that Debian enforces...
