### ISSUE TITLE
Repos From the New Organizations are not appearing to clone

### ISSUE THREAD

**Issue by irdanish11** [shiftkey/desktop#390]
### Describe the bug

Repos From the New Organizations are not appearing to clone. When you are added to a private GitHub organization and try to clone a new private repository from your new organization the repo or the organization does not appear, while this is not the case for GitHub Desktop for windows.

### Version & OS

2.5.7 Linux RC1 on Ubuntu 20.04 LTS

**Comment by shiftkey** [comment]
This is a known limitation. Please refer to #281 for more information.
