### ISSUE TITLE
Icon does not scale well on Ubuntu

### ISSUE THREAD

**Issue by ghost-458** [shiftkey/desktop#391]
### Describe the feature or problem you’d like to solve

The icon does not downscale well on Ubuntu 20.04. I'm using Github Desktop 2.5.4-linux1. Here's a screenshot of my activity bar next to other applications: 
![image](https://user-images.githubusercontent.com/4730591/102388717-fa279e00-3f86-11eb-97df-cab34b8af5b8.png)

This is a fairly minor problem but it just looks odd next to the other icons.

### Proposed solution

The ideal solution would be to include 128x128, 64x64, 32x32 prescaled icons and an svg. I think the issue is downscaling is done using nearest neighbor on a large icon, and it'd be better to just include the smaller icons instead and a vector image.

Here's what it should look like in comparison:

![image](https://user-images.githubusercontent.com/4730591/102389670-445d4f00-3f88-11eb-8938-69606a9fcfd8.png)

**Comment by shiftkey** [comment]
@kevinhikaruevans thanks for the report. I'm a bit puzzled about this one but here's some context about the packaging side of things.

These are the versions I'm specifying to `electron-installer-debian`:

https://github.com/shiftkey/desktop/blob/3945af9df74a0c1674017cc1af1fbedbd8da48ab/script/package-debian.ts#L59-L63

This seems to work fine based on the docs: https://github.com/electron-userland/electron-installer-debian#optionsicon

I'm not sure if there's an SVG version of the icon around that could be used here, but it would be worth checking the installer is actually using these values, and not falling back to something else unexpected here.

**Comment by ghost-458** [comment]
I've added a PR that adds in the smaller icons. I tested it and it looks less jagged. :+1: 

There is an svg available here: https://desktop.github.com/images/desktop-icon.svg but it looks a little different from the pngs, so I didn't include it.
