### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by everlyy** [shiftkey/desktop#397]
### Operating System/Distribution

Which distribution of Linux are you using?
Ubuntu 20.10

### Installer

I don't know what version of the app I'm using.
The installation instructions I followed where the ones described in the "packagecloud Debian/Ubuntu distributions" section

### What happened?

I run all the commands listed in the installation instructions in my terminal but when I run `sudo apt-get update` It says: `429  Too Many Requests [IP: 54.176.179.107 443]` and then it says: `W: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
