### ISSUE TITLE
Can't sign in Pop_Os 20.10

### ISSUE THREAD

**Issue by DaFray31** [shiftkey/desktop#398]
### Describe the bug

Just trying to connect to my github account.
Click on sign in, tht do nothing (the button load just 1s)

And with external, the load is infinite...

### Version & OS

Pop!_Os 20.10
Gnome : 3.38.1
X11

**Comment by shiftkey** [comment]
@DaFray31 please also specify which version of the app you are using

**Comment by DaFray31** [comment]
> @DaFray31 please also specify which version of the app you are using

Version 2.4.1-linux1

**Comment by DaFray31** [comment]
Okay, i just try
I skip the login
And retry in options, now i get :
![Capture d’écran du 2020-12-20 18-12-13](https://user-images.githubusercontent.com/24704691/102719522-ee253e80-42ee-11eb-8b64-a876e27f95d0.png)

**Comment by shiftkey** [comment]
I'm not familiar with those steps, but please try a newer version from the Releases page: https://github.com/shiftkey/desktop/releases

The version you are using is about 6 months behind.

**Comment by DaFray31** [comment]
> I'm not familiar with those steps, but please try a newer version from the Releases page: https://github.com/shiftkey/desktop/releases
> 
> The version you are using is about 6 months behind.

That work , soory ! Thanks !
