### ISSUE TITLE
github desktop in linux version 2.6.1-linux2, commit to master is slow

### ISSUE THREAD

**Issue by askgh** [shiftkey/desktop#399]
### Describe the bug

commit to master is slow, about 10s. but the version 2.5 has no this problem

### Version & OS

Version 2.6.1-linux2, centos 8 with kde

**Comment by shiftkey** [comment]
> commit to master is slow, about 10s. but the version 2.5 has no this problem

I'm pretty confident this is the same as #329 and while it seems the behaviour has changed in 2.6.x based on recent comments I think this remains unresolved.

Please follow along with #329
