### ISSUE TITLE
Chrome cant open the authorization page

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#400]
### Operating System/Distribution

Which distribution of Linux are you using?
ChromeOS 87 Linux Beta (Debian Buster VM)
### Installer

Which version of the app?
Version 2.6.1-linux2
Which installer type?
.deb file

### What happened?
When I went to sign in with github.com, it said Google ChromeOS couldn't open this page
Url: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=9839eb7c-e90b-43d0-a8ed-4c2516139132

Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by shiftkey** [comment]
@FlyingParrot225 is this the same as #138?

**Comment by ghost** [comment]
Yes

**Comment by shiftkey** [comment]
@FlyingParrot225 cool, I'm going to close this out in favour of that issue, but the last I looked at this there were some issues that remain unresolved https://github.com/shiftkey/desktop/issues/138#issuecomment-643782593
