### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by GeorgeKaragiannis** [shiftkey/desktop#401]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

After I setup the package repository and execute the apt-get update command, I have the following problem and I cannot install it. Why is this happening? But I didin't have any issue with installation using the .deb installation file. I run MX-Linux: MX-19.3_x64 patito feo February 15  2020 Kernel: 4.19.0-6-amd64 x86_64 bits: 64 Desktop: Xfce 4.14.2 

Hit:1 http://deb.opera.com/opera stable InRelease
Hit:2 http://ftp.cc.uoc.gr/mirrors/linux/mx/mx/repo buster InRelease                               
Hit:3 http://deb.debian.org/debian buster-updates InRelease                                        
Hit:4 https://deb.opera.com/opera-stable stable InRelease                                          
Hit:5 http://dl.google.com/linux/chrome/deb stable InRelease                                       
Hit:6 http://www.geogebra.net/linux stable InRelease                                               
Hit:7 https://repo.skype.com/deb stable InRelease                                                  
Hit:8 http://deb.debian.org/debian buster InRelease                                                
Hit:9 http://packages.microsoft.com/repos/edge stable InRelease                                    
Hit:10 https://repo.steampowered.com/steam stable InRelease                                        
Hit:11 http://deb.debian.org/debian-security buster/updates InRelease                              
Hit:12 http://deb.debian.org/debian buster-backports InRelease                                     
Hit:13 http://packages.microsoft.com/repos/vscode stable InRelease                                 
Ign:14 https://mkvtoolnix.download/debian buster InRelease                                         
Hit:15 https://mkvtoolnix.download/debian buster Release                                     
**Err:16 https://packagecloud.io/shiftkey/desktop/any any InRelease      
  429  Too Many Requests [IP: 54.183.38.243 443]
Hit:17 https://repo.steampowered.com/steam beta InRelease
Reading package lists... Done
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 54.183.38.243 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.**

**And when I run the sudo apt install github-desktop says to me this:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package github-desktop is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'github-desktop' has no installation candidate**

**Comment by shendeguize** [comment]
Same problem, if try to access [https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease](https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease) directly, the page shows that "Bandwidth or Storage Limit Exceeded"

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available. 

Please also follow along with the original issue tracking our use of PackageCloud: #278
