### ISSUE TITLE
Manjaro Installation Issue 

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#402]
Manjaro Installation Issue 

Preparing...
Cloning github-desktop-bin build files...
Checking github-desktop-bin dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building github-desktop-bin...
==> Making package: github-desktop-bin 2.5.7-1 (Sat 26 Dec 2020 12:51:09 PM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading GitHubDesktop-linux-2.5.7-linux1.deb...
** Resuming transfer from byte position 68145744
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   660  100   660    0     0   1349      0 --:--:-- --:--:-- --:--:--  1346

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
==> ERROR: Failure while downloading https://github.com/shiftkey/desktop/releases/download/release-2.5.7-linux1/GitHubDesktop-linux-2.5.7-linux1.deb
    Aborting...
Failed to build github-desktop-bin
Uhh dunno what's wrong but my package manager cant build github desktop

**Comment by shiftkey** [comment]
@meimei35 

> ** Resuming transfer from byte position 68145744
> ...
> curl: (22) The requested URL returned error: 416

This response code `416 Range Not Satisfiable` suggests the server isn't able to resume downloading the file. Are you able to clear out any temporary files and see if you can download the package from scratch.

**Comment by ghost** [comment]
Clean your pacman cache- `sudo pacman -Sc`
Update your repos- `sudo pacman -Syy`
Then retry installing.

**Comment by ghost** [comment]
> Clean your pacman cache- `sudo pacman -Sc`
> Update your repos- `sudo pacman -Syy`
> Then retry installing.

worked thanks
