### ISSUE TITLE
 I cant log in into my account

### ISSUE THREAD

**Issue by cmassavanhanejr** [shiftkey/desktop#407]
### Cant log in into my account

When I try to login into my account I get this error: he server responded with an error while attempting to authenticate (404)

### Steps to reproduce the behavior

1. Go to 'Sign in'
2. Click on '..sign in button.'

### Expected behavior

Access to My  account and see my repositories

### Actual behavior

404 error

**Comment by warshallrho** [comment]
I have met a similar issue, when I clicked on 'sign in', a blank page opened.
I use ubuntu 18.04

**Comment by shiftkey** [comment]
Please specify the version in use and the steps to reproduce this, as sign-in with username/password is no longer supported on GitHub - [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1) has more context.

**Comment by shiftkey** [comment]
Closing this out as I'm not clear on which version this is occurring with.

Please open a new issue if this is still happening on the latest release (`2.6.2-linux1`).
