### ISSUE TITLE
Issue in signing in into GitHub Desktop application

### ISSUE THREAD

**Issue by awaisanwar12** [shiftkey/desktop#408]
### Describe the bug
It says failed to sign in and authentification error 404

### Version & OS

Ubuntu lts 20.4 
![Screenshot from 2021-01-08 19-01-48](https://user-images.githubusercontent.com/74348183/104023924-2af49f00-51e4-11eb-931a-bbadab9f8219.png)

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
Please specify the version in use, as sign-in with username/password is no longer supported on GitHub - [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1) has more context.

**Comment by shiftkey** [comment]
Closing this out as I'm not clear on which version this is occurring with, and the steps to reproduce are missing.

Please open a new issue if this is still happening on the latest release (`2.6.2-linux1`).
