### ISSUE TITLE
Open in browser not working within WSL due to account requirement

### ISSUE THREAD

**Issue by joshhunt** [shiftkey/desktop#409]
I'm using this Linux fork on Windows within WSL, and accessing it via xserver remote (on the same windows machine), as this is much quicker than the windows App accessing my git repo over the WSL network share.

I use [wslu](https://github.com/wslutilities/wslu) to set a `BROWSER=wslview` variable to something that can only links within my browser in my host Windows environment. Running `wslview https://github.com` successfuly opens Chrome in Windows.

I appreciate this is exceptionally niche roundabout way of doing things 😅 

### Describe the bug

When running the app within a WSL2 Ubuntu 18.04.2 LTS environment, the "View on Github" options are not available.  

The initial in-browser signup flow did work successfully (launching a Ubuntu chrome app).  
I have set `BROWSER=wslview` environment variable to open links in my Windows default browser

### Version & OS

Version 2.5.4-linux1

Ubuntu 18.04.2 LTS running within WSL2 on Windows.

### Steps to reproduce the behavior

1. Set `BROWSER=wslview` environment variable
2. Click Repository Menu

### Expected behavior

"View on Github" is not greyed out, and it opens the repo in a browser configured by my BROWSER environment variable.

### Actual behavior

"View on Github" is greyed out

**Comment by shiftkey** [comment]
@joshhunt that _is_ an interesting setup.

I'm not aware of how the `BROWSER` environment variable works with Electron apps but `View on GitHub` is enabled/disabled based on whether we can detect the repository is hosted on GitHub:

https://github.com/shiftkey/desktop/blob/8bdb92182138ffc23691f81b4278b1a3002abbe8/app/src/lib/menu-update.ts#L267

I suspect that something related to how the repository is detected (i.e. can we get details about the repository through the GitHub API) isn't working for your situation:

https://github.com/shiftkey/desktop/blob/8bdb92182138ffc23691f81b4278b1a3002abbe8/app/src/lib/menu-update.ts#L78-L89

**Comment by joshhunt** [comment]
Ahhh. Your comment made me check, and i just noticed that I'm logged into Github in the app because of this error 
![image](https://user-images.githubusercontent.com/46142/104040651-d7785600-51cf-11eb-9838-93713d57d9bd.png).

That teaches me for ignoring errors.

Apparently this might have something to do with gnome-keyring? I notice the readme mentions that, and how it's related to X server. I'll investigate and report back whether this is still an issue once I'm logged in.

**Comment by shiftkey** [comment]
Authentication in the Linux fork of GitHub Desktop depends on the `libsecret` API and a service to be running to store credentials. `gnome-keyring` supports the `libsecret` API, which is why it gets a mention. Not sure how that works in WSL but I'm not aware of other options here.

**Comment by shiftkey** [comment]
Closing this out because it's outside the scope of the project, as we depend on `libsecret` for providing credentials

**Comment by MiloudiMohamed** [comment]
@joshhunt could you please explain how did you get GitHub desktop work on WSL2 or link me to a blog post explaining that, I've spent too many hours trying to figure that out with no success

Steps I did:
- Login to WSL Ubuntu
- Install github desktop
- Run `github-desktop`

I get as a result 

```
The futex facility returned an unexpected error code.
Aborted
```
Thank you
