### ISSUE TITLE
Broken Commit

### ISSUE THREAD

**Issue by Aeirex** [shiftkey/desktop#41]
I get this error, I moved my Windows repos to my Linux filesystem and Windows can still commit and pull just fine.

This is on Fedora 27, never tested on Arch Linux.

`"The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed"`

My repo is "private", I pay monthly to use GitHub private repos. This means it may be a bug with that, also my other issue with links not appearing. It lacks permission to access these repos due to broken account settings in the client.

Normal repos work fine. I tested out sync.

**Comment by shiftkey** [comment]
@Aeirex

> It lacks permission to access these repos due to broken account settings in the client.

Are you signed into your GitHub account in the app? Are there any errors in the Developer Tools console window when you try and sign in that might indicate it's not completing as expected?

**Comment by Aeirex** [comment]
I forgot that Electron is based on Google Chrome. Here are the console errors.

[-1524187496085.log](https://github.com/shiftkey/desktop/files/1930296/-1524187496085.log)

**Comment by Aeirex** [comment]
This issue is likely the same bug as this.
https://github.com/shiftkey/desktop/issues/39

**Comment by shiftkey** [comment]
> This issue is likely the same bug as this.
> #39

Lets get to the bottom of that over there
