### ISSUE TITLE
Popup windows get stuck loading for too much time 

### ISSUE THREAD

**Issue by lutzseverino** [shiftkey/desktop#412]
### Describe the bug

When, _for example_, discarding changes or committing them, a window shows up saying that all the changes are being discarded or committed, for some reason, the process takes a lot to finish. This can be avoided by resizing the window: immediately after doing this, the process ends instantly and successfully. If you, on the other hand, don't resize the window, the process will also finish successfully but after a ton more time.  

### Version & OS

GitHub desktop: Version `2.5.4-linux1` (Downloaded `2.6.1-linux2`, it also happens in this version)
OS: Ubuntu 20.10

### Steps to reproduce the behavior

1. Change a file.
2. Discard all changes.
3. See it takes a while to load.
4. Resize the window.
5. See the process ends instantly after resizing.

### Expected behavior

You shouldn't have to resize the window to make the process finish rapidly.

### Actual behavior

The popup window loads indefinitely until you resize or wait a long time.

### Screenshots

Easy to reproduce, no screenshots needed.

### Logs

Not applicable.

**Comment by shiftkey** [comment]
#332
