### ISSUE TITLE
GitHub Desktop very slow to commit after re-install

### ISSUE THREAD

**Issue by kvz** [shiftkey/desktop#413]
### Describe the bug

Before my reinstall, a commit would be immediate, just like on my commandline (which still is immediate touching the same files in the same repo). After the reinstall, it takes over a minute to commit a simple README.md change.

### Version & OS

Version 2.5.4-linux1.

I tried the latest version as well, to find the same behavior.

### Steps to reproduce the behavior

1. Change any file 
2. Commit

### Expected behavior

Near-immediate commit

### Actual behavior

Commit takes over a minute

### Screenshots

![image](https://user-images.githubusercontent.com/26752/104133133-d4bd6280-5381-11eb-8091-22e92294c7fc.png)

### Logs

```
2021-01-10T19:15:38.860Z - info: [ui] Background fetch for 3 repositories took 0.623sec
2021-01-10T19:16:35.940Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-01-10T19:18:13.325Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 95.848s)
2021-01-10T19:18:13.611Z - info: [ui] [Timing] Action 'create commit' for 'transloadit/transloadit-api2' took 96.172s
2021-01-10T19:20:24.302Z - info: [ui] Executing parseTrailers: git interpret-trailers --parse (took 122.124s)
```

Originally posted over at https://github.com/desktop/desktop/issues/11364

**Comment by csouers** [comment]
**Version & OS:** Version 2.5.4-linux1 on Ubuntu 20.04

If you leave the window and come back, it will apply the commit. Within the last week, I did a fresh install of Ubuntu 20.04 on two different machines and they both exhibit the same issue.

Additionally, I just created a test repository through Github Desktop and it has the same issue. The progress indicator just spins, but it doesn't move to the commit history screen until focus has left and returned to Github Desktop. The repository does get made in this instance, but it doesn't seem to finish properly until you've returned to the application.

**Reproduction flow:**
Step 1: Create a new repository inside of GitHub Desktop. The progress indicator will spin. The repository and its folder get created, but doesn't finish. It gets stuck on something related to `.gitattributes`. 
Step 2: Open terminal and verify with `git status`:
```pi@pi-ThinkPad-X250:~/Documents/GitHub/y$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitattributes

nothing added to commit but untracked files present (use "git add" to track)
```

Step 3: Go back to Github Desktop and it will quickly go to the commit screen. 
Step 4: Back to terminal once more to check what's changed:
```pi@pi-ThinkPad-X250:~/Documents/GitHub/y$ git status
On branch master
nothing to commit, working tree clean
```

So it's getting stuck somewhere within the process of setting up the repository. In the case of the topic of the issue, I've verified that any file commits don't take place until you've returned to the window.

Hope this helps.

**Comment by csouers** [comment]
Probably related to https://github.com/shiftkey/desktop/issues/329?

**Comment by pavlenex** [comment]
> If you leave the window and come back, it will apply the commit. Within the last week, I did a fresh install of Ubuntu 20.04 on two different machines and they both exhibit the same issue.

I can confirm this is the case. Leaving window and coming back works. Otherwise its stuck in a loop. Ubuntu 20.04 here.

**Comment by kvz** [comment]
Wow yes, confirmed, if the GitHub Desktop windows loses focus and regains it, commits are instant again, vs the previous 122s as measured in the log lines I inlined.

**Comment by johannesschobel** [comment]
Ubuntu 18.x here, same issue

**Comment by sergiialtana** [comment]
Ubuntu 20.04 LTS - same here

**Comment by shiftkey** [comment]
This is the same as #329, please follow along with that issue.
