### ISSUE TITLE
Cant install due to a Too Many Requests error

### ISSUE THREAD

**Issue by jmorrow10** [shiftkey/desktop#415]
### Operating System/Distribution

Which distribution of Linux are you using?

### What happened?

Tried to install on my Linux image but couldn't due to the error.   I looked around online and found that some people worked around the error by having different URL's.  Do you know what those would be or a way to fix it?  Terminal Text below

unlwendigo@RMC-desktop:~ wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
unlwendigo@RMC-desktop:~ sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
unlwendigo@RMC-desktop:~ sudo apt-get update
Get:1 file:/var/cuda-repo-10-2-local-10.2.89  InRelease
Ign:1 file:/var/cuda-repo-10-2-local-10.2.89  InRelease
Get:2 file:/var/visionworks-repo  InRelease
Ign:2 file:/var/visionworks-repo  InRelease
Get:3 file:/var/visionworks-sfm-repo  InRelease
Ign:3 file:/var/visionworks-sfm-repo  InRelease
Get:4 file:/var/visionworks-tracking-repo  InRelease
Ign:4 file:/var/visionworks-tracking-repo  InRelease
Get:5 file:/var/cuda-repo-10-2-local-10.2.89  Release [574 B]
Get:6 file:/var/visionworks-repo  Release [2,001 B]
Get:7 file:/var/visionworks-sfm-repo  Release [2,005 B]
Get:5 file:/var/cuda-repo-10-2-local-10.2.89  Release [574 B]
Get:8 file:/var/visionworks-tracking-repo  Release [2,010 B]
Get:6 file:/var/visionworks-repo  Release [2,001 B]
Get:7 file:/var/visionworks-sfm-repo  Release [2,005 B]
Get:8 file:/var/visionworks-tracking-repo  Release [2,010 B]
Hit:9 http://packages.ros.org/ros/ubuntu bionic InRelease
Hit:10 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:13 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:15 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Hit:16 https://repo.download.nvidia.com/jetson/common r32.4 InRelease
Err:17 https://packagecloud.io/shiftkey/desktop/any any InRelease
  429  Too Many Requests [IP: 54.176.179.107 443]
Hit:18 https://repo.download.nvidia.com/jetson/t210 r32.4 InRelease
Reading package lists... Done
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 54.176.179.107 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
unlwendigo@RMC-desktop:~ sudo apt install github-desktop
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package github-desktop

**Comment by fritz-0** [comment]
I am encountering the same issue. Is there a work around for this?

**Comment by johannesschobel** [comment]
same here

**Comment by fritz-0** [comment]
I had the same issue because the site where the packages are hosted might have reached the limits already.

Anyway, here is a possible **SOLUTION**. 

You can go to https://github.com/shiftkey/desktop/releases then find a release you want to install.

For example, you can use this if you have Ubuntu:
https://github.com/shiftkey/desktop/releases/tag/release-2.6.1-linux2

Download the .deb package for example:
![image](https://user-images.githubusercontent.com/55884003/104463062-439df400-55ec-11eb-8679-41e3b23f3add.png)

Then, just install it just like any other .deb package in Ubuntu.

**Comment by johannesschobel** [comment]
did the same, yes.. :) But would be nice to update the `README`, as the installation method is not correct in this case

**Comment by jmorrow10** [comment]
> I had the same issue because the site where the packages are hosted might have reached the limits already.
> 
> Anyway, here is the **SOLUTION**.
> 
> You can go to https://github.com/shiftkey/desktop/releases then find a release you want to install.
> 
> For example, you can use this if you have Ubuntu:
> https://github.com/shiftkey/desktop/releases/tag/release-2.6.1-linux2
> 
> Download the .deb package for example:
> ![image](https://user-images.githubusercontent.com/55884003/104463062-439df400-55ec-11eb-8679-41e3b23f3add.png)
> 
> Then, just install it just like any other .deb package in Ubuntu.

Are any of those files able to be downloaded on Ubuntu 18.04?  I'm trying to get it downloaded but none of them successfully download for some reason?  I guess I need a ARM 64 installation file and I dont know where to get one of those

**Comment by johannesschobel** [comment]
I run Ubuntu 18.04 as well.. I just downloaded the *.deb file. Works for
me.. but depend on the cpu architecture I guess

jmorrow10 <notifications@github.com> schrieb am Sa., 16. Jan. 2021, 22:16:

**Comment by mnh48** [comment]
I have the same issue, on Ubuntu 20.04.1 LTS
```
$ sudo apt update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Err:3 https://packagecloud.io/shiftkey/desktop/ubuntu focal InRelease
  429  Too Many Requests [IP: 54.183.38.243 443]
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 109 kB in 1s (77.0 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/ubuntu/dists/focal/InRelease  429  Too Many Requests [IP: 54.183.38.243 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by igorr0driguez** [comment]
Same thing here. https://packagecloud.io/shiftkey/desktop/ubuntu/dists/focal/InRelease isn't working.

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
