### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#417]
### Operating System/Distribution

Which distribution of Linux are you using?
POP OS
### Installer

Which version of the app?
Which installer type?
deb
### What happened?
All the installation wacannot login to githubs successful but 
Provide as much detail as possible. Error messages or output are extremely useful.
Github login error in the github desktop app

**Comment by shiftkey** [comment]
The version from the Pop_OS store seems to be using an old version of the app based on the discussion in #414, and needs to be upgraded.

There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).
