### ISSUE TITLE
Unable to get authorized while sign in. 

### ISSUE THREAD

**Issue by omerasif57** [shiftkey/desktop#421]
### Operating System/Distribution

Ubuntu 20.04.1 LTS

### Installer
GitHubDesktop-linux-2.6.1-linux2

Which version of the app?
2.6.1
Which installer type?
.AppImage

### What happened?
I get directed to browser then I authenticate my user credentials then It says redirecting to github app but fail. 
no error msg. nothing.

Please advise.

**Comment by shiftkey** [comment]
Closing this in favour of #416 to avoid duplicated issues
