### ISSUE TITLE
shared repo is not cloned ubuntu github desktop 2.6.2

### ISSUE THREAD

**Issue by Kathir120796** [shiftkey/desktop#425]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@Kathir120796 please fill out the provided template, as I lack the context to understand the issue at hand

**Comment by shiftkey** [comment]
Closing this out due to inactivity and incomplete issue template
