### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by jyotiranjan97** [shiftkey/desktop#426]
I can't login to my Git Hub account through Desktop App on POP OS 20.04 LTS

**Comment by shiftkey** [comment]
As I understand it based on #414 the version on the Pop store is older than the current version.

There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported, which I believe is what's happening here. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).
