### ISSUE TITLE
Add FreeBSD package

### ISSUE THREAD

**Issue by jalfonsi** [shiftkey/desktop#427]
Please, add binary package for FreeBSD.

**Comment by shiftkey** [comment]
I was curious what was involved with this but sadly it looks like a lot of additional work, based on this guide: https://blog.c6h12o6.org/post/freebsd-electron-app/

**Comment by shiftkey** [comment]
I'm going to close this out as I don't have plans to support it. On top of the porting work for Electron there will also need to be support for the native dependencies to be able to use the app in a FreeBSD distribution:

 - Git binaries and support in [`dugite`](https://github.com/desktop/dugite) and [`dugite-native`](https://github.com/desktop/dugite-native) for FreeBSD
 - [`node-keytar`](https://github.com/atom/node-keytar) and [`fs-admin`](https://github.com/atom/fs-admin) native Node modules require support for FreeBSD (and a `libsecret`-compatible backend to store tokens on behalf of the app)

I also need to support CI and releases to this new platform, which is built around Actions, and don't have time to invest there either...
