### ISSUE TITLE
apt fails: Bandwidth or Storage Limit Exceeded

### ISSUE THREAD

**Issue by jochenwezel** [shiftkey/desktop#428]
### Operating System/Distribution

Which distribution of Linux are you using?
Ubuntu 20.04

### What happened?

`apt update` fails with following message: 
```
apt update
Hit:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04  InRelease
Hit:2 https://download.mono-project.com/repo/ubuntu stable-focal InRelease
Hit:3 https://download.mono-project.com/repo/ubuntu vs-bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:7 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Err:9 https://packagecloud.io/shiftkey/desktop/any any InRelease
  429  Too Many Requests [IP: 192.168.0.1 8000]
```
Note: Last IP 192.168.0.1 address is my local proxy server.

A manual test call with browser (without proxy) at https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease also shows error message.
```
Bandwidth or Storage Limit Exceeded
```

**Comment by Saladin1812** [comment]
@jochenwezel  The storage limit was reached not just for ubuntu but the whole package cloud repo, as I already have the repo installed and unable to update with same error on Fedora, Shiftkey will have to exceed the bandwidth or shift the repo to OBS or other alternatives, I recommend installing from github releases until then. Personally I am currently just disabling the repo (not removing it) and re enable once its recharged.

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.

**Comment by Soneji** [comment]
Is there any way to use GitHub packages or pages to host this, instead of a 3rd party? I am happy to help with this. Or maybe it would be cheaper to setup a VPS?

**Comment by ShadrackKimutai** [comment]
encountering the same problem... switching to manual install

**Comment by jochenwezel** [comment]
Maybe I haven't understood completely: is it a problem of 
- [ ] storage limit 
- [ ] or bandwith in meaning of "traffic volume" (TB/month)
- [ ] or bandwith in meaning of "bandwith" (MB/second)

**Comment by jochenwezel** [comment]
And what is the current limit line and how much would be required?

**Comment by jochenwezel** [comment]
Are there chances to use alternative solutions, like @soneji suggested exemplarily?

**Comment by Soneji** [comment]
> Maybe I haven't understood completely: is it a problem of 
> 
> - [ ] storage limit 
> 
> - [x] or bandwith in meaning of "traffic volume" (TB/month)
> 
> - [ ] or bandwith in meaning of "bandwith" (MB/second)

I think it is 160gb per month

**Comment by jochenwezel** [comment]
> I think it is 160gb per month

The current limit or the required traffic volume?

**Comment by Soneji** [comment]
The current limit, I believe the required traffic volume was estimated at ~100GB of bandwidth each month at some point in the past (see [here](https://github.com/sponsors/shiftkey))

I think if @shiftkey would like, we should find a solution with unlimited bandwidth, as this package is amazing and I can't expect it to ever stop growing in popularity

**Comment by shiftkey** [comment]
> Is there any way to use GitHub packages or pages to host this, instead of a 3rd party? 

Not really. This was my "must-have" list of requirements from elsewhere:

- hosted infrastructure
- accepts .deb directly
- handles GPG signing natively
- also supports RPM hosting

I started looking at OBS but it seems that requires build scripts to be hosted by them, based on this comment https://github.com/shiftkey/desktop/issues/363#issuecomment-745600391

> You have to upload your deb build script rules files etc... to them. Then their system will build the packages and publish.

Unless someone has done this with an Electron app that I can get inspiration from, this won't work with how I'm doing building and packaging currently...

I've thought about reaching out to PackageCloud to see if they'll sponsor this (the [pricing page](https://packagecloud.io/pricing) mentions open source projects) but I feel this is a murky area, it's based off a GitHub OSS project. And I do want to support them monetarily because it's been a huge timesaver for me.

**Comment by jochenwezel** [comment]
>I've thought about reaching out to PackageCloud to see if they'll sponsor this

that would be really cool, since your project IS an open-source project :-)

> And I do want to support them monetarily 

this I don't understand

> because it's been a huge timesaver for me.

this I do understand

But in summary, 
* your project is open-source 
* you could get the support from PackageCloud for free
  * so, you don't have to collect money a huge amount from the community to support/spend that money to PackageCloud 
  * so, you should use that free offer (if there is no disadvantage), don't you?

**Comment by jochenwezel** [comment]
> Not really. This was my "must-have" list of requirements from elsewhere:
> 
> * hosted infrastructure
> * accepts .deb directly
> * handles GPG signing natively
> * also supports RPM hosting

Well, I don't know what needs to be done if you could run your own root server. I use vcloud root servers with approx. 5 TB/month bandwidth for 8 EUR (approx. 10 USD) per month. So it seems, there is lot of saving potential in comparison to 160 USD/month (if this money is really required)

**Comment by Soneji** [comment]
> I've thought about reaching out to PackageCloud to see if they'll sponsor this (the [pricing page](https://packagecloud.io/pricing) mentions open source projects) but I feel this is a murky area, it's based off a GitHub OSS project. And I do want to support them monetarily because it's been a huge timesaver for me.

I think the best solution is to reach out to PackageCloud – a lot of hosting/build companies offer free options for open source. And it looks as easy as emailing support@packagecloud.io. You can just send a link to the repo and this issue. I think this project definitely deserves the free hosting.

**Comment by tmiland** [comment]
How about [Hosting your own PPA repository on GitHub](https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html) 🤔

**Comment by Soneji** [comment]
Looks cool but it’s a lot of steps, maybe if there was some way to automate it with GitHub actions

**Comment by tmiland** [comment]
I went ahead and added a [repo](https://github.com/tmiland/deb) on GitHub.

Wrote a script to run with a cron job to automatically download the new deb file and publish it to the repo whenever there is a new release. :smile: 

Feel free to use it, whoever might need it. :+1:

**Comment by Soneji** [comment]
Can this be integrated into this existing repo?

**Comment by shiftkey** [comment]
> Can this be integrated into this existing repo?

I have no plans for this, as I don't feel this is a suitable use of GitHub Pages. Check out this [Terms of Service section](https://docs.github.com/en/github/site-policy/github-additional-product-terms#4-pages) and [this page about usage limits](https://docs.github.com/en/github/working-with-github-pages/about-github-pages#usage-limits), which I'll summarize here (emphasis mine):

> GitHub Pages are subject to some specific bandwidth and usage limits, and **may not be appropriate for some high-bandwidth uses** or other prohibited uses. 
>
> ...
>
> - GitHub Pages source repositories have a recommended limit of 1GB. For more information, see "What is my disk quota?"
> - Published GitHub Pages sites may be no larger than 1 GB.

Each `deb` release is ~65MB currently, so there's a bit of runway to go before you reach this limit, but it feels like a stopgap option given I also need to support RPM and AppImage releases.

**Comment by tmiland** [comment]
I wasn't aware of that. 

However, it's also possible to set up the repo hosted on a VPS as well.

```bash
$ apt policy github-desktop
github-desktop:
  Installed: 2.6.3-linux1
  Candidate: 2.6.3-linux1
  Version table:
 *** 2.6.3-linux1 500
        500 https://deb.tmiland.com/debian ./ Packages
        100 /var/lib/dpkg/status
     2.6.2-linux1 500
        500 https://deb.tmiland.com/debian ./ Packages
```

**Comment by Soneji** [comment]
> > I've thought about reaching out to PackageCloud to see if they'll sponsor this (the [pricing page](https://packagecloud.io/pricing) mentions open source projects) but I feel this is a murky area, it's based off a GitHub OSS project. And I do want to support them monetarily because it's been a huge timesaver for me.
> 
> I think the best solution is to reach out to PackageCloud – a lot of hosting/build companies offer free options for open source. And it looks as easy as emailing [support@packagecloud.io](mailto:support@packagecloud.io). You can just send a link to the repo and this issue. I think this project definitely deserves the free hosting.

@shiftkey did you miss this?

**Comment by shiftkey** [comment]
@soneji no, just busy with other stuff at the moment

**Comment by shiftkey** [comment]
I have reached out to PackageCloud about their OSS offerings but haven't heard back.

Closing this out as it's a new billing month.

**Comment by jochenwezel** [comment]
@shiftkey  Don't you expect the same behaviour on next month? I'd assume in a few weeks, we've got the very same problem again and this issue will appear again. That's why I'd recommend to keep this issue opened and to follow up.

**Comment by shiftkey** [comment]
@jochenwezel I've had previous months where different users submit multiple issues, so I don't see the value in keeping it around if people aren't looking for previous issues.

#278 is the tracking issue for this trial anyway
