### ISSUE TITLE
check Git installed and prompt if not found

### ISSUE THREAD

**Issue by Madis0** [shiftkey/desktop#43]
## Description

I am unsure on how to use the Github Desktop internal Git in terminal with the folder scope.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Ubuntu 17.10

## Steps to Reproduce

1. Open GitHub Desktop with some repo
2. Click on Repository -> Open in GNOME Terminal
3. Type `git`

### Expected Behavior

I expected it to work with GitHub Desktop's internal git, like in Windows.

### Actual Behavior

The system asks me to install Git separately, therefore I would have to create a duplicate clone just to use terminal commands.

## Additional Information

I am not sure what is the app's launchable name, so I wasn't able to try that. It certainly wasn't `github` (from #32).

**Comment by j-f1** [comment]
We don’t make the Git we use in the app available from the CLI because we apply some optimizations to it to decrease GitHub Desktop’s size that hinder usability. For example, we remove translations of text to languages other than English, because those translations take up space and make it harder to parse error messages.

**Comment by Madis0** [comment]
So what would be the recommended procedure of executing direct git commands, without having to clone repositories twice?

**Comment by shiftkey** [comment]
@Madis0 as @j-f1 pointed out, the embedded version of Git is not intended for end-users to invoke directly. Please refer to your distribution's package manager for how to obtain Git.

I'm going to mark this as an enhancement for an external contributor to make this experience better for Linux users to explain this message better. 

I think all we need to do here is update `is-git-on-path.ts` to check that `git` is available on the user's PATH.

https://github.com/desktop/desktop/blob/e17d8a565c28760c781c18c652c95ebf0e196066/app/src/lib/is-git-on-path.ts#L9-L11

I think `where` should be usable here, similar to the checks we do for Windows.

https://github.com/desktop/desktop/blob/e17d8a565c28760c781c18c652c95ebf0e196066/app/src/lib/is-git-on-path.ts#L14-L32

**Comment by shiftkey** [comment]
> That wasn't the case for the old design version (I believe it installed full Git with the Desktop already).

The "Git Shell" experience was not ported over to Desktop Electron for multiple reasons. The discussion to read the back story on this is https://github.com/desktop/desktop/issues/340

**Comment by shiftkey** [comment]
This was released in [1.2.0](https://github.com/shiftkey/desktop/releases/tag/release-1.2.0).
