### ISSUE TITLE
Logging in returns 404 error.

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#432]
### Version & OS
GitHub Desktop version 2.4.1-linux1 from the Pop!_Shop on Pop!_OS.

### Steps to reproduce the behavior
1. Press Ctrl+Comma to open Settings
2. Click "GitHub.com" to sign in with GitHub.
3. Login with your correct credentials.
4. Observe the 404 error.

### Expected behavior
The app should have logged me in without any issues.

### Actual behavior
GitHub Desktop doesn't log me in and returns "The server responded with an error while attempting to authenticate (404)

### Screenshots
![image](https://user-images.githubusercontent.com/58496249/107810798-185d1080-6d22-11eb-84b2-8617fbb60baf.png)

### Logs
[2021-02-12.desktop.production.log](https://github.com/shiftkey/desktop/files/5973843/2021-02-12.desktop.production.log)

### Additional context
Fresh installation of Pop!_OS I installed two days ago.

**Comment by ghost** [comment]
No proxy, I should mention.

**Comment by ghost** [comment]
I just realized how old the Pop!_Shop version of GitHub desktop is (two minor versions behind). Installing the latest version allows me to login correctly.

**Comment by shiftkey** [comment]
There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).
