### ISSUE TITLE
v2.5.4 and later doesn't update the UI at committing

### ISSUE THREAD

**Issue by LuKks** [shiftkey/desktop#436]
### Describe the bug

Maybe the Electron upgrade makes committing "slow", the commit is done at normal time but the UI doesn't update until unfocusing the app and focus it again.
It doesn't even let you to push until the `Committing to Master` is finished.

This also happens at the current latest version.

### Version & OS

Version 2.5.4-linux1.
Xubuntu 20.04.2 LTS

### Steps to reproduce the behavior

1. Install 2.5.4-linux1 version
2. Commit a change into a existing repo
3. "Committing to Master" will indefinitely load until you unfocus and focus the app.

Unfocus and focus can be done like: click in the desktop computer and later click in GitHub Desktop client.

### Expected behavior

I expect no need to unfocus/focus the app to update the UI, in this case the commit loading message.

### Actual behavior

I think the "Committing to Master" hangs out forever until unfocus/focus, so this is obviously wrong.

### Screenshots

A short GIF showing the bug:
![Peek 2021-02-15 03-30](https://user-images.githubusercontent.com/12686176/107912941-3f902980-6f3e-11eb-85ee-f67130fcb8a3.gif)

A long GIF showing the bug again, so you know it's not a slow cpu or whatever:
![Peek 2021-02-15 03-33](https://user-images.githubusercontent.com/12686176/107913162-a6154780-6f3e-11eb-9483-9bce8f3343c5.gif)

### Logs

For example:
```
2021-02-15T06:13:29.138Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 380.078s)
2021-02-15T06:13:29.556Z - info: [ui] [Timing] Action 'create commit' for 'sp-node' took 380.515s
```

Another one:
```
2021-02-15T06:16:19.489Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 17.644s)
2021-02-15T06:16:19.948Z - info: [ui] [Timing] Action 'create commit' for 'sp-node' took 18.119s
```

The delay depends on when I unfocus/focus the app.

**Comment by LuKks** [comment]
I had to increase the FPS for recording to catch how fast is it at 2.5.3:

https://user-images.githubusercontent.com/12686176/107913877-0062d800-6f40-11eb-9f0d-2617f9c98bec.mp4

**Comment by shiftkey** [comment]
This is the same root cause as #329, please follow along with that issue
