### ISSUE TITLE
after vs code update, github desktop does not recognize the editor

### ISSUE THREAD

**Issue by lucaspioto** [shiftkey/desktop#443]
the system shows an update to vs code, but after updating, github desktop does not recognize the editor

I'm using Pop OS...

**Comment by shiftkey** [comment]
@lucaspioto where is VSCode installed on disk now? Maybe it's changed and we need to look in a new location...

**Comment by shiftkey** [comment]
https://github.com/shiftkey/desktop/blob/7ce6a31b661546f974022f0c19f2ca2778456a50/app/src/lib/editors/linux.ts#L23-L26

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of information

**Comment by lucaspioto** [comment]
Sorry for the delay, but what should I do?
How do I modify this file?
I didn't find it on my computer.

**Comment by shiftkey** [comment]
@lucaspioto this is my original question:

> where is VSCode installed on disk now?

That file shows where we look for VSCode on disk, and it may be that VSCode is now in a different location.

> I'm using Pop OS...

If you're installing from the Pop Store, please provide the version that you have installed? I'm not maintaining that version, so it's not clear to me how far behind that version is from the latest release.
