### ISSUE TITLE
VS Code JavaScript Debugger doesn't run when VS Code was opened using Ctrl + Shift + A

### ISSUE THREAD

**Issue by EnzoHB** [shiftkey/desktop#444]
### Describe the bug
**A clear and concise description of what the bug is:**

When you open the VS Code on ChromeOS through the shortcut Ctrl + Shift + A, you cannot run either the JavaScript Debugger and other extensions like [Node.js Exec.](https://marketplace.visualstudio.com/items?itemName=miramac.vscode-exec-node) 

### Version & OS

**Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using:**

- Version 2.6.3-linux1
- ChromeOS - Installed through [Brunch Framework](https://github.com/sebanc/brunch)
  - ChromeOS Recovery Image: [Rammus 87](https://cros-updates-serving.appspot.com/)
  - Brunch Framework : [Brunch R87](https://github.com/sebanc/brunch/releases/tag/r87-stable-20201227)
- VS Code and Node.js installed through [the official website](https://code.visualstudio.com/blogs/2020/12/03/chromebook-get-started)
- System Info : Versão 87.0.4280.152 (Versão oficial) 64 bits

### Steps to reproduce the behavior

1. Open GitHub Desktop on ChromeOS - 
2. Open VS Code through CTRL + SHIFT + A
3. Try to Debug - Node.js or Node.js ( Legacy )
4. Find out you can't

### Expected behavior

**A clear and concise description of what you expected to happen:**

Debug my Script and run JS through Node.js Exec

### Actual behavior

**A clear and concise description of what actually happened.**

When trying to Debug, I get this message:

> Can't find Node.js binary "Node": Path does not exist. make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch JSON.

When trying to run JavaScript through Node.js Exec, I get the behavior when I accidentally run into a infinite Loop.
 
### Screenshots

**Add screenshots to help explain your problem, if applicable:**

#### The Error Message when I try to Debug -
![The Error Message](https://user-images.githubusercontent.com/75489073/108396022-25cc3c00-71f5-11eb-9538-8c194f60656e.png)

#### Node.js Exec running Forever - 
![Node.js Exec Running forever](https://user-images.githubusercontent.com/75489073/108396059-2ebd0d80-71f5-11eb-8a3c-2d4fbfbe2009.png)

### Logs

**Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable:**

[2021-02-15.desktop.production.log](https://github.com/shiftkey/desktop/files/6004658/2021-02-15.desktop.production.log)
[2021-02-16.desktop.production.log](https://github.com/shiftkey/desktop/files/6004659/2021-02-16.desktop.production.log)
[2021-02-17.desktop.production.log](https://github.com/shiftkey/desktop/files/6004660/2021-02-17.desktop.production.log)
[2021-02-18.desktop.production.log](https://github.com/shiftkey/desktop/files/6004661/2021-02-18.desktop.production.log)

### Additional context
**Add any other context about the problem here:**

I installed GitHub desktop on ChromeOS through the Brunch Framework. I'm testing the system and that's why I set up an environment installing VS Code too. As soon as I first ran GitHub Desktop, I got that error saying it couldn't open the authentication page. So, I installed Chrome for Linux and everything worked well. After that, I opened VS Code with the shortcut from GitHub Desktop and I installed Node.js Exec Extension and started writing a simple `console.log('Hello, ChromeOS')` and when I tried to execute the script, I got what I get when running into an infinite loop.

Really, weird. I did what I do every time - Uninstall and Install the extension again and... The same result. So I re-booted the system and now It was working. Well, I really didn't notice what was going on and forgot about that. A day later, I tried to Debug a Script and this message appeared:

> Can't find Node.js binary "Node": Path does not exist. make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch JSON.

I did it and didn't work as well. Then, I went to the terminal and Node.js was running normally. What to do now? Stackoverflow obvious. I find a post that said It was just restarting the computer and everything would work fine and it did it! I noticed this pattern: "Every time I reboot my computer, the problem goes away".

So, I started to test some hypothesis. I noticed that every time I couldn't ran Node.js Exec, I couldn't run JavaScript Debugger as well. Since I would need to reboot my computer, I closed all open programs and open VS Code to test if it was some application-related problem. And for my surprise IT WAS, because Debugger and Node.js Exec ran perfectly. Since I closed only Chrome and GitHub desktop, I knew it was a Bug. 

So I test it - I opened GitHub and opened VS Code through the shortcut. Both, the Debugger and Node exec didn't work. Then, I close GitHub and nothing worked again. After that, I opened VS Code and every thing worked just fine - Then I opened GitHub Desktop and everything stilled working fine! Bingo!! 

---

**Comment by shiftkey** [comment]
@EnzoHB there's some context here about how Desktop's editor integration works and some limits that we're kind of stuck with, but here's the back story.

This is the function that handles launching the chosen editor from Desktop - it's fairly boring, aside from the `detached: true` parameter to ensure the editor remains open if Desktop is closed first:

https://github.com/shiftkey/desktop/blob/7ce6a31b661546f974022f0c19f2ca2778456a50/app/src/lib/editors/launch.ts#L11-L41

I have a theory here that your PATH environment variable is different when launching GitHub Desktop, versus what is set when you launch from the terminal. When you launch the editor from Desktop, the new editor process will inherit the environment variables of the GitHub Desktop process, so you could have a different `PATH` if you use the OS launcher, or you launch it from the terminal (using `/usr/bin/github-desktop`).

This is pretty easy to spot from the developer tools in GitHub Desktop by poking at `process.env.PATH`.

Here's my app being opened from the OS launcher in Ubuntu (with `PATH` starting with `~/.cargo/bin`):

![](https://user-images.githubusercontent.com/359239/108635439-c9b42280-7455-11eb-9b00-673552c3ec33.png)

Heere's my app being opened from my terminal (the paths for `nodenv` and `rbenv` are prepended to the path before `~/.cargo/bin`):

![](https://user-images.githubusercontent.com/359239/108635516-2283bb00-7456-11eb-8ba8-fd728768b894.png)

That's what I believe is happening here. Not really sure what the best course of action here is, but hopefully the workaround for launching Desktop from your shell here is enough to support your use case.

**Comment by EnzoHB** [comment]
Thanks for the response and it worked!

**Comment by shiftkey** [comment]
@EnzoHB cool. I'm going to close this out as resolved as I think it's the best we can do in this situation.
