### ISSUE TITLE
GitHub Desktop after change username

### ISSUE THREAD

**Issue by SkipperCobbSquad** [shiftkey/desktop#445]
### Describe the bug

Can`t login to GitHub Desktop after change my username.

### Version & OS

Can`t select "About GitHub Desktop"
Pop OS 20.04
2.4.1-linux1 (Linux 5.8.0-7642-generic)

### Steps to reproduce the behavior

1. Change username on GitHub
2. Reinstall GitHub Desktop
3. Try login via standard login and password or via browser
4. See error in console

### Expected behavior

Login to GitHub

### Actual behavior

Nothing happened. 

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2021-02-21.desktop.production.log](https://github.com/shiftkey/desktop/files/6017705/2021-02-21.desktop.production.log)

**Comment by shiftkey** [comment]
> Pop OS 20.04
> 2.4.1-linux1 (Linux 5.8.0-7642-generic)

Please upgrade a later version of GitHub Desktop.

There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).
