### ISSUE TITLE
password deprecation, how can we use access tokens

### ISSUE THREAD

**Issue by rohit-gh** [shiftkey/desktop#446]
### Basic Auth Deprecation notice

I get this mail from Github more frequently which basically tells us that basic auth using a password is going to deprecate.
![image](https://user-images.githubusercontent.com/8948535/108634664-9c409680-74a0-11eb-9409-4e4a50aa88c0.png)

### Proposed solution

Although, I know it is a community-based repository for desktop client and not the official repository. (I shouldn't be asking for too much)

Can there be a solution where users can put in their access tokens and that can be used to push/pull/etc from the repo codebase?

#### How will it benefit Desktop and its users?

We could simply keep using the community version as before without any interruption.

**Comment by shiftkey** [comment]
@rohit-gh we defer to the OS for storing credentials, so I have two suggestions:

 - switching to using the OAuth flow will make this error go away for GitHub Desktop (the version of Git used in GitHub Desktop is a more recent version than `2.19.2`, so I think this is a different scenario you're being warned about).
 - you can find the stored credentials on your machine and swap in a different token if you feel bold (look for a network password for `[username]@github.com`)

Beyond that, I don't feel that I have the bandwidth to support anything custom in the app.

For general command line usage you should be able to use a personal access token just fine - you might need to nuke your settings, based on how it's configured.

**Comment by rohit-gh** [comment]
@shiftkey thanks, this was helpful. :+1: 
I can either try with OAuth flow. 
I've used this for quite a long time without switching any versions. Will update things on my end.
I can try some tweaks on my own.
