### ISSUE TITLE
push-pull merge discard - waiting.

### ISSUE THREAD

**Issue by EliseiNicolae** [shiftkey/desktop#447]
### Describe the bug

if i make a push, I wait in vain for nothing to happen, and I have to refresh it on github (to change with another tab and back)

### Version & OS

2.6.3-linux1

### Steps to reproduce the behavior

if i make a push,I wait in vain for nothing to happen, and I have to refresh the github to go (to change with another tab and back)

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

![image](https://user-images.githubusercontent.com/43387542/108684412-8b713e80-74fb-11eb-8bba-3de8bbec1ba0.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
Please follow along with #332 as this is an existing issue related to the Discard Changes step
