### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by sabuz** [shiftkey/desktop#448]
### Describe the bug

I received this mail from GitHub team for using this app

> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

### Version & OS
OS Ubuntu 18.04
Version 2.6.3-linux1

**Comment by shiftkey** [comment]
There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported, which I believe is what's happening here. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

Password login was removed in `2.6.0` so if you sign out and in again this should use the browser flow which will make this go away...
