### ISSUE TITLE
GitHub Desktop Hangs in Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by surfd4wg** [shiftkey/desktop#449]
**Describe the bug**
After installing GitHub Desktop on Ubuntu 20.04.02 LTS, created a new repo File --> New Repository.
Copy files into the local directory.
Commit

GitHub Desktop hangs. It says "Committing to main"

and doesn't come out of it...

**Version & OS**
Ubuntu focal 20.04.2 LTS
GitHub Desktop 2.6.3-linux1

**Steps to reproduce the behavior**
After installing GitHub Desktop on Ubuntu 20.04.02 LTS, created a new repo File --> New Repository.
Copy files into the local directory.
Commit
Hangs
**Expected behavior**
I expect the GitHub Desktop UI to come back right after the commit button is pushed.

**Actual behavior**
Hangs with "Committing to main"

**Screenshots**
![image](https://user-images.githubusercontent.com/63609504/109025823-52aca300-767c-11eb-9488-033b108d43de.png)

**Comment by shiftkey** [comment]
Please follow along with the existing issue which has more context on this #329
