### ISSUE TITLE
GUI locks in "pending" state until another input is given

### ISSUE THREAD

**Issue by TheScottishninja** [shiftkey/desktop#452]
### Describe the bug

When pressing commit button, changing branch or creating new branch, the GUI locks in a "pending" state with the loading wheel spinning. Pressing another button, such as Fetch, will exit the "pending" state. The seems to be a purely visual bug as the action is always completed after leaving the "pending" state. 

### Version & OS

Version 2.5.4-linux1
Ubuntu 16.04

### Steps to reproduce the behavior

1. Press button "Commit to ..." with changes made in branch and message filled in.
2. Button and Changes window will grey out and spinning wheel appears indicating the program is executing the Commit

### Expected behavior

After a duration, the Commit should complete. The spinning wheel will disappear and greyed out menus will return to normal. The Changes menu should be empty since no new changes are present

### Actual behavior

The menu remains greyed out and the spinning wheel remains as long as no new input is given to the window. If a button is pressed on the app, then the expected behaviour occurs immediately. 

### Additional context

All my repos are private. I've experienced this behaviour on all of them. On my Windows machine, I've never had this issue on either private or public repos.

**Comment by shiftkey** [comment]
Please follow along with #329
