### ISSUE TITLE
PopOS Desktop client disallows login

### ISSUE THREAD

**Issue by Cmhorn** [shiftkey/desktop#457]
### Describe the bug
I am on PopOs 20.10 and have installed the GitHub Destop app from the Pop Shop. When launching the app, I am presented with a login page. When I login using Username or Email Address, then hit the button for login, there is a quick ghosting out of the button, then a return to the pre-button push state without login. 

When I sign on using browser, the browser sign-on works, but the app login screen is stuck in a halfway state, never successfully completing the login. 

### Version & OS
The About GitHub Desktop option is ghosted out in the menu, but the PopShop app page references version 3.16. 

PopOs version is 20.10

### Steps to reproduce the behavior

1. Launch GitHub Destop
2. Fill in username and password
3. Click login

### Expected behavior

Github Desktop launches in logged in state

### Actual behavior
Login button is ghosted out with a spinning arrow circle. 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs
[2021-03-11.desktop.production.log](https://github.com/shiftkey/desktop/files/6124238/2021-03-11.desktop.production.log)

**Comment by shiftkey** [comment]
Please upgrade a later version of GitHub Desktop.

There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).

**Comment by Cmhorn** [comment]
Thanks for the tip. 

Tried it in GitKraken -- worked. I am on PopOs, so I guess the Desktop is a bit flaky there.

**Comment by shiftkey** [comment]
> I am on PopOs, so I guess the Desktop is a bit flaky there.

I'm unfamiliar with where this package is hosted or what the latest version is, so I can't really help out with getting it updated currently 🤷🏻

**Comment by Cmhorn** [comment]
No worries. GitKraken works fine.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
