### ISSUE TITLE
Error when installing 2.6.6

### ISSUE THREAD

**Issue by GrahamSH-LLK** [shiftkey/desktop#458]
### Describe the bug

When I try to install, I get ```Error while installing package: cannot copy extracted data for './usr/lib/github-desktop/icudtl.dat' to '/usr/lib/github-desktop/icudtl.dat.dpkg-new'```
### Version & OS

I'm using debian
### Steps to reproduce the behavior

Try to install with .deb
### Actual behavior

It should work

**Comment by shiftkey** [comment]
@GrahamSH-LLK a few questions to better understand the situation:

 - which version of Debian are you using?
 - is this an upgrade or a new install? if it's an upgrade, which version were you upgrading from?
 - is there anything else in the log that might help me understand the issue?

**Comment by shiftkey** [comment]
I was able to install `2.6.6-linux1` fine through `dpkg` on Ubuntu:

```
$ sudo dpkg -i GitHubDesktop-linux-2.6.6-linux1.deb 
... 
(Reading database ... 212130 files and directories currently installed.)
Preparing to unpack .../GitHubDesktop-linux-2.6.6-linux1.deb ...
Unpacking github-desktop (2.6.6-linux1) over (2.6.5-linux1) ...
Setting up github-desktop (2.6.6-linux1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```

And it seems like this is the problematic file (at the same path):

```
$ dpkg -c GitHubDesktop-linux-2.6.6-linux1.deb | grep icudtl
-rw-r--r-- root/root  10527632 2021-03-11 12:19 ./usr/lib/github-desktop/icudtl.dat
```

**Comment by shiftkey** [comment]
Another thing to confirm is that the installer itself isn't corrupted:

```
$ shasum -a 256 GitHubDesktop-linux-2.6.6-linux1.deb 
978d175f1a0dda589703dc99c463879bfb9ef06c1bc9168b58d6f363cc481cc0  GitHubDesktop-linux-2.6.6-linux1.deb
```

This shows my version matches the checksum in [the release notes](https://github.com/shiftkey/desktop/releases/tag/release-2.6.6-linux1).

**Comment by GrahamSH-LLK** [comment]
I was installing through ChromeOS's built in feature, which failed repeatedly. When I tried apt, it worked.
