### ISSUE TITLE
Bug on push code

### ISSUE THREAD

**Issue by pioupia** [shiftkey/desktop#459]
### Describe the bug

When I push my code to github, i've this error :
**/tmp/.mount_GitHubOEE1lg/resources/app/git/libexec/git-core/git-remote-https: symbol lookup error: /tmp/.mount_GitHubOEE1lg/resources/app/git/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset**

### Version & OS

Last Version of Github Desktop. On Xubuntu 16.04 

### Steps to reproduce the behavior

1. Click on push code

### Screenshots
![Capture d’écran_2021-03-14_10-49-34](https://user-images.githubusercontent.com/49518790/111064208-fdadc100-84b2-11eb-867e-9921ebc0975a.png)

**Comment by shiftkey** [comment]
I've seen this happen in the past when the version of libcurl lacks support for an expected API.

In this case [`curl_global_sslset`](https://curl.se/libcurl/c/curl_global_sslset.html) was added in `7.56.0`. Do you know what version of `libcurl` you have installed currently, and whether there's an upgrade available?

**Comment by pioupia** [comment]
$ curl -V

curl 7.47.0 (x86_64-pc-linux-gnu) **libcurl/7.47.0** GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

So I tested:

> sudo apt install curl -y

but he tells me that the curl is installed in the latest version... Do you think that the version of my linux is not recent enough ?

**Comment by shiftkey** [comment]
> Do you think that the version of my linux is not recent enough ?

That release of curl is from [January 2016](https://curl.se/mail/lib-2016-01/0138.html). [`7.56.0`](https://curl.se/mail/lib-2017-10/0005.html) is from October 2017, so it's still been available for 3+ years.

[Xubuntu 16.04](https://xubuntu.org/release/16-04/) was marked as "end of life" in April 2019, and [18.04](https://xubuntu.org/release/18-04/) will EOL next month, so I don't plan to address this specific issue.

Please upgrade to a support version of the distro as you will likely be able to get version of curl which supports this functionality...

**Comment by pioupia** [comment]
After some terrible hassles to get my pc up and running after the bad update, the link to log in to github when I click on sign_in seems to be blocked by my browser I think..
