### ISSUE TITLE
Connect to GitHub Enterprise

### ISSUE THREAD

**Issue by wanjizheng** [shiftkey/desktop#46]
Please refer to https://github.com/desktop/desktop/issues/4625 for more details.

**Comment by shiftkey** [comment]
I'm going to close this out as unclear, but I'll add to the comments from the initial thread:

> It will work for me, but my colleagues want to use the Linux version as well and I won't be able to repeat this process to create their "own" version for all of them if you see what I mean.

If you've created your own OAuth Client ID and secret to embed in the Desktop install, you could package that up (see [the distribution dependencies]() to ensure you have this all setup) and then run `yarn run package` to generate the necessary installer.

But for the moment the installers on this fork should work with GitHub Enterprise (unless it's a really old installation, https://github.com/desktop/desktop/issues/1628 has some context and clues for what to look for).
