### ISSUE TITLE
Cannot get the GPG key from PackageCloud

### ISSUE THREAD

**Issue by omega9380** [shiftkey/desktop#461]
### Operating System/Distribution

Which distribution of Linux are you using? - Linux Mint 20.1

### Installer

Which version of the app? Unknown, cant get that far
Which installer type? APT

### What happened?

Error when trying to install the GPG key.  When you try to access https://packagecloud.io/shiftkey/desktop/gpgkey in a browser, you get the following error:

Bandwidth or Storage Limit Exceeded

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
