### ISSUE TITLE
Too many IP requests

### ISSUE THREAD

**Issue by Catley94** [shiftkey/desktop#462]
### Operating System/Distribution

Which distribution of Linux are you using?
Ubuntu 20.10
### Installer

Which version of the app? 2.6.2
Which installer type? .deb

### What happened?
When I run `sudo apt install github-desktop`, I get back:
`W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 54.183.38.243 443]`

Provide as much detail as possible. Error messages or output are extremely useful.
`Err:7 https://packagecloud.io/shiftkey/desktop/any any InRelease
  429  Too Many Requests [IP: 54.183.38.243 443]
`

Looks like the server is overloaded, is there another that we can use?

**Comment by ghost** [comment]
Having the same issue on Linux Mint 20.1 Cinnamon

**Comment by AlejandroAkbal** [comment]
Same issue.

**Comment by HotNoob** [comment]
ditto. same.

**Comment by shiftkey** [comment]
> Looks like the server is overloaded, is there another that we can use?

#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
