### ISSUE TITLE
[Question] releases to packagecloud.io/app/shiftkey

### ISSUE THREAD

**Issue by saimusdev** [shiftkey/desktop#463]
# What's the cadency of the releases of this repo?

The desktop/desktop repo has releases (tags), but this one is not releasing everything from there (all tags), right? why is that? 
Furthermore, when is the debian distro [packagecloud.io/app/shiftkey](https://packagecloud.io/app/shiftkey) updated? I've seen there's missing packages there (the latest ones)...

It would be great if all of this info is posted in the `README.md` of the repo.

**Comment by shiftkey** [comment]
> The desktop/desktop repo has releases (tags), but this one is not releasing everything from there (all tags), right? why is that?

Not sure I understand this question - we use tags in this repository too and the corresponding releases are listed here: https://github.com/shiftkey/desktop/releases

> Furthermore, when is the debian distro packagecloud.io/app/shiftkey updated? I've seen there's missing packages there (the latest ones)...

I try and update it with each release but it's been so popular that I often hit the bandwidth limits and it then becomes unavailable.

> It would be great if all of this info is posted in the `README.md` of the repo.

For now I consider PackageCloud a trial - #278 is the ongoing discussion about that - and the README has this section which mentions the releases available in this repository, which is still the best way to get the latest bits: https://github.com/shiftkey/desktop#what-is-this-repository-for
