### ISSUE TITLE
How to completely uninstall GitHub Desktop

### ISSUE THREAD

**Issue by mryujitanaka** [shiftkey/desktop#464]
Hi, there!

I installed GitHub Desktop - The Linux Fork through PackageCloud for Debian/Ubuntu distributions. However, I was unsuccessful with the installation.

The error:

W: GPG error: https://packagecloud.io/shiftkey/desktop/any any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
E: The repository 'https://packagecloud.io/shiftkey/desktop/any any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

The steps I followed for the installation were [these](https://github.com/shiftkey/desktop#debianubuntu-distributions).

I like to install through PackageCloud because I can update the program with the command "update" and "upgrade" in the Terminal.

But unfortunately, from 6 months or more to today, I was not so lucky. I even needed to install and update GitHub Desktop by accessing the developer repository.

The OSs I used to install the program were Ubuntu and Pop_OS, all in version 20.04 LTS.

So, I would like you to teach me how to completely remove the repository and everything it installed on my computer.

Thank you in advance.

**Comment by mangledbottles** [comment]
Run `which github-desktop -a` and remove all the files
Remove each file with `sudo rm x ` (x is the directory)

**Comment by mryujitanaka** [comment]
Thanks!
