### ISSUE TITLE
Why PackageCloud and not Launchpad?

### ISSUE THREAD

**Issue by mryujitanaka** [shiftkey/desktop#465]
Hi, there!

I would like to know the reason why the GitHub Desktop - The Linux Fork project uses the PackageCloud and not the Launchpad.

I ask this because PackageCloud is a paid service and I always have problems updating the program via Terminal. While there is a free and OpenSource alternative like the Launchpad.

Thank you in advance.

**Comment by shiftkey** [comment]
From my investigation work in #105 it seems that Launchpad required a source package to be uploaded, which didn't match with what I've been building for packages.

I also summarized in a few places what PackageCloud gives me that Launchpad does not:

 - hosted infrastructure
 - accepts .deb directly
 - handles GPG signing natively
 - also supports RPM hosting

For now, please follow along with #278 which is the discussion about PackageCloud
