### ISSUE TITLE
Erro 404 in to Sign in

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#466]
By clicking on file -> Option

in Accounts when trying to log in to Sign in is giving a 404 error.

I'm using Fedora 32.

**Comment by shiftkey** [comment]
@bigallinux which version of the app are you using?

**Comment by ianwijma** [comment]
POP_os user here o/

I had similar issues with the version I downloaded from the POP!_shop, which was version `2.4.1-linux1`.
![image](https://user-images.githubusercontent.com/17692119/113371044-0bb77900-93b1-11eb-8366-d13b9b9e1d13.png)

After downloading and installing the latest .dep file from this repo, I was able to login :+1:

**Comment by shiftkey** [comment]
There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).
