### ISSUE TITLE
Installation instructions in the README do not work for Ubuntu 20.04

### ISSUE THREAD

**Issue by potthast** [shiftkey/desktop#469]
### Describe the bug

Following the commands in the installation instructions in the README fails.

### Version & OS

Ubuntu 20.04

### Steps to reproduce the behavior

Create the file `/etc/apt/sources.list.d/packagecloud-shift` with the appropriate contents as per the instructions.

2. 
3. Compared to other files in the directory, the extension `.list` is missing.

### Expected behavior

Executing `sudo apt-get update` does not yield an error but enables the installation of github-desktop.

### Actual behavior

Executing `sudo apt-get update` yields the error message `N: Ignoring file 'packagecloud-shift' in directory '/etc/apt/sources.list.d/' as it has no filename extension`. The package `github-desktop` cannot be installed.

### Additional context

Adding the extension `.list` to obtain `/etc/apt/sources.list.d/packagecloud-shift.list` fixes the error.
I did not directly send a pull request with an update, since I do not know whether this applies only to Ubuntu 20.04.

**Comment by shiftkey** [comment]
Not sure I understand the issue, as the command in the docs is different to what's specified in the repro steps:

```
$ sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
```

Typo aside (`shiftky -> shiftkey`), the extension is included here.

**Comment by potthast** [comment]
Hm, I stand corrected: I quickly copied command for command from the web page and must have simply failed to copy the `.list` part. My apologies for not double-checking properly. Feel free to close.
