### ISSUE TITLE
blank on return from suspend system

### ISSUE THREAD

**Issue by k-co** [shiftkey/desktop#473]
### Describe the bug

When i put my system to suspend with the GitHub Desktop window open, after i return to work the window shows menu bar ok but the content is blank (all black). Sometimes some chunks of the early view. Then i have to close and open again.

### Version & OS

2.6.6-linux1 

Linux k2 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Linux Mint 20-64 Mate 1.24.0
Compiz WM

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. System suspend
3. System return

### Expected behavior

All other windows still work only the GitHub Desktop broke.

### Actual behavior

App window black on resume from system suspend

### Screenshots

![image](https://user-images.githubusercontent.com/53130040/113516224-6edf1200-954f-11eb-9e29-5fc4d09b31c4.png)

**Comment by nerve-hawthorne** [comment]
Looks like a GPU-side issue to me.
What is your GPU model and driver?

Can you reproduse this behavior with chromium or any other electron app like slack?

**Comment by shiftkey** [comment]
I'm not too familiar with Compiz these days so I'm not sure where to start troubleshooting this. Aside from gathering more details about your setup to see if we can identify some clues, I'd recommend trying to disable hardware acceleration by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` environment variable and launching the app from a shell, to see if that changes the behaviour at all.

**Comment by K0-RR** [comment]
>Can you reproduse this behavior

I have the same issue with Caprine so it's an Electron thing. I don't use compiz.

**Comment by nerve-hawthorne** [comment]
@RDKRACZ What is your hardware config?
I still think this is a framebuffer issue like [I had with my Ryzen APU](https://askubuntu.com/questions/1208271/artifacts-with-amd-ryzen-5-3400g-with-radeon-vega-graphics-%C3%97-8).

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of information to dig into further.

Please open a fresh issue if you're still interesting in digging into this.
