### ISSUE TITLE
GitHub Desktop Hangs in Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by surfd4wg** [shiftkey/desktop#475]
**Describe the bug**
After installing GitHub Desktop on Ubuntu 20.04.02 LTS, created a new repo File --> New Repository.
Copy files into the local directory.
Commit

GitHub Desktop hangs. It says "Committing to main"

and doesn't come out of it...

**Version & OS**
Ubuntu focal 20.04.2 LTS
GitHub Desktop 2.6.3-linux1

**Steps to reproduce the behavior**
After installing GitHub Desktop on Ubuntu 20.04.02 LTS, created a new repo File --> New Repository.
Copy files into the local directory.
Commit
Hangs

**Expected behavior**
I expect the GitHub Desktop UI to come back right after the commit button is pushed.

**Actual behavior**
Hangs with "Committing to main"

**Screenshots**
image
![108907100-e92a8700-75de-11eb-97ae-7966652e8381](https://user-images.githubusercontent.com/63609504/113892685-7d157400-9783-11eb-8a31-1e293af9a179.png)

**Comment by shiftkey** [comment]
Already tracking this in #329, please follow along with that issue
