### ISSUE TITLE
commit takes minutes not seconds

### ISSUE THREAD

**Issue by ng0177** [shiftkey/desktop#476]
`Version 2.7.1-linux1` takes minutes not seconds for a commit even if a single character in respository consisting of just one file has changed. The command line only takes a fraction of a second.

**Comment by francescoinfante** [comment]
Very likely, duplicate of https://github.com/shiftkey/desktop/issues/329

**Comment by shiftkey** [comment]
Yep, this is the same thing as #329 there's some extra context in there about what I suspect is happening
