### ISSUE TITLE
Unable to update - errors from packagecloud

### ISSUE THREAD

**Issue by rogercreagh** [shiftkey/desktop#478]
When running `sudo apt update`I get this 
`Err:15 https://packagecloud.io/shiftkey/desktop/any any InRelease       
  429  Too Many Requests [IP: 54.183.38.243 443]`

This has always happened since I first installed 2.6.2 on Ubuntu 20.04.
Whilst 2.6.2 works fine (aside from the annoying quirk with commits sometimes appearing to never finish unless you go away and do something else) it is getting to the point that it would be nice to be able to update to the latest (2.7.2). 
It is also annoying because it prevents the Ubuntu updater running correctly unless you disable the shiftkey repository from updates.

Does anyone else have this problem, is there a fix (alternative ppa location?) as it seems packagecloud is broken?

**Comment by kzeitz** [comment]
Yes! Exactly the same error here.

You can't download the .deb file directly either, as it claims the bandwidth is exceeded.

**Comment by viniciusvalmeida** [comment]
Here too =(

**Comment by asyrewicze** [comment]
Same issue here as well.....

**Comment by GreatDefector** [comment]
Same, can't add the repo 

```

 sudo rpm --import https://packagecloud.io/shiftkey/desktop/gpgkey
curl: (22) The requested URL returned error: 429 
error: https://packagecloud.io/shiftkey/desktop/gpgkey: import read failed(2).

```

**Comment by xerohackcom** [comment]
Their bandwidth limit is reached. Shiftkey should update their packageio account fast! I can't continue my GitHub work..

**Comment by xerohackcom** [comment]
As for other projects using packagecloud.io, they continuesly keep facing the same issue. For now it's better to reinstall this fork via: https://github.com/shiftkey/desktop/releases 

You can easily get back all your repos read by the app on login :) Hope this helps. You will not be able to update it via 'apt update' and have to reinstall using the /releases page.

**Comment by csylvain** [comment]
"bandwidth or storage limit exceeded" has been going on for many weeks now. cannot update to 2.7.1 as a result. still at 2.6.2.

**Comment by lengockyquang** [comment]
Same issue with fedora
Errors during downloading metadata for repository 'shiftkey':
Status code: 429 for https://packagecloud.io/shiftkey/desktop/el/7/x86_64/repodata/repomd.xml (IP: 54.183.216.24)
Error: Failed to download metadata for repo 'shiftkey': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by xerohackcom** [comment]
For anyone facing similar packageio issues. Follow these steps for Debian/Ubuntu/PopOS etc., distros based on Debian and Ubuntu..:

1. Goto > [Releases Page](https://github.com/shiftkey/desktop/releases) and download the .deb package.
2. On your system, open terminal and install 'gdebi' via apt > _sudo apt install gdebi_
3. Now goto the downloaded .deb package folder and open terminal
4. Type: gdebi file_name.deb

Done :)

**Comment by csylvain** [comment]
"dpkg -i" also does a fine job after having downloaded the package from the
Releases Page.

**Comment by shiftkey** [comment]
This is not a new issue - see #310 for one of the earliest discussions:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.

**Comment by csylvain** [comment]
did not at all know this was a sponsorship issue. only could see the update
was not happening when i put 'apt' on the job.

hope making the rest of the story known on why this is happening brings
more sponsors.

perhaps add a mention in the desktop/Readme.md ? or is there a way for the
feedback ( x% of $150 ) to appear on the project page?
frankly, the existing "you can sponsor" message only says one *can* but
nothing about how well sponsored the project is ..

crowdsupply and groupgets and indiegogo all manage to make the financial
status of a project more evident.
