### ISSUE TITLE
能出个中文版本的吗,谢谢

### ISSUE THREAD

**Issue by xianrenqh** [shiftkey/desktop#479]
能出个中文版本的吗,谢谢

**Comment by K0-RR** [comment]
Much cursed

**Comment by shiftkey** [comment]
This needs to be requested to the main project - https://github.com/desktop/desktop - as I do not have the bandwidth to add support for this in the app.

Some context about this from 2019 - https://github.com/desktop/desktop/issues/8289#issuecomment-532742883
