### ISSUE TITLE
Installed Github Desktop and it won't log in

### ISSUE THREAD

**Issue by echeadle** [shiftkey/desktop#480]
### Describe the bug
Installed Github Desktop on Pop_OS and I cannot log in to github.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Pop!_OS 20.04 LTS
### Steps to reproduce the behavior
Install Github desktop from the Pop_OS POP_Shop.  
Try to login to github through the application
### Expected behavior

Enter name and password and login

### Actual behavior

Enter Name and password and nothing happens
![Screenshot from 2021-04-15 18-24-43](https://user-images.githubusercontent.com/578766/114954546-13970480-9e18-11eb-8384-15914a531a2d.png)

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
Please upgrade a later version of GitHub Desktop.

There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).

**Comment by echeadle** [comment]
Thanks for the information. I will close the ticket. This makes sense.
