### ISSUE TITLE
The graphical Github client for linux won't let me log in. on linux  POP OS 20.04

### ISSUE THREAD

**Issue by angel20125** [shiftkey/desktop#483]
### Describe the bug

The graphical Github client for linux won't let me log in.

Context of the problem.

1. Install github version found in pop_shop store (I use pop os as operating system). Install the .deb version, found in the store.

I tried to log in with the Morzilla firefox browser and this gave an error. Morzilla firefox said the following:

An error occurred during a connection to github.com.

    You might need to install other software to open this address.

2. Try to log in with the Google Chrome browser and in this case Google Chrome if it recognizes the authentication link that the application sends to the Google Chrome browser, once inside the Google Chrome browser I enter my credentials and then a pop-up window appears telling me that if i want to open the desktop app i give it ok but git hub does nothing.

3. I entered my credentials, username and email but also did not log in by this means

Excuse me, my English, I'm using google translator 

### Version & OS
OS: Pop!_OS 20.04 LTS x86_64 
Kernel: 5.11.0-7612-generic 
Uptime: 1 hour, 23 mins 
Packages: 1828 (dpkg), 8 (flatpak), 25 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1080, 1360x768 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-3770 (8) @ 3.900GHz 
GPU: NVIDIA GeForce GT 730 
Memory: 2714MiB / 7921MiB 

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Installation, Steps to reproduce the installation behavior

Steps for github installation
1. Go to 'Pop Store', and search for 'Github'
2. Click on 'Github'
3. Select the .deb version
4. Click install

### Steps to reproduce the behavior of, logging in with the Morzilla Firefox Explorer
1. Go to 'Menu on Gnome' and search 'Github',
2. Click on 'Github' to open it,
3. Select 'Sign in to GitHub.com'
4. The Morzilla Firefox browser opens automatically,
5. The explorer Morzilla in a sale opens and tells me the following:
An error occurred during a connection to github.com.

    You may need to install other software to open this address.
6. I close the Morzilla Firefox Explorer and GitHub

### Steps to reproduce the behavior of, login with Google Explorer
1. Go to 'Menu on Gnome' and search 'Github',
2. Click on 'Github' to open it,
3. Select 'Sign in to GitHub.com'
4. The Google Chrome browser opens automatically,
5. The Google explorer in a sale opens and asks me for my credentials.
6. I enter my credentials, password and username, then I accept.
7. GitHub won't login, does nothing
8. I close Github and Google Search

### Steps to reproduce the behavior of, login without internet browsers
1. Go to 'Menu on Gnome' and search 'Github',
2. Click on 'Github' to open it,
3. Select 'Sign in to GitHub.com'
4. I enter my credentials, password and username, then I accept.
5. GitHub won't login, does nothing 

### Actual behavior
no working

### Screenshots

logging in with the Morzilla Firefox Explorer

![Screenshot from 2021-04-19 16-23-14](https://user-images.githubusercontent.com/12899398/115298529-91fee980-a12b-11eb-8263-1f29ab330179.png)

login with Google Explorer
![Screenshot from 2021-04-19 16-25-03](https://user-images.githubusercontent.com/12899398/115298857-05086000-a12c-11eb-91cb-06e6cf4ec68b.png)
![Screenshot from 2021-04-19 16-25-30](https://user-images.githubusercontent.com/12899398/115298875-0b96d780-a12c-11eb-8e6e-9b03962551f8.png)
![Screenshot from 2021-04-19 16-25-36](https://user-images.githubusercontent.com/12899398/115298889-0fc2f500-a12c-11eb-9bfc-8f5ae8dac5ef.png)

### Logs

[2021-04-19.desktop.production.log](https://github.com/shiftkey/desktop/files/6338838/2021-04-19.desktop.production.log)

### Additional context

my linux installation is clean and new

**Comment by shiftkey** [comment]
> 1. Go to 'Pop Store', and search for 'Github'

Please upgrade a later version of GitHub Desktop.

There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).

**Comment by angel20125** [comment]
One question, what is the closest repository to the official one to install the github desktop for linux?

**Comment by shiftkey** [comment]
@angel20125 since I wrote this I found a repository that seems to be the source and submitted a PR which may resolve this for you https://github.com/pop-os/repo-curated-free/pull/3#pullrequestreview-644775880

**Comment by angel20125** [comment]
thank you for your help 😁😁
