### ISSUE TITLE
don't log in

### ISSUE THREAD

**Issue by MatheusLima20** [shiftkey/desktop#485]
### Describe the bug

I install github on the ubuntu operating system, but when I try to log in through the browser, git descktop crashes and doesn't do it.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@MatheusLima20 please fill out the template, including as much detail as possible about your setup

**Comment by MatheusLima20** [comment]
Hardware: 4G ram, HDD 1T, Intel CORE i3-10TH and UBUNTU 20.10

**Comment by RealDoigt** [comment]
I have a similar issue on PCLinuxOS. When I try to login firefox gives me a "The address wasn’t understood" error.

**Comment by shiftkey** [comment]
> Hardware: 4G ram, HDD 1T, Intel CORE i3-10TH and UBUNTU 20.10

@MatheusLima20 this isn't what I was asking for. Please read over the template as without more information I'm not sure what the actual issue is, or how to reproduce it.

@RealDoigt please open a new issue and fill out the template, as I suspect your case is different to this issue

**Comment by Firestar-Reimu** [comment]
Like this:

![Screenshot_20210508_130545](https://user-images.githubusercontent.com/65082432/117527387-276afc00-afbb-11eb-9afa-3b3691d30c01.png)

**Comment by Mrlinkwii** [comment]
i think its related to #416  and probably is  that issue it seems a common thing ,

**Comment by shiftkey** [comment]
@1900011604 please open a new issue and fill out the template

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of context
