### ISSUE TITLE
error : The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### ISSUE THREAD

**Issue by Irfanahmedkhan** [shiftkey/desktop#487]
### Describe the bug

1-   i am facing error while i am clicking on "fetch origen"
2-    and i can not clone the repo from github desktop .. asking username and password .. again and again ... 

3-    i can not merge the branches .... 

### Version & OS

Version 2.6.3-linux1   ,  Ubunto 20.04

### Expected behavior

before i was using Ubunto 18. and same steps was working fine for fetching and for merging 

### Actual behavior

error : The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### Screenshots

attached 

### Logs
[2021-04-29.desktop.production.log](https://github.com/shiftkey/desktop/files/6399155/2021-04-29.desktop.production.log)
![Screenshot from 2021-04-29 16-54-36](https://user-images.githubusercontent.com/64011793/116563135-6b4f6880-a90c-11eb-909a-f091fc1af660.png)

attached 

### Additional context

i have full access for this repo. i cann merg branches from website, i can pull data from vscode terminal,, I was able to do all this work from Github desktop when I was usign ubunto 16 and 18 ..

**Comment by shiftkey** [comment]
Please read #281 as I believe this falls under this category:

> - I cannot push commits to an organization repository, and instead see a generic authentication error

There's some extra context in that issue about why this is happening, and it's a complicated issue due to several factors.

**Comment by Irfanahmedkhan** [comment]
i checked the previous issues .. but I didn't found the proper solution. ..
