### ISSUE TITLE
Need add to favorites option for ubuntu taskbar

### ISSUE THREAD

**Issue by kwcooper** [shiftkey/desktop#49]
**Is your feature request related to a problem? Please describe.**
Right click on icon in taskbar, and select add to favorites to keep the icon there

**Comment by shiftkey** [comment]
This should be supported by the OS itself using `Lock to Launcher`, right?

<img width="244" src="https://user-images.githubusercontent.com/359239/41200337-f2465408-6ce1-11e8-8b02-99d8498d75e3.png">

**Comment by shiftkey** [comment]
I'm going to close this out as I think this should be handled by the window manager.
