### ISSUE TITLE
Failed to fetch -- 429  Too Many Requests [IP: 2600:1f1c:2e5:6901:48c1:8c0c:948d:3ce7 443]

### ISSUE THREAD

**Issue by atorresbr** [shiftkey/desktop#490]
### Describe the bug

Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:48c1:8c0c:948d:3ce7 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

the update via the terminal ((ubuntu 20.10)) fails to update the "Desktop" through the update command, generating this error. 

### Version & OS

Ubuntu 20.10  /  OS type -- 64-bit / GNome version - 3.38.3 /

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Desktop About -- Version 2.8.0-linux1

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by atorresbr** [comment]
i saw the real reason for the error now   -- 

![Screenshot from 2021-05-01 16-18-01](https://user-images.githubusercontent.com/13744483/116792758-13923800-aa99-11eb-9c89-94501b464356.png)

**Comment by iamdual** [comment]
It's an internal problem. Seems packagecloud.io plan has exceeded.

**Comment by shiftkey** [comment]
Yep, it's another another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
It's costing me USD $150 per month to do this hosting and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.

**Comment by atorresbr** [comment]
> Yep, it's another another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> It's costing me USD $150 per month to do this hosting and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further. The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available. 

<3 Thank you so much Bro -- i will support the project 

![bender](https://user-images.githubusercontent.com/13744483/116825110-2aea2780-ab64-11eb-915e-8cc8fa764604.gif)

**Comment by MikMuellerDev** [comment]
Okay just submitted an issue for that...
So anyway thanks for hosting it anyway, i really enjoy desktop so i can't complain so far.

Have you considered paying around 5 $ a month for a server (linode or other) there you'll get unlimited bandwith for the most part.

I don't know about repository hosting but i seems like you can have a look at it.

**Comment by shiftkey** [comment]
> Have you considered paying around 5 $ a month for a server (linode or other) there you'll get unlimited bandwith for the most part.
> 
> I don't know about repository hosting but i seems like you can have a look at it.

It's been an ongoing discussion but https://github.com/shiftkey/desktop/issues/278#issuecomment-694877417 and subsequent comments are the alternatives I've investigated and so far I haven't found a substitute that checks all of the boxes.
