### ISSUE TITLE
`process.env.PATH` not matching PATH in shell

### ISSUE THREAD

**Issue by leettaylor** [shiftkey/desktop#491]
### Describe the bug

The `process.env.PATH` value doesn't match up with what's available in my shell.

GitHub PATH:
```
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
```

Shell PATH:
```
/home/lee/.nvm/versions/node/v15.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Because it's not seeing the NVM value it's resulting in my git hooks failing as they rely on `npm` which cannot be found.

### Version & OS

Version 2.8.0-linux1
Ubuntu 20.04.2 LTS

### Steps to reproduce the behavior

1. [View the `PATH` in GitHub Desktop](https://github.com/desktop/desktop/issues/1796#issuecomment-400659724)
1. Open a terminal and type `echo $PATH`
1. Compare the outputs

### Expected behavior

Path should match the Path available in the shell.

### Actual behavior

Missing the NVM value from the PATH inside of GitHub Desktop.

### Logs

```
2021-05-05T15:26:48.456Z - info: [ui] [AppStore] loading 1 repositories from store
2021-05-05T15:26:48.456Z - info: [ui] [AppStore] found account: leettaylor (Lee Taylor)
2021-05-05T15:26:48.484Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-05T15:26:48.804Z - info: [ui] launching: 2.8.0-linux1 (Linux 5.4.0-72-generic)
2021-05-05T15:26:48.804Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
```

**Comment by shiftkey** [comment]
@leettaylor thanks for the report. I wrote up some notes on this based on an earlier question about this: https://github.com/shiftkey/desktop/issues/444#issuecomment-782908783

The workaround I suggested there was to launch `github-desktop` from your shell, which will inherit your desired `PATH` instead of the `PATH` from your OS launcher...

**Comment by leettaylor** [comment]
Thanks @shiftkey. That workaround does indeed work and the `PATH` is correct when launching it via the shell. 

This seems to be an issue in SmartGit and [Sourcetree](https://jira.atlassian.com/browse/SRCTREE-7184) as well. 

On a positive note it seems that when checking the `process.env.PATH` in my VS Code developer tools it's correctly showing the same `PATH` as my shell. I wonder how they managed to get that to work.

**Comment by shiftkey** [comment]
>  I wonder how they managed to get that to work.

I'm not sure, and I'd be curious if they have documented this somewhere. I couldn't spot anything obvious after skimming the repository for mentions of `PATH` in shell scripts, but perhaps there's tricks elsewhere they have.

Closing this out for now as there's a known workaround, but if someone has tips for getting these consisted I'd love to hear more.
