### ISSUE TITLE
No editors found under "Integration"

### ISSUE THREAD

**Issue by faelana** [shiftkey/desktop#495]
### Describe the bug

When going under "Integration" in the preferences github desktop doesnt detect any of my editors and displays the notice "No editors found. Install Visual Studio Code?". I have installed at the moment Vscodium, neovim and the gnome text editor.

### Version & OS

Version 2.8.0-linux1
Fedora Linux 34
Gnome 40

### Steps to reproduce the behavior

1. Go to File
2. Click on Options
3. Click on Integrations

### Expected behavior

The list to select my editor or an option to manualy do so
### Actual behavior

Alredy described 
### Screenshots

Add screenshots to help explain your problem, if applicable.

![Screenshot from 2021-05-06 22-48-15](https://user-images.githubusercontent.com/46012160/117369722-38cdde80-aebd-11eb-96d4-d6b7be505512.png)

### Logs

Log not usefull
### Additional context

If this is a mainline problem in can submit the bug report

**Comment by shiftkey** [comment]
@methane4 thanks for the report!

> I have installed at the moment Vscodium, neovim and the gnome text editor.

You can see the list of supported editors here:

https://github.com/shiftkey/desktop/blob/e2e04839e4151b10a62cfa1beee573deedd12be0/app/src/lib/editors/linux.ts#L18-L58

Of your list we only look for VScodium, but perhaps the path we're using isn't correct (or it can be installed in different locations)?

**Comment by faelana** [comment]
Oh i just reminded myself that i installed vscodium through flatpak, i have this path /var/lib/flatpak/app/com.vscodium.codium and i also found this /var/lib/flatpak/exports/share/applications with symlinks inside `lrwxrwxrwx. 1 root root  101 mai  6 16:06 com.vscodium.codium.desktop -> ../../../app/com.vscodium.codium/current/active/export/share/applications/com.vscodium.codium.desktop
`
those are probably not the best paths for you but maybe it will be some help, i saw you have paths for snap too so i think supporting flatpak too will be ok

So, for anybody else that reads this theres need for flatpak paths to check for app installation

**Comment by faelana** [comment]
And also, thank you for maintaining linux builds for github desktop :)

**Comment by Mrlinkwii** [comment]
@methane4 :wave:  what are the location for neovim ?

**Comment by faelana** [comment]
@Mrlinkwii i assume its /usr/bin
