### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by RodrigoTAbreu** [shiftkey/desktop#497]
404 error when trying to sign in using the option: Sing in to GitHub.com

Debian Linux operating system:
linux version 4.19.0-16-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.181-1 (2021-03-19)

thaks

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@RodrigoTAbreu I have several questions that would help to understand the situation better:

 - Which version of the app?
 - Which type of installer?
 - Which browser?
 - GitHub or GitHub Enterprise?

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of information
