### ISSUE TITLE
Does not show the GUI on Ubuntu Trusty

### ISSUE THREAD

**Issue by oktonion** [shiftkey/desktop#50]
## Description
Installed from last version of ".dep" packages on Ubuntu 14.04 LTS and GUI is not shown at all when application launched. If I kill the process of desktop a then try to launch with "desktop" command from terminal then I get following output:

> xdg-settings: unexpected/missing argument
> Try 'xdg-settings --help' for more information.
> xdg-settings: unexpected/missing argument
> Try 'xdg-settings --help' for more information.

If I try to launch dektop again it shows empty GUI window.

## Version

* GitHub Desktop:
GitHubDesktop v.1.2.3, v.1.2.0
* Operating system:
Ubuntu 14.04.05 LTS

## Steps to Reproduce
1. Launch desktop
2. No GUI
3. Launch desktop again
4. Window of desktop is shown but it's blank.

### Expected Behavior
GUI is shown correctly

### Actual Behavior
GUI is not shown or is empty window

## Additional Information
I used one of the first versions like 1.0.something and it worked like charm.

### Logs
IDK where are logs for Ubuntu

**Comment by shiftkey** [comment]
@oktonion thanks for the report!

> GUI is not shown or is empty window

If you're seeing a white window but the main menu is still rendered the **View** | **Toggle Developer Tools** might be accessible - the **Console** tab might have some clues about the underlying error.

<img width="537" src="https://user-images.githubusercontent.com/359239/41720376-423d07ae-7539-11e8-86f3-d3ce5b74cfed.png">

> I used one of the first versions like 1.0.something and it worked like charm.

If you're able to figure out a known good version this will help trace back to which Electron version was working for you previously. We're on Electron `1.8.3` currently and the Electron binaries are built against Ubuntu 12.04 so it's likely something in the app that I haven't come across yet rather than an upstream breaking change.

> IDK where are logs for Ubuntu

See if this folder exists on disk:

```
$ ls ~/.config/GitHub\ Desktop/logs/
```

**Comment by oktonion** [comment]
Developer console output after a second launch:
``
Uncaught Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/GitHubDesktop/resources/app/keytar.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (file:///opt/GitHubDesktop/resources/app/renderer.js:14:341097)
    at t (file:///opt/GitHubDesktop/resources/app/renderer.js:1:115)
``

2018-06-21.desktop.production.log:
``
2018-06-21T08:37:07.876Z - info: [main] Received possible protocol arguments: 1
2018-06-21T12:36:22.324Z - info: [main] Received possible protocol arguments: 1
2018-06-21T13:24:26.001Z - info: [main] Received possible protocol arguments: 1
``

**Comment by shiftkey** [comment]
@oktonion thanks, this is the same as #29 - please follow along with that issue

**Comment by oktonion** [comment]
@shiftkey I see that you closed issue #29 so I tried latest RC.
The issue is still there for me. When I try to run ver.1.3.2 release from terminal it still shows empty window. Then I tried to run it with sudo and that is what I got:

> /opt/GitHubDesktop/desktop --type=renderer --no-sandbox --service-pipe-token=5BDDAE2A29D3BA3070F58C47462298BF --lang=en-US --app-path=/opt/GitHubDesktop/resources/app --enable-experimental-web-platform-features --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --disable-blink-features=Auxclick --context-id=2 --enable-pinch --num-raster-threads=3 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;3,17,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553;4,17,3553 --disable-accelerated-video-decode --enable-gpu-async-worker-context --service-request-channel-token=5BDDAE2A29D3BA3070F58C47462298BF --renderer-client-id=3 --shared-files=v8_natives_data:100,v8_snapshot_data:101: relocation error: /opt/GitHubDesktop/resources/app/keytar.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Idk if I'm doing something wrong or the bug is still there so, please, could you clarify this problem?

**Comment by shiftkey** [comment]
@oktonion this should be resolved with the 1.3.3 update that I'm publishing today. Feel free to comment on #29 if you still spot something unexpected after that.

**Comment by oktonion** [comment]
@shiftkey oh, so the problem is that I am the impatient one. =)
Thank you for the info anyway.

**Comment by oktonion** [comment]
@shiftkey that's perfect!
