### ISSUE TITLE
enterprise account

### ISSUE THREAD

**Issue by vitali-droujko** [shiftkey/desktop#502]
cannot connect with my entreprise account,

unable to authentificate with github entreprise instance, verify that URL is correct, (//it is) that your github entreprise instance is running 2.8.0 or later, that you have an internet connection and try again.

**Comment by K0-RR** [comment]
Take a look at https://github.com/shiftkey/desktop/issues/72

Why did you delete the description?

**Comment by shiftkey** [comment]
GitHub Enterprise access is not supported currently because of how OAuth applications work there.

#72 has more details on why that's the case, but I don't really have the time to take it further because it's a lot of fiddly work (both within the app and for users).
