### ISSUE TITLE
unable to launch DEB after browser completes oauth flow 

### ISSUE THREAD

**Issue by ranu-patidar** [shiftkey/desktop#504]
i want to try signin github desktop but browser not redirect this application my login and password is correct i also try different browser . but  same issue is there. how to solve it .

**Comment by shiftkey** [comment]
@ranu-patidar which installer are you using?

**Comment by Mrlinkwii** [comment]
@ranu-patidar  if your using the appimage ,  make sure to the  following things and it should work : A) get the latest appimage release  B) make sure "The GitHub Desktop Development App" isnt already under "Authorized Oath apps"   , if it is revoke it  if your getting a browser redirection issues , and then go though the Oath process again on the latest version  , when if gets to the 'open with GitHub Desktop '  you have to choose  'open link with' and then choose the  appimage  in the  file browser

**Comment by ranu-patidar** [comment]
> @ranu-patidar which installer are you using?

GitHubDesktop-linux-2.8.1-linux1.deb

**Comment by tusharkeshav** [comment]
@ranu-patidar  Which debian you are using? 
Are you using default super user(root) or other user?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. Please open a fresh issue if you are still looking for support.
