### ISSUE TITLE
Can't Log in on Desktop

### ISSUE THREAD

**Issue by iolandamt** [shiftkey/desktop#509]
### Describe the bug

When I try to do a Push origin on Git Hub Desktop this happens:
<img width="592" alt="Screenshot 2021-05-26 at 21 27 54" src="https://user-images.githubusercontent.com/83780952/119736244-59160b00-be75-11eb-8316-c60f87a9cddb.png">

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@iolandamt please fill out the bug report template so I can understand more about your setup

**Comment by shiftkey** [comment]
Closing this out as I'm 99% sure that screenshot is from macOS - the message itself is also macOS only:

https://github.com/shiftkey/desktop/blob/fc4fdc902c9d238a3dae732180cb4f9b0fadb36a/app/src/lib/stores/accounts-store.ts#L87-L92
