### ISSUE TITLE
aur package

### ISSUE THREAD

**Issue by MetaiR** [shiftkey/desktop#51]
could you please create a package in `aur` that people who are working with `yaourt` package manager can install and update it automatically?

there is already a package for this but its version is old

https://aur.archlinux.org

**Comment by MetaiR** [comment]
I don't have enough knowledge in this field so I sent an email to both publishers and the maintainer of the package asked them to join us on this discussion. hope they can help.

I personally tried to build and install this application on my machine several times before and had no luck so far, so this issue is kind of important to me because I didn't see any application that works well, has nice UI and be free on Linux.

**Comment by mikelpint** [comment]
I don't have any idea about NPM and Electron so I don't think I can help. My package consisted in installing the DEB package with some custom .desktop files.

**Comment by mikelpint** [comment]
The DEB package was taken from [here](https://github.com/gengjiawen/desktop). Unfortunately, it is abandoned.

**Comment by mikelpint** [comment]
One thing I could do is to add the Spanish .desktop file.

**Comment by MetaiR** [comment]
why dont you take the DEB package from here?
we can cast it with debtap to cast it to arch package

**Comment by mikelpint** [comment]
Oh, I didn't see the DEB package.

**Comment by mikelpint** [comment]
I could do a package called github-desktop-deb for the people who have problems installing the official one.

**Comment by MetaiR** [comment]
@mikelpint 
it will be awesome but I think @shiftkey wants to improve and fix existing packages instead of creating another package

**Comment by MetaiR** [comment]
any idea around this issue? @shiftkey

**Comment by shiftkey** [comment]
@MetaiR I'm not keen to "fork" the existing packages unless we've exhausted all other avenues - the fixes seem minor, I'm just not sure how to get them incorporated into the AUR.

**Comment by MetaiR** [comment]
I can create arch package from deb using `debtap` and put them inside other released version
is it helpful?

**Comment by shiftkey** [comment]
@MetaiR it's only been a couple of days - let's give others a chance to reply.

**Comment by immackay** [comment]
Hi all.

First off, it's totally my fault for letting the aur packages get away from me. I may look into handing off control of the package, I've become rather busy with work recently.

I'll incorporate your changes Brendan and also look into debtap - the compile time on weaker systems is getting a little cumbersome.

**Comment by shiftkey** [comment]
@immackay thanks for dropping in to the discussion!

**Comment by alyyasser** [comment]
maybe someone need this, here's modified version of PKGBUILD that i used to install the latest version from this repo
```
_pkgname='github-desktop'
pkgname="${_pkgname}"
pkgver=1.2.6
gitname="release-${pkgver//_/-}"
pkgrel=1
pkgdesc="GUI for managing Git and GitHub."
arch=('x86_64')
url="https://desktop.github.com"
license=('MIT')
depends=('gnome-keyring' 'git' 'electron' 'nodejs' 'libcurl-compat' 'libcurl-gnutls')
optdepends=('hub: CLI interface for GitHub.')
makedepends=('libcurl-openssl-1.0' 'xorg-server-xvfb' 'yarn' 'python2' 'nvm')
DLAGENTS=("http::/usr/bin/git clone --branch ${gitname} --single-branch %u")
source=(
  git+https://github.com/shiftkey/desktop.git#tag=${gitname}
  ${_pkgname}.desktop
)
sha256sums=(
  'SKIP'
  be057e4a392e64760f7a40203ac886b7cf5551de254ad55c706376dca8aa4341
)
build() {
  cd desktop
  unset npm_config_prefix
  source /usr/share/nvm/init-nvm.sh
  nvm install --lts  
  nvm use --lts
  export DISPLAY=':99.0'
  Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  yarn install
  yarn build:prod
  nvm deactivate
}
package() {
  install -d "${pkgdir}/opt/${_pkgname}"
  cp -r --preserve=mode desktop/dist/desktop-linux-x64/* "${pkgdir}/opt/${_pkgname}/"
  printf '#!/bin/sh\n\nLD_PRELOAD=libcurl.so.3 /opt/github-desktop/desktop "$@"\n' | install -Dm755 /dev/stdin "${pkgdir}/usr/bin/github-desktop"
  install -Dm644 "${_pkgname}.desktop" "${pkgdir}/usr/share/applications/${_pkgname}.desktop"
  install -Dm644 "desktop/app/static/logos/1024x1024.png" "${pkgdir}/usr/share/icons/hicolor/1024x1024/apps/${_pkgname}.png"
  install -Dm644 "desktop/app/static/logos/512x512.png" "${pkgdir}/usr/share/icons/hicolor/512x512/apps/${_pkgname}.png"
  install -Dm644 "desktop/app/static/logos/256x256.png" "${pkgdir}/usr/share/icons/hicolor/256x256/apps/${_pkgname}.png"
}
```

**Comment by shiftkey** [comment]
I'm going to close this out for now because this is a community-based effort, and I don't want to come in over the top and add more problems while things are being figured out. But let me know if this still isn't resolved in a few months and we can revisit it.
