### ISSUE TITLE
Spamming "untrusted server" message

### ISSUE THREAD

**Issue by AFCMS** [shiftkey/desktop#511]
### Describe the bug

I often got this message on trusted network. The problem is the message is literally spamming. The button "Add certificate" don't work.
![image](https://user-images.githubusercontent.com/61794590/119779052-850eac00-bec8-11eb-858f-719361ffc6d5.png)

I don't know if it's an upstream issue.

### Version & OS

Ubuntu 20.04
Desktop version: 2.8.0

### Steps to reproduce the behavior

Get this message and see if the button add certificate works.

### Expected behavior
The button should work :-/

### Logs
Log isn't related to this issue, it just refresh repos.

### Additional context

?

**Comment by Winning117** [comment]
I'm having this issue as well. I've tried it on Ubuntu 18.04 and RHEL8 and I get the same issue on both.

**Comment by shiftkey** [comment]
This appears to be a proxy server issue (intercepting HTTPS requests and serving a certificate that isn't recognized by the machine as trusted), but as discussed in #376 I think a lot has changed with Electron that there's a [different API](https://www.electronjs.org/docs/api/app?q=certificate#event-certificate-error) that we could use to accept the certificate on-demand.

This isn't a bug that I've seen, but if someone is able to reproduce please open a fresh issue and I'll try and make time to put together a build that explores how we might workaround these certificate warnings.
