### ISSUE TITLE
How can I change the font size?

### ISSUE THREAD

**Issue by skavadias** [shiftkey/desktop#513]
The Options ==> Appearance menu item only provides the option between a Light and a Dark theme. But the fonts of the application appear too small on my monitor. In fact, it seems there is only one font size used in the whole application. How can I change this font size, though? I would think that this should be a very easy to add feature. I am pretty sure I am not the only one with this problem.

**Comment by shiftkey** [comment]
This question is probably better suited to the main project - see https://github.com/desktop/desktop/issues/3543 for some historical context

**Comment by skavadias** [comment]
Well, someone could tell me (at least) where is the appropriate .css file and what its name is on Linux (and specifically Ubuntu).
This is for this project, I guess!

Thank you.

**Comment by skavadias** [comment]
OK. I found it in View ==> Toggle Developer Tools

On Ubuntu, I changed file `/usr/lib/github-desktop/resources/app/renderer.css` so that `html,body{...}` includes:
`--font-size: 18px;--font-size-sm: 16px;--font-size-md: 22px;--font-size-xs: 12px`
(set the sizes to your preference)
