### ISSUE TITLE
The address wasn't understood

### ISSUE THREAD

**Issue by yanpenalva** [shiftkey/desktop#514]
![image](https://user-images.githubusercontent.com/72168914/119875423-1e57b580-befd-11eb-834e-18ecfeec3827.png)

Hey guys!
I am facing this error when trying to connect with my Github account.

I downloaded .deb 2.8.1 V3
I use: Debian Bullseye and the Firefox browser. 

Can you help me?

**Comment by Mrlinkwii** [comment]
can you make sure  before you  try to connect your  Github account that isnt already connected  to github deskop  this is can be done by ( setting >applications > authorized oath ) If their already an entry for `The GitHub Desktop Development App` revoke that accesses and restart the account connection process and see if that works

**Comment by yanpenalva** [comment]
Hello Mrlinkwii.

I installed version: 2.8.2 Linux RC1 now.

Result: 
![image](https://user-images.githubusercontent.com/72168914/120029968-3bf45000-bfcd-11eb-95f2-da0b189c60b9.png)
![image](https://user-images.githubusercontent.com/72168914/120030018-4b739900-bfcd-11eb-940d-b737b46ecae8.png)

The same error persists. What do you suggest?
OS: Debian GNU / Linux Bullseye KDE Plasma.

**Comment by yanpenalva** [comment]
Hi bro's.
The issue was resolved after I migrated from Debian to Kubuntu. bullseye needed to install some packages manually; despite having settled there, I decided to come to Kubuntu.
