### ISSUE TITLE
GitHub Desktop icon still get's loaded in new GitHub Desktop versions

### ISSUE THREAD

**Issue by ivoxavier** [shiftkey/desktop#518]
New one 
![Captura de ecrã de 2021-06-01 09-14-55](https://user-images.githubusercontent.com/16002474/120290480-4870f500-c2ba-11eb-82e3-c3d4fed69cc0.png)

When opening it loads the old version in the launcher
![Captura de ecrã de 2021-06-01 09-19-03](https://user-images.githubusercontent.com/16002474/120290617-6d656800-c2ba-11eb-8476-953ab6d4958b.png)

- OS version
Ubuntu 20.04

- Desktop Environment
GNOME

**Comment by Mrlinkwii** [comment]
odd , here , its updated :thinking: 
![image](https://user-images.githubusercontent.com/17685135/120889680-3498fc00-c5f6-11eb-8717-5f694d871dd3.png)

 , can you you try using the very latest version (check releases )

**Comment by ivoxavier** [comment]
Both my latop and desktop have this issue. Maybe I just uninstall and reinstall the app again. And yes, I'm running the latest version.

**Comment by shiftkey** [comment]
I have a theory here that it's related to this line, which is specific to the Linux build:

https://github.com/shiftkey/desktop/blob/a04c35efd3e23e652282d839875f65c88baa3bfb/app/src/main-process/app-window.ts#L60

This is the window-specific icon, and might be overriding the default icon as part of the installer. That's pointing to this file, which is using the old style:

https://github.com/shiftkey/desktop/blob/a04c35efd3e23e652282d839875f65c88baa3bfb/app/static/linux/icon-logo.png

I haven't seen this on my 20.04 install either, but that's my best guess currently about where to investigate.

**Comment by Mrlinkwii** [comment]
@ivoxavier which install medium are you using  (appimage , deb etc )

**Comment by ivoxavier** [comment]
Hi, the deb package from this ppa: https://packagecloud.io/shiftkey/desktop/any/
