### ISSUE TITLE
wayland?

### ISSUE THREAD

**Issue by CrezyDud** [shiftkey/desktop#520]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

xwayland with scaling on wayfire is very very blurry and my eyes hurt

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

would be very nice!

**Comment by CrezyDud** [comment]
oh, and i can't use xorg because it detects no displays and no solution has worked..

**Comment by CrezyDud** [comment]
is probably electrons fault

**Comment by shiftkey** [comment]
@MrSwedish currently we're using Electron 11 in GitHub Desktop, but it seems like Electron 12 has some Wayland improvements (based on something named "Ozone" that appears to have landed in Chromium a while ago). https://github.com/microsoft/vscode/issues/109176 has some context on how VSCode is exploring this support.

We'll likely get some of this for free once GitHub Desktop updates to a newer version of Electron, but it may require launching from the command line to opt-in - I haven't been following this closely. https://github.com/electron/electron/issues/10915 is also a good history of this area.
