### ISSUE TITLE
Changes are not detected until clicking on the icon in the app menu

### ISSUE THREAD

**Issue by phcorp** [shiftkey/desktop#523]
### Describe the bug

On Deepin, changes are not detected until clicking on the GitHub Desktop icon in the app menu.

### Version & OS

* version: 2.8.3-linux1
* OS: Deepin 20.2 (Debian 10)

### Steps to reproduce the behavior

1. open your repository in GitHub Desktop
2. produce a change in a file in your favorite IDE
3. minimize your IDE to display GitHub Desktop window: change does not appear
4. click on GitHub Desktop window: change does not appear
5. click on GitHub Desktop icon in the app menu to minimize it, then click it again to make it reappear: change appears

### Expected behavior

GitHub Desktop should detect changes on the repository files without the user toggling the application in the app menu.

### Actual behavior

GitHub Desktop does not detect changes on the repository files until the user toggles the application in the app menu.

### Screenshots

n/a

### Logs

n/a

### Additional context

I don't know if the problem is Deepin related or if it occurs on other distros to.

**Comment by shiftkey** [comment]
This is a bit of a deep topic but the short version is that `refreshRepository` is run when the app receives the `focus` event from Electron:

https://github.com/shiftkey/desktop/blob/51ff60477f199e0c15ab8d35eff78d90dc63feb1/app/src/ui/index.tsx#L304-L317

This itself is a complex part of the app, and handles updating a lot of the Git repository state, including the working directory state:

https://github.com/shiftkey/desktop/blob/51ff60477f199e0c15ab8d35eff78d90dc63feb1/app/src/lib/stores/app-store.ts#L2833-L2900

I believe the goal at the time was to support "switch between Desktop and your editor" and refreshing the state only when needed, but that's a different workflow to what you've outlined. There might be some old discussions floating around on the main project about this, but hopefully this helps to better understand the behaviour you're seeing.

**Comment by shiftkey** [comment]
Closing this out as answered, as I don't have plans to change this behaviour currently
