### ISSUE TITLE
Right click on dropdown item of branches not working

### ISSUE THREAD

**Issue by kimlimjustin** [shiftkey/desktop#527]
### Describe the bug

I was trying to modify a branch by right-clicking on the branch name from the dropdown of Branches, and this works on desktop/desktop on windows, but not working on Linux (idk the bug comes on this fork repo or the desktop/desktop, please inform me if I report on wrong repo)

### Version & OS

App: Version 2.6.3-linux1
OS: Ubuntu 21.04 x86_64

### Steps to reproduce the behavior

1. Click the branch button (the big button showing current branch one)
2. Right-click on a branch
3. It's not working

### Expected behavior

Right-clicking works fine like the desktop/desktop on Windows.

### Actual behavior

Right-clicking not working.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

[2021-06-15.desktop.production.log](https://github.com/shiftkey/desktop/files/6657004/2021-06-15.desktop.production.log)

**Comment by shiftkey** [comment]
> App: Version 2.6.3-linux1

This release was published on February 11, and I suspect was fixed in an update since then. I tested `2.8.2` locally and confirmed I see the context menu.

Please install the [latest release](https://github.com/shiftkey/desktop/releases/tag/release-2.8.3-linux1) and confirm this is working for you.

**Comment by kimlimjustin** [comment]
> > App: Version 2.6.3-linux1
> 
> This release was published on February 11, and I suspect was fixed in an update since then. I tested `2.8.2` locally and confirmed I see the context menu.
> 
> Please install the [latest release](https://github.com/shiftkey/desktop/releases/tag/release-2.8.3-linux1) and confirm this is working for you.

Yes, the latest release works fine, thanks!
