### ISSUE TITLE
Github Desktop does't install in Linux Mint 19.03

### ISSUE THREAD

**Issue by Igoroliveira98** [shiftkey/desktop#528]
### Operating System/Distribution

Which distribution of Linux are you using?
Linux Mint 19.03

### Installer

Which version of the app?
Currently

Which installer type?
Package Manager

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful:

When a try install, terminal return to me that it's impossible found out the github-desktop

**Comment by K0-RR** [comment]
You are supposed to include a log. Paste terminal output, a screenshot at minimum.

>terminal return to me that it's impossible found out the github-desktop

This sounds like you were in the wrong directory when installing. Actually, there is no "./" before "github-desktop". What command did you enter? Why not use a graphical installer? Mint should have it pre-installed.

>Which version of the app?
Currently

This doesn't help at all. The latest release for Debian-based systems is 2.8.3-linux1.deb. Can you confirm you were trying to install this file?
