### ISSUE TITLE
Want to install on ubuntu

### ISSUE THREAD

**Issue by TinajaLabs** [shiftkey/desktop#53]
I got here because I saw a reference that said there were some packages to install github desktop on Linux (ubuntu 18.04 for me).

For the life of me I see not a single reference to instructions about how to install this...

Please, somebody, point me in the right direction...

Thank you,
Chris.

**Comment by TinajaLabs** [comment]
Found it referenced in a random gist script:
https://github.com/shiftkey/desktop/releases

**Comment by shiftkey** [comment]
@TinajaLabs I'm glad you were able to figure it out.

For reference, the docs I wrote about this a while ago have more context: https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md
