### ISSUE TITLE
Can not open terminal by pressing ctrl + ` on Ubuntu 20.04

### ISSUE THREAD

**Issue by krushnaj** [shiftkey/desktop#532]
### Describe the bug

Can not open the repository folder in the terminal by pressing `ctrl` + `

### Version & OS
Ubuntu: 20.04.2 LTS
Github Desktop: 2.9.0

### Steps to reproduce the behavior

1. Open a repository
2. Press `ctrl` + `

### Expected behavior

Should open the terminal

### Actual behavior

Nothing happens when I press the keys to open the Terminal

**Comment by krushnaj** [comment]
This is the error displayed in the console

```
[GNOME Terminal] stderr: '# Failed to parse arguments: Unknown option --single-instance
'
install.ts:35 [GNOME Terminal] exit code: 1
```

**Comment by shiftkey** [comment]
@krushnaj that's an interesting clue, and looks like we're ending up in here:

https://github.com/shiftkey/desktop/blob/87a25c91786ca156b1fd4c9f78bd59293f01dc28/app/src/lib/shells/linux.ts#L161-L167


Seems like the rules from `Shell.Kitty` in #525 should be moved to the end, as the shells above it probably don't know about `--single-instance`
