### ISSUE TITLE
Packagecloud possible issue

### ISSUE THREAD

**Issue by MikMuellerDev** [shiftkey/desktop#534]
### Operating System/Distribution
first of all... I really enjoy desktop : )

``Debian / Ubuntu ``

(I use arch btw.) On arch it works fine because of yay / aur. 
On distros with apt however, some issues with the istallation appear.

### Installer

Trying to install the new version with packagecloud (used all commands from the guide)

### What happened?

when running apt-update i get this.

``
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests 
[IP: 2600:1f1c:2e5:6900:da62:ff28:8bff:54ed 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
``

* I tested it on 3 different machines, none of them worked

* So i believe the issue is with packagecloud not with desktop

**Comment by madSec** [comment]
Hi, I have the same issue on Linux Mint 20 (Ubuntu 20.04 basis) using the commands from the guide. When trying to download the package directly for example using [this link](https://packagecloud.io/shiftkey/desktop/packages/any/any/github-desktop_2.8.0-linux1_amd64.deb/download.deb) I get the message "Bandwidth or Storage Limit Exceeded" returned in my browser, looks like a download limit on the hast has been reached?

**Comment by iamdual** [comment]
Hi, just download manually from here: https://github.com/shiftkey/desktop/releases

**Comment by shiftkey** [comment]
From #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended. The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
>
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.
