### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by Rungrot19** [shiftkey/desktop#539]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.
#

**Comment by Mrlinkwii** [comment]
:wave:  can you fill out the template please :slightly_smiling_face:

**Comment by shiftkey** [comment]
@Rungrot19 please open a new issue and fill out the template if you are having specific issues with GitHub Desktop on Linux.

This is the third empty issue from you that I've had to cleanup - #543 #545 

Any further abuse of this template to create empty issues may result in you being blocked from the project.
