### ISSUE TITLE
Rs

### ISSUE THREAD

**Issue by Rungrot19** [shiftkey/desktop#543]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by shiftkey** [comment]
@Rungrot19 please open a new issue and fill out the template if you are having specific issues with GitHub Desktop on Linux
