### ISSUE TITLE
How do I update?

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#546]
I don't want to reinstall, just update

**Comment by K0-RR** [comment]
Huh? If you installed it by some package installer like gdebi or in the terminal using apt then just do it again using the newer deb file (assuming you are on a Debian based system).
Define what you mean by reinstalling, for me (or rather OS) it’s kinda the same as updating.

**Comment by ghost** [comment]
I mean, I want the latest pre-release, am on Ubuntu 21.04, have added the repo after using the stable .deb
Is there a repo for dev builds?

**Comment by shiftkey** [comment]
> Is there a repo for dev builds?

@VMGuy23 it's all the same feed. The `prerelease` label on releases is just a habit I formed from early on while things were stabilizing. I've opened #551 to signal this more clearly as part of the release workflow.
