### ISSUE TITLE
Open in folder does not work in flatpak

### ISSUE THREAD

**Issue by Lunarequest** [shiftkey/desktop#564]
Using open in folder in flatpaks results in the file opening in the code editor if one is set or just not opening if nothing is set

**Comment by shiftkey** [comment]
Can you confirm the part of the UI that you're using to start this? I'm assuming this is from the **Repository** | **Show in your file manager**. 

First, the menu item for Show in your File Manager - this goes into the standard menu event handlers in the app:

https://github.com/shiftkey/desktop/blob/9f3d916998ec0ae6ea7736572636f666bd743a4e/app/src/main-process/menu/build-default-menu.ts#L305-L314

This is where we handle the event:

https://github.com/shiftkey/desktop/blob/d3ce51dbfa322c1ebbb183a32daa9b27c13432b2/app/src/ui/app.tsx#L380-L381

After some validation we end up in here:

https://github.com/shiftkey/desktop/blob/b055ca70c80179ecec5c4e92b548ca353a872e44/app/src/ui/app.tsx#L2412-L2418

`showFolderContents` will use IPC to communicate to the main process (the renderer is essentially the `AppWindow` and is a separate process: 

https://github.com/shiftkey/desktop/blob/b055ca70c80179ecec5c4e92b548ca353a872e44/app/src/lib/app-shell.ts#L55-L57

The main process event handler for this has a lot of details:

https://github.com/shiftkey/desktop/blob/b055ca70c80179ecec5c4e92b548ca353a872e44/app/src/main-process/main.ts#L560-L610


The scarily-named `UNSAFE_openDirectory` is just a wrapper over [`shell.openPath`](https://www.electronjs.org/docs/api/shell#shellopenpathpath) that Electron makes available, so it's not clear to me why we're ending up with an editor, unless I'm mis-understanding the repro steps.

https://github.com/shiftkey/desktop/blob/b055ca70c80179ecec5c4e92b548ca353a872e44/app/src/main-process/shell.ts#L17-L32

Let me know if there's anything else that I can clear up in this area...

**Comment by Lunarequest** [comment]
I'm guessing `shell.openPath` uses xdg-open under the hood?

**Comment by Lunarequest** [comment]
> Can you confirm the part of the UI that you're using to start this? I'm assuming this is from the **Repository** | **Show in your file manager**.

yup that's what I'm using

**Comment by shiftkey** [comment]
> I'm guessing `shell.openPath` uses xdg-open under the hood?

[Correct](https://github.com/electron/electron/blob/fa0323a3db48338bf7cf3047927e4073bc9388c4/shell/common/platform_util_linux.cc#L165-L168)

**Comment by Lunarequest** [comment]
I've got a rough idea of why this doesn't work I need the person who reported the issue to confirm it. If a default file manager isn't set, xdg-open doesn't really work. if for some reason it isn't there changing it to something else and back should cause the generation of this association which should make it work.

**Comment by Lunarequest** [comment]
after some more testing this appears to be a improperly configure xdg setup not a issue with github-desktop
