### ISSUE TITLE
Switching to "History" and back to "Changes" makes pushes go faster than they normally would.

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#566]
### Describe the bug

Switching to "History" and back to "Changes" makes pushes go faster than they normally would.

### Version & OS

Version 2.9.0-linux4 (x64)
I'm using the RPM. I remember this bug from previous versions **though.**

### Steps to reproduce the behavior

1. Go to 'Push Origin'
2. Click it
3. Switch to "History" and back to "Changes" on the left under your repo name
4. It makes it go faster

### Expected behavior

It to always go at the same speed KEK

### Screenshots

[video](https://imgur.com/a/ThUSsTA)

### Logs

[2021-07-22.desktop.production.log](https://github.com/shiftkey/desktop/files/6861667/2021-07-22.desktop.production.log)

**Comment by shiftkey** [comment]
This is related to #508, let's roll this up into that issue
