### ISSUE TITLE
Unable to uninstall github from ubuntu 20

### ISSUE THREAD

**Issue by innoviussoftware** [shiftkey/desktop#568]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by K0-RR** [comment]
@innoviussoftware there is no Ubuntu 20. You didn’t provide any information at all, how do you think someone would help you?

**Comment by hholst80** [comment]
Pretty much the worst issue report I've seen in a long time. @innoviussoftware you are wasting the time of others, and to you probably more important, your own time.
Provide data such as: what did you attempt to do, how did you do it, did error messages appear, how did the outcome not match your expectations?

**Comment by shiftkey** [comment]
Closing this out as incomplete. @innoviussoftware please open a fresh issue and complete the template if you want us to investigate further...
