### ISSUE TITLE
Stuck on "Cloning to url".

### ISSUE THREAD

**Issue by OskarZyg** [shiftkey/desktop#569]
### Describe the bug

When cloning a (private,org) repository, the application gets stuck on the following screens (the password I am entering is correct)

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
`Version 2.9.0-linux4 (x64)`
![OS](https://user-images.githubusercontent.com/56176746/127223173-fdf02a6f-b4ae-4c34-b6e8-5ab538004705.png)

### Steps to reproduce the behavior

1. Go to 'Select a repository -> Add -> Clone new repository -> URL'
2. Enter a private repository url in an organisation and press Clone (cloning the repo using just author/repository results in `fatal:repository 'author/repository' does not exist
`)
4. Get Stuck

### Expected behavior

The repository is cloned to the folder

### Actual behavior

Gets stuck and never clones the directory

### Screenshots
![Screenshot from 2021-07-27 21-32-11](https://user-images.githubusercontent.com/56176746/127223390-712a4e09-2a2f-46ce-b137-297ad2b1c134.png)
![Screenshot from 2021-07-27 21-31-25](https://user-images.githubusercontent.com/56176746/127223398-68c876b9-7003-402d-814c-ef026b8bcac7.png)

Add screenshots to help explain your problem, if applicable
### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2021-07-27.desktop.production.log](https://github.com/shiftkey/desktop/files/6888626/2021-07-27.desktop.production.log)

### Additional context
none

**Comment by shiftkey** [comment]
```
Error: Although you appear to have the correct authorization credentials, the `OskarsMC-Sealeaf` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
```

This is a known limitation of the Desktop build: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 has more details, and sadly it's not something that I can easily fix for this fork.

**Comment by shiftkey** [comment]
Please follow along with #72 which is tracking the underlying limitation for this problem.
