### ISSUE TITLE
create organization based sub-folders while cloning repos into local system 

### ISSUE THREAD

**Issue by bala** [shiftkey/desktop#570]
### Describe the bug
Cloned repos doesn't create local folders based on organization

I am part of multiple organizations. I have 2 organizations containing same repo name. When i try to clone ORG1, it is cloning under  /home/USER/softwares/github/GitHub/REPO. 

But when i try to clone REPO from ORG2 then it points to the same folder as ORG1 (/home/USER/softwares/github/GitHub/REPO ) and it is throwing "FOLDER NOT EMPTY ERROR" 

it would be nice if it can create sub-folder for each organization as follows

/home/balaji/softwares/github/GitHub/ORG1/REPO
/home/balaji/softwares/github/GitHub/ORG2/REPO

### Version & OS
Ubuntu 20.04
Github desktop version: 2.9.0 RC4

### Steps to reproduce the behavior

1. Go to 'clone a repository from ORG1 into /home/USER/softwares/github/GitHub/REPO'
2. Go to 'clone a repository from ORG2 into /home/USER/softwares/github/GitHub/REPO' - this location is by default

### Expected behavior

Create folders in following structure - /GITHUB_DEFAULT_STORAGE_PATH/ORG-NAME/REPO

### Actual behavior

Currently it Create folders in following structure - /GITHUB_DEFAULT_STORAGE_PATH/REPO 

### Screenshots
![Screenshot_20210728_095831](https://user-images.githubusercontent.com/4012718/127265076-11ae0a2c-c7aa-4b7a-ac52-65d39c1a0517.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@bala thanks for your interest in this. I don't currently have the bandwidth to handle feature requests, so I'll have to refer you to the upstream discussion about this https://github.com/desktop/desktop/issues/5449

**Comment by bala** [comment]
@shiftkey I have created a PR for this issue myself - https://github.com/shiftkey/desktop/pull/572#issue-699974965
