### ISSUE TITLE
i cant sign into my github account

### ISSUE THREAD

**Issue by cyberraff** [shiftkey/desktop#578]
### Describe the bug
Write a clear and concise description of what the bug is.i can not sign into my github account

### Version & OS
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.10.56-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-3230M CPU @ 2.60GHz
Memory: 5.7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

_Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using._

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@cyberraff please fill out the Steps to reproduce section, providing as much detail as possible

Please also specify which version of GitHub Desktop you are running

**Comment by shiftkey** [comment]
Closing this out due to inactivity
