### ISSUE TITLE
In Zorin OS 16 the UI progress indicator freezes while Github Desktop is focused.

### ISSUE THREAD

**Issue by ronbarbosa** [shiftkey/desktop#580]
### Describe the bug
When performing most functions (commits, push, fetch) the UI seems to "spin" in place (showing no progress) as long as the application has focus. If I navigate to a different application and immediately come back to Github Desktop, the UI progress updates to the next step and then seems to stick again. Switching focus again will advance to the next phase. It seems like the application is just taking a long time to complete processes, but upon closer inspection it seems to just be a UI bug.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. I can only say for certain this is occurring in Zorin OS 16.
2. Load Github desktop and select any existing repository
3. Click "Fetch"
![image](https://user-images.githubusercontent.com/1733836/130552235-2a48eda2-053b-4be4-8d4e-3657fc8d4998.png)

5. Move focus to any other application (here I've used my terminal application just in front of the Github Desktop UI):
![image](https://user-images.githubusercontent.com/1733836/130552324-9231b151-c0e3-45b2-b2c1-04034c03896c.png)

6. Moving back to the GitHub Desktop UI shows that the process has completed:
![image](https://user-images.githubusercontent.com/1733836/130552383-92c74c79-6711-48b4-8509-4ad564f8db7a.png)

### Expected behavior

The expected behavior is that the progress indicator should show actual progress and clear itself back to its "idle state" without requiring the application to lose focus.

### Actual behavior

As long as the UI has focus, the progress indicator continues indefinitely. 

### Screenshots

Attached in description of the reproduction steps.

### Logs

Logs are not applicable.

### Additional context

None applies.

**Comment by shiftkey** [comment]
Two questions:

 - which version of the app are you running?
 - are you working with a private repository at the time of these issues?

**Comment by ronbarbosa** [comment]
Hello and thanks for the quick response. I'm running version 2.9.0 of Github Desktop. At last check, I think this was the latest.

I am, in fact working, on a private repository.

Update: I just cloned shiftkey/desktop and I do not see the same behavior from the public repository. Is this a known issue for private repositories?

**Comment by ronbarbosa** [comment]
My system auto-updated to 2.9.2 and it appears the problem is resolved.
