### ISSUE TITLE
Username is repeatedly appended to local path on clone repository

### ISSUE THREAD

**Issue by Raymo111** [shiftkey/desktop#585]
### Describe the bug
When cloning a repository from GitHub.com, the Local path gets the remote username appended to it repeatedly, likely because there's a forward slash between the username and repo name.

### Version & OS

`Version 2.9.2-linux1 (x64)` on Arch Linux (`5.13.12-arch1-1`)

### Steps to reproduce the behavior

1. Go to 'File > Clone Repository...'
2. Click on a repository under 'GitHub.com > Your repositories'
3. See error in Local path field

### Expected behavior

The local path should be updated with the new repo name, without the username.

### Actual behavior
The username is repeatedly appended to the path.

### Screenshots
![2021-08-27 21-12](https://user-images.githubusercontent.com/34818275/131201559-27c6d54e-c306-43b1-8ec4-2a57f053c9b2.gif)

**Comment by fanninpm** [comment]
@bala likely introduced this bug in #572

**Comment by balajib-b** [comment]
> @bala likely introduced this bug in #572

@shiftkey I'm on it, will submit PR asap

**Comment by bala** [comment]
@shiftkey I'm on it. will release PR asap.

**Comment by jesobreira** [comment]
Seems also that it uses historical data (from other repos?) and ends up mixing things when we are cloning organization repos (username + organization name), and had this result too:

![Captura de tela de 2021-09-14 09-57-14](https://user-images.githubusercontent.com/3002249/133262063-71af1bd9-f4d4-46e1-ac78-73f314ff90fc.png)

**Comment by qualk** [comment]
Yup, can confirm issue.

**Comment by shiftkey** [comment]
I've reverted this behaviour in `2.9.2-linux3` and you can grab the build from [here](https://github.com/shiftkey/desktop/releases/tag/release-2.9.3-linux2) until we can get a better version of this into a future release...

**Comment by Raymo111** [comment]
Will do, thanks.

@bala Please also let us choose the option of not using org names for the improved version if and when that's made!
