### ISSUE TITLE
Authentication failed.

### ISSUE THREAD

**Issue by Mahmoudgarwallane** [shiftkey/desktop#588]
### Describe the bug
when I try to push my repo
this message appears 

```
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
```

### Version & OS

I'm using
> ubuntu  20.04

GitHub desktop version:
>Version 2.8.0-linux1

### Steps to reproduce the behavior

1.make changes to the repo 
2. committing 
3. pushing the error

### Expected behavior

to push normally

### Actual behavior

this error appears

```
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
```

### Screenshots

Add screenshots to help explain your problem, if applicable.
![err](https://user-images.githubusercontent.com/68555232/131681735-cf82ba9a-999d-4243-8211-af68d95815e8.png)

**Comment by K0-RR** [comment]
You should update to the newest version before reporting an issue.

**Comment by Mahmoudgarwallane** [comment]
> You should update to the newest version before reporting an issue.

could you please tell me how to do
