### ISSUE TITLE
AppArmor policy error accessing password manager

### ISSUE THREAD

**Issue by NatoBoram** [shiftkey/desktop#59]
This is a duplicate of https://github.com/desktop/desktop/issues/5606, as requested [here](https://github.com/desktop/desktop/issues/5606#issuecomment-420410462).

> ## Description
> 
> Can't login to GitHub using the snap version of GitHub Desktop.
> 
> ![github desktop bug](https://user-images.githubusercontent.com/10495562/45384452-17b57280-b5dc-11e8-9e56-d44170c303c0.png)
> ## Version
> 
> ```shell
> $ snap info github-desktop 
> name:      github-desktop
> summary:   Extend your GitHub workflow beyond your browser with GitHub Desktop
> publisher: Snapcrafters
> contact:   https://github.com/snapcrafters/github-desktop/issues
> license:   unset
> description: |
>   Extend your GitHub workflow beyond your browser with our Desktop,
>   completely redesigned with Electron. Get a unified cross-platform
>   experience that's completely open source and ready to customize.
> commands:
>   - github-desktop
> snap-id:      vxuDrMy9vuqIU5Abf2MQOowf2e09tcm9
> tracking:     edge
> refresh-date: today at 15:50 EDT
> channels:                     
>   stable:    –                
>   candidate: –                
>   beta:      –                
>   edge:      1.3.4 (31) 140MB -
> installed:   1.3.4 (31) 140MB -
> ```
> 
>     * Operating system:
> 
> 
> ```shell
> $ neofetch --off
> nato@HelionUbuntu 
> ----------------- 
> OS: Ubuntu 18.04.1 LTS x86_64 
> Kernel: 4.15.0-34-generic 
> Uptime: 4 hours, 44 mins 
> Packages: 2148 
> Shell: bash 4.4.19 
> Resolution: 1920x1080 
> DE: GNOME 3.28.3 
> WM: GNOME Shell 
> WM Theme: Adwaita 
> Theme: Adwaita-dark [GTK2/3] 
> Icons: Ubuntu-mono-dark [GTK2/3] 
> Terminal: gnome-terminal 
> CPU: Intel i5-3570K (4) @ 4.100GHz 
> GPU: NVIDIA GeForce GTX 660 Ti 
> Memory: 6003MiB / 7922MiB 
> ```
> 
> ## Steps to Reproduce
> 
>     1. `sudo snap install github-desktop --edge`
> 
>     2. Open GitHub Desktop. It takes a while the first time.
> 
>     3. Login
> 
> 
> ### Expected Behavior
> 
> The login completes successfully.
> ### Actual Behavior
> 
> The login fails with the following message : `An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.291" (uid=1000 pid=22162 comm="/snap/github-desktop/31/opt/GitHubDesktop/desktop " label="snap.github-desktop.github-desktop (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.20" (uid=1000 pid=1732 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")`.
> ## Additional Information
> 
> I believe it's because of an undeclared capability in the app. It should be as simple as modifying the `package.json` file by adding an [interface](https://docs.snapcraft.io/core/interfaces).
> ### Logs
> 
> ... and I noticed I reported at the wrong place. There's already [snapcrafters/github-desktop#9](https://github.com/snapcrafters/github-desktop/issues/9).

# Edit

Solution : 

```bash
sudo snap connect github-desktop:password-manager-service
```

**Comment by ipkpjersi** [comment]
I have not been able to replicate this issue. The snap is working just fine for me (although - perhaps it is because I already had my credentials saved? Not sure).

**Comment by bb441db** [comment]
Can you try running the following command and see if that fixes it? (assuming **desktop** is the snap's name.)
```bash
sudo snap connect desktop:password-manager-service core:password-manager-service
```
See: https://forum.snapcraft.io/t/nextcloud-client-snap-app-armor-issue/4366/4

If this fixes it, we should add this to the snap.
```yaml
plugs: 
  - 'password-manager-service'
```

**Comment by NatoBoram** [comment]
@bb441db It works!

```bash
sudo snap connect github-desktop:password-manager-service
```

![image](https://user-images.githubusercontent.com/10495562/46552219-06dce180-c8a8-11e8-9d70-bb00d2d58a44.png)

**Comment by NatoBoram** [comment]
Now that this is done, there's another problem.

```
Cloning into '/home/nato/Documents/GitHub/FirstRun'...
/snap/github-desktop/35/opt/GitHubDesktop/resources/app/git/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

![image](https://user-images.githubusercontent.com/10495562/46560132-942c3000-c8c0-11e8-8dc8-9b19649fa2a7.png)

Should I open a separate issue for this?

**Comment by joaomlneto** [comment]
I believe this is being tracked at https://github.com/desktop/dugite-native/issues/109 :-)

**Comment by NatoBoram** [comment]
Thanks!

Wow, issues are being tracked at so many places at once x)

**Comment by bb441db** [comment]
See https://github.com/shiftkey/desktop/issues/68

Should be fixed in a newer release, I don't think it's in the snapcraft repos yet.

**Comment by shiftkey** [comment]
> I will admit I am a little sad to hear that this latest snap version on the snapcraft store has one or more regressions after the previous snap had other issues as well for me.

The previous Snap version had the "classic" confinement (which meant it wasn't confined at all) so I'm not surprised it was much better. Releasing packages with this setting required approval from Snapcraft to do, and isn't something they encourage. This version now uses the "strict" confinement, which is important for many reasons, but I suspect we'll have some more tweaks to the config to get it working smoothly.

It's not clear to me how to correlate errors like this to the right interfaces/plugs, so any pointers from those more experienced with Snap packaging would be greatly appreciated. cc @flexiondotorg

>  If this issue and #91 are fixed, is deploying an updated snap to the snapcraft store possible or does it take a long time to publish updates to there?

I can deploy to the Edge channel pretty in about an hour, and that's what I've been working towards over the last few weeks in my spare time. The hold up has been around getting permissions to publish to the existing package in the store (this wasn't started by me) but it was enabled in the last 24 hours.

**Comment by shiftkey** [comment]
@ipkpjersi I believe this is something that's a security measure we've encountered - [this document](https://forum.snapcraft.io/t/the-password-manager-service-interface/7899) suggests that the permission we had for `password-manager-service` is not auto-connect, which means the user likely needs to connect the app to be able to read/write credentials.

This worked on my machine with the latest build: `sudo snap connect github-desktop:password-manager-service` - I was able to sign in fine after that.

**Comment by shiftkey** [comment]
For the moment I'm going to leave this open to address these three things:

 - write some notes in the [install guide]() for Snap to indicate the `connect` step is already in place
 - improve the error handling here to display a better error message
 - investigate whether the app can request to connect (and potentially retry) to the password manager

**Comment by zypA13510** [comment]
Just updated to snap store version and encountered this error.

I would suggest including the `connect` instruction in the error message, people tends to ignore the install guide (I did). And maybe include an opt-out choice as well (instead of "close") as well.

**Comment by shiftkey** [comment]
> I would suggest including the `connect` instruction in the error message, people tends to ignore the install guide (I did).

We already have a similar scenario here about the Keychain access:

https://github.com/shiftkey/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/src/lib/stores/accounts-store.ts#L95-L105

If someone wants to try making a similar `isAppArmorError(e)` function here to make the error message friendlier I'd be happy to work with them on reviewing and merging the change.

**Comment by bangke213** [comment]
it's clear all the intentions of this data

**Comment by shiftkey** [comment]
With the help of the Snapcraft team, I've now been able to publicize the app again on the Snapcraft store now the enclosures are migrated. It is recommended to install the `beta` channel currently if you are working from a fresh install.

For existing installs the `edge` channel will remain using the `strict` enclosure for the moment, and refreshing to the latest version there will ask you to install the `beta` channel, which is using the `classic` enclosure and requires a manual upgrade:

<img width="929" src="https://user-images.githubusercontent.com/359239/55685440-adc03a00-592c-11e9-830e-32b6f429831d.png">
