### ISSUE TITLE
Flatpak: support for moving repos to trash

### ISSUE THREAD

**Issue by Lunarequest** [shiftkey/desktop#597]
### Describe the feature or problem you’d like to solve

Currently removing a repo to trash fails with the message file is open in another program. 

### Proposed solution

I am proposing in flatpaks the behavior be changed to use trash-cli to move files to the trash using portals  

### Additional context
https://github.com/flathub/io.github.shiftey.Desktop/issues/11

**Comment by Lunarequest** [comment]
okay I've found out you can force electron into using portals for trashing files. however by doing this we run into an issue of xdg-portal being broken. It should be fixed soon but this is outside fixable for us.

**Comment by RokeJulianLockhart** [comment]
You may want to rectify the orthographic error ("tash") that is comprising [the title of this issue](http://github.com/shiftkey/desktop/issues/597).
