### ISSUE TITLE
No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

### ISSUE THREAD

**Issue by Slips-PC** [shiftkey/desktop#601]
### Describe the bug
Attempting to sign in to my GitHub account via the desktop app provides the above error and prevents me from accessing a variety of options in the taskbar.

### Version & OS
Version 2.9.3-Linux1
OS: Arch Linux

### Steps to reproduce the behavior
1: Click Options
2: Click "Sign In" on the Accounts > Github.com tab.
### Expected behavior

It would open a link in Firefox, which would authenticate the app, thus allowing my Github account to be accessed.

### Actual behavior

The link was opened in firefox, but returning to the Github Desktop app provides this error:

No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

Furthermore, after this popup, I can no longer access multiple options in the taskbar, including the Options modal.

### Screenshots

![image](https://user-images.githubusercontent.com/59989951/133707534-9eee2678-1f1d-4233-8266-ca7cff3b7031.png)

### Logs

Cannot provide, as Help > Open logs in file manager hangs the app.

### Additional context

N/A.

**Comment by shiftkey** [comment]
@Slips-PC I have some familiarity with the Arch community `PKGBUILD`s but I wonder if you actually have `gnome-keyring` installed. That's needed for the credential manager that GitHub Desktop uses to store and retrieve credentials, and it seem like perhaps there's an error while it's trying to do that...

**Comment by DanOl98** [comment]
Hello, I have the same issue, gnome-keyring is installed. 
Version: 2.9.4-Linux1
OS: Ubuntu 20.04.3 LTS

**Comment by shiftkey** [comment]
This feels like something about the keyring setup is blocking the app from persisting it's token.

> Cannot provide, as Help > Open logs in file manager hangs the app.

@DanOl98 @Slips-PC the log files should be on disk at `~/.config/GitHub Desktop/logs/` and organized by date if you are able to find any extra details about the underlying error.

Based on other research this error is somewhat generic, and the advice I found to get the keychain working may not be the right fix for your setup, so I don't want to recommend anything that could break your setup.

**Comment by Slips-PC** [comment]
This issue no longer affects me as I have stopped using GitHub altogether. Thank you for the assistance, though. In retrospect this was likely an issue with gnome-keyring as you suggested.
