### ISSUE TITLE
Error when attempt to open in GNOME terminal "cannot read property 'path' of undefined"

### ISSUE THREAD

**Issue by katiehartrick** [shiftkey/desktop#607]
### Describe the bug
Write a clear and concise description of what the bug is.
New install on elementary OS 6. Attempt to open GNOME Terminal directly from Github Desktop Linux client. Error "Cannot read property 'path' of undefined".

**Comment by Mrlinkwii** [comment]
what version and are you using the appimage or deb etc ?

**Comment by shiftkey** [comment]
I think this is the same as #344 and my current theory here is that there's no available terminal for the user (or the default GNOME Terminal is not available)

> > "GNOME Terminal" is shown regardless it is installed or not, and Deepin Terminal works so far.
> 
> There's some history in here that I'm hazy on, but on initial launch we don't have a selected terminal and the placeholder we use is a best guess. This works fine on Windows and macOS because we know what shells are available by default, but clearly that won't work for Linux due to the different permutations of configurations available.
> 
> It'd be nice to be able to probe on this first launch and see what shells are installed, and choose the first valid shell, but I'm not sure if we have a suitable hook to do that.

Closing this in favour of that issue to avoid duplication
