### ISSUE TITLE
problem after xdg-open tries to launch the app

### ISSUE THREAD

**Issue by Meet-Nakhate** [shiftkey/desktop#609]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

i have downloaded the github desktop in linux mint and when i do sign in into github destop it redirects it to chrome then ask the permission of xdg-open and when a caalow it nothing happens how to solve this problem

**Comment by alexpseletr** [comment]
i have the same problem , xdg-open does not find github-desktop , one suggestion would be to add some way to copy the browser token and include in the application

**Comment by shiftkey** [comment]
A few questions to help guide the investigation:

 - what version of the package are you using?
 - which installer did you use?
 - any interesting log files you can share? `~/.config/GitHub Desktop/logs/` is where there are stored, organized by date

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of information. 

Please open a new issue with more information if you are still looking for assistance.
