### ISSUE TITLE
Can't access organization repositories

### ISSUE THREAD

**Issue by thedhruvunde** [shiftkey/desktop#610]
cant access my organization's repos, in Github.com section
and when I clone repository by URL section I can't push my changes to origin
It gives some authentication error

**Comment by doug-leasure** [comment]
The authentication error message is:

<hr>

We were unable to authenticate with `github.com`. Please enter your username and password to try again.  

Username: ` `  

Password: ` `  

Depending on your repository's hosting service, you might need to use a Personal Access Token (PAT) as your password. Learn more about creating a PAT in our [integration docs](https://github.com/desktop/desktop/tree/development/docs/integrations).
<hr>

This only happens for an organizational account on GitHub.com, not my personal GitHub. I [created a PAT with repo-level access](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and tried using it in the "Password" field of the authentication error dialogue box, but it was not successful.

**Comment by toddgibson** [comment]
I am experiencing this same issue, using Pop_OS! 21.04.  Like others said, personal repos are fine.  Organization repos are not accessible.

**Comment by Twinki14** [comment]
Getting the same issue

**Comment by amytimed** [comment]
This is quite annoying, I can't access any of my organization repositories.

**Comment by skypap** [comment]
same issue

**Comment by karleinarb** [comment]
Same issue here.
Running Version 2.9.4-linux1 (x64)

**Comment by amytimed** [comment]
This is the only thing stopping me from switching to Linux, and seems to be a common issue, judging by the amount of commenters. Can we please get this fixed?

**Comment by bookshiyi** [comment]
same issue.

Ubuntu 20.04.3 LTS
Github-Desktop version 2.9.4-linux1 (x64)

**Comment by shiftkey** [comment]
This is a [known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization) for the Linux build:

> ### I cannot access repositories under my organization
>
>The GitHub Desktop application is an OAuth application, but this fork does not
have the same permissions as the app does on Windows and macOS, which manifests
in a couple of different ways:
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a
>    generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access
> restrictions" enabled, which blocks the GitHub Desktop development app that is
> used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)
> to the GitHub Desktop development app.

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 has more context
