### ISSUE TITLE
If force push fails force push option disappears

### ISSUE THREAD

**Issue by istiak101** [shiftkey/desktop#614]
### Describe the bug
After squashing commits if force push fails you can no longer push/pull (in case of entire history rewrite). Force push option disappears and only available option is pull origin. In case of ancestor commits pull origin works but that will make the rebasing useless making cluttered commit history. In this moment you still can do a force push from command line but not from Github desktop.

Workaround I tried to get things normal again was doing a bogus commit and squashing again and then try force pushing again which succeed.

### Version & OS
Desktop: 2.9.3-linux3 (x64)
OS: Ubuntu 21.10

### Steps to reproduce the behavior
1. Go to any repository
2. Squash multiple commits with drag and drop from history
3. Do the force push and let it fail (disable network/block commits from real mail/any other way)
4. You can no longer force push. The option is disappeared. Only Pull Origin is available and if you try that you will get `Unable to merge unrelated histories in this repository (in case of entire rewrite)` . In case of ancestor commits pulling works but that is not intended after a rebase. After failed force push there should be option of force push.

### Expected behavior
Force push option should be available if force push fails.

### Actual behavior
Force push disappears and Pull Origin appears.

### Screenshot
![Screenshot from 2021-10-17 20-45-35](https://user-images.githubusercontent.com/30789544/137632591-c1975bf1-3341-46cf-a713-d3529c6e5f4e.png)

**Comment by shiftkey** [comment]
Closing this out due to inactivty. As I suspect this is not a Linux-specific issue, I think this is worth reporting to the main project if it's spotted again...
