### ISSUE TITLE
GitHub Desktop Translation to PT-BR for Windows and Linux

### ISSUE THREAD

**Issue by Gustavocgsg** [shiftkey/desktop#615]
Hi Brendan, My name is Gustavo, I'm from Brazil and would like to collaborate with a possible PT-BR translation of GitHub Desktop, would it be possible?

If yes... could you tell me which projectp files are intended to accomplish this task?

Thank you in advance for your attention.

**Comment by shiftkey** [comment]
@Gustavocgsg at the moment I don't have the bandwidth to support translation works. This needs to be handled by the main project, but sadly they're also in the same situation: https://github.com/desktop/desktop/issues/8289#issuecomment-532742883

**Comment by Gustavocgsg** [comment]
@shiftkey, I understand, anyway, if there is a possibility in the not-too-distant future, please don't hesitate to get in touch, it will be a pleasure to be able to contribute in some way to help make the project more accessible around the world! I would like to thank you on behalf of the Brazileria community for contributing to this version on Linux, and making the job of running Git command a little easier and more intuitive!

**Comment by shiftkey** [comment]
At the moment I think this will need co-ordination with the upstream project, and tracking this request here doesn't reflect where the work needs to happen. This could be a big lift to support any sort of localization in the UI, and I don't have the bandwidth to work on this either.

Given how quite this has been, I'm going to close this out for now.
