### ISSUE TITLE
Unable to login with appimage

### ISSUE THREAD

**Issue by SpookyKipper** [shiftkey/desktop#616]
Hi,
So basically I've downloaded the latest github appimage, after i launched the app, i tried to login, after i logged in with my browser, it appears to open xdg-open, i opened it, and it didn't redirect me to the github app. Thanks
Spooky Kipper

**Comment by Mrlinkwii** [comment]
i think with the  appimage you have to use the  'open with' option in the xdg-open and then  choose the appimage  ,

**Comment by JACGWD** [comment]
I have this issue as well. There is no prompt to choose the appimage (Pop!_OS 21.04, Firefox and Brave).

**Comment by ghost** [comment]
Same here, same issue which has been described by @SpookyKipper 

Moreover: even if his failed, Github showed this program as authorized in https://github.com/settings/applications which is interesting.

**Comment by GoudronViande24** [comment]
Same here. Pop!_OS 21.04.

**Comment by shiftkey** [comment]
A few questions to help guide the investigation:

 - what version of the package are you using?
 - which installer did you use?
 - any interesting log files you can share? `~/.config/GitHub Desktop/logs/` is where there are stored, organized by date

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of additional information.

Please open a fresh issue if you are still encountering this problem.
