### ISSUE TITLE
can not clone other team`s project 

### ISSUE THREAD

**Issue by fengchao988** [shiftkey/desktop#618]
### Describe the bug
Write a clear and concise description of what the bug is.

using GitHubDesktop-linux-2.9.4-linux1.AppImage

### Version 
![image](https://user-images.githubusercontent.com/73015088/139012881-683b1628-c147-4db6-b416-7fbdd1643204.png)

this is my githu.com shows info
![image](https://user-images.githubusercontent.com/73015088/139013155-2f064928-0501-4237-839c-2c1b073e2779.png)

but in desktop i only see to my creat`s pronject
![image](https://user-images.githubusercontent.com/73015088/139013349-a88ce32d-3635-4bee-a66a-5b72b152a832.png)

**Comment by shiftkey** [comment]
This is a [known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization) for the Linux build:

> ### I cannot access repositories under my organization
>
>The GitHub Desktop application is an OAuth application, but this fork does not
have the same permissions as the app does on Windows and macOS, which manifests
in a couple of different ways:
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a
>    generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access
> restrictions" enabled, which blocks the GitHub Desktop development app that is
> used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)
> to the GitHub Desktop development app.

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 has more context
