### ISSUE TITLE
wsl account authorization 

### ISSUE THREAD

**Issue by 515orestis** [shiftkey/desktop#623]
### Describe the bug
after installing github-desktop via 
$ wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
$ sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
$ sudo apt-get update

can not authorize my account via any browser I am having this error 

Unknown or unsupported transport “disabled” for address “disabled:”

### Version & OS
windows 11
debian 10 wsl2

**Comment by 515orestis** [comment]
> Write a clear and concise description of what the bug is.

**Comment by 515orestis** [comment]
after updated with the following commands



sudo wget https://github.com/shiftkey/desktop/releases/download/release-2.9.4-linux1/GitHubDesktop-linux-2.9.4-linux1.deb
### Uncomment below line if you have not installed gdebi-core before
sudo apt-get install gdebi-core 
sudo gdebi GitHubDesktop-linux-2.9.4-linux1.deb

same behavior

**Comment by shiftkey** [comment]
> can not authorize my account via any browser I am having this error
>
> Unknown or unsupported transport “disabled” for address “disabled:”

Please check that you have `gnome-keyring` installed, but also refer to this earlier issue as there were some instructions here that may be helpful: https://github.com/shiftkey/desktop/issues/225#issuecomment-596221082

**Comment by 515orestis** [comment]
> > can not authorize my account via any browser I am having this error
> > Unknown or unsupported transport “disabled” for address “disabled:”
> 
> Please check that you have `gnome-keyring` installed, but also refer to this earlier issue as there were some instructions here that may be helpful: [#225 (comment)](https://github.com/shiftkey/desktop/issues/225#issuecomment-596221082)

hi, for some reason didn't find this thread
gnome-keyring is already the newest version (3.28.2-5)

dbus-monitor result

`signal time=1636331638.262023 sender=org.freedesktop.DBus -> destination=:1.2 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.2"
signal time=1636331638.262068 sender=org.freedesktop.DBus -> destination=:1.2 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.2"
method call time=1636331682.181077 sender=:1.3 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1636331682.181118 sender=org.freedesktop.DBus -> destination=:1.3 serial=1 reply_serial=1
   string ":1.3"
signal time=1636331682.181139 sender=org.freedesktop.DBus -> destination=(null destination) serial=5 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.3"
   string ""
   string ":1.3"
signal time=1636331682.181175 sender=org.freedesktop.DBus -> destination=:1.3 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.3"
method call time=1636331682.181225 sender=:1.3 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.gnome.SessionManager"
error time=1636331682.181255 sender=org.freedesktop.DBus -> destination=:1.3 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=2
   string "Could not get owner of name 'org.gnome.SessionManager': no such name"
signal time=1636331682.181360 sender=org.freedesktop.DBus -> destination=:1.3 serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.3"
signal time=1636331682.181402 sender=org.freedesktop.DBus -> destination=(null destination) serial=7 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.3"
   string ":1.3"
   string ""
method call time=1636331682.197536 sender=:1.4 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1636331682.197582 sender=org.freedesktop.DBus -> destination=:1.4 serial=1 reply_serial=1
   string ":1.4"
signal time=1636331682.197666 sender=org.freedesktop.DBus -> destination=(null destination) serial=8 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.4"
   string ""
   string ":1.4"
signal time=1636331682.197794 sender=org.freedesktop.DBus -> destination=:1.4 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.4"
method call time=1636331682.197852 sender=:1.4 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.gnome.SessionManager"
error time=1636331682.197900 sender=org.freedesktop.DBus -> destination=:1.4 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=2
   string "Could not get owner of name 'org.gnome.SessionManager': no such name"
signal time=1636331682.197961 sender=org.freedesktop.DBus -> destination=:1.4 serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.4"
signal time=1636331682.197992 sender=org.freedesktop.DBus -> destination=(null destination) serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.4"
   string ":1.4"
   string ""
method call time=1636331796.102726 sender=:1.5 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1636331796.102769 sender=org.freedesktop.DBus -> destination=:1.5 serial=1 reply_serial=1
   string ":1.5"
signal time=1636331796.102778 sender=org.freedesktop.DBus -> destination=(null destination) serial=11 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.5"
   string ""
   string ":1.5"
signal time=1636331796.102785 sender=org.freedesktop.DBus -> destination=:1.5 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.5"
method call time=1636331796.102805 sender=:1.5 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.gnome.SessionManager"
error time=1636331796.102861 sender=org.freedesktop.DBus -> destination=:1.5 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=2
   string "Could not get owner of name 'org.gnome.SessionManager': no such name"
signal time=1636331796.102960 sender=org.freedesktop.DBus -> destination=:1.5 serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.5"
signal time=1636331796.102995 sender=org.freedesktop.DBus -> destination=(null destination) serial=13 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.5"
   string ":1.5"
   string ""
method call time=1636331796.118992 sender=:1.6 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1636331796.119029 sender=org.freedesktop.DBus -> destination=:1.6 serial=1 reply_serial=1
   string ":1.6"
signal time=1636331796.119037 sender=org.freedesktop.DBus -> destination=(null destination) serial=14 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.6"
   string ""
   string ":1.6"
signal time=1636331796.119044 sender=org.freedesktop.DBus -> destination=:1.6 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.6"
method call time=1636331796.119065 sender=:1.6 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.gnome.SessionManager"
error time=1636331796.119098 sender=org.freedesktop.DBus -> destination=:1.6 error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=2
   string "Could not get owner of name 'org.gnome.SessionManager': no such name"
signal time=1636331796.119268 sender=org.freedesktop.DBus -> destination=:1.6 serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.6"
signal time=1636331796.119303 sender=org.freedesktop.DBus -> destination=(null destination) serial=16 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.6"
   string ":1.6"
   string ""
`

**Comment by mariamatz** [comment]
Same behaviour here, every time I try to log in, I get this:
![image](https://user-images.githubusercontent.com/25902414/142922876-becd7792-6918-428c-a972-6a32535048f9.png)

Version: 2.9.4-linux1

Any updates?

**Comment by shiftkey** [comment]
> `error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=2 string "Could not get owner of name 'org.gnome.SessionManager': no such name" `

This to me seems to be the underlying error, but I'm not familiar enough with WSL (nor have a working Windows setup) to advise how to get this working currently.

**Comment by 515orestis** [comment]
`dbus-launch  github --exit-with-x11`
seems to run

**Comment by 515orestis** [comment]
> > `error_name=org.freedesktop.DBus.Error.NameHasNoOwner reply_serial=2 string "Could not get owner of name 'org.gnome.SessionManager': no such name" `
> 
> This to me seems to be the underlying error, but I'm not familiar enough with WSL (nor have a working Windows setup) to advise how to get this working currently.

`dbus-launch github --exit-with-x11` works but after closing the window and rerun the command i am again logged out
and after a few seconds, i am getting the following
![github](https://user-images.githubusercontent.com/48755181/143142750-eddc98f0-a7be-4d57-8ccd-b294ca0a2d27.jpg)


I need to restart WSL and log in via browser again

**Comment by shiftkey** [comment]
At the moment I'm not sure what my options are for handling this, and switching away from `libsecret` to something else isn't something I plan to support, so I'm going to close this out. Thanks for the details @515orestis
