### ISSUE TITLE
packagecloud not up to date

### ISSUE THREAD

**Issue by jagiella** [shiftkey/desktop#624]
Following your README I added the packagecloud-apt-repo (packagecloud.io/shiftkey/desktop/any/ any main) to receive always the newest version of this excellent linux port (by the way!).
Those last months I always updated to newer versions directly by downloading the respective deb files of new releases from github as they never get updated through apt-get.

Today (in detective mode) I checked out the https://packagecloud.io/shiftkey/desktop website to investigate why apt-get seems to be always behind in available versions and a saw that the **automatic upload of deb files seems to have stopped on April 28th with v2.8.0**. 

Is this on purpose? If so, a testing repo would be nice including all cutting edge release (available on github) as well.

Cheers and keep up the excellent work for the linux community!!!
Nick

**Comment by markymarkfunky** [comment]
Don't know if this is for me but would appreciate help if it is for me

**Comment by K0-RR** [comment]
If packagecloud is no longer in use it should be removed from the readme. Flatpak link could be added in its place.

**Comment by pietryszak** [comment]
@shiftkey And so, what. What is the solution of downloading not newest version.

**Comment by shiftkey** [comment]
Thanks for the reminder on this. I have a script that handles the updating, but I've been busy and burnt out and so the release pipeline had stopped when the release was published to GitHub.

As part of catching up with upstream updates I've published 2.9.6 to PackageCloud again.

> And so, what. What is the solution of downloading not newest version.

The Releases tab on this repository continues to be the canonical source of packages: https://github.com/shiftkey/desktop/releases
