### ISSUE TITLE
Fedora download ver.2.8.0 insted latest

### ISSUE THREAD

**Issue by pietryszak** [shiftkey/desktop#633]
### Describe the bug
When use a script to install app in fedora 35 a version 2.8.0 is installed instead latest 2.9.4. rc1

### Steps to reproduce the behavior

1.
 ```
sudo rpm --import https://packagecloud.io/shiftkey/desktop/gpgkey
sudo sh -c 'echo -e "[shiftkey]\nname=GitHub Desktop\nbaseurl=https://packagecloud.io/shiftkey/desktop/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/shiftkey/desktop/gpgkey" > /etc/yum.repos.d/shiftkey-desktop.repo'
```

2.`sudo dnf install github-desktop`
3. github-desktop-2.8.0.linux1-1.x86_64 is installed instead GitHubDesktop-linux-2.9.4-linux1.rpm

### Expected behavior

Newest version is installed GitHubDesktop-linux-2.9.4-linux1.rpm

### Actual behavior

Old 2.8.0 version in installed instead newest

### Screenshots
![image](https://user-images.githubusercontent.com/45850093/145817433-6d412bd2-18bb-42ee-bc9f-a9eb441c84d5.png)

**Comment by shiftkey** [comment]
Please follow along with #624
