### ISSUE TITLE
Open in Code/Vscode/Visual Studio Code via context menu on repositories

### ISSUE THREAD

**Issue by philippthiele** [shiftkey/desktop#635]
### Describe the feature or problem you’d like to solve
On Windows, the client supports opening a repository from itself in vscode via context menu, meaning there is an entry here
![image](https://user-images.githubusercontent.com/1737722/146329136-aab9f137-63c7-4837-b929-f66cd0ece849.png)

Same thing for the "Repository" menu item at the top
![image](https://user-images.githubusercontent.com/1737722/146330915-c812b4a7-07e1-4d18-844c-1d815540710c.png)

### Proposed solution
add an entry for vscode

Also just wanted to say thank you very much for this port, I love this client from an overview & feature point of view and the port makes it possible to use it everywhere

**Comment by shiftkey** [comment]
We detect a number of VS Code installs:

https://github.com/shiftkey/desktop/blob/6b189255ca4a389576932317e7c2638dea62826e/app/src/lib/editors/linux.ts#L27-L42

Please check the **File | Options** menu as the **Integrations** tab should let you choose a different editor, based on what's available on your machine.

<img width="775" src="https://user-images.githubusercontent.com/359239/146482094-605f3160-0063-444b-b10f-185116dbae12.png">

This screenshot is from macOS so there's some minor differences, but hopefully that helps find the setting!

**Comment by philippthiele** [comment]
oh great, I wasn't aware that that is a setting that can be changed. Thank you very much!
