### ISSUE TITLE
Repo returns error 429

### ISSUE THREAD

**Issue by rgoubet** [shiftkey/desktop#640]
On updating with `apt`:

```
Ign :38 https://packagecloud.io/shiftkey/desktop/any any InRelease
Err :38 https://packagecloud.io/shiftkey/desktop/any any InRelease                                              
  429  Too Many Requests [IP : 52.52.239.191 443]
```

**Comment by shiftkey** [comment]
Yep, it's another another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
It's costing me USD $150 per month to do this hosting and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month (today!), and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
