### ISSUE TITLE
Authentication fail

### ISSUE THREAD

**Issue by Operaconga14** [shiftkey/desktop#641]
I tried cloning an organization i joined with github desktop from my ubuntu 20.4.03 but it gives me error and ask for my username and password which i did and it gives me error authentication fail and my account can't be connected to github.com

**Comment by shiftkey** [comment]
This is a [known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization) for the Linux build:

> ### I cannot access repositories under my organization
>
>The GitHub Desktop application is an OAuth application, but this fork does not
have the same permissions as the app does on Windows and macOS, which manifests
in a couple of different ways:
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a
>    generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access
> restrictions" enabled, which blocks the GitHub Desktop development app that is
> used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)
> to the GitHub Desktop development app.

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 has more context
