### ISSUE TITLE
error in login in to github desktop

### ISSUE THREAD

**Issue by mmsaeed509** [shiftkey/desktop#642]
When logging in, this error appears
OS Garuda Linux
```
The name org.freedesktop.secrets was not provided by any .service files
```
![Screenshot_GitHub Desktop_1](https://user-images.githubusercontent.com/62524855/147580351-b58df44c-cc1b-49d1-b165-24fe79e5dd5e.png)

**Comment by shiftkey** [comment]
@mmsaeed509 please add some extra details to the issue template:

 - which version of the app you are using
 - which installer you are using
 - do you also have `gnome-keyring` installed or some credential provider that is compatible with `libsecret`?

**Comment by mmsaeed509** [comment]
@shiftkey 
I installed it via command line  `sudo pacman -S github-desktop`
package mangers
- pacman
- Octopi
version 2.9.6-linux(x64)

![Screenshot_GitHub Desktop_1](https://user-images.githubusercontent.com/62524855/147972185-7ae7fa21-3c42-4691-9786-4631d4687d31.png)

**Comment by DiedByDisgust** [comment]
Same error when login

### Description

After login returns error popup 

### Version

    GitHub Desktop: 2.9.6-linux1 (x64)
    Operating system: Archlinux x86_64 kernel 5.16.1-arch1-1
    
    Edit: Also Wayland... i think this is a Gnome-keyring/Wayland Issue

**Comment by mwt** [comment]
I believe pacman will accept any of

```
keepassxc-kde-fix, gnome-keyring-git, pass-secrets-git, bitw-git, keepassxc-git, kwallet-secrets, gnome-keyring, keepassxc
```

The one you have might have a compatibility issue, or perhaps it didn't install any. The best bet is to install `gnome-keyring`.

**Comment by AnasAttaullah** [comment]
> I believe pacman will accept any of
> 
> ```
> keepassxc-kde-fix, gnome-keyring-git, pass-secrets-git, bitw-git, keepassxc-git, kwallet-secrets, gnome-keyring, keepassxc
> ```
> 
> The one you have might have a compatibility issue, or perhaps it didn't install any. The best bet is to install `gnome-keyring`.

This works.Thank you.

**Comment by shiftkey** [comment]
I'm going to close this out for now as there's nothing actionable I can do here, but if you have any suggestions for better packaging of the app on Arch I recommend submitting to the `PKGBUILD` here https://github.com/alerque/aur/tree/master/github-desktop
