### ISSUE TITLE
I cannot authorise the application

### ISSUE THREAD

**Issue by antonellocaroli** [shiftkey/desktop#643]
### Describe the bug
The application does not normally start, I get the following error:

`github-desktop %U

xdg-settings: default-url-scheme-handler not implemented for xfce
xdg-settings: default-url-scheme-handler not implemented for xfce
(node:12374) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[12374:1229/132546.614030:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Rilevato trace/breakpoint`

but I can start it with
**github-desktop --in-process-gpu**

but I cannot authorise the application (chrome):

![image](https://user-images.githubusercontent.com/11161093/147658711-e783b092-b899-484f-a26e-8da425c15fe3.png)

![image](https://user-images.githubusercontent.com/11161093/147658755-abc6c034-2932-4f3f-85ca-c416ba6d0481.png)

_cannot open url:
the specified position is not supported_

### Version & OS
2.9.6 
Gentoo

**Comment by antonellocaroli** [comment]
ok,
I do not know how and why but I solved the problem of authorization....

but the problem remains that to start it I have to launch it with the command

`gihub-desktop --in-process-gpu`

or

`github-desktop --no-sandbox`

**Comment by thesmallcreeper** [comment]
Yeah, I had to use `--no-sandbox` on .desktop in order to launch github-desktop but from my understanding this argument blocks "Open link with" functionality. So I launched github-desktop with `--no-sandbox`, while opened I removed `--no-sandbox` from .desktop and saved (also exit from sudoedit), then opened authorize link with github-desktop successfully and afterward I added `--no-sandbox` back for feature launches.

**Comment by shiftkey** [comment]
@antonellocaroli thanks for the report!

> but the problem remains that to start it I have to launch it with the command
> 
> `gihub-desktop --in-process-gpu`
> 
> or
> 
> `github-desktop --no-sandbox`

Sadly this is a limitation of the Electron version currently used in the app, and #604 is the tracking issue for that work. This requires us to update to Electron 13 with support for newer `glibc` versions, so I'm keeping an eye on the upstream project as I think they're planning to do that in the coming weeks.

Please follow along with that issue.
