### ISSUE TITLE
Cant install due to PackageCloud being suspended

### ISSUE THREAD

**Issue by vil** [shiftkey/desktop#644]
### Operating System/Distribution

Fedora (Latest version)

### Installer

Which version of the app?
latest

Which installer type?
rpm

### What happened?
Getting this error when doing `sudo rpm --import https://packagecloud.io/shiftkey/desktop/gpgkey` :

`curl: (22) The requested URL returned error: 429
error: https://packagecloud.io/shiftkey/desktop/gpgkey: import read failed(2).`

**Comment by shiftkey** [comment]
Yep, it's another another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.

It's costing me USD $150 per month to do this hosting and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.

See #278 for more context and discussion.

**Comment by samstride** [comment]
@shiftkey , Hi, I can sponsor the full amount of $150/month for a duration of 6 months. I don't see the value of $150 on the sponsor page so if you could please add it, I will sort it out.

I understand that the $150/month will only allow a bandwidth of 200GB/month (150+50) ? What happens if we need more bandwidth?

**Comment by mwt** [comment]
I would like to help by mirroring the repos. Perhaps others can contribute by doing the same?

I can mirror the deb repository from shiftkey or something else using [`apt-mirror`](https://apt-mirror.github.io/). I don't know anything about redhat repos, but I imagine there's a way to do it while keeping the upstream signature untouched.

I already use `apt-mirror` to mirror the repos for termux. So, I could just add the shiftkey repo to the end of the config file. I think I'll set this up and I'll offer it for testing when your bw resets.

Update: Posted instructions in the mentioned thread. The url <https://mirror.mwt.me/ghd/deb/> is a drop-in replacement for the main deb repo.

**Comment by carsten-riedel** [comment]
> Yep, it's another another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to do this hosting and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.
> 
> The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
> 
> See #278 for more context and discussion.

Hm i am so lazy and i don't like to mess up with keys, build me a script cause there other .deb files on my list. Need to enhance it with hash and version check.
```
wget -q --no-cache --no-cookies --no-check-certificate -O - https://raw.githubusercontent.com/NaitWatch/uconf/main/github-install.sh | bash -s - "https://github.com/shiftkey/desktop/releases/latest" "deb$" "github-desktop"
```

**Comment by mwt** [comment]
> Hm i am so lazy and i don't like to mess up with keys, build me a script cause there other .deb files on my list. 

If this is about the mirror I mentioned you can just do:

```sh
sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
```

This only affects the one repo and does not install any additional keys (still uses the original from packagecloud). If you don't have the key, you can get it with

```sh
wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
```

**Comment by shiftkey** [comment]
Closing this out as we've merged https://github.com/shiftkey/desktop/pull/667 to document this alternative feed
