### ISSUE TITLE
I can't find the repositories in my work organizations

### ISSUE THREAD

**Issue by HusseinMoHu** [shiftkey/desktop#646]
### Work-account | Work-organization
When I sign in with my personal account all thing works fine, but when I sign in with my work-account the repositories in my work organizations don't appear, and this message "Looks like there are no repositories for 'my-username' on github.com refresh this list if you've created a repository recently" shown.

Thanks

**Comment by segefjord** [comment]
I can confirm, i also get this exact same bug. Was about to report.

**Comment by hayd1n** [comment]
I can confirm, i also get this exact same bug. Was about to report.

**Comment by superdioz** [comment]
same problem here, on ubuntu 21-10, i''ve tried 2.6.6 and 2.9.3, login/logout an any other workaround, no solution so far.

**Comment by shiftkey** [comment]
This is a known limitation of this fork: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization


> 
> ### I cannot access repositories under my organization
> 
> The GitHub Desktop application is an OAuth application, but this fork does not have the same permissions as the app does on Windows and macOS, which manifests in a couple of different ways:
> 
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access restrictions" enabled, which blocks the GitHub Desktop development app that is used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization) to the GitHub Desktop development app.
>
