### ISSUE TITLE
Error when clone repository after install

### ISSUE THREAD

**Issue by azur-wolve** [shiftkey/desktop#648]
After install, do the "account confirmation through Web Browser, and try to _"Clone a Repository from the Internet"_

![github_app_startup_error](https://user-images.githubusercontent.com/88264884/151082954-977e70e1-4fcb-4df0-b079-afbd299aa440.png)

Linux Debian 10

CONTEXT:
Have followed installation from here:
https://www.vitainbeta.org/2020/06/24/installing-github-desktop-linux/

```
wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -

sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'

sudo apt-get update

sudo apt-get install github-desktop
```

**Comment by shiftkey** [comment]
I've seen some issues with Debian setup being more restricted than Ubuntu, with this error bubbling up in different way:

 - https://github.com/netblue30/firejail/issues/2407
 - https://community.parrotsec.org/t/chromium-dont-open/2100/3

I'm not familiar enough with this side of dbus to guess what the setup issue might be, but there's a `--no-sandbox` flag that can be passed to `github-desktop` that changes this behaviour. I suspect you'll get some different behaviour but I'm not sure if that'll fix this issue...

**Comment by azur-wolve** [comment]
@shiftkey thanks for answer
Solved the issue weeks ago after upgrading to Debian 11, the dependency resolver of my Desktop Environment handled it, but also did some stuff, so not pretty sure on what happened and have not it fresh so don't remember well.

**Comment by shiftkey** [comment]
Thanks for following up @KiwwiPity. 

I'm going to close this out as I don't think there's much we can do within the app about this sort of issue...
