### ISSUE TITLE
Unable to sign in to GitHub Enterprise from GitHub Desktop

### ISSUE THREAD

**Issue by marellanoq** [shiftkey/desktop#649]
### Description
The Desktop client for Linux, won't pass the validation of the user into GitHub Enterprise through the web browser hence it does not establish the connection.  The issue is present with any web browser.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

Version: 2.9.6-linux1 (x64)
Operating System: Ubuntu 20.04.3 LTS
Kernel: x86_64 Linux 5.10.0-1057-oem

### Steps to reproduce the behavior

1. Go to 'File -> Options'
2. Click on 'Accounts -> GitHub Enterprise -> Sign in'
3. In the opened window, fill the Enterprise address required

### Expected behavior

Once logged in through the browser, control should return to GitHub Desktop with the corresponding login validated.

### Actual behavior

No matter the web browser used , the control never returns to GitHub Desktop and the "Sign in using your bropwser" window remains opened indefinitely.

### Screenshots

![Flameshot_2022-01-26_16-49-35_35](https://user-images.githubusercontent.com/18318336/151236780-e48fb24f-0626-42f0-ac37-0a526aa4d23d.png)

### Logs

2022-01-26T19:47:27.911Z - info: [ui] [AppStore] loading 2 repositories from store
2022-01-26T19:47:28.260Z - info: [ui] launching: 2.9.6-linux1 (Linux 5.10.0-1057-oem)
2022-01-26T19:47:28.260Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2022-01-26T19:48:08.317Z - info: [ui] [SignInStore] initializing OAuth flow
2022-01-26T19:48:08.320Z - info: [main] opening in browser: https://github.hpe.com/login/oauth/authorize?client_id=--------------------&scope=repo%20user&state=676e60e4-228a-4645-a29d-f26d8fcac8af
2022-01-26T19:49:42.374Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.1s of which 0.0s paused, total 0.1s

### Additional context
Before the installation of this version I cleaned all the system from previous version and installed as new.

**Comment by guidezpl** [comment]
+1

**Comment by Chiayen0503** [comment]
+1

**Comment by Ibrahmm** [comment]
+1

**Comment by shiftkey** [comment]
GitHub Enterprise is not supported due to the dependency on OAuth to authenticate - https://github.com/shiftkey/desktop/issues/229#issuecomment-604639903

> > What you suggest to do then? On windows and Mac is working properly.
> 
> This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in [desktop#1525](https://github.com/desktop/desktop/issues/1525) (please upvote if you care) but #72 is tracking this known limitation.
> 
> As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.
> 
> Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.
> 
> The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.

Please follow along with #72 which is the underlying reason this doesn't work currently.
