### ISSUE TITLE
Custom periodic fetch interval

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#651]
### Describe the feature or problem you’d like to solve

Custom periodic fetch interval

### Proposed solution

Add the option to customise the interval for the automatic fetch option

### Additional context

Currently there is a periodic fetch option but no interval specified

**Comment by shiftkey** [comment]
Please submit feature requests that aren't Linux-specific to the main project. https://github.com/desktop/desktop/issues/8551 has some earlier discussion and in particular https://github.com/desktop/desktop/issues/8551#issuecomment-547878626 has some context about why it's not currently configurable:

> The interval with which we refresh data from the server varies depending on what type of host we're communicating with (GitHub.com, GitHub Enterprise, or a third-party host) and there are also mechanisms in place that allow us to back of clients in case we're encountering availability concerns.
> 
> > (For the record, I would like to fetch every 5 mins.)
> 
> As a data point here, background refreshing of the currently selected repository when working with GitHub.com is normally done every five minutes.
