### ISSUE TITLE
Fedora 35 GPU process isn't useable error on github-desktop 2.9.6

### ISSUE THREAD

**Issue by joshwhieb** [shiftkey/desktop#653]
Not sure if this has been fixed on master but upon running the 2.9.6 github-desktop on fedora 35 it runs into an error similar to this issue on another electron app. - https://github.com/marktext/marktext/issues/2675

According to the electron thread it should be resolved (electron 13?) as it's an issue with the latest glibc.  I can get around it by running it as follows:  $ github-desktop --disable-gpu-sandbox

**Error message**
```
[...]$ github-desktop
(node:284495) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
**[284495:0204/173337.070877:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.**
Trace/breakpoint trap (core dumped)
```
**Running with the workaround**
```
[...]$ github-desktop --disable-gpu-sandbox
(node:284843) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
error: [ui] Error reporting stats:
TypeError: Failed to fetch

```

**Comment by shiftkey** [comment]
Please follow along with the previous discussion #604 - it looks like the upstream project has upgraded to Electron 14 on the `development` branch so I'll look at testing and getting ready for when they publish the next release...
