### ISSUE TITLE
429  Too Many Requests

### ISSUE THREAD

**Issue by crazyn2** [shiftkey/desktop#659]
### Operating System/Distribution

Which distribution of Linux are you using?
Ubuntu 20.04 LTS amd64

### Installer

Which version of the app?
Which installer type?
just configurate the environment with steps provided
### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.
```sh
$ apt update
Err:8 https://packagecloud.io/shiftkey/desktop/any any InRelease               
  429  Too Many Requests [IP: 52.52.85.114 443]
```

**Comment by mwt** [comment]
From Shiftkey:

> Yep, it's another another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to do this hosting and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.
> 
> The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
> 
> See #278 for more context and discussion.

I made a mirror to try to help with this problem. See #647 for instructions on using the mirror. The more mirror users, the longer it will take to go bust each month.

**Note:** 165GB of bandwidth in a month with no release! That's a lot of new users.

**Comment by crazyn2** [comment]
Thanks for your rely
