### ISSUE TITLE
Cant install in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by ejgutierrez74** [shiftkey/desktop#66]
## Version

* GitHub Desktop:

* Operating system: Ubuntu 18.04.1

### Expected Behavior
<!-- Version 1.4.0 installed

### Actual Behavior
<!-- Nothing

**Comment by shiftkey** [comment]
@ejgutierrez74 Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ejgutierrez74** [comment]
Thanks
## Description

I want to install de .deb package from version 1.4.0 using Software Center in Ubuntu 18.04.1 ( as i did with 1.3.5 and 1.4.0v2

## Version

* GitHub Desktop: 1.4.0

* Operating system: Ubuntu 18.04.1


## Steps to Reproduce


### Expected Behavior

1- Download and install .deb using Software Center in Ubuntu 18.04.1.

### Actual Behavior

Doesnt install.

## Additional Information


### Logs

**Comment by shiftkey** [comment]
>  as i did with 1.3.5 and 1.4.0v2

[1.4.0 RC 2](https://github.com/shiftkey/desktop/releases/tag/release-1.4.0-linux2) is the later release (the website is sorting the tags in a different way), which addresses a packaging issue with newer Ubuntu distributions that we spotted in #60

> Doesnt install.

I need more information than this. Are you able to use the command line interface to install, like we did in #60, and confirm that it's the same issue?

**Comment by asianjakepaul** [comment]
Have you installed the dependencies?
```shell
sudo dpkg -i package.deb
```
followed by:
```shell
sudo apt install -f
```

**Comment by ejgutierrez74** [comment]
No, but as @shiftkey pointed out RC2 was a newer release and problem was solved. Also yesterday i have updated to latest version RC3 and no problems. So seems a error in 1.4.0RC solved.
