### ISSUE TITLE
Integrate external editor flags

### ISSUE THREAD

**Issue by red5h4d0w** [shiftkey/desktop#665]
### Describe the feature or problem you’d like to solve

Not sure if this belongs upstream or not...

Personally I'd like the option to launch external editors with flags.
The best use case scenario I can think of is launching an external editor on wayland with fractional scaling. 
For example: 
Editors based on electron need to be called with `editor --ozone-platform=wayland` instead of `editor` to run in wayland mode (not running in wayland mode makes the editor look blurry)

### Proposed solution

A proposed solution is either to add in the options a field for flags (under the preferred editor dropdown) or to have the ability to add custom editor config to the dropdown.

Another solution, would be to add another property named "flags" to entries in `/src/lib/editors/linux.ts` and then add more complex entries. But I feel that may add clutter to the dropdown and if every config would be added there, it would be horrendous, so idk...

### Additional context

Essential to make the open in editor button usable on fractional scaling displays. Also useful in general.

**Comment by shiftkey** [comment]
Rather than adding support for passing in arbitrary command line flags I wonder if there's a different approach here that we could do without needing to support anything in the UI. The approach I keep thinking about is:

 - we already know the set of editors [we need to support](https://github.com/shiftkey/desktop/blob/476f157f65a7f3aa33b8de70975d5bbe4ae8a739/app/src/lib/editors/linux.ts#L18-L78)
 - we have the ability to control how [the editor is launched](https://github.com/shiftkey/desktop/blob/476f157f65a7f3aa33b8de70975d5bbe4ae8a739/app/src/lib/helpers/linux.ts#L81-L105)
 - can we detect if we're running in a Wayland DE and then merge that context with how the editor is spawned?


A rough patch of all the touch points follow, I haven't tested this code at all:

```diff
diff --git a/app/src/lib/editors/found-editor.ts b/app/src/lib/editors/found-editor.ts
index c6a54597c..5d6f67874 100644
--- a/app/src/lib/editors/found-editor.ts
+++ b/app/src/lib/editors/found-editor.ts
@@ -8,4 +8,7 @@ export interface IFoundEditor<T> {
    * editors as their launch programs end in `.cmd`
    */
   readonly usesShell?: boolean
+
+  /** Opt-in this editor to pass in `--ozone-platform=wayland` when spawning the editor */
+  readonly supportsWayland?: boolean
 }
diff --git a/app/src/lib/editors/launch.ts b/app/src/lib/editors/launch.ts
index 45cbfd1b3..d6f487a4a 100644
--- a/app/src/lib/editors/launch.ts
+++ b/app/src/lib/editors/launch.ts
@@ -54,7 +54,7 @@ export async function launchExternalEditor(
     // for us, we only need the path to the editor .app folder.
     spawn('open', ['-a', editorPath, fullPath], opts)
   } else if (__LINUX__) {
-    spawnEditor(editorPath, fullPath, opts)
+    spawnEditor(editor, fullPath, opts)
   } else {
     spawn(editorPath, [fullPath], opts)
   }
diff --git a/app/src/lib/editors/linux.ts b/app/src/lib/editors/linux.ts
index 5abd1fcca..e71edb0d3 100644
--- a/app/src/lib/editors/linux.ts
+++ b/app/src/lib/editors/linux.ts
@@ -9,6 +9,9 @@ interface ILinuxExternalEditor {
 
   /** List of possible paths where the editor's executable might be located. */
   readonly paths: string[]
+
+  /** Opt-in this editor to pass in `--ozone-platform=wayland` when spawning the editor */
+  readonly supportsWayland?: boolean
 }
 
 /**
@@ -27,6 +30,7 @@ const editors: ILinuxExternalEditor[] = [
   {
     name: 'Visual Studio Code',
     paths: ['/usr/share/code/bin/code', '/snap/bin/code', '/usr/bin/code'],
+    supportsWayland: true,
   },
   {
     name: 'Visual Studio Code (Insiders)',
@@ -95,7 +99,11 @@ export async function getAvailableEditors(): Promise<
   for (const editor of editors) {
     const path = await getAvailablePath(editor.paths)
     if (path) {
-      results.push({ editor: editor.name, path })
+      results.push({
+        editor: editor.name,
+        path,
+        supportsWayland: editor.supportsWayland,
+      })
     }
   }
 
diff --git a/app/src/lib/editors/shared.ts b/app/src/lib/editors/shared.ts
index 3375efddd..a44c388fe 100644
--- a/app/src/lib/editors/shared.ts
+++ b/app/src/lib/editors/shared.ts
@@ -14,6 +14,9 @@ export type FoundEditor = {
    * the editor requires a shell spawn to launch
    */
   usesShell?: boolean
+
+  /** Opt-in this editor to pass in `--ozone-platform=wayland` when spawning the editor */
+  readonly supportsWayland?: boolean
 }
 
 interface IErrorMetadata {
diff --git a/app/src/lib/helpers/linux.ts b/app/src/lib/helpers/linux.ts
index 5595d2a53..d026ef5a3 100644
--- a/app/src/lib/helpers/linux.ts
+++ b/app/src/lib/helpers/linux.ts
@@ -6,6 +6,7 @@ import {
   SpawnOptionsWithoutStdio,
   SpawnOptions,
 } from 'child_process'
+import { FoundEditor } from '../editors/shared'
 
 export function isFlatpakBuild() {
   return __LINUX__ && process.env.FLATPAK_HOST === '1'
@@ -86,10 +87,12 @@ export function spawnShell(
  * @param options additional options to provide to spawn function
  */
 export function spawnEditor(
-  path: string,
+  editor: FoundEditor,
   workingDirectory: string,
   options: SpawnOptions
 ): ChildProcess {
+  const { path, supportsWayland } = editor
+
   if (isFlatpakBuild()) {
     const actualpath = formatPathForFlatpak(path)
     const EscapedworkingDirectory =
@@ -100,6 +103,14 @@ export function spawnEditor(
       options
     )
   } else {
-    return spawn(path, [workingDirectory], options)
+    const isWaylandEnvironment = false // ????
+
+    const launchWayLandEditor = supportsWayland && isWaylandEnvironment
+
+    const args = launchWayLandEditor
+      ? [workingDirectory, '--ozone-platform=wayland']
+      : [workingDirectory]
+
+    return spawn(path, args, options)
   }
 }
```

It's just this last question - can we detect the environment is Wayland-compatible? - that I'm not sure about.

**Comment by red5h4d0w** [comment]
I believe this is a good way to handle it!
It is possible to look at the environment variable `$XDG_SESSION_TYPE` to know whether a user runs wayland. If it outputs `wayland` then the user runs wayland, else it is not wayland and may output `x11` or whatever the user has.

**Comment by shiftkey** [comment]
I'm inclined to close this out because I worry about deviating from the extensibility provided by the upstream project from a support perspective (I spend enough bandwidth on managing dependencies currently and am currently stuck trying to maintain compatibility with different architectures), and without someone to champion this work and figure out a solution this is not going to progress...

**Comment by red5h4d0w** [comment]
I also no longer think this is not needed, since the main goal I wanted to achieve with external flags for VSCode can be achieved by setting said flags in VSCode's config files. If still wanted, this feature should belong upstream, I think.
