### ISSUE TITLE
18.04 just libcurl4

### ISSUE THREAD

**Issue by torikulhabib** [shiftkey/desktop#67]
ubuntu 18.04 many app support suppot libcurl4
if i replace libcurl4 to libcurl3 many app to be remove
![screenshot from 2018-09-21 05-20-03](https://user-images.githubusercontent.com/26135527/45850025-a05fab80-bd5e-11e8-8bf8-c989d599687e.png)

**Comment by immackay** [comment]
See desktop/dugite-native#109. I've posted a fix there that should work for ubuntu 18.04 - you don't have to replace libcurl4, just LD_PRELOAD libcurl3.
