### ISSUE TITLE
Unable to persist received token to credential store

### ISSUE THREAD

**Issue by f-and** [shiftkey/desktop#672]
### Description

Installed from the 2.9.9 deb version and got the #666 error, as a lot of people said downgrading was the thing to do I started trying various updates but got the `Unknown or unsupported transport “disabled” for address “disabled:”` error from #225 in every version I tried (actually using the PackageCloud version), I have all the dependencies, already uninstalled and reinstalled everything countless times and am still at the same error.

### Version & OS

Version: 2.9.6 Linux RC
OS: Linux Debian 11

### Logs

Dbus monitor log says:
error time=1646753260.521898 sender=:1.7 -> destination=:1.17 error_name=org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code15 reply_serial=67
   string "The specified location is not supported"
method call time=1646753260.522548 sender=:1.17 -> destination=org.freedesktop.DBus serial=68 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.gtk.vfs.Daemon'"
method return time=1646753260.522589 sender=org.freedesktop.DBus -> destination=:1.17 serial=49 reply_serial=68
signal time=1646753260.563353 sender=:1.17 -> destination=(null destination) serial=69 path=/org/gtk/gio/DesktopAppInfo; interface=org.gtk.gio.DesktopAppInfo; member=Launched
   array of bytes "/usr/share/applications/github-desktop.desktop" + \0
   string ""
   int64 22747
   array [
      string "x-github-desktop-dev-auth://oauth?code=Deleting my auth code just in case but it appears"
   ]
   array [
      dict entry(
         string "origin-prgname"
         variant             array of bytes "firefox-esr" + \0
      )
      dict entry(
         string "origin-pid"
         variant             int64 16168
      )
   ]
   
   
If I run `github-desktop` and repeat the steps I get these messages: 
(node:1665) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 or more information
error: [ui] Error adding account 'enferd'
Error: Unknown or unsupported transport “disabled” for address “disabled:”
[2022-03-08.desktop.production.log](https://github.com/shiftkey/desktop/files/8207545/2022-03-08.desktop.production.log)

**Comment by khaneliman** [comment]
Also can't log in to github-desktop 2.9.9 from the aur on Arch Linux. 

`2022-03-10T16:47:41.457Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...`
`2022-03-10T16:47:41.918Z - info: [main] Received possible protocol arguments: 4`
`2022-03-10T16:47:41.918Z - info: [main] Processing protocol url`
`2022-03-10T16:47:41.918Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--enable-crashpad"}`

**Comment by shiftkey** [comment]
@enferd thanks for the report.

We use `libsecret` to store the token returned by the OAuth flow on your local machine, but this error suggests there's a problem with the receiving service (typical `gnome-keyring`) so we are unable to complete the login flow:

```
2022-03-08T15:36:49.180Z - info: [ui] [AppStore] adding account enferd (enferd) to store
2022-03-08T15:36:49.184Z - error: [ui] Error adding account 'enferd'
Error: Unknown or unsupported transport “disabled” for address “disabled:”
```

That dbus error report you've included is probably also related, but I don't know enough about your setup to suggest a resolution here. I guess confirming which `libsecret`-compatible tool you have running on your machine to store credentials would help here, as it may not be configured correctly...

**Comment by shiftkey** [comment]
Closing this out due to inactivity

**Comment by eylenburg** [comment]
Still doesn't work for me.
