### ISSUE TITLE
Could not sign in

### ISSUE THREAD

**Issue by tanaybhomia** [shiftkey/desktop#673]
### Describe the bug
Write a clear and concise description of what the bug is.
I have been installing and reinstalling Github on Manjaro Linux but cannot sign in. When it asks to sign in using Github.com and when I select it , 
It does not sing myself in but gets stuck in the screenshot below

### Version & OS

Manjro, gnome 41

### Expected behavior

Should sing my account it

### Actual behavior

Does not sign in

### Screenshots

![image](https://user-images.githubusercontent.com/71910027/157783419-5f9eb596-374d-4d84-bc0d-a10f7c6fdb3c.png)

**Comment by mira-miracoli** [comment]
Same for me with Fedora 35 & Gnome 41.3

**Comment by 0xflucas** [comment]
same for me w/ elementary os

**Comment by AlexisDrogoul** [comment]
Same on Ubuntu 20.04

**Comment by TheDeafCreeper** [comment]
Same on EndeavourOS KDE kernel 5.16.13-arch1-1

**Comment by Sebastiaan23** [comment]
Same for me on ArchLinux Kernel: 5.16.14-arch1-1

**Comment by mwt** [comment]
Duplicate of #666

**Comment by lvillalobos-cr** [comment]
Took me a bit to find a solution. I had to downgrade the flatpak version to 2.9.6 as per the issue comment linked below. 

I wasn't able to get it resolved from the AUR version when I was on Manjaro though.

https://github.com/shiftkey/desktop/issues/666#issuecomment-1063849724

`sudo flatpak update --commit=cfe12885e04a5e10a911f51847c194391479ba7e8389f1ffcce63bfc26eb910e io.github.shiftey.Desktop
`

OS: Fedora Linux 35 (Workstation Edition) 
Kernel: 5.16.13-200.fc35.x86_64

**Comment by lvillalobos-cr** [comment]
> Same for me with Fedora 35 & Gnome 41.3

https://github.com/shiftkey/desktop/issues/666#issuecomment-1063849724 < try this

**Comment by vanruesc** [comment]
Here's how to downgrade the AUR package: https://forum.manjaro.org/t/downgrading-github-desktop/105340

**Comment by tanaybhomia** [comment]
@vectorcr Thank you so much , Its working now and I am now able to sing in
