### ISSUE TITLE
github sign in hanging

### ISSUE THREAD

**Issue by ggrrll** [shiftkey/desktop#674]
### Describe the bug

sign in is hanging

### Version & OS

GH v. 2.9.9

### Steps to reproduce the behavior

1. Go to settings > accounts > github.com  
2. Click on  register > browser > open app 

### Actual behavior

the app hangs -- see screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/15370425/158191696-325c1366-b05b-4a26-a0b4-09da7bb8f15f.png)

### Logs

[2022-02-15.desktop.production.log](https://github.com/shiftkey/desktop/files/8245645/2022-02-15.desktop.production.log)

**Comment by K0-RR** [comment]
Try downgrading to 2.9.6.

**Comment by ggrrll** [comment]
yeah, there it seems fine indeed

**Comment by K0-RR** [comment]
If you successfully logged in you can now update to 2.9.9.

**Comment by RafaelMSantana** [comment]
Downgrading worked just like a charm, thanks

**Comment by K0-RR** [comment]
@ggrrll consider closing this duplicate as the issue is being tracked already.
