### ISSUE TITLE
Unable to complete authentication doing browser flow - `--enable-crashpad` received

### ISSUE THREAD

**Issue by laercio-carvalho** [shiftkey/desktop#677]
### Describe the feature or problem you’d like to solve

I can't sign in with browser. 
I'm trying to do login in the browser but it never finish.
![image](https://user-images.githubusercontent.com/90795100/158921185-b280524f-0f0c-47f2-af8a-ec41e5894015.png)

### Proposed solution

To have a "sign in" on the GitHub Desktop again. 
![image](https://user-images.githubusercontent.com/90795100/158921399-2207effd-34e5-43fa-ad3a-5991a7140dc9.png)

PS: I'm try to talk in english but my native language is Portuguese.

**Comment by 1vanK** [comment]
same problem 
![изображение](https://user-images.githubusercontent.com/13021826/158972357-bf526721-50ec-48ea-a2ea-b9d9c66f1f58.png)

Browser is opens and opens link with token, then offers to open the link using the application. But the application does not receive information from the browser and infinte wait

**Comment by laercio-carvalho** [comment]
> ### Describe the feature or problem you’d like to solve
> I can't sign in with browser. I'm trying to do login in the browser but it never finish. ![image](https://user-images.githubusercontent.com/90795100/158921185-b280524f-0f0c-47f2-af8a-ec41e5894015.png)
> 
> ### Proposed solution
> To have a "sign in" on the GitHub Desktop again. ![image](https://user-images.githubusercontent.com/90795100/158921399-2207effd-34e5-43fa-ad3a-5991a7140dc9.png)
> 
> PS: I'm try to talk in english but my native language is Portuguese.

**Temporarily I solved my problem using 2.9.6**

**Comment by BrahimDahmani** [comment]
+1

**Comment by joaoKuchnir** [comment]
+1

**Comment by DerGoogler** [comment]
Have the same issue with latest version

**Comment by bronnel** [comment]
I have the same issue

**Comment by vinicioslc** [comment]
I have the same issue ElementaryOS
Apparently something with url from deeplinking url
![image](https://user-images.githubusercontent.com/10997022/159166458-33e3e2a3-2500-46a5-ab6f-5e8f99242670.png)
The function that receives the oauth action its receiving unknown instead oauth with data
![image](https://user-images.githubusercontent.com/10997022/159166762-6aa26440-5fb9-458c-97ba-42cde3d192ff.png)

Version used its flatpak most recent
[AppStore] loading 0 repositories from store
install.ts:28 launching: 2.9.9-linux2 (Linux 5.13.0-35-generic)

**Comment by owocado** [comment]
I also have the same issue on latest version. I checked dev console and seeing the same warning message posted by @vinicioslc above. I installed through yay/pacman (bin version).

**Comment by miracleflame** [comment]
+1 on fresh Linux Mint

**Comment by guipaulo** [comment]
+1 i have the same issue

**Comment by nahuel3pro** [comment]
+1 on manjaro

**Comment by LarveyOfficial** [comment]
+1 popOS

**Comment by WilPermenter** [comment]
+1 

Edit: This is a known issue. The best fix for this is to  install an old version 2.9.6> and sign in on it. Once that is done then Login on that and then you can install the newer version. This Solution works on Ubuntu & Arch and probably everything else.

**Comment by pegvin** [comment]
Same issue with me:

OS: Manjaro Linux
Linux Version 5.15
GitHub Desktop Version: 2.9.9-linux2
Architecture: x64

My Log File:

```
2022-03-25T06:59:15.600Z - info: [ui] [AppStore] loading 0 repositories from store
2022-03-25T06:59:15.707Z - info: [ui] launching: 2.9.9-linux2 (Linux 5.15.28-1-MANJARO)
2022-03-25T06:59:15.707Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2022-03-25T06:59:20.021Z - info: [ui] [SignInStore] initializing OAuth flow
2022-03-25T06:59:20.024Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=ID-HIDDEN-BECAUSE-NOT-SURE-IF-ITS-SAFE-TO-SHARE
2022-03-25T06:59:22.746Z - info: [main] Received possible protocol arguments: 4
2022-03-25T06:59:22.746Z - info: [main] Processing protocol url
2022-03-25T06:59:22.748Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--enable-crashpad"}
```

**Comment by mattheusts** [comment]
+1 Archlinux using the version provided by aur 2.9.9-2.

**Comment by pegvin** [comment]
I downgraded my version to 2.9.4 and it works currently!

**Comment by shiftkey** [comment]
Apologies for the delay in digging into this - I've had many other things distracting me. I recommend downgrading in the meantime to an earlier version, as those should be unaffected.

I've dusted off my test machine and walked through the steps here and I see this `--enable-breakpad` message when I do the sign-in flow, so clearly something's broken here with how the app is being re-launched with the `2.9.9` update.

**Comment by shiftkey** [comment]
My working theory on this bug is the Electron upgrade has changed what parameters are passed through. After tracing what URL is received within the app I see a number of parameters preceding the URL parameter that we need:

```
handlePossibleProtocolLauncherArgs: ["github-desktop","--enable-crashpad","--allow-file-access-from-files","x-github-desktop-dev-auth://oauth?code=[snip]&state=[snip]"]
```

What we do currently is just pass in the item at index 1, which appears to be this line:

https://github.com/shiftkey/desktop/blob/2b48044f12de459e03025d1c669b1fa3c378f280/app/src/main-process/main.ts#L264-L266

**Comment by shiftkey** [comment]
I've backported the bugfix from #687 to the release where this was first noticed, if you want to verify this addresses the issue we were originally seeing:

 - [`2.9.9 Linux RC3`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.9-linux3)

Otherwise this is available in the latest release that contains all the upstream changes:

 - [`2.9.12 Linux RC2`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.12-linux2)

I'll leave this open for a while to confirm this has resolved the problem for users, but if you're seeing different behaviour let's move this to a fresh issue due to the noise.

**Comment by shiftkey** [comment]
@thyeun has informed me that #687 doesn't cover the cases completely, and was seeing this with the latest release:

```
2022-04-03T18:15:34.707Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"/usr/bin/github-desktop"}
```

I think https://github.com/shiftkey/desktop/pull/689 will also handle that case. Will drop a link to the new installer when it's ready.

**Comment by shiftkey** [comment]
[`2.9.12 Linux RC3`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.12-linux3) is available for testing which has an additional fix

**Comment by SpriteOvO** [comment]
@shiftkey I successfully logged in on `2.9.12 Linux RC3`, but not `RC2`. Thank you very much!

**Comment by joaoKuchnir** [comment]
Fixed for me in manjaro, thanks!

**Comment by mwt** [comment]
RC3 works for me on Ubuntu Focal.

**Comment by shiftkey** [comment]
Closing this out as resolved
