### ISSUE TITLE
Error while loading shared libraries: libcurl.so.4 on Ubuntu 16.04 Xfce 4.12

### ISSUE THREAD

**Issue by ipkpjersi** [shiftkey/desktop#68]
## Description

I cannot clone my repositories, when I attempt to do so I get an error about libcurl.so.4: cannot open shared object file: no such file or directory

## Version

* GitHub Desktop: 1.4.0-linux2 (also happened on 1.3.x and earlier) snap

* Operating system: Ubuntu 16.04 with Xfce 4.12

## Steps to Reproduce

1. `Open GitHub desktop on Ubuntu 16.04 Xfce 4.12`
2. `Click clone repository`
3. `Pick a repository to clone then click clone repository`
### Expected Behavior

I expect it to clone the repository
### Actual Behavior

I get an error about libcurl.so.4: cannot open shared object file: no such file or directory

Here is a screenshot of the error: ![](https://i.imgur.com/UFyIqF4.png)

**Comment by asianjakepaul** [comment]
I think we have to add `libcurl4-openssl-dev` to the snap stage packages, will see if I can reproduce this issue and see if my solution fixes it.

**Comment by ipkpjersi** [comment]
I am very certain I have installed the 1.4.0-linux2 snap:

![](https://i.imgur.com/7Agg78J.png)

How do I install 1.4.0-linux3 - the latest version on snapcraft is 1.4.0-linux2 as seen here: https://snapcraft.io/github-desktop

**Comment by asianjakepaul** [comment]
Here is the 1.4.0-linux3 release: https://github.com/shiftkey/desktop/releases/tag/release-1.4.0-linux3

**Comment by ipkpjersi** [comment]
`sudo snap install ~/Downloads/GitHubDesktop-linux-amd64-1.4.0-linux3.snap`

`error: cannot find signatures with metadata for snap`

**Comment by asianjakepaul** [comment]
You have to add the `--classic` and `--dangerous` flags

**Comment by ipkpjersi** [comment]
Okay it installs successfully and it works so I'll close this issue, hopefully it will work when it is added to snapcraft. If not, I'll re-open this issue.

**Comment by asianjakepaul** [comment]
@shiftkey it might have something to do with the `--dangerous` flag, I believe it does make a difference to how the install works, maybe it allows it to use system libraries outside the snap.

Also I don't know if something changed since 1.4.0-linux2 and 1.4.0-linux3.

**Comment by shiftkey** [comment]
> Also I don't know if something changed since 1.4.0-linux2 and 1.4.0-linux3.

I'm not sure what was used before for the staging packages but upstream we changed our embedded Git to use `libcurl` with OpenSSL (and not `libcurl-gnutls`) and the latest build has these staging packages defined: https://github.com/shiftkey/desktop/pull/64/files#diff-c46ab57cbefdfb467fcd9978d6fff421

**Comment by ipkpjersi** [comment]
I'm very pleased how quickly this issue was looked into and resolved. Any chance my other issue - #65 could be looked into some time? Cheers.

**Comment by shiftkey** [comment]
I've just published `1.5.0-linux1` that should address the `libcurl` issue https://github.com/shiftkey/desktop/releases/tag/release-1.5.0-linux1

> I know this issue is basically fixed and this is somewhat unrelated but @shiftkey any idea when the snapcraft store will update the snap?

@ipkpjersi I'm trying to get access to that feed so I can start publishing these builds to the channel, but I don't have an ETA on that.
