### ISSUE TITLE
Desktop does not recognize new PAT

### ISSUE THREAD

**Issue by Papa-26** [shiftkey/desktop#691]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I was informed that my PAT had expired, and I no longer could commit via Desktop. So I created a new PAT, but it doesn't let me commit either.

### Release version

 2.9.9-linux2 (x64)

### Operating system

Linux Mint 20.3 Cinnamon

### Steps to reproduce the behavior

commit in Desktop does not recognize either old (expired) or new PAT

**Comment by shiftkey** [comment]
> So I created a new PAT, but it doesn't let me commit either.

Two questions on this:

 - How are you adding the PAT to the app?
 - Can you share the log file with the details of the error?

As an aside, I'd suggest trying a newer version like [`2.19.12`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.12-linux3) where we've fixed a bug with the authentication flow that should allow you to signout and sign in again to get a new token?

**Comment by Papa-26** [comment]
have changed to version 2.19.12, and sent log file to 'shiftkey'. But it made no difference. I can commit and push directly to GitHub, but desktop does not recognize my PAT.

**Comment by shiftkey** [comment]
> have changed to version 2.19.12, and sent log file to 'shiftkey'

I've been off work for the last couple of weeks but had to check on some other things, however I couldn't find this in my inbox.

**Comment by shiftkey** [comment]
> have changed to version 2.19.12, and sent log file to 'shiftkey'.

Closing this out as I've not been able to find this log file, nor am I sure how to reproduce this locally. If you can answer these questions I'm happy to revisit and try to understand what's going wrong here...

> 
> Two questions on this:
> 
> - How are you adding the PAT to the app?
> - Can you share the log file with the details of the error?
>
