### ISSUE TITLE
404 page when logging into GitHub Enterprise

### ISSUE THREAD

**Issue by sftgunner** [shiftkey/desktop#694]
### The problem

When signing in to GitHub Enterprise Server 3.4.0, the login flow takes me to a 404 error page in my browser, rendering me unable to login. Unlike #632 the webpage opens correctly, but simply displays a 404 page rather than a login or "authorise" page.
I am using the .deb package. 

### Release version

2.9.12-linux4

### Operating system

Ubuntu 20.04, 18.04

### Steps to reproduce the behavior

1. Go to options
2. Click "Sign in" on GitHub Enterprise
3. Enter https://[hostname]
4. "Continue with browser"
5. Default browser (Firefox, in my case) opens to 404 page on GitHub Enterprise

### Log files

```
2022-04-09T11:05:36.391Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-09T11:05:36.399Z - info: [main] opening in browser: https://[hostname]/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=9ae5d240-fc62-4d11-ac6c-ba743003870f
```

**Comment by f-brinkmann** [comment]
I am having the same problem using the AppImage on Ubuntu 20.04 LTS

**Comment by shiftkey** [comment]
GitHub Enterprise is not supported due to the dependency on OAuth to authenticate - https://github.com/shiftkey/desktop/issues/229#issuecomment-604639903

> > What you suggest to do then? On windows and Mac is working properly.
> 
> This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in [desktop#1525](https://github.com/desktop/desktop/issues/1525) (please upvote if you care) but #72 is tracking this known limitation.
> 
> As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.
> 
> Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.
> 
> The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.

Please follow along with #72 which is the underlying reason this doesn't work currently.
