### ISSUE TITLE
can't log in: The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by obedm503** [shiftkey/desktop#7]
### Description
just installed the `.deb` version from https://github.com/shiftkey/desktop/releases/tag/release-1.0.11 it installed fine but fails to log in to my github account consistently, and shows the error
![screenshot_20171214_080239](https://user-images.githubusercontent.com/9118707/33995975-429f0572-e0a5-11e7-97bf-edaa0b4faf82.png)

then I tried the "Sign in using you browser" but that also fails  and shows 
![screenshot_20171214_080620](https://user-images.githubusercontent.com/9118707/33996288-64a9a612-e0a6-11e7-9c81-eabd8fee816f.png)

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** 
![image](https://user-images.githubusercontent.com/9118707/33996371-a0f52024-e0a6-11e7-9f2c-dc680587d1df.png)

### Steps to Reproduce

1. install
2. try to login
3. fail to login

**Expected behavior:** log in somehow
**Actual behavior:** doesn't log in

**Reproduces how often:** 100%

### Logs

couldn't find logs in `~/GitHub Desktop` which is where I expected them to be. so these are the logs in the devtools
![image](https://user-images.githubusercontent.com/9118707/33996750-c0bf0b94-e0a7-11e7-81db-3e16882cc2db.png)
 and judging from the network tab, it seems i was successfully authenticated by the server

#### Additional Information
if there more information needed about the environment feel free to let me know

**Comment by shiftkey** [comment]
@obedm503 thanks for the details!

My initial gut feeling on this is that the login flow where you provide username/password/2fa is failing when we try and add credentials to the OS credential store. We're using [`node-keytar`](https://github.com/atom/node-keytar/) which then uses `libsecret` which should work with both GNOME and KDE services for storing secrets, but maybe I'm missing something.

Using the browser to login is probably the same as #10, which is an Electron limitation that was fixed recently. Even if that was working, you'll probably still face the above issue because we need somewhere to store stuff.

**Comment by shiftkey** [comment]
Found this [extra context](https://github.com/lbryio/lbry-app/issues/386#issuecomment-318036509) for the first error:

> keytar uses libsecret, which is a frontend to gnome-keyring. KWallet does not support org.freedesktop.secrets
>just installed the package `gnome-keyring` and everything workes fine

I'm not sure how feasible that is for your use case, but I also don't have enough familiarity with whether there's an alternative to `gnome-keyring` that's more suitable

**Comment by obedm503** [comment]
so if I install gnome-keyring it should work?

**Comment by shiftkey** [comment]
@obedm503 I believe so

**Comment by Bleser92** [comment]
Version: 1.1.0 Linux RC
OS: KDE-nenon 5.12.3
I have the same spell.
If this can be of some help, in VS Code KWalet is used without problems.

**Comment by shiftkey** [comment]
> If this can be of some help, in VS Code KWalet is used without problems.

@Bleser92 if you can find out which Node library they're using (and how they're using it) I'm happy to figure out if this can be applied to `keytar` in some way.

**Comment by mathetes87** [comment]
I'm also using KDE Neon and installing `gnome-keyring` solved the login problem for me!

**Comment by sl1pkn07** [comment]
any other alternative? i don't what install gnome-keyring because my system is crafted for gnome-free

is possible use kwallet instead?

**Comment by shiftkey** [comment]
> is possible use kwallet instead?

Not currently - someone needs to contribute support for KWallet to [`node-keytar`](https://github.com/atom/node-keytar) as well as the ability to detect and choose the right backend. 

This is the issue discussing that change: https://github.com/atom/node-keytar/issues/17

**Comment by shiftkey** [comment]
I'm going to close this out because this is outside the scope of GitHub Desktop. I'd recommend looking for alternatives to KWallet for KDE systems, but I don't seem to be able to find any based on a quick google search.

**Comment by obedm503** [comment]
After almost a year, I decided to replace KWallet with Gnome's Seahorse. It now lets me login.
