### ISSUE TITLE
Error: User interaction failed

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#702]
### The problem

The error message of _User interaction failed_ is thrown when an attempt is made to publish a repository that is currently only available on the local machine, to the cloud.

### Release version

Version 2.9.14-linux2 (x64)

### Operating system

Linux Mint 20.3 Una

### Steps to reproduce the behavior

Please refer to the screenshots section, this ordered list corresponds to the order of the captures.

1. Click the button to create a new repository on your hard drive
2. Enter the repository details, then click the button for Publish repository
3. Click the button for Sign in
4. Click the button for Continue with browser
5. A blank browser window is opened to what appears to be the oauth page
6. The error message is thrown

### Log files

2022-04-19T17:57:35.696Z - info: [ui] [AppStore] loading 1 repositories from store
2022-04-19T17:57:36.186Z - info: [ui] launching: 2.9.14-linux2 (Linux 5.4.0-109-generic)
2022-04-19T17:57:36.220Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2022-04-19T17:57:46.054Z - info: [ui] [SignInStore] initializing OAuth flow
2022-04-19T17:57:46.066Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=fdbb6999-05c8-4e31-8060-8144758f529a
2022-04-19T17:58:01.592Z - info: [main] Received possible protocol arguments: 4
2022-04-19T17:58:01.593Z - info: [main] Processing protocol url
2022-04-19T17:58:01.612Z - info: [ui] [Dispatcher] requesting authenticated user
2022-04-19T17:58:02.647Z - info: [ui] [SignInStore] account resolved
2022-04-19T17:58:02.649Z - info: [ui] [AppStore] adding account CitizenWhite (CitizenWhite) to store
2022-04-19T17:58:02.708Z - error: [ui] Error adding account 'CitizenWhite'
Error: user interaction failed

### Screenshots

![image](https://user-images.githubusercontent.com/69254153/164071964-d76080f0-9f5e-4930-86bb-d0f9dd4bd1a5.png)
![image](https://user-images.githubusercontent.com/69254153/164072528-468235c9-8fa3-4e19-ab3a-472342558690.png)
![image](https://user-images.githubusercontent.com/69254153/164072950-f5b335ff-2161-406e-9895-a409fb27a4b3.png)
![image](https://user-images.githubusercontent.com/69254153/164073205-60bad9ed-b642-402e-9e6e-c3da0df443bc.png)
![image](https://user-images.githubusercontent.com/69254153/164073417-ec03dcbe-3a91-41ad-bad4-17a35915e290.png)
![image](https://user-images.githubusercontent.com/69254153/164075319-82e0b053-b6ba-484a-b795-fb280e6f3462.png)
![image](https://user-images.githubusercontent.com/69254153/164074667-f9ce1656-77da-45ca-8fc6-e6e27e4faa7c.png)

### Additional context

Browser version: Firefox 99.0.1 (64-bit)
Nothing seems to be submitted to the browser console when the steps to reproduce are executed.
The browser appears to be the registered handler for this action:

![image](https://user-images.githubusercontent.com/69254153/164078465-1694a0f2-448a-4369-b0f6-10b226c92c3e.png)

**Comment by shiftkey** [comment]
This error message is related to the application trying to store the credential it receives from the browser, which it communicates using `dbus` to a `libsecret`-compatible backend (typically `gnome-keyring`, but there are others). 

This error is the backend fails to save the credential, and sadly I don't have much assistance here beyond "check `gnome-keyring-daemon` is working as expected".

**Comment by ghost** [comment]
Hi @shiftkey

Thank you for looking into this. I am uncertain if I comprehend your instruction, my Linux skill would be best described as a power user.

I opened a terminal window and copy/pasted the _check gnome-keyring-daemon_ command. I was then informed that command could not be found, but could be installed with the gitlab-shell package.  After installing the package I then tried the command again which threw this error: _Failed to read config, exiting_

If this was the output that you were looking for & the intent of what you wanted me to do, I will continue to perform anything else that is needed. Thank you for your help.

**Comment by shiftkey** [comment]
@CitizenWhite apologies for not being clear, but I don't think running `gnome-keyring-daemon` alone will yield you much. I also haven't had much in the way of clues for understanding this issue as it's not one I've faced, and other mentions of this don't really explain the underlying issue:

 - https://gitlab.gnome.org/GNOME/evolution/-/issues/1529
 - https://github.com/flathub/org.gnome.Evolution/issues/26
 - https://github.com/flathub/com.skype.Client/issues/131

There's [a comment here](https://github.com/bitwarden/directory-connector/issues/17#issuecomment-499935581) about interacting with they keyring daemon as an example for how you might get this unstuck:

```
export $(dbus-launch)
dbus-launch
gnome-keyring-daemon --start --daemonize --components=secrets
echo '<RANDOM-PASSPHRASE>' | gnome-keyring-daemon -r -d --unlock
```

**Comment by shiftkey** [comment]
Closing this out due to lack of bandwidth to dig into this further, and I don't want to be "on the hook" for messing around with credential stores...

**Comment by tazihad** [comment]
I have also same problem in Fedora Kinoite 38

**Comment by rph-r** [comment]
+1 on Kubuntu 22.04

**Comment by Ezzz-dev** [comment]
+1 on Nobara 38 (Fedora based)

**Comment by cmwg71** [comment]
+1 LMDE 6 (Debian based)

**Comment by AlXavi2004** [comment]
This error usually occurs due to some linux updates. In my case it worked for me by uninstalling github Desktop and reinstalling git from terminal https://gist.github.com/berkorbay/6feda478a00b0432d13f1fc0a50467f1.

**Comment by richard-muvirimi** [comment]
Refer to this comment for the fix
https://github.com/shiftkey/desktop/issues/753#issuecomment-2656131421
