### ISSUE TITLE
Application Fails to Start

### ISSUE THREAD

**Issue by mikeyd85** [shiftkey/desktop#707]
### The problem

When clicking the icon in the dock, the application does not open.

When running github-desktop from Terminal, the application does not open.

### Release version

2.8.1-linux1

### Operating system

Pop!_OS 22.04 LTS

### Steps to reproduce the behavior

1. Open the application via dock.

OR

1. Open the application via Terminal using command: github-desktop

### Log files

Terminal output: 

(node:17777) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[17777:0426/210415.768891:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

### Additional context

This is the only application I'm having issues with on this system. It was fine prior to the upgrade to 22.04. Appreciate this might not be a github-desktop issue, but thought I should raise the issue either way.

**Comment by shiftkey** [comment]
`2.8.1-linux1` is about a year behind what we've currently release. Please re-test with a more recent build - particularly if you're testing with a newer OS.
