### ISSUE TITLE
Editable list of text editors

### ISSUE THREAD

**Issue by borodinalive** [shiftkey/desktop#709]
### The feature request

Now text editors list is hardcode. It would be nice if user could manage this list via text configs or some visual tool

### Proposed solution

a. text configs in json-file

or 

b. modal with system apps list for adding to Github Desktop app text editors list

**Comment by Etaash-mathamsetty** [comment]
this would be smart, since there are so many editors. I don't think it would really help having this list modified locally for every single computer, so it would probably exist on this github repo. (having it in a seperate file would make it easier for newbs to add support for new ones)

**Comment by shiftkey** [comment]
> I don't think it would really help having this list modified locally for every single computer, so it would probably exist on this github repo. (having it in a seperate file would make it easier for newbs to add support for new ones)

This is basically what [the current solution is](https://github.com/shiftkey/desktop/blob/linux/docs/technical/editor-integration.md#linux), and has several benefits:

 - once it's implemented, all users can benefit from it when they upgrade to this version
 - upgrades can handle changes and additional ways to detect apps without the user needing to make changes
 - for advanced features like Wayland support we could integrate into the app and not need the user to make changes to their setup, e.g. https://github.com/shiftkey/desktop/issues/665

I'm skeptical that adding support for a secondary source like a JSON file gives us enough to support it, for a few reasons:

 - a file outside the application that will be trusted to launch programs feels like a security risk
 - adhering to a specific format could make this brittle and have a bad experience for users
 - long-term support for this would require keeping in sync with whatever the upstream project supports, which isn't something I'm interested in maintaining...

**Comment by borodinalive** [comment]
> a file outside the application that will be trusted to launch programs feels like a security risk

it could be created by the app with app's regular tools

Ok. In Windows version there is IntelijjIdea in editors list, in Linux it is not in list.
It installed in custom directory and I suspect it is the problem. Maybe there is some solution for my problem?

**Comment by shiftkey** [comment]
> Ok. In Windows version there is IntelijjIdea in editors list, in Linux it is not in list.
> It installed in custom directory and I suspect it is the problem. Maybe there is some solution for my problem?

This is because on Windows the apps leverage the registry when they install, which GitHub Desktop can inspect to find the information about where on disk it's located:

https://github.com/shiftkey/desktop/blob/dcb67bc7fdf4090a7106f80fa765988f39a621ff/app/src/lib/editors/win32.ts#L353-L359

**Comment by shiftkey** [comment]
> Ok. In Windows version there is IntelijjIdea in editors list, in Linux it is not in list.
> It installed in custom directory and I suspect it is the problem. Maybe there is some solution for my problem?

@borodinalive the custom directory is an issue here, and an upstream PR from @patinthehat https://github.com/desktop/desktop/pull/15375/ added support for the Snap packages for other JetBrains tools that seem to be available under `/snap/bin/`. If there's a similar default setup for IntelliJ I'd recommend following this convention to add support for it.

**Comment by adil192** [comment]
> @borodinalive the custom directory is an issue here, and an upstream PR from @patinthehat [desktop#15375](https://github.com/desktop/desktop/pull/15375) added support for the Snap packages for other JetBrains tools that seem to be available under `/snap/bin/`. If there's a similar default setup for IntelliJ I'd recommend following this convention to add support for it.

I've just opened a PR https://github.com/desktop/desktop/pull/16029 which adds IntelliJ IDEA among others

**Comment by borodinalive** [comment]
> > Ok. In Windows version there is IntelijjIdea in editors list, in Linux it is not in list.
> > It installed in custom directory and I suspect it is the problem. Maybe there is some solution for my problem?
> 
> @borodinalive the custom directory is an issue here, and an upstream PR from @patinthehat [desktop#15375](https://github.com/desktop/desktop/pull/15375) added support for the Snap packages for other JetBrains tools that seem to be available under `/snap/bin/`. If there's a similar default setup for IntelliJ I'd recommend following this convention to add support for it.

I've installed IntellijIdea from original *.deb to custom directory. This won't work for me, unfortunately
Anyway, thank you!

**Comment by jordan4ibanez** [comment]
This would be nice. I've read through this, and I still cannot get IntelliJ to show up. I've installed a desktop entry as both privileged and unprivileged and it still does not show up as an option. :(

**Comment by shiftkey** [comment]
I'm inclined to close this out because I worry about deviating from the extensibility provided by the upstream project from a support perspective (I spend enough bandwidth on managing dependencies currently and am currently stuck trying to maintain compatibility with different architectures), and without someone to champion this work and figure out a solution this is not going to progress...

**Comment by shiftkey** [comment]
I'm going to close this out for now as it hasn't moved in a while, and point anyone who is curious to https://github.com/shiftkey/desktop/issues/1113 where the upstream project is working on "Custom integrations" as a way to make this experience more tailored to those power users.

Please try it out and see if that helps with what you need.
