### ISSUE TITLE
Missing some libraries in Snap package

### ISSUE THREAD

**Issue by showerying** [shiftkey/desktop#71]
## Version

* GitHub Desktop: **1.4.2 Linux RC1**

* Operating system: 

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic

## Steps to Reproduce

1. Run `$ sudo snap install GitHubDesktop-linux-amd64-1.4.2-linux1.snap --dangerous --classic`
2. Click the icon in the launcher, nothing happens
3. Run `$ /snap/bin/desktop`, output shows:

> cp: '/home/ying/.config/user-dirs.locale' and '/home/ying/.config/user-dirs.locale' are the same file
> /snap/desktop/x1/app/desktop: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by shiftkey** [comment]
@showerying thanks for the report!

>  error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

This feels like we overlooked a dependency for the snap package, but I'm not sure why yours is the first report about it.

`libgconf-2.so.4` comes from [`libgconf-2-4`](https://packages.ubuntu.com/bionic/libgconf-2-4) which is available for bionic (I need to dig into how these packages map to Snap packages).

Can you try installing that manually and see if it fixes it? If so, that should be easy to publish a new update with...

**Comment by showerying** [comment]
@shiftkey Yes. Now it can be started normally.

**Comment by showerying** [comment]
When I try to clone one repository, it indicates that  `libcurl.so.4` is missing:
![image](https://user-images.githubusercontent.com/6418433/46950527-8abc7800-d0b7-11e8-9d66-554dac77f788.png)
`sudo aptinstall libcurl3` fixed this.

**Comment by zypA13510** [comment]
Same here. I have to manually run `apt install libcurl3` to get cloning repository working.
On 1.4.2-linux1, Ubuntu 18.04.1

**Comment by shiftkey** [comment]
@flexiondotorg any ideas why this might be occurring? They seem to be using the snap from [this release](https://github.com/shiftkey/desktop/releases/tag/release-1.4.2-linux1), FWIW.

**Comment by bb441db** [comment]
I have a problem with cloning repositories too, however I get a slightly different error:
```
Cloning into '/home/user/Documents/GitHub/desktop'...
/snap/desktop/x1/app/resources/app/git/libexec/git-core/git-remote-https: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /snap/desktop/x1/app/resources/app/git/libexec/git-core/git-remote-https)
```
This should be fixed by adding this dependency: `libcurl-openssl1.0-dev` (https://github.com/atom/github/issues/1680)

**Comment by shiftkey** [comment]
@bb441db the `CURL_OPENSSL_3` is a different problem - see https://github.com/desktop/dugite-native/issues/109 for more details. It required a fix to the embedded Git https://github.com/desktop/dugite-native/pull/129, and I'll ask people to retest this with `1.5.0` as that will contain the bump of the embedded Git package #79

**Comment by shiftkey** [comment]
I'm going to close this out because there's a new Snap package in the store and things have changed significantly enough to revisit this. Please test out `1.5.0-linux5` and submit new issues for things that have been noticed.
