### ISSUE TITLE
[temporary-fix]: a workaround for auth from webbrowser into an .AppImage

### ISSUE THREAD

**Issue by ibrahemesam** [shiftkey/desktop#710]
every time you want to sign-in from webbrowser into an .AppImage

- ensure that these libs are installed: sudo pacman -S gnome-keyring libsecret
  - if not installed: install them and reboot
  - if you proceed without installing them, you get that error later:
    "The name org.freedesktop.secrets was not provided by any .service files"

- run the *.AppImage normally
- go to: temp folder in your root directory [ie: /tmp]
- search for the folder that AppImage is mounted to [eg: .mount_blabla]
- copy that folder to another location
- close the running *.AppImage
- inside that folder: modify the "AppRun" shell file:-
  - find the [   BIN="$APPDIR/   ] and change it to [   BIN="./   ] ((remove brackets[ ]))
  - save the file and quit the txt editor
- run that "AppRun" shell file
- (the app will run)
- proceed with the login the login process [eg:]:-
  - click "sign in from browser"
  - (the web browser automatically opens)
  - (you then enter your credintials in the browser to proceed)
  - (then the browser generates an authentication xdg link [eg: "blabla://auth?blabla_bla"])
  - an error dialog will appear telling you that xdg-open can't find the application that open that xdg link.
    I am on KDE, so: in my case, it is "Error - KIO Client"
  - copy that xdg link that appear on that Error dialog
  - do NOT close the app at this point

- from terminal: run: ./AppRun "your_xdg_link"
- and voila! the application finally signin successfully
- (after signing in: the app should create configuration files [in your HOME directory] that holds your login info)
- close the app
- delete the .mount_blabla folder [as it is no longer needed]
- normally, run the *.AppImage again:
  - (it should read your configuration files from your HOME directory)
  - (then you should be automatically signed in)
- Have fun!

**Comment by Etaash-mathamsetty** [comment]
instead of digging in /tmp you could
./GitHubDesktop-linux-3.0.0-linux1.AppImage --appimage-extract 
welp this method didn't work at all lmao

**Comment by LarveyOfficial** [comment]
Thank you this worked! (I'm using the install from the AUR but I still seem to have this issue). I downloaded the AppImage to simply run --appimage-extract, then followed the instructions you gave, and it properly signed me in.

Note for anyone trying to do the same steps. At the part you run `./AppRun "your_xdg_link"`, Yes you have " " around the xdg link, and make sure to remove the period at the end that is added by KIO - Client
