### ISSUE TITLE
I can't access to organizations private repository

### ISSUE THREAD

**Issue by boraoksuzoglu** [shiftkey/desktop#713]
### The problem

Hi, i can't access my organizations private repositories. I think I need to enter my Developer Access Token somewhere to be able to access them, but I couldn't find a place to enter it.

`The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.`

I'm pretty sure I'm logged in with my correct GitHub account.
I logged out of my GitHub account and logged back in. It still didn't work.

### Release version

Lastest

### Operating system

Linux Mint 20.3 Cinnamon

**Comment by shiftkey** [comment]
This is a [known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization):

> ### I cannot access repositories under my organization
> 
> The GitHub Desktop application is an OAuth application, but this fork does not
> have the same permissions as the app does on Windows and macOS, which manifests
> in a couple of different ways:
> 
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a
>    generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access
> restrictions" enabled, which blocks the GitHub Desktop development app that is
> used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)
> to the GitHub Desktop development app.

Please follow along with #72 which is tracking the underlying issue

**Comment by boraoksuzoglu** [comment]
**Solution of the problem:**

Click on the link below and click on the "Grant" button next to the organization you want to access.

https://github.com/settings/connections/applications/3a723b10ac5575cc5bb9

**Comment by xinthose** [comment]
> **Solution of the problem:**
> 
> Click on the link below and click on the "Grant" button next to the organization you want to access.
> 
> https://github.com/settings/connections/applications/3a723b10ac5575cc5bb9

I don't know if I feel comfortable giving `The Github Desktop Development App` access to all of my organizations repositories.
