### ISSUE TITLE
Err:4 https://packagecloud.io/shiftkey/desktop/any any InRelease 429  Too Many Requests [IP: 2600:1f1c:2e5:6901:dfce:2ed2:fe18:45d0 443]

### ISSUE THREAD

**Issue by sakunix** [shiftkey/desktop#715]
### The problem

Err:4 https://packagecloud.io/shiftkey/desktop/any any InRelease               
  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:dfce:2ed2:fe18:45d0 443]

Fallo al obtener https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:dfce:2ed2:fe18:45d0 443]

### Release version

no install

### Operating system

Xubuntu

### Steps to reproduce the behavior

Fallo al obtener https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:dfce:2ed2:fe18:45d0 443]

### Log files

Fallo al obtener https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 2600:1f1c:2e5:6901:dfce:2ed2:fe18:45d0 443]

**Comment by SkoZombie** [comment]
This is blocking my updates too. As a work around I'm just downloading and installing the deb files manually.

I'd suggest moving the hosting to github to avoid packagecloud restrictions. There are lots of guides and tools to help you do this but their presence suggests it might be a viable option.

**Comment by mwt** [comment]
There's an alternative with unlimited bandwidth in the readme. This is discussed more in #278

**Comment by shiftkey** [comment]
> I'd suggest moving the hosting to github to avoid packagecloud restrictions. There are lots of guides and tools to help you do this but their presence suggests it might be a viable option.

Please refer to #278 for the discussion as there has been a lot of proposals dismissed as not suitable for what I require to support these feeds.
