### ISSUE TITLE
PhpStorm Jetbrains is not visible

### ISSUE THREAD

**Issue by PadowYT2** [shiftkey/desktop#716]
### The problem

In options > integrations > external editor it should show PhpStorm, but it doesn't. All it shows is VSC, VSC (insiders), GNOME text editor.

### Release version

Version 2.9.3-linux3 (x64)

### Operating system

Ubuntu 20.04.3 LTS

### Screenshots

![https://cdn.padow.ru/c4mm](https://cdn.padow.ru/c4mm)

**Comment by shiftkey** [comment]
These are detected based on a known good list of values documented here: https://github.com/shiftkey/desktop/blob/linux/docs/technical/editor-integration.md#linux

If you're able to contribute I'd happily review a pull request
