### ISSUE TITLE
Cant push my comments!

### ISSUE THREAD

**Issue by ahmedaljaali** [shiftkey/desktop#719]
### The problem

When I press push it says "We are unable to authenticate with github.com please enter your username and password and try again " and when I do what it says it again

### Release version

3.0.0-2

### Operating system

Arch linux

### Steps to reproduce the behavior

Just push a commit

### Screenshots

![2022-05-28-130103_548x498_scrot](https://user-images.githubusercontent.com/82327047/170820583-4ff54f18-0543-4ecd-a819-bcd7221c9c8e.png)

**Comment by shiftkey** [comment]
Please attach a log file from ` ~/.config/GitHub Desktop/logs/` as that will have more details about the underlying issue

**Comment by shiftkey** [comment]
Closing this out due to inactivity and lack of log files. 

@IZenithy if you're able to check the logs for help around why this might be failing we can revisit.

**Comment by ahmedaljaali** [comment]
I apologize for the delay, I solve the problem by cloning my repo via ssh
