### ISSUE TITLE
Can't push to organization I have permissions in

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#720]
### The problem

I own the @TapVM organization, but when I try to push a commit to a repository in the org, it fails with the following error

![image](https://user-images.githubusercontent.com/93856041/172042854-33bb5d66-be83-4902-9db5-db8b2a6f2595.png)

Neither does the menu to clone repos from github show any repos from the organization, even though I own it 

### Release version

Version 3.0.0-linux2 

### Operating system

Pop OS 22.04 (Based on Ubuntu 22.04)

### Steps to reproduce the behavior

1. Make a commit in an organization
2. Try to push
3. Failure 😦

**Comment by ghost** [comment]
To make it clear, `git push` from the CLI works completely fine

**Comment by ghost** [comment]
And I have tried to logout and login, didn't fix it :(

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/93856041/172043300-294b699d-69fb-44db-8aad-140356fe760e.png)


Seems like the desktop app doesn't have third-party application permissions to the organization?

How can I allow GH Desktop the permissions? Fwiw, this worked OOTB on windows

**Comment by shiftkey** [comment]
[This is a known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization).

> ### I cannot access repositories under my organization
> 
> The GitHub Desktop application is an OAuth application, but this fork does not
> have the same permissions as the app does on Windows and macOS, which manifests
> in a couple of different ways:
> 
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a
>    generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access
> restrictions" enabled, which blocks the GitHub Desktop development app that is
> used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)
> to the GitHub Desktop development app.

#72 has more context, but this isn't something I can resolve in the near term: https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547
