### ISSUE TITLE
Reinstallation, how to sync local folder?

### ISSUE THREAD

**Issue by rtek1000** [shiftkey/desktop#721]
Hello,

I created the repository using Xubuntu 20.04 but had to format Linux to 22.04 because of virus.

Now I'm not finding the option to sync the local folder.

When I try to clone it says that the folder contains file.
When I try to add the local repository, it says it appears to be from another user.

**Comment by shiftkey** [comment]
> When I try to add the local repository, it says it appears to be from another user.

Can you share the exact error message you're seeing here? This should be the way to add the existing repository to your new install but I'm not sure what this error would mean.

Also, please check if there's any interesting error messages in the log files at ` ~/.config/GitHub Desktop/logs/` that might help with identifying this underlying cause...

**Comment by rtek1000** [comment]
If this is the right procedure, I believe I understand what happened. Due to the fact that Linux 20.04 has been formatted and is now using another installation, this warning occurs that the repository cannot be trusted. Am I correct?

I tried again and clicked **"add an exception for this directory"** and now this warning no longer appears.



![Github_Desktop1](https://user-images.githubusercontent.com/8660811/172228279-f9627bca-9142-4cd5-bc0b-90d1d4677907.png)


This is the other message, but I now see that this is not the correct procedure:
![Github_Desktop2](https://user-images.githubusercontent.com/8660811/172226825-2723243c-e59b-4e8a-9223-243fbe713c5b.png)

**Comment by shiftkey** [comment]
> If this is the right procedure, I believe I understand what happened. Due to the fact that Linux 20.04 has been formatted and is now using another installation, this warning occurs that the repository cannot be trusted. Am I correct?

This was a warning from Git itself to address a potential security issue as another user could have crafted a malicious repository: https://github.blog/2022-04-12-git-security-vulnerability-announced/ 

> I tried again and clicked **"add an exception for this directory"** and now this warning no longer appears.

Given the situation, this seems fine. Alternatively `chown`-ing the repository to reclaim ownership here should also resolve this.

Closing this out as it's the intended behaviour - thanks for the context @rtek1000!

**Comment by rtek1000** [comment]
Thanks!
