### ISSUE TITLE
Installing github desktop 3.0.0 doesn't show in apps

### ISSUE THREAD

**Issue by jredfox** [shiftkey/desktop#722]
### Operating System/Distribution

Which distribution of Linux are you using?
linux mint

### Installer
3.0.0-linux2 deb version

Which version of the app?
3.0.0-linux2 deb version
Which installer type?

### What happened?
it installed but doesn't show up in the apps. I have to go to terminal and type github in order to launch it. when I finally created the shortcut it was missing the icon of course. 

Provide as much detail as possible. Error messages or output are extremely useful.
again the installer installed the app but it didn't register in the apps when searching for it. I couldn't make a desktop icon nor find it in the start. it was installed like a library package not an actual application

**Comment by kushcheva** [comment]
I have the same problem
Linux Mint 18.2

**Comment by jredfox** [comment]
Rebooting it fixes it but it doesn't show up without reboot in the menus

**Comment by kushcheva** [comment]
> Rebooting it fixes it but it doesn't show up without reboot in the menus

didn't help(

**Comment by jredfox** [comment]
did you run the .deb file? does it appear when typing `github` in the terminal? try using the deb

**Comment by kushcheva** [comment]
I tried everything. Can't run git. I do not know what to do! (

**Comment by kushcheva** [comment]
> did you run the .deb file? does it appear when typing `github` in the terminal? try using the deb

In any case, I permanently use it in the terminal. No other way. I'm sorry to trouble you)

**Comment by Etaash-mathamsetty** [comment]
this is my desktop file: (download it)
[github-desktop.txt](https://github.com/shiftkey/desktop/files/8856352/github-desktop.txt)
run
```
mv github-desktop.txt github-desktop.desktop
sudo cp github-desktop.desktop /usr/share/applications
```
and hopefully it shows up now

**Comment by shiftkey** [comment]
> it installed but doesn't show up in the apps.

@TitiTatiTiti thanks for the report! At the moment I'd be focused on what's in `github-desktop.desktop` and why . Here's mine:

```
> cat /usr/share/applications/github-desktop.desktop 
[Desktop Entry]
Name=GitHub Desktop
Comment=Simple collaboration from your desktop
GenericName=GitHub Desktop
Exec=github-desktop %U
Icon=github-desktop
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;x-scheme-handler/x-github-desktop-dev-auth;
```

Does this file exist for you? If so, what's inside?

>  I have to go to terminal and type github in order to launch it.

This is an additional integration point to integrating with the system applications, but good to know it works.

> when I finally created the shortcut it was missing the icon of course.

These are the icons that should be included with the app that should be picked up by the `Icon=github-desktop` value inside the `.desktop` file:

```
> find /usr/share/icons -name "github-desktop*"
/usr/share/icons/hicolor/64x64/apps/github-desktop.png
/usr/share/icons/hicolor/256x256/apps/github-desktop.png
/usr/share/icons/hicolor/512x512/apps/github-desktop.png
/usr/share/icons/hicolor/128x128/apps/github-desktop.png
/usr/share/icons/hicolor/1024x1024/apps/github-desktop.png
/usr/share/icons/hicolor/32x32/apps/github-desktop.png
```
