### ISSUE TITLE
UI bug for longer branch names, make possible to view the entire branch name

### ISSUE THREAD

**Issue by etnikbeqiri1** [shiftkey/desktop#723]
### The problem

if branch names are longer for example 'feature/15055' the text in the ui gets cutter of to only showing 'feature/15...' , make possible to show the entire branch name, or add new settings configuration for this one

### Release version

3.0.0

### Operating system

Ubuntu 22.04 LTS

### Steps to reproduce the behavior

create new branch with name longer that this: 'feature/15005' 

### Screenshots

![image](https://user-images.githubusercontent.com/82059535/173003337-633835eb-3ddb-47cc-9146-675b2a2e2971.png)

**Comment by shiftkey** [comment]
@etnikbeqiri1 thanks for the feedback! This is probably better to raise on the upstream project and see if there's interest in making these header buttons more flexible with the presence of the pull request id.

I also can't seem to find an upstream issue similar to this so perhaps there's context I'm not up to speed with on this change.

For reference, this is the related component in the codebase:

https://github.com/shiftkey/desktop/blob/ebeb34c33d4430527e431fc93d057765bc0d1a2c/app/src/ui/toolbar/branch-dropdown.tsx#L190-L214

I'm not aware of examples where the UI resizes it's width based on the content itself, but the width that you see is set here:

https://github.com/shiftkey/desktop/blob/ebeb34c33d4430527e431fc93d057765bc0d1a2c/app/styles/ui/toolbar/_toolbar.scss#L40-L44

I'll leave this open in the meantime so it's tracked _somewhere_.

**Comment by shiftkey** [comment]
Closing this out because I believe this was fixed upstream

![Image](https://github.com/shiftkey/desktop/assets/359239/cc19d8fc-94f5-4d6b-903d-86976d2d786c)
