### ISSUE TITLE
Continue repository cloning

### ISSUE THREAD

**Issue by rtek1000** [shiftkey/desktop#725]
### The feature request

Continue repository cloning if any interruption occurs

### Proposed solution

Continue repository cloning if any interruption occurs

### Additional context

Hi, I tried to download the contents of the repository (*) and an error occurred while unzipping the file. So I tried to clone the repository, which has a lot of files and it takes time for me to download due to the low bandwidth. My surprise is that I was already more than 54% cloning, but I can't continue where I left off.

(*): https://github.com/pecostm32/FNIRSI-1013D-1014D-Hack

I tried adding the local repository too but it fails to sync, files are not downloaded. I believe it is due to me not being the owner of the repository.

Is there any other alternative to continue the cloning? Or do I have to delete everything that has already been downloaded whenever cloning stops?

**Comment by shiftkey** [comment]
This is a limitation of Git and how the clone operation works, so this isn't something I can fix easily in the app.

> Is there any other alternative to continue the cloning?

What I'd do in this case is avoid the clone operation and try and build up the repository from scratch. Thankfully your example is rather easy to work with, so here's what I did to avoid `git clone`.

1. Create an empty repository with the default branch matching the remote branch

```
> git init FNIRSI-1013D-1014D-Hack -b main
> cd FNIRSI-1013D-1014D-Hack 
```

2. From within the repository, add the remote 

```
> git remote add origin https://github.com/pecostm32/FNIRSI-1013D-1014D-Hack
```

3. Now fetch all the objects from the remote repository - run this command again if it fails

```
> git fetch
```

4. Now reset your local branch to the one on the remote

```
> git reset origin/main --hard
```

5. Set the tracking branch so the local branch is associated with the remote repository's default branch

```
> git branch -u origin/main   
```

Now you can add this to GitHub Desktop or just work with it locally.

**Note:** this advice is specific to this situation, and may not work for all repositories.

**Comment by rtek1000** [comment]
Thank you
