### ISSUE TITLE
Linux Github desktop won't authenticate

### ISSUE THREAD

**Issue by red-smeg** [shiftkey/desktop#727]
### The problem

I open the github desktop app on linux arch.  choose sign in, continue with browser.  I login successfully on the website but the final page does not load and the app doesnot get past the "sign in using your browser" menu.

### Release version

3.0.0-linux2

### Operating system

linux (arch)

### Steps to reproduce the behavior

1. open github app
2. choose clone a repository
3. choose sign in (github.com)
4. choose continue with browser
5. choose authorise on the browser

browser fails to open this page

`x-github-desktop-dev-auth://oauth?code=[snip]

**Comment by red-smeg** [comment]
[2022-06-25.desktop.production.log](https://github.com/shiftkey/desktop/files/8983592/2022-06-25.desktop.production.log)

**Comment by shiftkey** [comment]
> browser fails to open this page
> 
> `x-github-desktop-dev-auth://oauth?code=[snip]`

This URL should be registered by the app with the OS in the `.desktop` file:

```
> cat /usr/share/applications/github-desktop.desktop

[Desktop Entry]
Name=GitHub Desktop
Comment=Simple collaboration from your desktop
GenericName=GitHub Desktop
Exec=github-desktop %U
Icon=github-desktop
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;x-scheme-handler/x-github-desktop-dev-auth;
```

That's how we hook into this protocol handler, and if that's not working then I think we're stuck. 

Which browser are you using?

**Comment by weyounsix** [comment]
same issue. using firefox-esr 91-1 in debian vm (with shiftkey/desktop installed in same vm via deb repo). desktop file looks the same as what you posted @shiftkey

**Comment by weyounsix** [comment]
a little belated, but just popping in to say the solution I found to this was to install chromium browser and set that to default. chromium was then able to link back to github-desktop. I don't know why this was an issue in firefox. may be resolvednow, but if not, for new users out there: try authenticating via chromium.
