### ISSUE TITLE
Snap version has no output files under $HOME/.config/

### ISSUE THREAD

**Issue by showerying** [shiftkey/desktop#73]
## Description
Can't find Github Desktop directory under $HOME/.config/.
But I can find them when I tried to install the AppImage one.

## Version
* GitHub Desktop:  1.4.2 Linux RC1
* Operating system: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by bb441db** [comment]
I believe a snap's user data directory is `$HOME/snap/$SNAP`

**Comment by shiftkey** [comment]
@showerying can you confirm whether @bb441db is correct about the location Snap data directory?

**Comment by shiftkey** [comment]
I can confirm its in this location: `$HOME/snap/github-desktop/current/.config/GitHub\ Desktop/logs/`

This should be added to the installation doc: https://github.com/shiftkey/desktop/blob/linux/docs/installation.md
