### ISSUE TITLE
Won't authenticate with github enterprise

### ISSUE THREAD

**Issue by notauser9876** [shiftkey/desktop#730]
### The problem

We run our own github enterprise 3.5 instance and we cannot authenticate via github desktop.

We've tried with the Github Enterprise default self-signed certificate and we also tried configuring GE with certificates created using our own CA cert.

### Release version

3.0.2-linux1

### Operating system

Ubuntu 20.04.4 LTS

### Steps to reproduce the behavior

1. run github-desktop from the command line (for error output)
2. Sign in to Github Enterprise
3. Enter the url of github enterprise
4. Continue
5. fail
6. skip step
7. File -> Options -> Accounts
8.  Under Github Enterprise -> Sign In -> provide URL
9.  Continue
10. Untrusted Server Error
11. click `add certificate`
12. still can't connect after adding the cert. it just asks us to add the certificate every time and nothing happens.

### Additional context

Yes the CA is available in the system for use via update-ca-certificates.

I can't add any screenshots but here is the error output.
```
[259825:0630/161138.355765:ERROR:cert_issuer_source_aia.cc(134)] AiaRequest::OnFetchCompleted got error -301
[259825:0630/161138.355765:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for github.enterprise.dev failed:
----- Certificate i=1 (CN=our-ca,0.xxxxxxx) -----
ERROR: no matching issuer found

error: [ui] fetchMetadata: unable to load metadata ....
```

**Comment by shiftkey** [comment]
GitHub Enterprise is not supported due to the dependency on OAuth to authenticate - https://github.com/shiftkey/desktop/issues/229#issuecomment-604639903

> > What you suggest to do then? On windows and Mac is working properly.
> 
> This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in [desktop#1525](https://github.com/desktop/desktop/issues/1525) (please upvote if you care) but #72 is tracking this known limitation.
> 
> As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.
> 
> Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.
> 
> The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.

Please follow along with #72 which is the underlying reason this doesn't work currently.
