### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by prak899** [shiftkey/desktop#731]
### The feature request

While am login to github desktop at my linux system it's showing a error message like:-Cannot create an item in a locked collection
Hope github team will solve this issue.
Thanks in Advance!

### Proposed solution

Login issue

**Comment by shiftkey** [comment]
> Cannot create an item in a locked collection

This is related to the keychain not being configured correctly, and is dependent on how the OS is configured for the user.

Please read #507 which is the same report and suggests a couple of options to investigate.
