### ISSUE TITLE
Unable to login (API v2 would go away)

### ISSUE THREAD

**Issue by Firestar-Reimu** [shiftkey/desktop#734]
https://github.blog/2012-06-12-github-api-v2-end-of-life/

### The problem

![Screenshot_20220710_162446](https://user-images.githubusercontent.com/65082432/178137202-63779cd6-c505-4db1-af74-dba9ae3e80da.png)

The login using browser

### Release version

3.0.3

### Operating system

Manjaro

**Comment by shiftkey** [comment]
> ### Steps to reproduce the behavior
> _No response_

Please provide more details about how you found this issue.

**Comment by Firestar-Reimu** [comment]
https://github.com/desktop/desktop/issues/14938

**Comment by shiftkey** [comment]
Closing this out in favour of https://github.com/desktop/desktop/issues/14938 which has further progress on investigating this
