### ISSUE TITLE
how to run with paramter "--no-sandbox"

### ISSUE THREAD

**Issue by askgh** [shiftkey/desktop#739]
### The feature request

the github desktop will be launched by other app.

the login user is root, so need add "--no-sandbox" to launch cmd. 

but other app is released by third party.

how to add paramter "--no-sandbox" in system wide.

thanks

### Proposed solution

a

### Additional context

a

**Comment by shiftkey** [comment]
Would an environment variable be feasible here? If this is set globally, we can detect this at launch and pass this through, without needing to change all the places where the app is launched:

```diff
diff --git a/app/src/main-process/main.ts b/app/src/main-process/main.ts
index 3c2e290ea..9d75e94cc 100644
--- a/app/src/main-process/main.ts
+++ b/app/src/main-process/main.ts
@@ -298,6 +298,13 @@ function setAsDefaultProtocolClient(protocol: string) {
   }
 }
 
+if (process.env.GITHUB_DESKTOP_FORCE_NO_SANDBOX) {
+  log.info(
+    `GITHUB_DESKTOP_FORCE_NO_SANDBOX environment variable set, forcing app to run without sandbox`
+  )
+  app.commandLine.appendArgument('no-sandbox')
+}
+
 if (process.env.GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION) {
   log.info(
     `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION environment variable set, disabling hardware acceleration`
```
