### ISSUE TITLE
GitHub Desktop for Linux fails authentication in cloning a repo requiring a PAT.

### ISSUE THREAD

**Issue by gtrevi** [shiftkey/desktop#740]
### The problem

On Ubuntu 20.04, cloning a private repo on GitHub requiring PAT fails, whereas both bare git command line and GitHub Desktop for Windows can perfectly clone the repo just fine, with the same PAT credentials.
This issue is happening only when using GitHub Desktop **for Linux**

My PAT is generated with *all* permissions enabled.

### Release version

Version 2.9.3-linux3 (x64)

### Operating system

Ubuntu 20.04.4 LTS

### Steps to reproduce the behavior

Just go for *"Clone a repository from the internet..."* on a Private repo, requiring PAT authentication.

### Log files

[2022-07-19.desktop.production.log](https://github.com/shiftkey/desktop/files/9139319/2022-07-19.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/22826130/179714629-c70e838b-999f-4ad1-be05-c9dd2712b005.png)

**Comment by Chifouuu** [comment]
I have the same problem

**Comment by shiftkey** [comment]
> Just go for "Clone a repository from the internet..." on a Private repo, requiring PAT authentication.

@gtrevi @Chifouuu is this a repository belonging to an organization?

**Comment by Chifouuu** [comment]
yes

**Comment by shiftkey** [comment]
I believe this is #217 and organizations having OAuth application restrictions enabled. I'm not 100% sure why a PAT wouldn't work with this case but it's a known difference between this and the Windows build (with this one being unofficial).

I'd suggest trying to add the repository manually and seeing if the fetch/push/pull encounters the same issue.

**Comment by gtrevi** [comment]
@shiftkey thanks for looking into this.
Cloning through the CLI, and then adding them as local repos works, but unfortunately, fetch/push/pull do encounter the same issue.

**Comment by ShinoharaHaruna** [comment]
Same problem here. Since I do not want to modify the git url using PAT, nor do I want to return to git command line, my *temporary* method is to **cancel all restrictions** in `<Organization>|Settings|Third-party Access|OAuth application policy|Third-party application access policy`.

**Comment by shiftkey** [comment]
Please follow along with https://github.com/shiftkey/desktop/issues/217 which is the root cause here.
