### ISSUE TITLE
Sign-in issue

### ISSUE THREAD

**Issue by Asqit** [shiftkey/desktop#741]
### The problem

Hello, 
I cannot log in with my GitHub account. As always I install `.deb` file, because I have debian-based distro, then I press sign-in button inside application which opens a new browser tab with GitHub login. Once I type my credentials and send that form away, the electron application should sign-in to github, usually I should see my repos, but this time I cannot. When I press `clone repository from the internet...` and chose GitHub, the application tells me to sign-in and when I do the process repeats (no login yet another browser tab and no login after).

### My tries to fix

1. I tried to fix this issue by removing config folder at `~/.config/GitHub Desktop` then signing-in again, issue remained.
2. I tried logging-off from my github account inside browser and then I tried to log-in via electron app
3. I combined steps 1 and 2 with no luck
I also use `visual studio code` which also is electron application and I have sucessfully signed in via microsoft account. 

### Release version

2.9.12

### Operating system

Linux Mint 

### Steps to reproduce the behavior

1. Install `.deb` package
2. open GitHub desktop application 
3. try logging-in with GitHub 
4. try cloning repo from internet

### Additional context

I am using firefox 102.0.1 as main browser
My operating system is LMDE 5 (codename Elsie)
I am using zsh as my main shell. (Electron app used to work, when I was using regular bash)
I have intel i5 haswell cpu 
I tried version 2.9.xx because I had the same issue with newer releases

**Comment by Asqit** [comment]
**update:** I tried switching my main shell from `zsh` to `bash` and I have sucessfully logged-in and everything seems to work. 
Once I tried logging-in a keyring windows showed up, which changed. (No keyring window with `zsh`)

**Comment by peter-power-594** [comment]
Bump impossible to signin here as well on Linux with OpenMandriva 4.3. Similar issue to @Asqit.
I'm using the 3.0.3 Standalone AppImage and need to authentificate via oauth through the browser. 

Then I'm stuck because the browser throw this kind of url 
```
x-github-desktop-dev-auth://oauth?code=XXXXX
```
not recognized by xdg-open. 

I tried to run the command via the terminal ion bash without success. In the best case I ended with an error, could move forward but after setting my account it was impossible to pull / push local repositories. 

When I check in the Options, I'm not signed in. Oauth token lost during the callback ?
I tried to clear the browser cache and retried, no success. 

Kind regards,

Peter

**Comment by shiftkey** [comment]
> Once I tried logging-in a keyring windows showed up

Please check the logs under `~/.config/GitHub Desktop/` for more information as I think there's a better error message shown in here than what we pass up to the user.

**Comment by peter-power-594** [comment]
Thank you very much for your promt answer @shiftkey 

Sure, here is the steps reproduced with a fresh start :

I open the application GitHubDesktop-linux-3.0.3-linux1.AppImage
```
2022-07-27T00:40:53.009Z - info: [ui] [AppStore] loading 2 repositories from store
2022-07-27T00:40:53.189Z - info: [ui] launching: 3.0.3-linux1 (Linux 5.16.13-desktop-1omv4003)
2022-07-27T00:40:53.194Z - info: [ui] execPath: '/tmp/.mount_GitHubtQiQTI/github-desktop'
2022-07-27T00:41:07.928Z - info: [ui] [SignInStore] initializing OAuth flow
2022-07-27T00:41:07.936Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=XXXXX&scope=repo%20user%20workflow&state=XXXX
```

This triggered the following url in the browser : 
```
x-github-desktop-dev-auth://oauth?code=XXXX&state=YYYYYYY
```

Then get an error with KIO client or similar depending on the graphical environment / browser about not knowing how to handle the url.
Then without closing the app (other issue) I tried to pass the url directly to the app through the Terminal :
```
[peter@concorde bin]$ cd bin
[peter@concorde bin]$ ./GitHubDesktop-linux-3.0.3-linux1.AppImage "x-github-desktop-dev-auth://oauth?code=XXXX&state=YYYYYYY"
```

Then the following error pops up : "The name is not activatable"
```
2022-07-27T00:41:45.562Z - info: [main] Received possible protocol arguments: 4
2022-07-27T00:41:45.563Z - info: [main] Processing protocol url
2022-07-27T00:41:45.571Z - info: [ui] [Dispatcher] requesting authenticated user
2022-07-27T00:41:46.407Z - info: [ui] [SignInStore] account resolved
2022-07-27T00:41:46.409Z - info: [ui] [AppStore] adding account peter-power-594 (Peter Power) to store
2022-07-27T00:41:46.421Z - error: [ui] Error adding account 'peter-power-594'
Error: The name is not activatable
```

Actually it looks like a dbus issue, isn't it? ... ><

**Comment by Asqit** [comment]
Hello, 
unfortunately, I can't give you more information, because as I mentioned above I have deleted `~/.config/GitHub Desktop/` 
I have tried to switch back to `zsh` and once again removing `~/.config/Git.....` folder, but the issue did not occur.
