### ISSUE TITLE
xdg-open do not work for Flatpak package (Deepin 20.6/Debian 10)

### ISSUE THREAD

**Issue by eduardomozart** [shiftkey/desktop#747]
### The problem

I installed the Flatpak package but when I click to sign-in it opens the browser and when I click at "xdg-open" a new window is open with a new GitHub Desktop instance instead of logging in.

### Release version

3.0.0-linux1 (x64)

### Operating system

Deepin 20.6 (Debian 10)

**Comment by shiftkey** [comment]
For Flatpak-specific issues it may be quicker to ask at https://github.com/flathub/io.github.shiftey.Desktop where the packaging is being managed...

**Comment by eduardomozart** [comment]
Sorry, I didn't know. I'll close this issue and open a new one there (https://github.com/flathub/io.github.shiftey.Desktop/issues/60).
Regards.
