### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by yllekz** [shiftkey/desktop#749]
### Operating System/Distribution

Which distribution of Linux are you using?
Linux Mint 21

### Installer

Which version of the app? Latest
Which installer type? apt

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

Followed the instructions on the readme. Apt errors out with "unable to locate package github-desktop"

**Comment by mwt** [comment]
Hi,

What exactly did you do and what output did you get?

```sh
wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
sudo apt update && sudo apt install github-desktop
```

I just tested in a fresh image and that worked.

**Comment by yllekz** [comment]
Hello, I'm also doing this from a fresh install in a VM, as I'm testing an install script.

I ran it this way:

```
wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
sudo apt-get update && sudo apt install github-desktop
```

The error seems to be ``429  Too Many Requests [IP: 52.8.238.184 443]``

The output was this:

```
Ign:1 https://packagecloud.io/shiftkey/desktop/any any InRelease
Hit:2 http://ppa.launchpad.net/hluk/copyq/ubuntu jammy InRelease               
Hit:3 http://mirror.us-ny2.kamatera.com/ubuntu jammy InRelease                 
Ign:4 http://packages.linuxmint.com vanessa InRelease                          
Get:5 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates InRelease [114 kB]
Hit:6 http://packages.linuxmint.com vanessa Release                            
Hit:7 https://download.onlyoffice.com/repo/debian squeeze InRelease            
Get:8 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]      
Hit:9 http://ppa.launchpad.net/lutris-team/lutris/ubuntu jammy InRelease       
Get:11 http://mirror.us-ny2.kamatera.com/ubuntu jammy-backports InRelease [99.8 kB]
Ign:12 https://download.docker.com/linux/ubuntu vanessa InRelease              
Get:13 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease [8,041 B]      
Err:14 https://download.docker.com/linux/ubuntu vanessa Release                
  404  Not Found [IP: 13.249.190.55 443]
Get:15 https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04 ./ InRelease [1,604 B]
Get:16 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/main amd64 Packages [502 kB]
Hit:17 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu jammy InRelease   
Get:18 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/main i386 Packages [269 kB]
Get:19 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [91.5 kB]
Get:20 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/universe i386 Packages [113 kB]
Get:21 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/universe amd64 Packages [210 kB]
Get:22 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [127 kB]
Get:23 http://mirror.us-ny2.kamatera.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:24 https://packages.microsoft.com/repos/vscode stable InRelease [3,959 B]  
Hit:25 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Get:26 http://mirror.us-ny2.kamatera.com/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [12.5 kB]
Get:27 https://dl.winehq.org/wine-builds/ubuntu jammy/main amd64 Packages [38.5 kB]
Get:28 https://dl.winehq.org/wine-builds/ubuntu jammy/main i386 Packages [38.5 kB]
Ign:1 https://packagecloud.io/shiftkey/desktop/any any InRelease
Get:29 http://security.ubuntu.com/ubuntu jammy-security/main i386 Packages [96.2 kB]
Get:30 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [266 kB]
Get:31 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages [315 kB]
Get:32 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [11.4 kB]
Get:33 http://security.ubuntu.com/ubuntu jammy-security/universe i386 Packages [55.3 kB]
Get:34 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [107 kB]
Get:35 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [10.1 kB]
Ign:1 https://packagecloud.io/shiftkey/desktop/any any InRelease               
Err:1 https://packagecloud.io/shiftkey/desktop/any any InRelease               
  429  Too Many Requests [IP: 52.8.238.184 443]
Reading package lists... Done                                                  
W: http://ppa.launchpad.net/hluk/copyq/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://download.docker.com/linux/ubuntu vanessa Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/lutris-team/lutris/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/./InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://ppa.launchpad.net/obsproject/obs-studio/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package github-desktop
```

**Comment by mwt** [comment]
Yes. The packagecloud repo has limited bandwidth.

>There are two options for this:
>
>* A [PackageCloud](https://packagecloud.io/) repository with excellent global connectivity but very limited bandwidth. **This option will stop working each month when the bandwidth limit is reached.**
> * A [mirror](https://mattwthomas.com/mirrors/) in the US which has effectively infinite bandwidth and performs well in most regions (especially the Americas and Europe).

To solve this, run:
```sh
wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
sudo apt update && sudo apt install github-desktop
```

The mirror actually now has great global connectivity as well. It has three distributed origins and a global CDN on top of them.

**Comment by yllekz** [comment]
Ah okay, using the mirror seemed to work. Thanks.

**Comment by zakwear** [comment]
> Yes. The packagecloud repo has limited bandwidth.
> 
> > There are two options for this:
> > 
> > * A [PackageCloud](https://packagecloud.io/) repository with excellent global connectivity but very limited bandwidth. **This option will stop working each month when the bandwidth limit is reached.**
> > * A [mirror](https://mattwthomas.com/mirrors/) in the US which has effectively infinite bandwidth and performs well in most regions (especially the Americas and Europe).
> 
> To solve this, run:
> 
> ```shell
> wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
> sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
> sudo apt update && sudo apt install github-desktop
> ```
> 
> The mirror actually now has great global connectivity as well. It has three distributed origins and a global CDN on top of them.

I tried PackageCloud and the mirror, neither are working for me:

`E: Unable to locate package github-desktop
`

**Comment by mwt** [comment]
> @zakwear 
> I tried PackageCloud and the mirror, neither are working for me:
> 
> `E: Unable to locate package github-desktop`

Did you forget to run `apt update` and is the repo listed there without errors when you run that command?

**Comment by zakwear** [comment]
> > @zakwear
> > I tried PackageCloud and the mirror, neither are working for me:
> > `E: Unable to locate package github-desktop`
> 
> Did you forget to run `apt update` and is the repo listed there without errors when you run that command?

I ran this block:

`wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
sudo apt update && sudo apt install github-desktop`

**Comment by zakwear** [comment]
:~ $ wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
:~ $ sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'
:~ $ sudo apt update && sudo apt install github-desktop
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:5 https://mirror.mwt.me/ghd/deb any InRelease
Ign:5 https://mirror.mwt.me/ghd/deb any InRelease
Ign:5 https://mirror.mwt.me/ghd/deb any InRelease
Err:5 https://mirror.mwt.me/ghd/deb any InRelease
  503  backend read error [IP: 151.101.41.91 443]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://mirror.mwt.me/ghd/deb/dists/any/InRelease  503  backend read error [IP: 151.101.41.91 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package github-desktop

**Comment by mwt** [comment]
That looks like a CDN node issue. Your can just try running `sudo apt update && sudo apt install github-desktop` again.

**Comment by zakwear** [comment]
Worked this time, thank you!!
