### ISSUE TITLE
Chinese version Linux GitHub Desktop

### ISSUE THREAD

**Issue by englianhu** [shiftkey/desktop#750]
### The feature request

> ```r
> :~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Redflag
> Description:    RedFlag Desktop 11.0
> Release:        11.0
> Codename:       Kunlun
> ```
> 
> triangular_flag_on_postcnbow_and_arrow [scibrokes/setup-centOS7-DO#2 (comment)](https://github.com/scibrokes/setup-centOS7-DO/issues/2#issuecomment-1221559222)
> 
> https://github.com/shiftkey/desktop/releases 
>
><img alt="" height="200" src="https://user-images.githubusercontent.com/7227582/185798363-cc4b020b-d6e0-47ba-97b8-372f2dadfea0.png">

https://github.com/scibrokes/setup-centOS7-DO/issues/2#issuecomment-1221559222

I installed GitHub Desktop on Linux 🚩🇨🇳🏹 RedFlag, a Chinese Linux based Operating System below are official wwebsite:

- http://www.chinaredflag.cn
- http://www.linuxsir.cn

May I know if GitHub peovide Chinese simplified and traditional language version similar with VSCode?

### Proposed solution

May I know if GitHub peovide Chinese simplified and traditional language version similar with VSCode?

### Additional context

May I know if GitHub peovide Chinese simplified and traditional language version similar with VSCode?

**Comment by shiftkey** [comment]
@englianhu thanks for your interest!

At the moment I don't have the bandwidth to support translation works. This needs to be handled by the main project, but sadly they're also in the same situation: [desktop#8289 (comment)](https://github.com/desktop/desktop/issues/8289#issuecomment-532742883)
