### ISSUE TITLE
GPG faild and failed to write commit object

### ISSUE THREAD

**Issue by jeromejermanus** [shiftkey/desktop#752]
### The problem

Whenever i commit my files i'm getting the GPG faild and failed to write commit object.

### Release version

Version 2.6.3-linux1

### Operating system

ubuntu 18.04

### Log files

[2022-08-24.desktop.production.log](https://github.com/shiftkey/desktop/files/9413235/2022-08-24.desktop.production.log)

### Screenshots

![git-error](https://user-images.githubusercontent.com/98008470/186341874-a3e1fb1c-7196-432b-b5f8-b4e05a20109b.png)

**Comment by shiftkey** [comment]
> Version 2.6.3-linux1

Please upgrade to a more recent version and retest - 2.6.3 is from February 2021 and is not something I wish to go back and reinstall

**Comment by KBeDevel** [comment]
I have this issue using version 3.3.8-linux1 from the shiftkey-packages RPM repo.

This does not happen after the execution of `git commit --signoff -m '...' [...files]` from the CLI. Then I can create signed commits from github-desktop, at least while the GPG key access is cached.
