### ISSUE TITLE
login fails after sign-in through browser

### ISSUE THREAD

**Issue by JonasunderscoreJones** [shiftkey/desktop#754]
### The problem

I found myself signed out of GitHub Desktop and followed the steps to log back in. After making it past the sign in prompt in my browser and the redirect back to GitHub Desktop, I get an error message saying 
**Unknown or unsupported transport “disabled” for address “disabled:”**
No matter how many times I try this (in multiple different browsers), the output is always the same

### Release version

3.0.5-linux1 (x64)

### Operating system

Arch Linux

### Steps to reproduce the behavior

1. get mysteriously signed out
2. click on File > Options > Accounts > Sign In (GitHub.com normal account) > Continue with browser
3. Sign in to your account in the browser and click on the prompt to redirect back
4. be presented with the error message **Unknown or unsupported transport “disabled” for address “disabled:”**

### Log files

a log file is generated in the moment when I am being redirected back to GitHub Desktop, however it is empty.

### Additional context

I installed the *github-desktop-bin* package on the AUR (I also tried the *github-desktop* package without any success) and gnome keyrings is installed on this system.

**Comment by shiftkey** [comment]
This is an environmental issue where the app is not able to interact with the credential store on the OS over `dbus`.

I don't have any fresh information to share on debugging this but https://github.com/atom/node-keytar/issues/132 has some notes that might work for your setup.

**Comment by JonasunderscoreJones** [comment]
Thanks a lot for the response. A clean reinstall of the program or using an alternative source (e.g. flatpak) solved the issue. Since reinstalling Linux seems to be simpler (which I do anyways, on occasion) and the possibility to switch to an alternative e.g. from flatpak, I will do that instead.
