### ISSUE TITLE
Amazon Linux 2 workspace install 

### ISSUE THREAD

**Issue by kalam-87** [shiftkey/desktop#760]
### Operating System/Distribution

Amazon Linux 2 (workspaces)

### Installer

Red Hat/CentOS/Fedora distributions
sudo yum install github-desktop

### What happened?
It says that it will install but nothing happens - even after I reboot the VM 

Loaded plugins: amzn_workspaces_filter_updates, halt_os_update_check,
              : priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package github-desktop.x86_64 0:3.0.5.linux1-1 will be installed

**Comment by shiftkey** [comment]
@kalam-87 I'm not sure how to investigate this further without any error message or thing that I can Google for. I also don't have the time to try and install Amazon Linux to reproduce this myself.
