### ISSUE TITLE
Authentication failed issue

### ISSUE THREAD

**Issue by pchest** [shiftkey/desktop#764]
### The problem

I am using the flatpak version of Github Desktop on Pop!_OS 22.04. I have an authenticated Github account, yet I repeatedly see "authentication failed" when attempting to push repository changes. Logging in and logging out does not eliminate this error, nor does restarting my computer or reinstalling this application. 

### Release version

3.0.7-linux1 x64

### Operating system

Pop!_OS 22.04

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Make commits to a repository
3. Push origin

### Log files

[2022-09-11.desktop.production.log](https://github.com/shiftkey/desktop/files/9543723/2022-09-11.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/23111423/189553472-a0a14fb9-e2e2-4aa2-862c-0fd695f2bda9.png)

**Comment by secondl1ght** [comment]
I am having the same issue - when I run `ssh -T git@github.com` I get `Hi secondl1ght! You've successfully authenticated, but GitHub does not provide shell access.` and I am able to use Git in the terminal. However when I try to use Git in GitHub Desktop I get this Authentication failed message.

**Comment by pchest** [comment]
@secondl1ght Exactly. Like you, I can use git via command line and in other applications, like RStudio. The only application that has given me trouble is GitHub Desktop.

**Comment by secondl1ght** [comment]
I tried installing the .deb package from this repo directly and it works fine now. So it seems to be an issue with installing via your distributions app store, I am using elementary OS for reference.

The version I installed is this one and it works: https://github.com/shiftkey/desktop/releases/tag/release-3.0.6-linux1 The version on my app store says it is 3.0.7 which is weird because it doesn't even look like that version has been officially released yet. :\

Not sure if I will receive auto-updates through the .deb package but I will use this for now.

**Comment by pchest** [comment]
Thanks! The deb version worked for me as well. As you say, the flatpak version is one version ahead of the github release. Perhaps they accidentally released the experimental version of the app on flatpak. Either way, I hope this issue with the version available on the Elementary and Pop!_OS app stores is addressed.

**Comment by Marcos-Barranquero** [comment]
Well this is weird. I'm having this issue when I try to clone from an organization repo but not when I'm cloning someone else's repos or mines. 

I'm was on the 3.0.5 version and found this, tried the 3.0.6 version  installing the .deb file, and I'm finding the same issues.

In windows version works properly trying the same repo.

Log file:  
[logfile.log](https://github.com/shiftkey/desktop/files/9629585/logfile.log)

I'd appreciate any help or workaround. Thanks!!

**Comment by PrimedPixel** [comment]
https://github.com/shiftkey/desktop/issues/759#issuecomment-1279756719

**Comment by shiftkey** [comment]
@Marcos-Barranquero 

> In windows version works properly trying the same repo.

The log file provides more details about why this is failing for you on Linux:

```
2022-09-22T21:40:25.529Z - error: [ui] Failed to look up repository clone info for 'https://github.com/PROPAGAMAP/yarn-template'
Error: Although you appear to have the correct authorization credentials, the `PROPAGAMAP` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. 
```

Please see #217 for more context on this error.

@pchest @secondl1ght @PrimedPixel if you could share a recent logfile from `~/.config/GitHub Desktop/` when you see this problem there may be more information about why this is failing to work for you...

**Comment by Marcos-Barranquero** [comment]
@shiftkey , you're correct. I've changed the organization config and now I can clone repos form Github desktop. Thanks for the input!

However, it still bugs me that I was able to clone the repos from Windows without changing the access restrictions.
