### ISSUE TITLE
Support For VSCodium

### ISSUE THREAD

**Issue by ShreshthTiwari** [shiftkey/desktop#765]
### The feature request

Please add a support for 
Open with VSCodium
in GitHub-Desktop

### Proposed solution

VSCodium is a fork of VSCode and is lighter so many people use it.
But, they cannot open it directly from the github app, instead they have to first open the folder and then launch codium in it.

**Comment by shiftkey** [comment]
:wave: please check our current support as I suspect there's a path that we're not detecting correctly:

https://github.com/shiftkey/desktop/blob/609b14bfbe6c98f5aa2d378cf33f5fd63361a118/app/src/lib/editors/linux.ts#L53-L58

Where is your VSCodium installed?

**Comment by ShreshthTiwari** [comment]
> desktop/app/src/lib/editors/linux.ts

inside snap folder probably

**Comment by shiftkey** [comment]
> inside snap folder probably

Please provide more details, as I need to understand more about your setup.

**Comment by Ujhhgtg** [comment]
There is another possible VSCodium location:
```
/usr/bin/codium-insiders
```
