### ISSUE TITLE
I deleted the repository on github & deleted the repository on Github. Tried to create a new one. Still opens old repo

### ISSUE THREAD

**Issue by venturaEffect** [shiftkey/desktop#767]
### The problem

HI!

I don't know why but when I first created a repo on Github desktop, it didn't add some files and folders from one folder. Tried to add this files and folders with no success. So I decided start from scratch deleting the repo on github.com and the repo on Github Desktop.

When trying to create a new one it tells me it is already a git repository and it doesn't allow me to create a new one. If I try to add this repository instead it still doesn't show all the folders and files.

How can I start from scratch and push all the files and folders completely?

I think this is a bug on Github Desktop. Any help will be really appreciated.

Thanks!

### Release version

Version 2.8.1-linux2

### Operating system

Ubuntu 18.04

### Steps to reproduce the behavior

1. Remove repository.
2. Create new one.
3. Not allowing, pointing to the repo removed.
5. When adding this repo instead still doesn't show all files.

### Log files

[2022-09-29.desktop.production.log](https://github.com/shiftkey/desktop/files/9683125/2022-09-29.desktop.production.log)
[2022-09-30.desktop.production.log](https://github.com/shiftkey/desktop/files/9683126/2022-09-30.desktop.production.log)

### Screenshots

![Selection_742](https://user-images.githubusercontent.com/29057173/193246392-9f7220ae-1627-49eb-b35c-308833145ba4.png)
![Selection
![Selection_744](https://user-images.githubusercontent.com/29057173/193246522-60566a97-d42f-4b76-95fb-e9188a86004f.png)
_743](https://user-images.githubusercontent.com/29057173/193246410-7e343121-5a05-4f45-887b-ece90163a0f1.png)

### Additional context

I've been searching everywhere and can't find any solution to this. As said, I tried deleting the repo on Github.com and then deleting it on Github Desktop. When trying to create one new it doesn't allow me because it tells the is already one. EVEN if I deleted on Github.com and on Github Desktop. How can I upload my project on Github.com? Thank you

**Comment by shiftkey** [comment]
> When trying to create a new one it tells me it is already a git repository and it doesn't allow me to create a new one. If I try to add this repository instead it still doesn't show all the folders and files.

I believe this is because the folder on disk still has a `.git` directory, which is how Git stores data for the repository. It may be hidden in your file explorer but that's the reason why it's suggesting you add the repository - it doesn't need to create the `.git` directory.

> How can I start from scratch and push all the files and folders completely?

Delete the `learnwel` folder from your system and try again.
