### ISSUE TITLE
V3.0.7 assets

### ISSUE THREAD

**Issue by Testato** [shiftkey/desktop#770]
### The problem

why the 3.0.7 version do not have a download link like the other versions ?

https://github.com/shiftkey/desktop/tags

### Release version

3.0.7

### Operating system

Ubuntu

**Comment by shiftkey** [comment]
> why the 3.0.7 version do not have a download link like the other versions ?

Because I put it aside and forgot to come back.

Anyway, the release is now available: https://github.com/shiftkey/desktop/releases/tag/release-3.0.7-linux1
