### ISSUE TITLE
Wayland mode stopped working

### ISSUE THREAD

**Issue by red5h4d0w** [shiftkey/desktop#771]
Wayland worked in the previous release using the `--ozone-platform=wayland` flag, but on 3.0.6 it now crashes before starting.

To reproduce: 
0. Use a distro running Wayland instead of X
1. Download the 3.0.6 .appimage  
2. make it executable
3. run the .appimage with the flag `ozone-platform=wayland`

Example of console output
```bash
./GitHubDesktop-linux-3.0.6-linux1.AppImage --ozone-platform=wayland
[975670:1009/112342.563871:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[975624:1009/112342.607649:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
Erreur de segmentation (core dumped)

**Comment by jcalonso** [comment]
Adding: `--enable-features=UseOzonePlatform` works for me.

`github-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by red5h4d0w** [comment]
It doesn't seem to work for me on two different machines. Maybe we have different versions of GitHub Desktop since it used to work?

Systems (2) info:
- OS: EndeavourOS
- Kernel: 5.19.13-arch1-1
- CPU: Intel i7-1165G7 / AMD Ryzen 3800X
- GPU: Intel Tigerlake-LP GT2 [Iris Xe Graphics] / Nvidia Geforce RTX 2060
- DE: Gnome 42.5
- Display Protocol: Wayland
 
 console output

```
./GitHubDesktop-linux-3.0.6-linux1.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland
[1162323:1009/224948.550403:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[1162269:1009/224948.585667:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
Erreur de segmentation (core dumped)

**Comment by jcalonso** [comment]
I am using this AUR package, not appimage:
`github-desktop-bin 3.0.6_linux1-1`

* Kernel 5.19.12-arch1-1
* ThinkPad T480s
* Wayland / Sway

I hope that helps

**Comment by shiftkey** [comment]
I'm not sure what changed between `3.0.5` and `3.0.6` as they both seem to be Electron 17 (`17.0.1` to be exact):

https://github.com/shiftkey/desktop/blob/2cd0ae9a18bcd8fa90befded91b2a468217571d4/package.json#L158

`3.0.8` and later versions are using Electron `19.0.0` so I think whatever changed here isn't worth digging too much into:

https://github.com/shiftkey/desktop/blob/1beb438cfd992737486ef5292daeed6c17639d26/package.json#L158

**Comment by red5h4d0w** [comment]
Not sure too, but I've tried the new release candidate and it seems I do not run anymore into this issue anymore. Might have been an upstream issue somewhere.

I'm looking forward to this release on the AUR!

**Comment by red5h4d0w** [comment]
I've tested 3.1.1 RC and it now works, so I'll be closing this as the original issue is gone
