### ISSUE TITLE
Where to edit the list of editors

### ISSUE THREAD

**Issue by avalonv** [shiftkey/desktop#773]
### Operating System/Distribution
Linux

Which distribution of Linux are you using?
Arch

### Installer

Which version of the app?
Which installer type? AUR

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

Hi Brendan, this is a really silly question which hopefully can be solved quickly, but after I pushed #757 I had a beautiful version of Desktop which supported integration with Neovide/Nvim-qt. I had a drive issue recently and had to reinstall everything and now I can't remember where to find the file to actually re-add those editors to my installation, this is driving me insane -_-. The [wiki](https://github.com/shiftkey/desktop/blob/linux/docs/technical/editor-integration.md#linux) covers this nicely, but the thing is I can't find /editors/linux.ts on my machine, so does that mean I need to rebuild it from source? I don't remember doing that last time.

**Comment by avalonv** [comment]
Okay, apologies, I figured it out on my own. Last time I did this I queried package files with `pacman -Ql github-desktop` which referred me to `/opt/github-desktop/resources/app/renderer.js`, and I inserted entries for neovide et al by searching for "neovim" to find where the list of editors starts. And I will never forget again because editing minified javascript is highly anxiety inducing. Although by the time 3.0.7 releases hopefully #757 will have been merged and this won't even be necessary.

Leaving this out here should anyone struggle with adding their own custom editors in the future, as I suspect some people come here asking how it's done and what's on the wiki is not necessarily applicable for existing installations (see #443). Would you accept a PR documenting that? Otherwise, feel free to close this.

**Comment by shiftkey** [comment]
Apologies for the delay in getting those changes out. I just haven't gotten around to adding your change to one of the releases, which is why it's not working and you're having to make changes manually.

I'll close this out once it's incorporated into a release (I thought the `3.0.7` release had it but that wasn't the case).

**Comment by shiftkey** [comment]
The feature should be available in [3.0.8](https://github.com/shiftkey/desktop/releases/tag/release-3.0.8-linux1) or later.

Thanks again for the addition!
