### ISSUE TITLE
Add install script

### ISSUE THREAD

**Issue by Rudxain** [shiftkey/desktop#778]
### The feature request

The install script will automatically follow the install instructions in README.md, and it should execute code based on existing cmds (IIRC, there's a cmd to check if another cmd is found in the `PATH`).

Since the script is the same regardless of release version, it shouldn't be located in GH-releases (although a link in the description may be helpful). Instead I propose that the script should be at the repo root

### Proposed solution

[from #797](https://github.com/Rudxain/desktop/blob/patch-1/install.sh)

**Comment by mwt** [comment]
You can use this as a starting point if you want:
```sh
wget -qO- "https://mirror.mwt.me/ghd/install.sh" | sudo sh
```

It's based off this gist: https://gist.github.com/mwt/1bc605c6fbcef451142cf145b8518439

**Comment by Rudxain** [comment]
Thank you for the info+help! I'll add support to other systems later (when I have more time)

**Comment by 0n1cOn3** [comment]
> ```shell
> wget -qO- "https://mirror.mwt.me/ghd/install.sh" | sudo sh
> ```

Just a note to it: 

APT only as I have seen. a check for rpm/dnf is highly requested 💯  :-)

**Comment by mwt** [comment]
> 
> > ```shell
> > wget -qO- "https://mirror.mwt.me/ghd/install.sh" | sudo sh
> > ```
> 
> Just a note to it: 
> 
> APT only as I have seen. a check for rpm/dnf is highly requested 💯  :-) 

This script already supports yum/dnf and zypper.

**Comment by 0n1cOn3** [comment]
Mhm... I use apt under special conditions under Fedora for my own developments and the script tries it with it. And not with dnf. 
Maybe it would make sense to specify the OS instead of package manager to solve this.

**Comment by mwt** [comment]
> Mhm... I use apt under special conditions under Fedora for my own developments and the script tries it with it. And not with dnf. 
> Maybe it would make sense to specify the OS instead of package manager to solve this.

I don't think it's a good idea to check for OS instead of the package manager. There are too many! 

I think it would be better to fix this edge case by checking to see if apt is installed using dnf/yum. That should be the necessary and sufficient condition for this subcase. Something like:

```sh
if dnf list installed | grep -qE '^apt\.x86_64'; then
    # this case
fi
```

I don't have a Fedora test environment setup anymore and am busy with job applications. So, I probably won't make any changes to this script until about March.

**Comment by 0n1cOn3** [comment]
Well that sounds promising too!
Didn't though about this step 🤦🏻‍♂️

**Comment by Rudxain** [comment]
I'm confused. Should I take inspiration from both scripts to modify my own? Or should I "add them as dependencies" to my script? (if so, which one: the dependent or the dependency?)

**Comment by mwt** [comment]
Feel free to copy and paste this and edit as you want:

https://github.com/mwt/mirror-scripts/blob/main/misc/universal-install.sh

I release this under the BSD 2-clause license.

**Comment by Rudxain** [comment]
@mwt the PR (and script) is ready! Did I made a mistake somewhere? (I'm asking just-in-case)

About the README, I don't know if [this line](https://github.com/Rudxain/desktop/blob/a69fa1f12d5f8a87341de8f2b514a5e39c4a826c/README.md?plain=1#L45) will work as intended, because the file-owner could be a standard-user, but `sudo` runs the cmd as super-user, which may imply the admin won't have execution permission

**Comment by mwt** [comment]
@0n1cOn3 I overhauled my install script to use a mix of OS detection and heuristics to guess the package manager. I'm keeping the script here now: https://github.com/mwt/mirror-scripts/blob/main/misc/universal-install.sh

You can test with

```sh
wget -qO- "https://mirror.mwt.me/shiftkey-desktop/install.sh" | sudo -s
```

I keep the install script working on the site using [this stub with nginx SSI](https://github.com/mwt/mirror-scripts/blob/main/misc/default-install.ssi.sh).

**Comment by Rudxain** [comment]
I think this issue can be closed, for now. Because of 2 reasons:

1. [That](https://github.com/shiftkey/desktop/pull/797#issuecomment-1437365156)
2. [This](https://github.com/shiftkey/desktop/issues/778#issuecomment-1510621764)
