### ISSUE TITLE
Don't use Electron 19.0.0 as it is broken on Buster/Bionic and older GLIBC distros

### ISSUE THREAD

**Issue by theofficialgman** [shiftkey/desktop#779]
### The problem

https://github.com/shiftkey/desktop/blob/6c9aa22035a5e0317d3089df1d8ce8513f5ea165/package.json#L160

https://github.com/shiftkey/desktop/blob/c506ab21c56895270a277582e969dd8786175f36/yarn.lock#L3887-L3894

refer to my blacklist of bad electron versions https://github.com/Botspot/pi-apps/issues/1930

you need to upgrade to 19.0.5+ for this to be fixed.

In general the original release of electron for a specific version is always terrible, never use it until it is many releases in. I realize this version bump from 17.X to 19.0.0 came from upstream but it is just something that you need to check especially on linux.

### Release version

3.1.1-linux1

### Operating system

Bionic/Buster

**Comment by shiftkey** [comment]
> you need to upgrade to 19.0.5+ for this to be fixed.

While I wait to queue this up, [`3.0.7`](https://github.com/shiftkey/desktop/releases/tag/release-3.0.7-linux1) is the latest release on Electron 17 for folks who encounter this issue.

**Comment by theofficialgman** [comment]
@shiftkey I should have been more specific.
19.0.0-19.0.4 were only broken on arm64 (as Google disabled the glibc reversion script on arm64 only due to issues with ChromeOS arm64).
You aren't in need of a release since you don't build from that but regardless it would be good to change in the repo.

**Comment by shiftkey** [comment]
Closing this out as [`3.1.5-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-3.1.5-linux2) has the last v19 release (`development` is currently on v22 so the next release will jump to that).
