### ISSUE TITLE
Unable to push

### ISSUE THREAD

**Issue by FHLX-J** [shiftkey/desktop#784]
### The problem

Unexpectedly, an issue indicating that my authentication failed has appeared. I have not been able to correct the issue despite trying this so far:

- Logging out & back into my account
- Reinstalling GitHub
- Upgrading Ubuntu to 22.10 (from 22.04)

The significantly more bizarre part is that this is not a problem on my Windows computers; it works fine and I am able to push stuff no problem. This seems to be an issue that is specific to Linux or Ubuntu specifically. I have repositories that are saved on my Dropbox, but this again does not seem to be a problem since all of my Windows devices seem to work fine even with the repositories stored in my Dropbox.

### Release version

2.9.3-linux3

### Operating system

Ubuntu 22.10

### Steps to reproduce the behavior

1. Make a test text file on a repository
2. Commit it
3. Push it, which causes this error to show up.

### Screenshots

https://cdn.discordapp.com/attachments/781556908602818581/1035334889265967124/Screenshot_from_2022-10-27_19-22-56.png

**Comment by shiftkey** [comment]
Please have a look at the log files located at `~/.config/GitHub Desktop/` and organized by date as this will have more details about why this is failing
