### ISSUE TITLE
Application fails to start by GUI method on Kubuntu 22.04

### ISSUE THREAD

**Issue by Mathiaszero** [shiftkey/desktop#787]
### The problem

After installation on Kubuntu 22.04, GitHub Desktop fails to start and shows a crash face icon on the bottom right corner of the taskbar, after selecting it on the Application Launcher.  

After clicking on the crash face, a box will pop up saying that the application has closed unexpectedly.  See logs for more info (var/log/syslog).  It is believed that the version is 3.1.1 based on installation, but when opening alternatively, the menu item is greyed out.

### Release version

3.1.1

### Operating system

Kubuntu 22.04

### Steps to reproduce the behavior

1. Click on Application Launcher
2. Search for "GitHub"
3. Click on GitHub Desktop application

### Log files

Nov  2 13:23:37 xxx1055127 systemd[1]: Started crash report submission.
Nov  2 13:23:37 xxx1055127 whoopsie[761375]: [13:23:37] Using lock path: /var/lock/whoopsie/lock
Nov  2 13:23:37 xxx1055127 whoopsie[761375]: [13:23:37] Parsing /var/crash/_usr_lib_github-desktop_github-desktop.0.crash.
Nov  2 13:23:37 xxx1055127 whoopsie[761375]: [13:23:37] Uploading /var/crash/_usr_lib_github-desktop_github-desktop.0.crash.
Nov  2 13:23:38 xxx1055127 whoopsie[761375]: [13:23:38] Sent; server replied with: No error
Nov  2 13:23:38 xxx1055127 whoopsie[761375]: [13:23:38] Response code: 200
Nov  2 13:23:38 xxx1055127 whoopsie[761375]: [13:23:38] Reported OOPS ID 7833c00a-5adb-11ed-9a32-fa163e993415
Nov  2 13:23:38 xxx1055127 systemd[1]: whoopsie.service: Deactivated successfully.

**Comment by pnathan01** [comment]
I face this issue as well, and hasn't been resolved yet

**Comment by shiftkey** [comment]
Are you able to run the program from the command line - `github-desktop` may be on your PATH, but I think being able to tell _how_ the app is crashing for you would be a good first step...

**Comment by Mathiaszero** [comment]
I was able to run the command as long as it required --no-sandbox flag.  Where can I find the correct log to show how it crashed?

**Comment by shiftkey** [comment]
@Mathiaszero please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by Mathiaszero** [comment]
There's an error, when I attempted to enter the folder, one level up: "Could not enter folder /root/.config/GitHub Desktop."

**Comment by shiftkey** [comment]
Could the space in the directory name be an issue here?
