### ISSUE TITLE
source.list web page breaking up

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#794]
### The problem

Whenever trying to retrieve the package from the 'https://packagecloud.io/shiftkey/desktop/packages/any' the following messages show up on the terminal:

```
Err:4 https://mirror.mwt.me/ghd/deb any InRelease                      
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
Hit:6 https://packagecloud.io/shiftkey/desktop/ubuntu focal InRelease
Reading package lists... Done
W: GPG error: https://mirror.mwt.me/ghd/deb any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
E: The repository 'https://mirror.mwt.me/ghd/deb any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
![Screenshot_2022-11-13_01-43-33](https://user-images.githubusercontent.com/58838266/201506187-2d47973e-aae4-4c28-9104-3196e35d2eba.png)

```

This starts happening after running either of the commands:

`sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'`

`sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'`

The page is broken ('https://packagecloud.io/shiftkey/desktop/any')

### Release version

 github-desktop_3.0.5-linux1_amd64.deb (I believe it goes across the table)

### Operating system

20.04, 22.04

### Steps to reproduce the behavior

Debian/Ubuntu distributions

First install our GPG certificate:

1. wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null

To setup the package repository, run one of these commands:

# if you want to use packagecloud.io
2. sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'

# if you want to use the US mirror
2. sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'

3. sudo apt update && sudo apt install github-desktop

### Log files

Err:4 https://mirror.mwt.me/ghd/deb any InRelease                      
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
Hit:6 https://packagecloud.io/shiftkey/desktop/ubuntu focal InRelease
Reading package lists... Done
W: GPG error: https://mirror.mwt.me/ghd/deb any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
E: The repository 'https://mirror.mwt.me/ghd/deb any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
![Screenshot_2022-11-13_01-43-33](https://user-images.githubusercontent.com/58838266/201506187-2d47973e-aae4-4c28-9104-3196e35d2eba.png)

### Screenshots

![Screenshot_2022-11-13_01-43-33](https://user-images.githubusercontent.com/58838266/201506313-1c02ca9b-bac5-43d3-a51f-5f3bf965c3d8.png)

**Comment by shiftkey** [comment]
@mwt it looks like there are some issues here with the signature being verified. 

```
Reading package lists... Done
W: GPG error: https://mirror.mwt.me/ghd/deb any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
E: The repository 'https://mirror.mwt.me/ghd/deb any InRelease' is not signed.
```


Aside from recommending @victorkolis try the commands again, is there anything else worth troubleshooting?

**Comment by mwt** [comment]
This is still a mirror of the packagecloud repo. It works for me. He probably needs to run the following command again:

```sh
wget -qO - https://mirror.mwt.me/ghd/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null
```

That being said, I think the certificate has changed from packagecloud -> your repo. So, it's probably best to fix this after I change sources (further explanation in #834).

**Comment by shiftkey** [comment]
> That being said, I think the certificate has changed from packagecloud -> your repo. 

Yeah, I'm not across all of the rough edges of GPG and I created a fresh certificate (instead of wrapping the one from PackageCloud) so apologies for that.

**Comment by mwt** [comment]
> > That being said, I think the certificate has changed from packagecloud -> your repo.
> 
> Yeah, I'm not across all of the rough edges of GPG and I created a fresh certificate (instead of wrapping the one from PackageCloud) so apologies for that.

Yeah, I don't even know if you could have kept using the packagecloud one anyway. This is fine. It's not a lot of work for me.

**Comment by ghost** [comment]
Rerunning the commands fixed it. Thank you!
