### ISSUE TITLE
Conflict with mailspring while installing Github Desktop

### ISSUE THREAD

**Issue by 0n1cOn3** [shiftkey/desktop#796]
### Operating System/Distribution

Which distribution of Linux are you using?

Fedora 36

### Installer

Which version of the app?

idk - The package which is the latest on repo.

Which installer type?
dnf

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.
#
sudo dnf install github-desktop
Last check for expired metadata: 0:06:35 on Sun 13 Nov 2022 22:54:25 ago.
Dependencies are resolved.

Package Architecture Version Package Source Size

Install:
github-desktop x86_64 3.0.5.linux1-1 shiftkey 94 M

Transaction summary

Install 1 package

Total size: 94 M
Installation size: 322 M
Is this OK? [y/N]: y
Packages downloaded:
[SKIPPED] github-desktop-3.0.5.linux1-1.x86_64.rpm: Already downloaded                                                                                                                                                                     
Transaction verification is running
Transaction verification was successful.
Transaction is being tested
The downloaded packages have been cached until the next successful transaction.
You can remove cached packages with the command "dnf clean packages".
Error: Transaction test failed:
  File /usr/lib/.build-id/0c/42bafd2a685e794204ca324424b97defdf517f from the installation of github-desktop-3.0.5.linux1-1.x86_64 collides with the file from the package mailspring-1.10.5-0.1.x86_64
  File /usr/lib/.build-id/1a/748b384a307a449725ccf1f8fa7a1e80b7e03e from the installation of github-desktop-3.0.5.linux1-1.x86_64 conflicts with the file from the package mailspring-1.10.5-0.1.x86_64
  File /usr/lib/.build-id/3e/5ddfa3f763787484222e0129355a46f5852c53 from the installation of github-desktop-3.0.5.linux1-1.x86_64 conflicts with the file from the package mailspring-1.10.5-0.1.x86_64
  File /usr/lib/.build-id/70/1a8c90b80fc7b21ab802d31ef1dc84564abfb2 from the installation of github-desktop-3.0.5.linux1-1.x86_64 conflicts with the file from the package mailspring-1.10.5-0.1.x86_64
  File /usr/lib/.build-id/9c/ea93fad89b2657dd6c86ceaefd966401c3ec72 from the installation of github-desktop-3.0.5.linux1-1.x86_64 conflicts with the file from the package mailspring-1.10.5-0.1.x86_64
  File /usr/lib/.build-id/be/3de1e7b9f4091f69dfd725fb88791aa6c6a9e2 from the installation of github-desktop-3.0.5.linux1-1.x86_64 conflicts with the file from the package mailspring-1.10.5-0.1.x86_64
  File /usr/lib/.build-id/dd/6005cc96f2e73704ae040e75e5eb6e9db79858 from installation of github-desktop-3.0.5.linux1-1.x86_64 conflicts with file from package mailspring-1.10.5-0.1.x86_64

**Comment by shiftkey** [comment]
Looks like both packages are generating the same file on disk and one of them needs a workaround like this to disable it: https://github.com/microsoft/vscode/pull/116105

I'm not sure how to pass this into [`electron-installer-redhat`](https://www.npmjs.com/package/electron-installer-redhat) which handles the packaging for us.

**Comment by Rewangmanik4** [comment]
![Screenshot_20221120-185643_1](https://user-images.githubusercontent.com/119468300/204696458-c45547fd-b38a-4298-af0d-5bf66c80dd8e.png)

**Comment by Rewangmanik4** [comment]
![Uploading Screenshot_20221120-205524.png…]()

**Comment by 0n1cOn3** [comment]
> ![Screenshot_20221120-185643_1](https://user-images.githubusercontent.com/119468300/204696458-c45547fd-b38a-4298-af0d-5bf66c80dd8e.png)
> 
> 

What does an Indonesian bank have to do with this issue? 
This is spam and does not belong here. 
Either a bot or an A... the rest You can guess.

**Comment by sarim** [comment]
Umm I'm guessing the big hash looking filename is actually a hash? Why two project is creating the same hash?

**Comment by shiftkey** [comment]
> By default, `rpmbuild` generates build_id links, which are debugging symbols for binaries included in a package.

**Comment by sarim** [comment]
Yeah, sorry, commented too fast. The draft PR you made is the best solution right now imo. An issue needs to be filled in electron-installer-redhat so they make it a configurable option. These days its very common to have multiple electron-based apps running in a machine, so I don't see any other solution other than disabling the build_id links.
