### ISSUE TITLE
I can't create a pull request

### ISSUE THREAD

**Issue by titleofliberty** [shiftkey/desktop#798]
### The problem

After pushing up a branch I am offered the chance to create a pull request but the button is disabled. I can however, go to the GitHub website and create the pull request there.

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Pop_OS 22.04 LTS

### Steps to reproduce the behavior

Push changes to GitHub
Create Pull request disabled

### Screenshots

![image](https://user-images.githubusercontent.com/20482035/202796316-dbd79afb-d646-4ac7-97f2-31415d56da82.png)

**Comment by shiftkey** [comment]
The rules for this button are the same as the menu:

https://github.com/shiftkey/desktop/blob/b4dd5c72825b9fdcafa000da9fb53511fa4c7a90/app/src/lib/menu-update.ts#L290-L292

Any clues about the branch that you're on at the moment that might match up with these conditions?

**Comment by ahmedash95** [comment]
the same issue happens to me. the branch is new and I've full access to the repo
