### ISSUE TITLE
cannot login in github-desktop

### ISSUE THREAD

**Issue by uniquegch** [shiftkey/desktop#799]
### The problem

I have arco linux installed and cannot update github-desktop. I have totally removed it from the cache from yay and installed the flatpac package, but when I try to login it fails. I can login without any problems using a webbrowser. I do have MFA enabled.
This is very frustrating. 

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Arco Linux Kernel: 6.0.8-arch1-1

### Steps to reproduce the behavior

1. starting github-desktop
2. try to login, entering username and password
3. required to enter MFA based code.
4. not possible

**Comment by Firestar-Reimu** [comment]
have you installed `gnome-keyring`?

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
