### ISSUE TITLE
App Icon is missing in some places in GNOME

### ISSUE THREAD

**Issue by ziggy42** [shiftkey/desktop#8]
### Description

The app icon is missing in some places:
![screenshot from 2017-12-14 15-28-43](https://user-images.githubusercontent.com/4258550/33997125-b224c1dc-e0e3-11e7-9668-83dfaf6114e1.png)
![screenshot from 2017-12-14 15-29-19](https://user-images.githubusercontent.com/4258550/33997126-b2416cba-e0e3-11e7-93eb-23273bad17a8.png)

I'm using the Appimage. I think that's the problem, because I have the exact same problem with NoSQLBooster and they're using Appimages too.

### Version

**GitHub Desktop version:** 1.0.11
**OS version:** Fedora 27 with GNOME

### Steps to Reproduce

1. Launch the app
2. Observe the icon is missing

**Expected behavior:** The icon is present

**Actual behavior:** The icon is not present

**Reproduces how often:** 100%

**Comment by picandocodigo** [comment]
This happens when running the app from source in development mode too. It could be some configuration that's missing in electron specific to Linux.

**Comment by shiftkey** [comment]
The fact this occurs in development mode as well as after installation probably means it's something related to the configuration values passed to `electron-packager`. And I did find [this](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon) important note in the docs:

> Linux: this option is not required, as the dock/window list icon is set via [the icon option in the BrowserWindow constructor](http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions). Please note that you need to use a PNG, and not the OS X or Windows icon formats, in order for it to show up in the dock/window list. Setting the icon in the file manager is not currently supported.
 
Long story short, we should be able to fix this by setting `icon` as part of constructing the BrowserWindow instance here: https://github.com/desktop/desktop/blob/master/app/src/main-process/app-window.ts#L36-L62

We should only do this for Linux, which we can check at runtime using the `__LINUX__` global.

**Comment by Croydon** [comment]
I can confirm the same issue for Fedora 26 with KDE.
