### ISSUE TITLE
The name org.freedesktop.secrets was not provided by any .service files”

### ISSUE THREAD

**Issue by Firestar-Reimu** [shiftkey/desktop#800]
### The problem

if you do not install `gnome-keyring`

you will encounter `The name org.freedesktop.secrets was not provided by any .service files”` when login, fetching, pushing git repos.

this is not good for KDE and other non-Gnome users.

### Release version

3.1.1

### Operating system

Archlinux

**Comment by ManuelWDev** [comment]
At least for KDE users KWalletManager should provide org.freedesktop.secrets, too.

**Comment by Firestar-Reimu** [comment]
No, I installed kwalletmanager from archlinux, and rebooted, and:

```
2023-01-11T14:40:53.110Z - info: [ui] [AppStore] adding account Firestar-Reimu (Firestar-Reimu) to store
2023-01-11T14:40:53.120Z - error: [ui] Error adding account 'Firestar-Reimu'
Error: The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by shiftkey** [comment]
https://github.com/shiftkey/desktop/issues/7 is the first discussion about this, and I'd recommend looking for alternatives to `gnome-keyring` that support `libsecret` if you want to avoid GNOME dependencies. 

KWallet's support seems to be in KDE Neon but I don't think it's enabled by default - https://invent.kde.org/frameworks/kwallet/-/merge_requests/11 has more context.
