### ISSUE TITLE
sign with github.com

### ISSUE THREAD

**Issue by CristianoTobias** [shiftkey/desktop#801]
### The problem

![Screenshot_2022-11-25_15_07_58](https://user-images.githubusercontent.com/62651576/204038633-16a695e6-67a0-437d-ae53-155b61f02ae6.png)

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

kali linux

### Steps to reproduce the behavior

file
option
sign with github.com
sign in with your browser
error ->
Failed to open URL
The especified location is not supported
auth ...
code...
state....

### Screenshots

![Screenshot_2022-11-25_15_07_58](https://user-images.githubusercontent.com/62651576/204038661-4d42e640-ef0a-4f7b-a1be-ac178290c6ba.png)

**Comment by markcst** [comment]
same here

**Comment by shiftkey** [comment]
This is the protocol handler integration that the browser is using to re-activate the application. If that's not able to resolve the current application then it's going to impact the sign-in flow. 

As Kali is a Debian-based distribution I'm assuming this stuff works as it does on other Debian flavours, but could there be something about this distribution that means the protocol handlers are limited or disabled for some users?
