### ISSUE TITLE
cannot log in to GitHub: home directory is prefixed to URL by GitHub Desktop

### ISSUE THREAD

**Issue by GrahamAsher** [shiftkey/desktop#803]
### The problem

When I try to log in to GitHub using 'sign in using your browser', the authentication URL is corrupted by the addition of my home directory at the start. Thus I get an error message like this (I've X-ed out sensitive parts):

/home/graham/https:/github.com/login/oauth/authorize?client_id=xxxxxxxxxxxxxxx&scope=repo%20user%20workflow&state=xxxxxxxxxxxxxxxxxxx: No such file or directory

Obviously this URL won't work because the string /home/graham/ has been added at the start.

### Release version

3.1.1

### Operating system

Ubuntu 19.10

### Steps to reproduce the behavior

start GitHub Desktop
try to log in to GitHub using browser

**Comment by aryehbeitz** [comment]
I tried to reproduce: I went into the File menu, Options, Accounts and clicked the "Sign out" button. Then I closed and reopened Github Desktop(version 3.1.1) and signed in from there. The url was fine and I was logged in. Good luck!

```
Operating System: Linux Mint 20.2
Kernel: Linux 5.4.0-132-generic
Architecture: x86-64

```

**Comment by GrahamAsher** [comment]
Thank you for your wishes of good luck. However, the issue remains to be fixed. The home directory should not be prefixed to the URL.

**Comment by ijuuu930104** [comment]
- [ ] - [[]()]()

**Comment by shiftkey** [comment]
> start GitHub Desktop

@GrahamAsher can you be more explicit here about how you're launching the app? Via the command line, or the app launcher, or something else?

**Comment by GrahamAsher** [comment]
I tried both methods of starting GitHub Desktop (command line and app launcher). The same problem occurred for both methods.

I think it might be best to look at the way the URL is built up from the information supplied. It looks like something's wrong there. By the way, I use GitHub Desktop without problems on my Mac and on my other Linux computer.

**Comment by shiftkey** [comment]
The other bit that I'm curious about @GrahamAsher is where that error was occurring - is there a stack trace or component that comes with the "directory + url" message that'll help with tracing into this area?

**Comment by GrahamAsher** [comment]
@shiftkey Brendan, I did answer both questions in fact. But I understand that you can't prioritise this issue.

**Comment by GrahamAsher** [comment]
Closing this - didn't mean it to be reopened.
