### ISSUE TITLE
Visual Studio Code launches instead of the file manager application.

### ISSUE THREAD

**Issue by Arinze-Odukwe** [shiftkey/desktop#804]
### The problem

I created a new folder for the local repository. However, whenever I select the project files I want to move to my newly created repository folder by clicking the "show in your file manager" button, Visual Studio Code launches. And When Visual Studio Code is launched, Github Desktop freezes until Visual Studio Code is closed.

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Debian 10

**Comment by shiftkey** [comment]
@Arinze-Odukwe are you able to walk me through the steps to reproduce this? I'd like to understand how these are linked, as the selected editor and shell integration should be separate:

> However, whenever I select the project files I want to move to my newly created repository folder by clicking the "show in your file manager" button, Visual Studio Code launches.

Also, are you able to share what your configured integrations are currently (available under the Options menu):

![](https://user-images.githubusercontent.com/359239/215345212-4c05a20a-d9c3-4bbd-97ee-e07fabf5dfa2.png)
