### ISSUE TITLE
Git hub not  taking passwords and no way to log in from CLI

### ISSUE THREAD

**Issue by GregJetter** [shiftkey/desktop#805]
### The problem

using github desktop I cannot authenticate , passwords don't work , no way to generate a token because the web page  produces an error whenever I click on my user icon upper right of screen. so I have no way of  using the service I pay for  , how about you fix it or refund my money ?

### Release version

2.0.4 linux

### Operating system

linux ubuntu 14.04

**Comment by ijuuu930104** [comment]
> ### The problem
> 
> using github desktop I cannot authenticate , passwords don't work , no way to generate a token because the web page  produces an error whenever I click on my user icon upper right of screen. so I have no way of  using the service I pay for  , how about you fix it or refund my money ?
> 
> ### Release version
> 
> 2.0.4 linux
> 
> ### Operating system
> 
> linux ubuntu 14.04
> 
> ### Steps to reproduce the behavior
> 
> _No response_
> 
> ### Log files
> 
> _No response_
> 
> ### Screenshots
> 
> _No response_
> 
- - > ### Additional[@]() context@

> 
> _No response_

**Comment by shiftkey** [comment]
> `2.0.4 linux`
> `linux ubuntu 14.04`

@GregJetter this version is about 3 years old. Are you able to upgrade to a more recent release?

I also need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
