### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by maysadeli** [shiftkey/desktop#806]
### The problem

I can not sign in, it keeps loading but nothing ever happens.
I allowed access to my github account. I don't know what else i can do.

### Release version

i can't open the 'about github desktop' it is in light gray and when i click nothing happens

### Operating system

ubuntu 22

### Steps to reproduce the behavior

1. Sign In to Github
2. Password from GitHub Account
3. Permission to Github Desktop access my Github account
4. Page "you are being redirected to Github Desktop" loading forever
5. I click "if your browser is not redirecting you, please click here"
6. Github Desktop 'sign in' button has a loading icon next to it and nothing happens.

**Comment by bob448** [comment]
Me too..

**Comment by antonellocaroli** [comment]
same problem here

gentoo linux

**Comment by markcst** [comment]
same here

**Comment by IllTamer** [comment]
the same
archlinux use appimage

**Comment by IllTamer** [comment]
Hey guys, do you install these two dependencies? After I install, restart the system, and then the functions of such desktop applications will return to normal
```shell
sudo pacman -S gnome-keyring libsecret
```

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
