### ISSUE TITLE
Crash on lanch

### ISSUE THREAD

**Issue by Sandroid75** [shiftkey/desktop#810]
### The problem

every time I start Github Desktop, it crashes !!! I have to lanch two or three times....

HW info:
MB ASUS P5K
RAM 4Gb
CPU Intel Core 2 Duo E8500 x2
GPU nVidia Quadro K2200
SSD 1Tb

SW Info:
Fedora Linux 37 (Workstation Edition) 64bit
GNOME 43.2

these are the system info, but the problem has always been there both with previous versions of Fedora 35 and 36 and with previous versions of GitHub Desktop.

### Release version

3.1.1

### Operating system

Fedora Linux 37 (Workstation Edition) 64bit

### Steps to reproduce the behavior

lanch GitHub Desktop

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by Sandroid75** [comment]
Now I solved! i had problems until i used the version installed with Gnome-Software, then i uninstalled it (also delete the logs) and i installed it again from shell following your instruction in README.MD, now i have no more problems, THANK YOU!!!
