### ISSUE TITLE
Authentication Failed with PAT

### ISSUE THREAD

**Issue by MuhammadTahac3** [shiftkey/desktop#812]
### The problem

when ever i try to authenticate with PAT it does not authenticate on Linux Ubuntu

### Release version

3.0.1

### Operating system

 Linux Ubuntu

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
