### ISSUE TITLE
Run multiple instances of the app at the same time

### ISSUE THREAD

**Issue by onattech** [shiftkey/desktop#813]
### The feature request

Hi,
Is there a way to run multiple instances of the app at the same time? I have multiple workspaces for multiple jobs that I work for and would like have each project to run its own instance of Github Desktop.

Thank you for the hard work!

### Proposed solution

None

**Comment by shiftkey** [comment]
This is not supported, and I'll point you to https://github.com/desktop/desktop/issues/3606 which is a length discussion about it.

For feature requests that aren't Linux-specific please submit these to the main project.
