### ISSUE TITLE
The menu bar always has a light appearance (flatpak app version)

### ISSUE THREAD

**Issue by oleksiisedun** [shiftkey/desktop#814]
### The problem

The menu bar always has a light appearance, even if I set the Dark appearance in the app options.

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Linux Mint 21.1

### Steps to reproduce the behavior

1. Launch the app
2. Set Dark appearance in the app Options
3. Observe menu bar

### Screenshots

![Screenshot from 2022-12-25 14-53-45](https://user-images.githubusercontent.com/22419456/209468735-3e44735a-81bd-4b33-acb8-5fe9d3f1a828.png)

**Comment by oleksiisedun** [comment]
The issue reproduces only with flatpak app version.

**Comment by hoggatt** [comment]
Have the same issue with just the flatpak version. It also doesn't respect the system's dark theme (but does for the normal .rpm and .deb versions... not that this is an issue since you can manually set the theme).

**Comment by oleksiisedun** [comment]
CNR in Version 3.2.1-linux2 (x64).
