### ISSUE TITLE
Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

### ISSUE THREAD

**Issue by aminya** [shiftkey/desktop#815]
### The problem

When launching GitHub Desktop from the terminal on WSL, I get this error constantly in the terminal. It doesn't seem to be important because the app works as intended, but this error is repeated each time I do something.

### Release version

All versions? 
Tested on 3.0.5 and 3.1.1

### Operating system

Ubuntu 20.04

### Steps to reproduce the behavior

- Launch github-desktop from the terminal
- Do things

### Screenshots

```
[1307:0105/142537.925841:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "UNIX")
```

**Comment by shiftkey** [comment]
I don't have access to a WSL environment to test this but my gut feeling is that this is a Chromium message.

[`dbus/bus.cc` seems to be this file, and the relevant error message is here](https://source.chromium.org/chromium/chromium/src/+/main:dbus/bus.cc;l=398-402?q=bus.cc&ss=chromium)


```cpp
  if (!connection_) {
    LOG(ERROR) << "Failed to connect to the bus: "
               << (error.is_set() ? error.message() : "");
    return false;
  }
```

Given the mention of `dbus` I wonder if that's part of the issue. https://github.com/shiftkey/desktop/issues/623 comes to mind as an issue where authentication was affected, and we found a workaround to use `dbus-launch github --exit-with-x11` but that didn't seem to be a full fix.

I'm not sure of the impact here (perhaps we could suppress these messages when running from the terminal) but I wonder if there's something underlying here that we should be aware of...
