### ISSUE TITLE
showing authentication failed even after loggen into the github desktop

### ISSUE THREAD

**Issue by karthikgowda785** [shiftkey/desktop#817]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by karthikgowda785** [comment]
Refered following link to install

https://www.javatpoint.com/github-desktop-for-ubuntu#:~:text=First%20of%20all%2C%20we%20need,2.6.3%2Dlinux1.deb

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

I'm also not willing to support arbitrary versions of the application (2.6.3 is almost two years behind the latest release) so please ensure you are also using a newer version of the application.

**Comment by karthikgowda785** [comment]
Please send me the documentation for how to install github desktop for
ubuntu

Because I tried shift key
When I try to clone the repo using url
It's through authentication error.

It would be a great help if you share the document with me

Regards,
Karthik S

**Comment by shiftkey** [comment]
@karthikgowda785 the instructions in the README are intended to help users install the application: https://github.com/shiftkey/desktop#repositories

**Comment by karthikgowda785** [comment]
Thanks for your reply, will try this, if any problem faced will let you know

Regards,
Karthik S
