### ISSUE TITLE
Organization managed repos

### ISSUE THREAD

**Issue by svenbrill** [shiftkey/desktop#818]
### The problem

Github Desktop does not show me my organization managed repos after authentification.

### Release version

3.1.1

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

Goto "Let's get started" screen and login. Your account needs to be a part of an organization on GitHub and you should be able to clone organizaion manged repos. These repos are not listed. Also you cannot clone them, if you use the direct URL. You will get an auth error.

**Comment by shiftkey** [comment]
This is a known limitation of the Linux build: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

> The GitHub Desktop application is an OAuth application, but this fork does not have the same permissions as the app does on Windows and macOS, which manifests in a couple of different ways:
>
> -    the "Clone a Repository" view does not show all organization repositories
>    pushes to a repository owned by an organization may be rejected with a generic error message
>
> The root cause of this is organizations by default will have "OAuth App access restrictions" enabled, which blocks the GitHub Desktop development app that is used by this fork.
>
> **Workaround**: ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization) to the GitHub Desktop development app.

#72 is the tracking issue for this issue, but I'm not satisfied with either option here:

> > What you suggest to do then? On windows and Mac is working properly.
> 
> This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in [desktop#1525](https://github.com/desktop/desktop/issues/1525) (please upvote if you care) but #72 is tracking this known limitation.
> 
> As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.
> 
> Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.
> 
> The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.
