### ISSUE TITLE
The setuid sandbox is not running as root. Common causes 

### ISSUE THREAD

**Issue by Salim9304** [shiftkey/desktop#820]
### The problem

I am getting the same error from the last decade https://github.com/shiftkey/desktop/issues/222.
It helped me to add "--no-sandbox"

But now I can't login. through the browser. When I try to log in (success), I get endless CPU usage and nothing

![0](https://user-images.githubusercontent.com/61138725/213672571-df6c5910-1961-4417-bb61-a90ebe84df4e.png)
![00](https://user-images.githubusercontent.com/61138725/213672580-edeac7ce-0063-4880-a207-9f92e6456b48.png)

GitHubDesktop-linux-3.1.1-linux1.AppImage
Debian 10

### Release version

3.1.1

### Operating system

Debian 10

**Comment by shiftkey** [comment]
Asking for logs or more information about whether this is still relevant.
