### ISSUE TITLE
Linux: Git lfs files does not fetch

### ISSUE THREAD

**Issue by Watcher3056** [shiftkey/desktop#821]
### The problem

Git LFS files won`t fetch by github-desktop. Fetching, repository lfs init - does not help at all. Only manual "git lfs pull" from command line helps, but even after this action github-desktop marks lfs-files that was loaded as "changed".

### Release version

3.1.1

### Operating system

Linux

### Steps to reproduce the behavior

UPD: problem appears to be in filenames. While Linux is case-sensitive and file with name art.Png and art.png is two different files then on windows they are the same. So every commit cause problems with such files. Renaming files windows-side does not help at all - git for windows even not notice the difference and still will cause conflicts.

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

I also suspect that some normalization is needed of files to get them consistent across both operating systems, but I'm not sure of a way to do this easily with LFS-backed files in a Git repository.

**Comment by Watcher3056** [comment]
I was able to resolve it by renaming *.Png and *.FBX to lower-case on Linux machine with double-commander then commit it. After fetching windows will not notice any change for this files.
So its easy-fixable, but better to not encounter such problems. Maybe some automatic mechanism inside git or github-desktop could prevent such soft-conficts?

**Comment by shiftkey** [comment]
> Maybe some automatic mechanism inside git or github-desktop could prevent such soft-conficts?

At the moment this is technically challenging, as it depends on the underlying filesystem. The last time I looked into this I wrote up some notes https://github.com/desktop/desktop/issues/2672#issuecomment-329011490 and with some additional notes from another Git contributor in https://github.com/desktop/desktop/issues/2672#issuecomment-338171399 but I'd recommend checking the `core.ignorecase` setting (which should be part of the defaults set by the Git installation).

Closing this out as worked around, as I believe this is not something that can be resolved just for this package.

**Comment by Watcher3056** [comment]
I will add a little more info about what is going on. So previously on windows I added *.fbx and *.png to track by git-lfs, so those files(including *.Png and *.FBX) was loaded to git-lfs. On linux after fetching repository git on linux machine successfully fetched *.png and *.fbx files from git-lfs, but not for *.Png and *.FBX. For the last two file types git on linux only fetched files with their lfs-related metadata. After all if you will try to make commit from linux you will overwrite git-lfs files for *.Png and *.FBX with their lfs-metadata... and thats really bad. But on windows git will notice that *.Png and *.FBX lfs-metadata files is the same as *.png and *.fbx and will load them automatically or something. Next commit from windows will overwrite previously pushed lfs-metadata files linux-side with actual files and every commit from linux then again windows will everytime overwrite those files.
