### ISSUE TITLE
dark mode 

### ISSUE THREAD

**Issue by aniketraz** [shiftkey/desktop#822]
please add dark mode

**Comment by shiftkey** [comment]
This is available under the Appearance section of the Options menu:

![](https://user-images.githubusercontent.com/359239/215342738-e59fdae3-3a16-459b-aaea-e1775c12e119.png)

The documentation also has more details on this: https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/setting-a-theme-for-github-desktop
