### ISSUE TITLE
Git hooks that call external programs do not work in Flatpak

### ISSUE THREAD

**Issue by aminya** [shiftkey/desktop#828]
### The problem

I am not sure where I should open this issue, but in case Flatpak is supported here:

When using the Flatpak version of GitHub Desktop, the Git hooks that call the external programs (e.g. Node, npm, yarn, etc.), will not work. The program cannot call them.

### Release version

3.1.5-linux2

### Operating system

Kubuntu 22.10

### Steps to reproduce the behavior

1. Create a git hook (e.g. using Husky)
2. Call an external program inside the hook

**Comment by shiftkey** [comment]
This is probably better being opened in https://github.com/flathub/io.github.shiftey.Desktop/ as that repository handles the Flatpak customizations on top of this project.
