### ISSUE TITLE
github desktop readme

### ISSUE THREAD

**Issue by hanbing5210** [shiftkey/desktop#83]
Since it is Linux, could you please make a corresponding readme file and do not refer to the official one? Because the official version doesn't yet support Linux

**Comment by bb441db** [comment]
This repository get merged upstream, so probably not until it has an official release I assume

**Comment by hanbing5210** [comment]
Then if I write another readme file as you see fit can I add it in? @bb441db

**Comment by bb441db** [comment]
@hanbing5210 Maybe a `linux.md`, I don't think we should modify or replace the `readme.md` file

**Comment by hanbing5210** [comment]
ok @bb441db

**Comment by shiftkey** [comment]
We can make the README in this fork say whatever we need it to say. @hanbing5210 go for it.
