### ISSUE TITLE
Application Blank - Not responding to any Action

### ISSUE THREAD

**Issue by sadorect** [shiftkey/desktop#830]
### The problem

I am using Ubuntu 22.04 with Github Desktop.
The app is not responding to any menu command, Its just there, not active. Not useful

### Release version

 (2.9.3-linux3)

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

1. Install the app normally as you would any other app. After installation, try to perform any action at all from the menu. It's all blank. No response

### Screenshots

![Screenshot from 2023-02-17 10-15-38](https://user-images.githubusercontent.com/24244892/219603288-441ca750-9f11-429b-800c-06884fdd266b.png)

**Comment by shiftkey** [comment]
Can you access the **View** | **Toggle Developer Tools** menu item? That should open a console which might show some errors that would explain what's happening.

If nothing is present there, I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.
