### ISSUE TITLE
🆕  [Debian/Ubuntu users] Feedback on new package feed

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#834]
I'm looking to migrate away from PackageCloud for many reasons, and after a bunch of false starts I have a new server setup with the necessary keys and bits that this should work as-is:

https://apt.packages.shiftkey.dev/

Relevant steps:

 - install the GPG key associated with the signing key

```
wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.asc > /dev/null
```

 - add the package feed to `apt` 

```
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/shiftkey-packages.gpg] https://apt.packages.shiftkey.dev/ubuntu/ any main" > /etc/apt/sources.list.d/shiftkey-packages-desktop.list'
```

 - Refresh the feed

```
sudo apt update
```

If you have a previous version of `github-desktop` installed, you should be able to upgrade to the latest release from earlier this week, otherwise you can manually install the latest version `3.1.7-linux1`:

```
sudo apt install github-desktop
```

Before I update the docs to point everyone to this I figure I'd open this up to anyone who wants to test it out and ensure I haven't missed any details...

**Comment by mwt** [comment]
Cool. I have a script that I've been using for a while over here:

https://github.com/mwt/desktop-makerepo

The script scans the github releases and adds new apt/rpm to the repos. There might be something useful in there that you can use (particularly the steps after scanning releases for rpm).

**Edit:** The repo works for me.

**Comment by jfgordon2** [comment]
Tested successfully on Ubuntu 22.04 - looking great 👍

**Comment by mwt** [comment]
I should set the origin of my mirror to these two new feeds so that packages are updated. If I do this, I think existing users will get a gpg error because they key likely changed. I think this is fine.

I could get around this by setting the new repo in a different path (i.e. not `/ghd/`) and put a more descriptive error on the old path that sends people to an issue that explains the transition. This is probably the smart way.

**Comment by mwt** [comment]
I set up a mirror from the new origins here:
https://mirror.mwt.me/shiftkey-desktop/

It seems to be working. There are two options:

1. Move `/shiftkey-desktop/` -> `/ghd/`. Users will get a GPG error and come to the repo where they will see updated instructions.
2. Update readme to `/shiftkey-desktop/` and put a descriptive error on `/ghd/` so that users understand that they have to transition.

I think 2 will result in fewer issues being filed here.

**Comment by phanect** [comment]
@shiftkey Thanks for creating the official deb repository!

Unfortunately, it didn't work as expected on my end.
I use KDE neon, an Ubuntu variant. I think it should not so different from Ubuntu.

I installed the GPG key and repository info as written in the README.

```shell
wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.asc > /dev/null
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/shiftkey-packages.asc] https://apt.packages.shiftkey.dev/ubuntu/ any main" > /etc/apt/sources.list.d/shiftkey-packages.list'
```

Then I ran `sudo apt update`, but GPG error was raised.

```shell
$ sudo apt update
Hit:1 http://download.virtualbox.org/virtualbox/debian jammy InRelease
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                     
Hit:3 https://apt.releases.hashicorp.com jammy InRelease                                                                                                                                                          
Hit:4 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                                   
Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
Hit:6 https://deb.nodesource.com/node_18.x jammy InRelease                                                                                                                                                        
Get:7 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                                                                         
Hit:8 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                                           
Get:9 https://apt.packages.shiftkey.dev/ubuntu any InRelease [1,226 B]                                                                                           
Err:9 https://apt.packages.shiftkey.dev/ubuntu any InRelease                                                                                                                   
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                    
Hit:11 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease                                                                         
Get:12 http://archive.neon.kde.org/user jammy InRelease [178 kB]                                                                                       
Reading package lists... Done                                                                       
W: GPG error: https://apt.packages.shiftkey.dev/ubuntu any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
E: The repository 'https://apt.packages.shiftkey.dev/ubuntu any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$
$ cat /etc/apt/sources.list.d/shiftkey-packages.list 
deb [arch=amd64 signed-by=/etc/apt/keyrings/shiftkey-packages.asc] https://apt.packages.shiftkey.dev/ubuntu/ any main
$ ls /etc/apt/keyrings/shiftkey-packages.asc
/etc/apt/keyrings/shiftkey-packages.asc
```

I found InRelease may have wrong `Origin` and `Label`: https://apt.packages.shiftkey.dev/ubuntu/dists/any/InRelease
In InRelease, `Origin` and `Label`'s values are packages.shiftkey.**online**, while the actual hostname is apt.packages.shiftkey.**dev**.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: packages.shiftkey.online
Label: packages.shiftkey.online
Codename: any
Date: Sun, 19 Feb 2023 20:32:57 UTC
Architectures: amd64
Components: main
Description: Package feed for GitHub Desktop on Linux packages
...
```

Can you check the configuration?
Thanks!

**Comment by mwt** [comment]
@phanect afaik origin and label shouldn't cause an error like that. For example, these always differ from the hostname of any mirror (such as the official Ubuntu mirrors) and there is no issue caused by this.

The InRelease has the right signature. Perhaps there is something wrong with your local copy of `shiftkey-packages.asc`? Try running:

```sh
gpg --show-keys /etc/apt/keyrings/shiftkey-packages.asc
```

The output should be something like:
```
pub   ed25519 2023-02-19 [SC] [expires: 2028-02-18]
      4E02A356A18314B00A481F067FC979028B1997C1
uid                      Brendan Forster <packages@brendanforster.com>
sub   cv25519 2023-02-19 [E] [expires: 2028-02-18]
```

If not, then the first command (`wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.asc > /dev/null`) should be rerun.

**Comment by shiftkey** [comment]
@phanect that's a good point - I'll get that into an update when I generate the next release, but I don't think that's why you're seeing GPG errors with the feed. As @mwt mentioned, let's confirm the GPG key you have is which one we expect to have...

**Comment by phanect** [comment]
@mwt @shiftkey Thanks for your assistance.

I have run the command, and it shows the identical result as @mwt's output:

```shell
$ gpg --show-keys /etc/apt/keyrings/shiftkey-packages.asc
pub   ed25519 2023-02-19 [SC] [expires: 2028-02-18]
      4E02A356A18314B00A481F067FC979028B1997C1
uid                      Brendan Forster <packages@brendanforster.com>
sub   cv25519 2023-02-19 [E] [expires: 2028-02-18]
```

> afaik origin and label shouldn't cause an error like that.

If I remember correctly, it caused an error when I was trying to create a deb repo.
Actually, I was working on creating [a deb repo for github-desktop](https://github.com/phanect/apt.phanective.org) these two or three days. (I didn't know @shiftkey is working on creating the repo by himself :joy:)
While I was working on it, I changed the hostname from deb.phanective.org to apt.phanective.org, but I forgot to change the `Origin` and `Label`, and it caused an error.

KDE neon uses PackageKit as a package manager frontend while it is based on apt and deb, so perhaps it might have more strict restrictions than Ubuntu.

**Comment by mwt** [comment]
Hmm. The only thing I can think of is that there is possibly some other file in `/etc/apt/sources.list.d/` with the same link without the `signed-by` part?

> KDE neon uses PackageKit as a package manager frontend while it is based on apt and deb, so perhaps it might have more strict restrictions than Ubuntu.

I don't think so. Too much would break. An example from the legacy packagecloud mirror:
https://mirror.mwt.me/ghd/deb/dists/any/InRelease

The purpose of `origin` is not to copy the hostname. Apt already knows the hostname. It's purpose is to give the canonical source.

**Edit:** Maybe also try replacing the `.asc` extension with `.gpg`. Apt might be assuming that the key is armored.

**Comment by phanect** [comment]
@mwt Thanks.

> Hmm. The only thing I can think of is that there is possibly some other file in `/etc/apt/sources.list.d/` with the same link without the `signed-by` part?

I confirmed there is only one file pointing to apt.packages.shiftkey.dev repo in /etc/apt/sources.list.d.

```shell
$ cat /etc/apt/sources.list.d/*
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main
deb http://archive.neon.kde.org/user jammy main
deb-src http://archive.neon.kde.org/user jammy main
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x jammy main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x jammy main
deb https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy main
deb [arch=amd64 signed-by=/etc/apt/keyrings/shiftkey-packages.asc] https://apt.packages.shiftkey.dev/ubuntu/ any main
deb http://download.virtualbox.org/virtualbox/debian jammy contrib
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
```

I also tried to your mirror (mirror.mwt.me) and `apt update` also raised the same error.

```shell
$ sudo apt update
Hit:1 http://download.virtualbox.org/virtualbox/debian jammy InRelease
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                     
Hit:4 http://packages.microsoft.com/repos/code stable InRelease                                                                                                             
Hit:5 https://apt.releases.hashicorp.com jammy InRelease                                                                                                                                                          
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                                                                         
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                                                                                  
Get:8 https://deb.nodesource.com/node_18.x jammy InRelease [4,563 B]                                                                                                                                     
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                                                                                           
Get:10 https://apt.packages.shiftkey.dev/ubuntu any InRelease [1,226 B]                                                                                                                                           
Err:10 https://apt.packages.shiftkey.dev/ubuntu any InRelease                                                                                                                                                     
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
Get:11 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease [1,226 B]                                                                                                                     
Err:11 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease                                                                                                                                                   
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
Get:12 https://deb.nodesource.com/node_18.x jammy/main amd64 Packages [777 B]                                                                                                 
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [41.6 kB]                                                                                          
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [15.2 kB]                                                              
Hit:15 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease                                
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [101 kB]                     
Get:17 http://archive.neon.kde.org/user jammy InRelease [178 kB] 
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [267 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Reading package lists... Done               
W: GPG error: https://apt.packages.shiftkey.dev/ubuntu any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
E: The repository 'https://apt.packages.shiftkey.dev/ubuntu any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://mirror.mwt.me/shiftkey-desktop/deb any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
E: The repository 'https://mirror.mwt.me/shiftkey-desktop/deb any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

> **Edit:** Maybe also try replacing the `.asc` extension with `.gpg`. Apt might be assuming that the key is armored.

~~Unfortunately, it didn't solve the problem.~~

```shell
$ sudo mv /etc/apt/keyrings/shiftkey-packages.asc /etc/apt/keyrings/shiftkey-packages.gpg
$ sudo mv /etc/apt/keyrings/mwt-desktop.asc /etc/apt/keyrings/mwt-desktop.gpg
$ sudo apt update
Hit:1 http://download.virtualbox.org/virtualbox/debian jammy InRelease
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
Hit:3 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                                   
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                     
Hit:5 https://apt.releases.hashicorp.com jammy InRelease                                                                                                                                                          
Hit:6 https://deb.nodesource.com/node_18.x jammy InRelease                                                                                                                                                        
Get:7 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease [1,226 B]                                                                                                                                          
Err:7 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease                                                                                                                                                  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
Hit:8 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                                 
Hit:9 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                       
Hit:10 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                  
Get:11 https://apt.packages.shiftkey.dev/ubuntu any InRelease [1,226 B]                                                          
Err:11 https://apt.packages.shiftkey.dev/ubuntu any InRelease                     
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
Hit:12 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease
Get:13 http://archive.neon.kde.org/user jammy InRelease [178 kB]
Reading package lists... Done    
W: GPG error: https://mirror.mwt.me/shiftkey-desktop/deb any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
E: The repository 'https://mirror.mwt.me/shiftkey-desktop/deb any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://apt.packages.shiftkey.dev/ubuntu any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FC979028B1997C1
E: The repository 'https://apt.packages.shiftkey.dev/ubuntu any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Thanks anyway for your advice.

**Comment by mwt** [comment]
> Unfortunately, it didn't solve the problem.

You need to change the `signed-by` strings in the source list file to use the new path that you moved the files to.

**Comment by phanect** [comment]
> > Unfortunately, it didn't solve the problem.
> 
> You need to change the `signed-by` strings in the source list file to use the new path that you moved the files to.

Year, I just noticed I forgot to change `signed-by` in the shiftkey-packages.list :sweat_smile:
By changing that, the problem was resolved.

```shell
$ sudo apt update
Hit:1 http://download.virtualbox.org/virtualbox/debian jammy InRelease
Hit:2 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                                   
Hit:3 https://deb.nodesource.com/node_18.x jammy InRelease                                                                                                                                                        
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                     
Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
Hit:6 https://apt.releases.hashicorp.com jammy InRelease                                                                                                                                                          
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                                                                  
Get:8 https://apt.packages.shiftkey.dev/ubuntu any InRelease [1,226 B]                                                                                                                    
Get:9 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease [1,226 B]                                                                                                                  
Get:10 https://apt.packages.shiftkey.dev/ubuntu any/main amd64 Packages [617 B]                                                                                     
Hit:11 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                   
Hit:12 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                    
Get:13 https://mirror.mwt.me/shiftkey-desktop/deb any/main amd64 Packages [617 B]                                                
Hit:14 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease
Get:15 http://archive.neon.kde.org/user jammy InRelease [178 kB]
Fetched 181 kB in 2s (87.1 kB/s)   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
$ cat /etc/apt/sources.list.d/shiftkey-packages.list 
deb [arch=amd64 signed-by=/etc/apt/keyrings/shiftkey-packages.gpg] https://apt.packages.shiftkey.dev/ubuntu/ any main
```

Thanks so much for your assistance!

**Comment by mwt** [comment]
> > > Unfortunately, it didn't solve the problem.
> > 
> > You need to change the `signed-by` strings in the source list file to use the new path that you moved the files to.
> 
> Year, I just noticed I forgot to change `signed-by` in the shiftkey-packages.list :sweat_smile:
> By changing that, the problem was resolved.
> 
> ```shell
> $ sudo apt update
> Hit:1 http://download.virtualbox.org/virtualbox/debian jammy InRelease
> Hit:2 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                                   
> Hit:3 https://deb.nodesource.com/node_18.x jammy InRelease                                                                                                                                                        
> Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                     
> Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                                                    
> Hit:6 https://apt.releases.hashicorp.com jammy InRelease                                                                                                                                                          
> Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                                                                  
> Get:8 https://apt.packages.shiftkey.dev/ubuntu any InRelease [1,226 B]                                                                                                                    
> Get:9 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease [1,226 B]                                                                                                                  
> Get:10 https://apt.packages.shiftkey.dev/ubuntu any/main amd64 Packages [617 B]                                                                                     
> Hit:11 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                   
> Hit:12 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                    
> Get:13 https://mirror.mwt.me/shiftkey-desktop/deb any/main amd64 Packages [617 B]                                                
> Hit:14 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu jammy InRelease
> Get:15 http://archive.neon.kde.org/user jammy InRelease [178 kB]
> Fetched 181 kB in 2s (87.1 kB/s)   
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> 1 package can be upgraded. Run 'apt list --upgradable' to see it.
> $ cat /etc/apt/sources.list.d/shiftkey-packages.list 
> deb [arch=amd64 signed-by=/etc/apt/keyrings/shiftkey-packages.gpg] https://apt.packages.shiftkey.dev/ubuntu/ any main
> ```
> 
> Thanks so much for your assistance!

Oof. No problem!

I guess some versions of apt assume that any `.asc` key is ASCII-armored.

@shiftkey readme should probably have all instances of `.asc` replaced with `.gpg`.

**Comment by phanect** [comment]
I opened #839 to fix the README.

**Comment by phanect** [comment]
@mwt Oops, you also wrote the same patch. Then just close my PR :)

**Comment by mwt** [comment]
> @mwt Oops, you also wrote the same patch. Then just close my PR :)

No, that's good! I just won't finish making mine.

**Comment by remlapmot** [comment]
Thanks so much for making this Linux build and adding this package feed - I really appreciate it.

I'm leaving this comment in case anyone else hits the very minor issue I did.

I found that (perhaps because I haven't added a package feed before) that the directory `/etc/apt/keyrings` was missing on my Ubuntu Focal in WSL. So when I first ran you commands they failed with the following message
```
$ wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.gpg > /dev/null
[sudo] password for tom:
tee: /etc/apt/keyrings/shiftkey-packages.gpg: No such file or directory
```

This was simply solved by creating the directory with 
```bash
sudo mkdir /etc/apt/keyrings
```
and then running your instructions.

**Comment by mwt** [comment]
> I found that (perhaps because I haven't added a package feed before) that the directory /etc/apt/keyrings was missing on my Ubuntu Focal in WSL.

That's a good point. I think I had to create this directory the first time even in Jammy. Though, I might be misremembering. If you want to rectify:

```sh
sudo mkdir -p /etc/apt/keyrings && wget ...
```

(at some point, these may just become lines in an install script...)

**Comment by phanect** [comment]
I found the majority of the third-party repositories let the users create GPG keys under /usr/share/keyrings/.

e.g.
- [Nodesource's Node.js distribution](https://github.com/nodesource/distributions)
- [Hashicorp](https://developer.hashicorp.com/vagrant/downloads)
- [VirtualBox](https://www.virtualbox.org/wiki/Linux_Downloads)
- Ubuntu's default keyring

@remlapmot Does /usr/share/keyrings exist by default on WSL Ubuntu?

@shiftkey @mwt If it exists by default, it might be better to change the command as follows:

```diff
- wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.gpg > /dev/null
+ wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/shiftkey-packages.gpg > /dev/null
```

**Comment by remlapmot** [comment]
> @remlapmot Does /usr/share/keyrings exist by default on WSL Ubuntu?

Thanks @phanect. I confirm that `/usr/share/keyrings` is present in my Ubuntu Focal on WSL. I don't remember creating it, so I assume that it is there by default.

**Comment by mwt** [comment]
@phanect Good point. It's there on Debian 11 too and even contains the default Debian keys.

**Comment by akwala** [comment]
> I found InRelease may have wrong `Origin` and `Label`: https://apt.packages.shiftkey.dev/ubuntu/dists/any/InRelease
> In InRelease, `Origin` and `Label`'s values are packages.shiftkey.**online**, while the actual hostname is apt.packages.shiftkey.**dev**.

+1

**Comment by shiftkey** [comment]
@phanect @akwala this was fixed as today's release - `apt update` will probably ask you to confirm the change:

> I found InRelease may have wrong `Origin` and `Label`: https://apt.packages.shiftkey.dev/ubuntu/dists/any/InRelease
> In InRelease, `Origin` and `Label`'s values are packages.shiftkey.**online**, while the actual hostname is apt.packages.shiftkey.**dev**.

**Comment by charlotth** [comment]
Hello, 

Fresh install of Ubuntu 22.04 here.
```bash
$ wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.gpg > /dev/null
gpg: no valid OpenPGP data found
```

**Comment by shiftkey** [comment]
@tcharlot-datasweet I had a a check and the `gpg.key` file should be valid and contain data:

<img width="532" src="https://user-images.githubusercontent.com/359239/225605720-573f14d2-bed5-468d-8c57-1c8657b1e1e3.png">

Are you able to confirm the file downloads as expected to your machine (and no errors are causing the download to fail)?

```
$ wget -O - https://apt.packages.shiftkey.dev/gpg.key | cat
```

Otherwise I wonder what version of `gpg` you have installed (probably a long shot given it's a fresh 22.04 install).

**Comment by charlotth** [comment]
Hi, 
Today the `$ wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/shiftkey-packages.gpg > /dev/null`  is ok :+1:

**Comment by mwt** [comment]
Also relevant to #835, I have properly disconnected https://mirror.mwt.me/ghd/ and put an error that directs people to the new link.

**Comment by EllenLouiseRipley** [comment]
Hi,
I tried on a rasperry pi 4.
I could install on 32 bit OS the .deb directly.
But I failed on the latest 64 Bit OS, then I tried the package feed, failed too:
thomas@raspisd02:~ $ wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/shiftkey-packages.gpg > /dev/null
thomas@raspisd02:~ $ sudo sh -c 'echo "deb [arch=aarch64 signed-by=/usr/share/keyrings/mwt-desktop.gpg] https://mirror.mwt.me/shiftkey-desktop/deb/ any main" > /etc/apt/sources.list.d/mwt-desktop.list'
thomas@raspisd02:~ $ sudo apt update && sudo apt install github-desktop
OK:1 http://archive.raspberrypi.com/debian bookworm InRelease
OK:2 http://raspbian.raspberrypi.com/raspbian bookworm InRelease                                    
Holen:3 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease [1.228 B]                          
Fehl:3 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7FC979028B1997C1
Paketlisten werden gelesen... Fertig
W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Schlüssel ist im veralteten Schlüsselbund trusted.gpg gespeichert (/etc/apt/trusted.gpg), siehe den Abschnitt MISSBILLIGUNG in apt-key(8) für Details.
W: GPG-Fehler: https://mirror.mwt.me/shiftkey-desktop/deb any InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 7FC979028B1997C1
E: Das Depot »https://mirror.mwt.me/shiftkey-desktop/deb any InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
Thanks and Best regards,
Thomas

**Comment by mwt** [comment]
@EllenLouiseRipley You put a certificate file in `/usr/share/keyrings/shiftkey-packages.gpg` but apt is looking for it in `/usr/share/keyrings/mwt-desktop.gpg`.

Easiest fix is:

```sh
sudo mv /usr/share/keyrings/shiftkey-packages.gpg /usr/share/keyrings/mwt-desktop.gpg
```

**Comment by shiftkey** [comment]
> I tried on a rasperry pi 4.
> I could install on 32 bit OS the .deb directly.

I haven't published any of the ARM packages to this feed currently

**Comment by EllenLouiseRipley** [comment]
Well, the package GitHubDesktop-linux-armhf-3.2.7-test7.deb did install on Pi4 running Raspbian buster 32-Bits. more than once.

**Comment by mwt** [comment]
> Well, the package GitHubDesktop-linux-armhf-3.2.7-test7.deb did install on Pi4 running Raspbian buster 32-Bits. more than once.

He just means that the packages are not in the apt repo.

**Comment by niccokunzmann** [comment]
For me to follow and give input, it would be nice to see exactly at the top of the issue the current commands that I should give feedback to. I am scrolling through and seems that there has been progress and I do not know what to do give feedback to now. Could you help me by pointing to the current process?

---

where to update the information

I came from here: https://www.linuxcapable.com/how-to-install-github-desktop-on-ubuntu-linux/
and here: https://www.githubdesktop.com/github-desktop-linux-install/
They will need updating to the latest process.

**Comment by mwt** [comment]
@niccokunzmann, the current process is in the readme. The linuxcapable article is up to date. That other one is not.

**Comment by shiftkey** [comment]
Closing this out as things appear to be stable, and I suspect folks are fine to open fresh issues for whatever support questions they have

**Comment by theofficialgman** [comment]
both debian package feeds are out of date (only have 3.3.8)
