### ISSUE TITLE
🆕 [RPM users] Feedback on new package feed

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#835]
I'm looking to migrate away from PackageCloud for many reasons, and after a bunch of false starts I have a new server setup with the necessary keys and bits that this should work as-is:

https://rpm.packages.shiftkey.dev/

Relevant steps:

 - install the GPG key associated with the signing key

```
> sudo rpm --import https://rpm.packages.shiftkey.dev/gpg.key
```

*Note:* I've stumbled into some issues with importing the key on specific versions of `rpm` - https://github.com/rpm-software-management/rpm/issues/1977 - which meant that CentOS 8.5 didn't work for me, but I haven't been able to spot why the key wasn't being consumed (it's generated using SHA256) and I was able to test this with RHEL 9.1 and didn't see any issues with this step.

 - add the package feed to `apt` 

```
> sudo sh -c 'echo -e "[shiftkey-packages]\nname=GitHub Desktop\nbaseurl=https://rpm.packages.shiftkey.dev/rpm/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://rpm.packages.shiftkey.dev/gpg.key" > /etc/yum.repos.d/shiftkey-packages.repo'
```

*Note:* I've set `gpgcheck=1` and `repo_gpgcheck=1` here as that seems to work with this setup, but if you encounter GPG issues with the key it may be worth tweaking this setup to relax the checks.

 - Refresh the feed

```
> sudo yum update
```

If you have a previous version of `github-desktop` installed, you should be able to upgrade to the latest release from earlier this week, otherwise you can manually install the latest version `3.1.7-linux1`:

```
> sudo yum install github-desktop
```

Before I update the docs to point everyone to this I figure I'd open this up to anyone who wants to test it out and ensure I haven't missed any details...

**Comment by sarim** [comment]
gpg imports and repo works, but interesting error when actually installing it. Fedora 36.

```
  ~    sudo dnf update github-desktop
Last metadata expiration check: 0:00:20 ago on Tue 21 Feb 2023 04:42:43 AM +06.
Dependencies resolved.
========================================================================================================================
 Package                      Architecture         Version                        Repository                       Size
========================================================================================================================
Upgrading:
 github-desktop               x86_64               3.1.7.linux1-1                 shiftkey-packages                91 M

Transaction Summary
========================================================================================================================
Upgrade  1 Package

Total download size: 91 M
Is this ok [y/N]: y
Downloading Packages:
GitHubDesktop-linux-3.1.7-linux1.rpm                                                    2.5 MB/s |  91 MB     00:35
------------------------------------------------------------------------------------------------------------------------
Total                                                                                   2.5 MB/s |  91 MB     00:35
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/a2/562c52725bb7caa27cd0de814ec368b8c45e7f from install of github-desktop-3.1.7.linux1-1.x86_64 conflicts with file from package insomnia-2022.5.1-1.x86_64
  ```

**Comment by shiftkey** [comment]
@sarim yeah, that's something known #796

**Comment by Larbear71** [comment]
I don't know what will work with windows but as far as Mac simply Mac OS is flawless with the new release. Besides a miracle the others are worthless.

**Comment by ucihariskoding** [comment]
```
error: can't create transaction lock on /usr/lib/sysimage/rpm/.rpm.lock (Permission denied)
error: https://rpm.packages.shiftkey.dev/gpg.key: key 1 import failed.
```

im using opensuse tumbleweed slowroll

**Comment by shiftkey** [comment]
@ucihariskoding that looks like a permissions error at the OS level, which I think is blocking the GPG key import. Did you run the command as `sudo`?

**Comment by ucihariskoding** [comment]
> @ucihariskoding that looks like a permissions error at the OS level, which I think is blocking the GPG key import. Did you run the command as `sudo`?

yap, i used the command gpg key import as sudo

**Comment by ucihariskoding** [comment]
```
> dell7300@localhost:~> sudo zypper ref
> Repository 'base-non-oss' is up to date.                                        
> Repository 'base-oss' is up to date.                                            
> Repository 'Packman Repository' is up to date.                                  
> Repository 'google-chrome' is up to date.                                       
> Repository 'h264' is up to date.                                                
> Repository 'openSUSE:Tumbleweed' is up to date.                                 
> Repository 'home:pandom79' is up to date.                                       
> Repository 'openSUSE:Tumbleweed' is up to date.                                 
> Repository 'packman' is up to date.                                             
> Repository 'Open H.264 Codec (openSUSE Tumbleweed)' is up to date.              
> Repository 'update' is up to date.                                              
> All repositories have been refreshed.
> dell7300@localhost:~> sudo zypper in github-desktop
> Loading repository data...
> Reading installed packages...
> 'github-desktop' not found in package names. Trying capabilities.
> No provider of 'github-desktop' found.
> Resolving package dependencies...
> Nothing to do.
> dell7300@localhost:~> 
```

**Comment by ucihariskoding** [comment]
> ```
> > dell7300@localhost:~> sudo zypper ref
> > Repository 'base-non-oss' is up to date.                                        
> > Repository 'base-oss' is up to date.                                            
> > Repository 'Packman Repository' is up to date.                                  
> > Repository 'google-chrome' is up to date.                                       
> > Repository 'h264' is up to date.                                                
> > Repository 'openSUSE:Tumbleweed' is up to date.                                 
> > Repository 'home:pandom79' is up to date.                                       
> > Repository 'openSUSE:Tumbleweed' is up to date.                                 
> > Repository 'packman' is up to date.                                             
> > Repository 'Open H.264 Codec (openSUSE Tumbleweed)' is up to date.              
> > Repository 'update' is up to date.                                              
> > All repositories have been refreshed.
> > dell7300@localhost:~> sudo zypper in github-desktop
> > Loading repository data...
> > Reading installed packages...
> > 'github-desktop' not found in package names. Trying capabilities.
> > No provider of 'github-desktop' found.
> > Resolving package dependencies...
> > Nothing to do.
> > dell7300@localhost:~> 
> ```

so i decided to install from flatpak

**Comment by leongersen** [comment]
Regarding the `key 1 import failed` error in the RPM issue linked, I'm also encountering this on Rocky Linux 8.8.

**Comment by shiftkey** [comment]
@leongersen @ucihariskoding can we get a better understanding of whether this command is working for you all?

```
sudo rpm --import https://rpm.packages.shiftkey.dev/gpg.key
```

There's some details beyond `key 1 import failed` that I think your machines can provide that would help me to understand _why_ your machines don't like this public key...
