### ISSUE TITLE
Check for updates not currently supported

### ISSUE THREAD

**Issue by ejgutierrez74** [shiftkey/desktop#84]
## Description

Chack of updates doesnt work in Ubuntu 18.04

## Version

* GitHub Desktop:1.5.0 Rc2

* Operating system: Ubuntu 18.04 64 bits

## Steps to Reproduce

1. Menu -> Help -> About Github Desktop -> Check for updates

### Expected Behavior
Redirect to one webpage or check if newer version has been released. Ideally download and install the new version

### Actual Behavior
Nothing happens

**Comment by shiftkey** [comment]
This was something I had to disable in https://github.com/desktop/desktop/pull/3732 because we don't have any infrastructure currently around updating.

**Comment by shiftkey** [comment]
Closing this out as I don't have bandwidth to support in-app updates. 

We have packages for RPM/DEB supported currently so that's as much as I can support for the foreseeable future...
