### ISSUE TITLE
Selection start is lost when scrolling

### ISSUE THREAD

**Issue by Escain** [shiftkey/desktop#840]
### The problem

Selection seems to not work properly when scrolling making part of the selection to be hidden.

### Release version

3.0.5

### Operating system

Debian 11

### Steps to reproduce the behavior

How to reproduce:

1) Click any document, either modified in the working directory or in the history of any commit. Make sure the modification is long enough to have many lines there.
2) Select side-by-side view
3) Start selecting (mouse press at some point in the code).
4) Without releasing the mouse, scroll down up to a point where the top of the selection is no longer visible, and release the mouse (so that is should select those many lines).

Expected: selection to capture all from the mouse-press position (as a position in the text) up to the mouse-release position.

Observed: selection only captures from the top of the visible code, skipping any selected line above.

### Screenshots

![image](https://user-images.githubusercontent.com/10837802/221236150-e7d40563-35ad-45cf-9c10-29460d3c52be.png)
![image](https://user-images.githubusercontent.com/10837802/221236315-c715aa10-4f81-4a76-ac7d-9184f86bb655.png)
![image](https://user-images.githubusercontent.com/10837802/221236529-057746fc-f082-49c2-a942-c02083e8e275.png)

**Comment by shiftkey** [comment]
@Escain are you able to install the latest release (`3.1.7` currently) and see if this behaviour is still present? I've not been able to see this on the latest version, which makes me suspect this has been fixed upstream...
