### ISSUE TITLE
arm64 builds 

### ISSUE THREAD

**Issue by necrose99** [shiftkey/desktop#841]
### The feature request

https://www.electron.build/cli.html

--linux --arm64   

arm64  linux builds might be of use...also since mire hardware is becoming comparable  ... 

https://github.com/patrikx3/onenote/blob/master/package.json 

electron-builder --linux    --x64   --arm64 deb  rpm tar.xz [Snap](https://www.electron.build/configuration/snap) [AppImage](https://appimage.org/). flatpak  , used on gentoo rpi4 to render Kage for pentoo / etc for or parrot os. 
as deb/rpm/or tar on a limited ram bit easier on 4 gigs and less...  

some the newer Rpi clones are at 16 and few dev boards at 32 gigs ram so quite useful .. 

m1/m2 apple or ms silicon aloke laptops are slowly becoming more common

### Proposed solution

as mentioned above can tweak electron build recipe to cook more bits///

**Comment by shiftkey** [comment]
Please refer to #251 for the discussion about unblocking the dependencies for ARM/ARM64 support - without that we're not able to properly package the application for these platforms...
