### ISSUE TITLE
Neovim-qt, Neovide support revoked

### ISSUE THREAD

**Issue by Smubge** [shiftkey/desktop#845]
### The problem

I noticed that somewhere along the way in the versions that in  desktop/app/src/lib/editors/linux.ts both neovim-qt and neovide were removed.

### Release version

Version 

### Operating system

EndeavourOS

### Steps to reproduce the behavior

1. Install Github-Desktop through paru package manager
2. Install neovide and neovim-qt
3. See them both not pop up in external editors

**Comment by Smubge** [comment]
Thank you for fixing the issue

**Comment by Smubge** [comment]
Adding the following code to the ILinuxExternalEditor[] variable in desktop/app/src/lib/editors/linux.ts would fix the issue: 
`
  {
    name: 'Neovim-Qt',
    paths: ['/usr/bin/nvim-qt'],
  },
  {
    name: 'Neovide',
    paths: ['/usr/bin/neovide'],
  },
  `

**Comment by shiftkey** [comment]
@Smubge which version do you have installed? The `3.2.0` version I've just published should have the right entries:

https://github.com/shiftkey/desktop/blob/f5f68928c2cae3a4dad4e9814681115c9d3ef834/app/src/lib/editors/linux.ts#L23-L38

**Comment by shiftkey** [comment]
Looks like this was a regression with the previous release:

https://github.com/shiftkey/desktop/blob/12e1f25d37c6d530105781eda5b01639fce01c17/app/src/lib/editors/linux.ts#L19-L30

This seems like it was just a bad merge on my part, and now that https://github.com/desktop/desktop/pull/16030 was merged upstream we're in a good place again

**Comment by Smubge** [comment]
Thanks so much :D
