### ISSUE TITLE
Logging in via Enterprise Account

### ISSUE THREAD

**Issue by shahirsiraj** [shiftkey/desktop#847]
### The problem

the issue I am currently facing on Pop OS is that I am unable to login via my enterprise account. I input all the required information correctly but when it redirects to the browser, I get the 404 page not found error on github. 

### Release version

3.1.7

### Operating system

Pop OS 

### Log files

https://git.generalassemb.ly/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=be155d5b-b0dc-4943-9803-07f97fb39fb8

**Comment by shiftkey** [comment]
Enterprise support is not possible currently, for the reasons outlined in #72 and in particular https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547

Please follow along with that thread.
