### ISSUE TITLE
Can't push/create branch on organization

### ISSUE THREAD

**Issue by Catif** [shiftkey/desktop#849]
### The problem

When I try to do an action like commit or publish a branch to my repository of my organization. I got an error of "Authentication Failed".

At the beginning, I was just thinking it was my fault, like repository private or something else. But when I try on my GitHub Desktop (Windows Version), that works!

I reinstall 2 time GitHub Desktop Linux version, disconnected my account and login several times. I don't use SSH Key. My repository is public, and I am the owner.

### Release version

Version 3.2.0-linux1 (x64)

### Operating system

Ubuntu 22.04.2 LTS

### Steps to reproduce the behavior

1. Run Github Desktop (Linux)
2. Go to a repository of your organization
3. Code
4. Commit
5. Push

### Log files

[2023-03-07.desktop.production.log](https://github.com/shiftkey/desktop/files/10912475/2023-03-07.desktop.production.log)

### Screenshots

![Capture d’écran du 2023-03-07 19-04-03](https://user-images.githubusercontent.com/84462178/223510637-f54f9617-c4f2-4fe7-8d07-f423de50b822.png)

**Comment by Catif** [comment]
### Update
Before I had the problem only with organization repositories, now I just can't use it for my personal tasks. I mean that even my private/public repository doesn't work anymore (with the same error message)

I have no idea what else to do to fix that. If you have any clue I'm interested 👍

**Comment by Catif** [comment]
### Update
With several tests, my issue is about access folder. I clone repo organization inside subfolder (better organization), but in these folders I can't push origin any more...

- Github/
  - Repo1 (Working)
  - Repo2 (Working)
  - ... (Working)
  - Subfolder/
    - Repo1 (Not working)
    - Repo2 (Not working)
    - ... (Not working)

What I did : 
```bash
sudo chmod -R 777 ./Github/
```
That not work, I don't know if it is an issue with GitHub Desktop or with my computer.

**Comment by shiftkey** [comment]
Are you able to provide a fresh log file? I'm not sure what this could be and a mention of `chmod` here makes me wonder if something about the specific repositories is bubbling up a `git` error that the application doesn't handle well currently...

**Comment by Catif** [comment]
Sorry to not respond, I didn't see the notification.

My issue is only with organization, with the time I push a lot of things, and that will happen only on organization repository, even if I'm alone and owner of it.

And I can push commit / create branch in organization when I use terminal or vscode. 

To create this log, I did : 
1. close Github desktop
2. delete all log (privacy)
3. open Github Desktop
4. create branch "testGithub" on LeBonSandwich (repo organization)
5. create commit (new file)
6. publish branch (I try it a lot of time, but no error is showing in log )
7. Then get the error (see first comment to watch picture)

[2023-04-10.desktop.production.log](https://github.com/shiftkey/desktop/files/11189420/2023-04-10.desktop.production.log)

**Comment by shiftkey** [comment]
@Catif apologies for the delay - I checked the log files and didn't spot the error (and the underlying context that might have helped).

Without more information it's hard to say what else this might be aside from OAuth restrictions for the organization that you're trying to push changes to.

**Comment by Catif** [comment]
Unfortunately, I can no longer reproduce the error, I've changed hardware and I'm no longer running Ubuntu.

Maybe it was related to a local configuration, we'll never know.

**Comment by shiftkey** [comment]
> Maybe it was related to a local configuration, we'll never know.
