### ISSUE TITLE
Error in login sessio n

### ISSUE THREAD

**Issue by ejgutierrez74** [shiftkey/desktop#85]
## Description
Newer version gets stuck in /etc/profile in line 28. Cant start X server and enter in my session.
for i in /etc/profile.d/*.sh; do if [ -r $i ]; then . $i fi ( In /etc/profile.d/Github Desktop.sh its the error located.

Github Desktop.sh ( notice space between Github and Desktop):
 #!/bin/sh
export PATH='/opt/GitHub Desktop:$PATH'

## Version
* GitHub Desktop: 1.5.0RC2

* Operating system: Ubuntu 18.04 64 Bits

## Steps to Reproduce

1. Try to login in the select user window.
2. As usual select your user and enter your password, to login.
3. Gets stuck in that window.

### Expected Behavior
Login in your session.

### Actual Behavior
Got stuck.

**Comment by shiftkey** [comment]
This is likely related to #69 (where the hooks were added) and #80 where I had to update the script because of the product name changes.

cc @bb441db in case you have any ideas about how to tweak the scripts

**Comment by bb441db** [comment]
@shiftkey Yes, `productName` was used in the post install hook, see line: https://github.com/shiftkey/desktop/blob/f2cdd7ad7d8bfa479db8a159b05d2d1e2126e2ec/script/linux-after-install.sh#L5

We can just replace it with:
```
 PROFILE_D_FILE="/etc/profile.d/githubDesktop.sh" 
```

**Comment by shiftkey** [comment]
@bb441db yeah, I like this idea if we can't trust the defaults that `electron-builder` chooses. I'll see if I can get a PR together tomorrow.

**Comment by sagarpanchal** [comment]
> @shiftkey Yes, `productName` was used in the post install hook, see line:
> 
> [desktop/script/linux-after-install.sh](https://github.com/shiftkey/desktop/blob/f2cdd7ad7d8bfa479db8a159b05d2d1e2126e2ec/script/linux-after-install.sh#L5)
> 
> Line 5 in [f2cdd7a](/shiftkey/desktop/commit/f2cdd7ad7d8bfa479db8a159b05d2d1e2126e2ec)
>  PROFILE_D_FILE="/etc/profile.d/${productFilename}.sh" 
> 
> We can just replace it with:
> 
> ```
>  PROFILE_D_FILE="/etc/profile.d/githubDesktop.sh" 
> ```


`github-desktop" ` format is more accurate for Linux
