### ISSUE TITLE
unable to clone repositories - symbol lookup error in `git-remote-https`: undefined symbol: `curl_global_sslset`

### ISSUE THREAD

**Issue by Sivel0302** [shiftkey/desktop#850]
### The problem

When trying to clone a repository, it writes some strange error, as I understand it, something related to https.
Tried different versions - does not work.
Used debian based distribution, installed from deb package.
I'm attaching a screenshot.
Tell me, how to solve problems?

### Release version

3.2.0 linux RC1 and others

### Operating system

debian based distribution

### Log files

Cloning into '/home/sivel/Desktop/test'...
/usr/lib/github-desktop/resources/app/git/libexec/git-core/git-remote-https: symbol lookup error: /usr/lib/github-desktop/resources/app/git/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset

### Screenshots

![20230310_203324](https://user-images.githubusercontent.com/104088789/224461597-3496a488-ce36-4ef7-abd6-9ae38428b0f0.jpg)

**Comment by shiftkey** [comment]
> debian based distribution

Please provide more details about your distro, as the package should depend on a `libcurl` version but perhaps you're on a very old or new version of `libcurl`

https://github.com/shiftkey/desktop/blob/5ef18243ac41b5abfec8c58eb37af08ec066fa46/script/package-debian.ts#L62

**Comment by Sivel0302** [comment]
> > debian based distribution
> 
> Please provide more details about your distro, as the package should depend on a `libcurl` version but perhaps you're on a very old or new version of `libcurl`
> 
> https://github.com/shiftkey/desktop/blob/5ef18243ac41b5abfec8c58eb37af08ec066fa46/script/package-debian.ts#L62

I using Astra linux Common Edition: [https://astralinux.ru/products/astra-linux-common-edition/](https://astralinux.ru/products/astra-linux-common-edition/) 
Everything works on Ubuntu, but I need Astra linux(
How to update this libcurl?

**Comment by Sivel0302** [comment]
> > debian based distribution
> 
> Please provide more details about your distro, as the package should depend on a `libcurl` version but perhaps you're on a very old or new version of `libcurl`
> 
> https://github.com/shiftkey/desktop/blob/5ef18243ac41b5abfec8c58eb37af08ec066fa46/script/package-debian.ts#L62

It seems to have found how to see the version of `libcurl`, here's what it says:
```
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/2.0.5 libpsl/0.21.0 (+libidn2/2.0.5) libssh2/1.7.0 nghttp2/1.36.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp r
tsp scp sftp smb smbs smtp smtps telnet tftp  Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TL
S-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by Sivel0302** [comment]
> > debian based distribution
> 
> Please provide more details about your distro, as the package should depend on a `libcurl` version but perhaps you're on a very old or new version of `libcurl`
> 
> https://github.com/shiftkey/desktop/blob/5ef18243ac41b5abfec8c58eb37af08ec066fa46/script/package-debian.ts#L62

I tried to update the libraries - it didn't work(  Is it possible to replace the **`git-remote-https`** file?

**Comment by shiftkey** [comment]
> How to update this libcurl?

What version of `libcurl` do you have installed? `apt list | grep libcurl` might show us the specific package you have installed - this can be separate to the version of `curl`

> Is it possible to replace the **`git-remote-https`** file?

Not easily - this is something that the embedded `git` installation uses.

**Comment by Sivel0302** [comment]
> > How to update this libcurl?
> 
> What version of `libcurl` do you have installed? `apt list | grep libcurl` might show us the specific package you have installed - this can be separate to the version of `curl`
> 
> > Is it possible to replace the **`git-remote-https`** file?
> 
> Not easily - this is something that the embedded `git` installation uses.

Show this:

```
sivel@astra:~$ apt list | grep libcurl


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libcurl3/stable,now 7.52.1-5+deb9u16 amd64 [установлен, автоматически]
libcurl3-gnutls/stable,now 7.52.1-5+deb9u16 amd64 [установлен, автоматически]
libcurl3-nss/stable,now 7.52.1-5+deb9u16 amd64 [установлен]
libcurl4-doc/stable,stable 7.52.1-5+deb9u16 all
libcurl4-gnutls-dev/stable 7.52.1-5+deb9u16 amd64
libcurl4-nss-dev/stable 7.52.1-5+deb9u16 amd64
libcurl4-openssl-dev/stable 7.52.1-5+deb9u16 amd64
```

![image](https://user-images.githubusercontent.com/104088789/224566606-7eaf723a-6c06-4aca-92f7-50fbeddb4ad9.png)

**Comment by shiftkey** [comment]
This looks like you're on an old version of `libcurl` which doesn't have the `curl_global_sslset` symbol that this program expects. 

Based on [the docs](https://curl.se/libcurl/c/curl_global_sslset.html) this appears to have been added in `7.56.0`, so that explains why your version is erroring:

> This function was added in libcurl 7.56.0. Before this version, there was no support for choosing SSL backends at runtime. 

This is something that is part of the HTTP stack of `git` itself, so it's not something we can turn off or swap out:

https://github.com/git/git/blob/725f57037d81e24eacfda6e59a19c60c0b4c8062/http.c#L1094

```c
		switch (curl_global_sslset(-1, http_ssl_backend, &backends)) {
```

For reference, this is the output on my machine:

```
apt list | grep libcurl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libcurl-ocaml-dev/jammy 0.9.2-1build1 amd64
libcurl-ocaml/jammy 0.9.2-1build1 amd64
libcurl3-gnutls/jammy-updates,jammy-security,now 7.81.0-1ubuntu1.8 amd64 [installed,automatic]
libcurl3-gnutls/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
libcurl3-nss/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 amd64
libcurl3-nss/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
libcurl4-doc/jammy-updates,jammy-updates,jammy-security,jammy-security 7.81.0-1ubuntu1.8 all
libcurl4-gnutls-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 amd64
libcurl4-gnutls-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
libcurl4-nss-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 amd64
libcurl4-nss-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
libcurl4-openssl-dev/jammy-updates,jammy-security,now 7.81.0-1ubuntu1.8 amd64 [installed]
libcurl4-openssl-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
libcurl4/jammy-updates,jammy-security,now 7.81.0-1ubuntu1.8 amd64 [installed]
libcurl4/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
```

`7.56.0` was published in [October 2017](https://curl.se/mail/lib-2017-10/0005.html) and because of how the cURL project ships fixes (no backports), I'd try and find updates for your distribution to ensure you're on a more secure version of `libcurl` and `curl`.

**Comment by Sivel0302** [comment]
> This looks like you're on an old version of `libcurl` which doesn't have the `curl_global_sslset` symbol that this program expects.
> 
> Based on [the docs](https://curl.se/libcurl/c/curl_global_sslset.html) this appears to have been added in `7.56.0`, so that explains why your version is erroring:
> 
> > This function was added in libcurl 7.56.0. Before this version, there was no support for choosing SSL backends at runtime.
> 
> This is something that is part of the HTTP stack of `git` itself, so it's not something we can turn off or swap out:
> 
> https://github.com/git/git/blob/725f57037d81e24eacfda6e59a19c60c0b4c8062/http.c#L1094
> 
> ```c
> 		switch (curl_global_sslset(-1, http_ssl_backend, &backends)) {
> ```
> 
> For reference, this is the output on my machine:
> 
> ```
> apt list | grep libcurl
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libcurl-ocaml-dev/jammy 0.9.2-1build1 amd64
> libcurl-ocaml/jammy 0.9.2-1build1 amd64
> libcurl3-gnutls/jammy-updates,jammy-security,now 7.81.0-1ubuntu1.8 amd64 [installed,automatic]
> libcurl3-gnutls/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
> libcurl3-nss/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 amd64
> libcurl3-nss/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
> libcurl4-doc/jammy-updates,jammy-updates,jammy-security,jammy-security 7.81.0-1ubuntu1.8 all
> libcurl4-gnutls-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 amd64
> libcurl4-gnutls-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
> libcurl4-nss-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 amd64
> libcurl4-nss-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
> libcurl4-openssl-dev/jammy-updates,jammy-security,now 7.81.0-1ubuntu1.8 amd64 [installed]
> libcurl4-openssl-dev/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
> libcurl4/jammy-updates,jammy-security,now 7.81.0-1ubuntu1.8 amd64 [installed]
> libcurl4/jammy-updates,jammy-security 7.81.0-1ubuntu1.8 i386
> ```
> 
> `7.56.0` was published in [October 2017](https://curl.se/mail/lib-2017-10/0005.html) and because of how the cURL project ships fixes (no backports), I'd try and find updates for your distribution to ensure you're on a more secure version of `libcurl` and `curl`.

I see, but what command should I update the libraries with? I tried `sudo apt install curl` and it didn't update, it said it was the latest version.

**Comment by shiftkey** [comment]
> I see, but what command should I update the libraries with? 

This is up to the distribution maintainers to handle - there may be another feed you can install which contains newer packages but I'm not familiar enough with this distribution to know if/where to find these.

**Comment by Sivel0302** [comment]
> > I see, but what command should I update the libraries with?
> 
> This is up to the distribution maintainers to handle - there may be another feed you can install which contains newer packages but I'm not familiar enough with this distribution to know if/where to find these.

I understand, I will try to find this.

**Comment by Sivel0302** [comment]
> > I see, but what command should I update the libraries with?
> 
> This is up to the distribution maintainers to handle - there may be another feed you can install which contains newer packages but I'm not familiar enough with this distribution to know if/where to find these.

I tried installing other repositories via Synapsys - none of them had libcurl3 updates, can you tell me where can I get links to repositories that have what I need?
Here's what I used:
![image](https://user-images.githubusercontent.com/104088789/224583929-733d439a-b6a9-4433-964b-cbbfb63d8852.png)

I also compiled **curl-7.71.0** from sources into **[this](https://curl.se/download/)**, and [this guide](https://www.linuxadictos.com/ru/utilizas-curldebes-actualizar-ya-la-nueva-version-7-71-0-soluciona-dos-fallos-graves.html#Como_instalar_cURL_en_Linux) but it was libcurl that was not updated. Here is what `curl --version` says:
```
sivel@astra:~$ curl --version
curl 7.71.0 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libid
n2/2.0.5 libpsl/0.21.0 (+libidn2/2.0.5) libssh2/1.7.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2020-06-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp  
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.
curl: symbol lookup error: curl: undefined symbol: curl_mime_free
```

**Comment by shiftkey** [comment]
> I tried installing other repositories via Synapsys - none of them had libcurl3 updates, can you tell me where can I get links to repositories that have what I need?

I don't know enough about your distribution and how it handles updates. But there's a typo in those settings that might be related: `strech` -> `stretch`.

> I also compiled **curl-7.71.0** from sources into **[this](https://curl.se/download/)**, and [this guide](https://www.linuxadictos.com/ru/utilizas-curldebes-actualizar-ya-la-nueva-version-7-71-0-soluciona-dos-fallos-graves.html#Como_instalar_cURL_en_Linux) but it was libcurl that was not updated.

Manually installing `curl` won't work here because it's the shared libraries on your machine here that are out of date. I also see this message in your output that suggests being out of sync with these shared libraries will have additional problems:

```
WARNING: curl and libcurl versions do not match. Functionality may be affected.
curl: symbol lookup error: curl: undefined symbol: curl_mime_free
```

**Comment by shiftkey** [comment]
Closing this out as something outside the scope of what I can support
