### ISSUE TITLE
Integration button doesn't launch IDE

### ISSUE THREAD

**Issue by tfrum** [shiftkey/desktop#851]
### The problem

This may be a VSCodium issue. Selecting gedit works fine. Selecting VSCodium doesn't. Regular Visualstudio never shows up.

### Release version

3.2.0

### Operating system

Fedora 37

**Comment by shiftkey** [comment]
I need more information to understand the issue:

 - what version of VSCodium do you have installed?
 - any errors or messages in the log files that might provide extra clues?

Please check the logs created at `~/.config/GitHub Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by tfrum** [comment]
Unfortunately there's nothing in the logs. I should have mentioned that, though. No errors are thrown.

I'm on VSCodium 1.76.1 installed via flatpak.
![image](https://user-images.githubusercontent.com/119856929/224840065-46ba9675-9ce8-427e-a9b9-415e2a843ccf.png)

**Comment by shiftkey** [comment]
These are the paths that we check for a valid VSCodium install:

https://github.com/shiftkey/desktop/blob/84aeb5d5f3fa392f067d75582332992d4d0caf4b/app/src/lib/editors/linux.ts#L53-L58

And these are the paths that we check for a valid VSCode:

https://github.com/shiftkey/desktop/blob/84aeb5d5f3fa392f067d75582332992d4d0caf4b/app/src/lib/editors/linux.ts#L40-L46

My hunch here is that your versions are located somewhere else on disk.

**Comment by tfrum** [comment]
> These are the paths that we check for a valid VSCodium install:
> 
> https://github.com/shiftkey/desktop/blob/84aeb5d5f3fa392f067d75582332992d4d0caf4b/app/src/lib/editors/linux.ts#L53-L58
> 
> And these are the paths that we check for a valid VSCode:
> 
> https://github.com/shiftkey/desktop/blob/84aeb5d5f3fa392f067d75582332992d4d0caf4b/app/src/lib/editors/linux.ts#L40-L46
> 
> My hunch here is that your versions are located somewhere else on disk.

Neither install has had its installation customized from the default that Flatpak uses. That it can see vscodium at all should indicate as much.
