### ISSUE TITLE
How to install in OpenSUSE with YaST

### ISSUE THREAD

**Issue by JulianGiles** [shiftkey/desktop#852]
### Operating System/Distribution

OpenSUSE Leap 15.4

### Installer

Which version of the app? 
The latest release **3.2.0 Linux RC1**

Which installer type?
I am following the steps in the Readme to install using RPM package.

### What happened?

I am trying to install following the steps in the Readme. My package manager is YaST software. When I try to execute the second command 

```
sudo sh -c 'echo -e "[shiftkey-packages]\nname=GitHub Desktop\nbaseurl=https://rpm.packages.shiftkey.dev/rpm/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://rpm.packages.shiftkey.dev/gpg.key" > /etc/yum.repos.d/shiftkey-packages.repo'
```

I get `sh: /etc/yum.repos.d/shiftkey-packages.repo: No such file or directory` since I am not using `yum` as my package manager. How to do that with YaST? I could not figure out an equivalent command for YaST to complete the installation.

**Comment by shiftkey** [comment]
I'm not familiar with `YaST` and don't have a working SuSE install to test on so I'm looking for help here about where the package metadata should live for these cases...

**Comment by Rainmaker0102** [comment]
Setting up a new openSUSE install, I had to change this command
```
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/shiftkey-packages.gpg] https://apt.packages.shiftkey.dev/ubuntu/ any main" > /etc/apt/sources.list.d/shiftkey-packages.list'
```
into this
```
sudo sh -c 'echo -e "[shiftkey-packages]\nname=GitHub Desktop\nbaseurl=https://rpm.packages.shiftkey.dev/rpm/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://rpm.packages.shiftkey.dev/gpg.key" > /etc/zypp/repos.d/shiftkey-packages.repo'
```
Essentially just changing the `yum.repos.d` to `/zypp/repos.d`.

**Comment by JulianGiles** [comment]
That worked! Thank you!
