### ISSUE TITLE
I can't push to my companies repository using Desktop every since they purchased Copilot

### ISSUE THREAD

**Issue by titleofliberty** [shiftkey/desktop#857]
### The problem

Ever since the company purchased Copilot I can't push to our repo using Github Desktop. However, I can push using the CLI or using VS Code. I have logged out of the Desktop and in again. We do not have an enterprise server so that can't be it. I have compared my Desktop settings with my co-worker. The log file indicates a 403 error, but I don't understand how that can be true since I can do everything using VS Code or the terminal.

![Screenshot from 2023-03-23 13-23-32](https://user-images.githubusercontent.com/20482035/227300211-3cdf48b5-95a7-4c3d-971b-3c408d8e516b.png)

### Release version

Version 3.2.0-linux1 (x64)

### Operating system

Pop!_OS 22.04 LTS

### Steps to reproduce the behavior

Make changes to your branch.
Commit your changes using VS Code.
Switch to Github Desktop.
Click the Push button.

### Log files

[2023-03-23.desktop.production.log](https://github.com/shiftkey/desktop/files/11054372/2023-03-23.desktop.production.log)

### Screenshots

![Screenshot from 2023-03-23 13-23-32](https://user-images.githubusercontent.com/20482035/227303402-1be00ff2-4d98-44b5-9cc8-2dbac4f06640.png)

**Comment by shiftkey** [comment]
Looks like the organization has OAuth access restrictions enabled:

```
Error: Although you appear to have the correct authorization credentials, the `JobFlo-co` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Dt (/home/marion/webpack:/[name]/app/src/lib/http.ts:178:11)
    at vn.fetchPushControl (/home/marion/webpack:/[name]/app/src/lib/api.ts:1396:7)
    at Zn.refreshBranchProtectionState (/home/marion/webpack:/[name]/app/src/lib/stores/app-store.ts:1144:39)
```

Please see #217 and in particular this workaround which avoids the token the app uses by default: https://github.com/shiftkey/desktop/issues/217#issuecomment-1416686941
