### ISSUE TITLE
support for ARM64 package

### ISSUE THREAD

**Issue by RichNeese** [shiftkey/desktop#86]
what is needed to get a test build fro arm64 ubuntu ? We would like to have the client for development

**Comment by RussianNeuroMancer** [comment]
Currently there is one [arm64 workstation](https://www.solid-run.com/nxp-lx2160a-family/honeycomb-workstation/), two [arm64 laptops with preinstalled Linux](https://www.pine64.org/), four [arm64 laptops capable of running Linux](https://github.com/aarch64-laptops/build#device-status), twelve [Samsung DeX](https://www.linuxondex.com) capable devices, several desktop-capable arm64 SBC (such as ODROID-N2, ROCKPRo64, RPi4, HiKey960/970, etc.).

> No current plans

Still no change in plans?

**Comment by shiftkey** [comment]
It looks like the Desktop team is no longer distributing an ARM64 version of Git with the `dugite-native` package, so without an alternative way of invoking Git and the engineering work to incorporate it into our builds, this isn't going to happen.

https://github.com/desktop/dugite-native/pull/315 has more context behind the change.
