### ISSUE TITLE
Organization repositories is not seen

### ISSUE THREAD

**Issue by zeynepbaydemr** [shiftkey/desktop#860]
### The problem

in ubuntu 20.04, i couldn't clone repositories of my organization, because it is not seen in clone screen.

### Release version

Version 2.6.3-linux1

### Operating system

Ubuntu 20.04

### Screenshots

![Screenshot from 2023-04-03 12-08-28](https://user-images.githubusercontent.com/125470704/229464760-87a98049-0e55-4435-84c4-5d006f68ebf9.png)

**Comment by mjamilasfihani** [comment]
maybe this can help you: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

---

edit:

I've took different example on it, the first one was not restricted and I could see all my forked repositories while the second is restricted, so on it won't display my forked repositories.

**Comment by mscheltienne** [comment]
Hello, I'm having the same issue. In the `known-issues` file, the link to approve access to the development app is useful, however I would also add this one:

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps
