### ISSUE TITLE
RPM [SUSE/FEDORA] Build Instructions:

### ISSUE THREAD

**Issue by MartinVonReichenberg** [shiftkey/desktop#865]
### RPM Install instructions request:

Hello, 

I would like to ask for a **.SPEC file** and/or **.SRPM package** either for Fedora or openSUSE.
I want to add GitHub Desktop `github-desktop` application into [Open Build Service](https://build.opensuse.org/) (OBS).

Just provide it by adding it into any _build/packaging_ directory or into the comment here . . .

Thank you in advance!
Martin

**Comment by shiftkey** [comment]
Currently we use a package named `electron-installer-redhat` which generates the spec file from a template, and we don't have plans to move away from that: https://github.com/electron-userland/electron-installer-redhat/blob/main/resources/spec.ejs

**Comment by MartinVonReichenberg** [comment]
> Currently we use a package named `electron-installer-redhat` which generates the spec file from a template, and we don't have plans to move away from that: https://github.com/electron-userland/electron-installer-redhat/blob/main/resources/spec.ejs

But can I see the generated template?

It is also for supporting SUSE and not only Fedora.

I can change the `.spec` file accordingly to SUSE needs instead of writing everything from scratch . . .
Such files should also be accessible somewhere because they are a part of compilation instructions which relate to open source code as such ...


Thank you in advance!

**Comment by shiftkey** [comment]
> But can I see the generated template?

Not easily. It's something that gets generated on the fly, and gets combined with the files on disk to generate the package. You could try and dump the file that gets created when you run `yarn run package` but it's not part of the outputs currently.
