### ISSUE TITLE
Unable to clone third-party repositories

### ISSUE THREAD

**Issue by mjimenezco10** [shiftkey/desktop#867]
### The problem

When cloning a repository, I get a message with a sign in request to GitHub.com.
(**Authentication failed:**  We were unable to authenticate from GitHub.com. Please enter your username and password to try again.) I put the correct credentials, and it says that the authentication failed.
I'm not able to clone repositories.

It is a repository from GitHub Classroom.
Doing the same with a PC with Windows 10 it works.
The problem is with the Linux app.

### Release version

GitHubDesktop-linux-3.2.1

### Operating system

Ubuntu 22.04 LTS

### Steps to reproduce the behavior

1. Press "Clone a repository from the internet..."
2. Press "URL"
3. Paste the correct URL
4. Click on clone
5. Then, it displays the error.

### Screenshots

![Captura desde 2023-04-17 08-54-59](https://user-images.githubusercontent.com/122433753/232407719-23ddc4ad-97f6-411f-a002-1181378fd41a.png)

**Comment by mjimenezco10** [comment]
Here's the solution: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

**Comment by shiftkey** [comment]
> Doing the same with a PC with Windows 10 it works.

Known issue: #72
