### ISSUE TITLE
https://mirror.mwt.me/github-desktop/install.sh

### ISSUE THREAD

**Issue by Jejaimin** [shiftkey/desktop#869]
### Operating System/Distribution

Which distribution of Linux are you using?

### Installer

Which version of the app?
Which installer type?

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by shiftkey** [comment]
I'm closing out the issue as the template has not been filled out.

@Jejaimin please submit a new issue if you have a bug report.
