### ISSUE TITLE
`geany` does not launch with correct directory

### ISSUE THREAD

**Issue by id027102** [shiftkey/desktop#871]
### The problem

If I use "geany" as editor , geany opens with "Open with geany" , but it opens in last used directory , not in choosed repo.

When using "Visual Studio Code" it opens well in the good directory .

"Show in your file manager" is also Ok

### Release version

3.2.1-linux1 (x64)

### Operating system

Linux 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2 (2023-04-08) x86_64 GNU/Linux

### Steps to reproduce the behavior

1. Choose repo
2. Open in Geany

**Comment by shiftkey** [comment]
> If I use "geany" as editor , geany opens with "Open with geany" , but it opens in last used directory , not in choosed repo.

Is there something with the command line interface for `geany` that means our trick of passing in a path as the first argument doesn't work? Is it expecting something else?

https://github.com/shiftkey/desktop/blob/217a7da2c66184ed0c90adfd6fd074dbcf72f4f8/app/src/lib/helpers/linux.ts#L103

**Comment by id027102** [comment]
Its easy , install geany and try.
If you have a repo named test , geany will open a file named test in the last directory he was busy.
Visual Stududio is ok he open the folder test , geany not.
So I am not a developper , but I think the parameters passed to geany are not correct

**Comment by shiftkey** [comment]
> Its easy , install geany and try.

I have limited time for this project at the moment so any extra instructions or documentation you can point me to would help here.

> If you have a repo named test , geany will open a file named test in the last directory he was busy.

This is the bit that's not clear to me - do you pass any arguments to `geany` when this happens? Do you launch it via the command line? Or do you launch it some other way?

**Comment by id027102** [comment]
No arguments, in github-desktop ->File->Options->Integration->External
Editor I choose geany  that's all
I think github-desktop call geany with repo as argument (is working so with
visual studio which opens folders , but geany does not open folder but file)
It's github-desktop gives visual studio and geany as choice , and I wanted
to try geany
Thanks for your time

**Comment by theofficialgman** [comment]
`geany` has no notion of opening a folder. Sorry I was the one who had it added to shiftkey/destop. Opening specific files works fine but there isn't any way to open a folder with geany.
you can see that I mention this in the PR comment: https://github.com/shiftkey/desktop/pull/711

I knew then when adding it but felt that it still deserved to be there since `geany` is such a common file editor and it works fine when opening a specific file (like right clicking on one in the commit history and selecting open in geany)

This issue can be closed.
