### ISSUE TITLE
WSL2 Ubuntu 22 LTS github-desktop does not run Trace/breakpoint trap

### ISSUE THREAD

**Issue by poroburu** [shiftkey/desktop#873]
### Operating System/Distribution

Which distribution of Linux are you using?

WSL2 on Windows 10 19045.2846
```Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

### Installer

Which version of the app?
Which installer type?
https://github.com/shiftkey/desktop#shiftkey-package-feed
https://github.com/shiftkey/desktop#deb-get

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

Install:
```
sudo apt update && sudo apt install github-desktop
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Fetched 337 kB in 1s (356 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  gir1.2-gnomekeyring-1.0 libgnome-keyring0
The following NEW packages will be installed:
  github-desktop
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/91.5 MB of archives.
After this operation, 333 MB of additional disk space will be used.
Selecting previously unselected package github-desktop.
(Reading database ... 49648 files and directories currently installed.)
Preparing to unpack .../github-desktop_3.2.1-linux1_amd64.deb ...
Unpacking github-desktop (3.2.1-linux1) ...
Setting up github-desktop (3.2.1-linux1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```
Run:
```
$ github-desktop
Trace/breakpoint trap
```
I have done `wsl --update` and have used WSLg for some apps.
I see a few mentions of WSL in the repository. But nothing specific to WSL not being supported or being an issue with using github-desktop.

**Comment by shiftkey** [comment]
I haven't got access to a WSL2 setup to test this out, so I'm not really sure what this might be off-hand. I'd suggest trying out the upstream packages for Windows and keeping an eye on https://github.com/desktop/desktop/pull/16378

**Comment by sarim** [comment]
Can you run google-chrome? Are you using wslg? I see you are using windows 10. Keep in mind wsl in windows 10 doesn't have feature parity with windows 11's.

**Comment by shiftkey** [comment]
Marking as `more-info-needed` as @sarim has mentioned some questions that would help here
