### ISSUE TITLE
Build deb Applicaton Fail

### ISSUE THREAD

**Issue by huangcs427** [shiftkey/desktop#875]
Hi

I downloaded your source code, in my local linux (deepin, based on debain10), found a problem in the packaging process, the error is as follows:
```
⨯ Application entry file "main.js" in the "xxx/desktop/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "main.js" in the "xxx/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
```
I added the following code to the package.json of the root directory:
```
"build": {
    "productName": "GitHub Desktop",
    "linux": {
      "target": "deb",
      "category": "Production",
      "icon": "app/static/logos/icon-logo.ico"
    },
    "appId": "com.github.electron"
  },
```
I didn't make any changes to the other files. I packaged them with the following command:
```
yarn dist.
```
Local configuration Information:
```
system Info: Deepin 20 (based on debain10).
node Version: v16.17.1.
python Version: 3.9.0.
yarn Version: 1.21.1 
```
what is wrong with my configuration? Thank you for your answer.

**Comment by shiftkey** [comment]
> `yarn dist.`

Not sure where you saw this but the command I run to build and package things locally is this

```
> yarn install
> yarn build:prod
> yarn run package
```

**Comment by huangcs427** [comment]
I set it up in scripts，But it failed. 
```
"dist": "electron-builder"
```
I later solved the problem of deb packaging, with the following code.
```
electron-installer-debian --src dist/github-desktop-linux-x64/ --dest dist/installers/ --arch amd64
```
Sorry, I didn't notice the `yarn run package` script, I tried it and it worked.

Thank you.
