### ISSUE TITLE
wont login/doesnt report it failed to login

### ISSUE THREAD

**Issue by zarosath** [shiftkey/desktop#878]
### The problem

it wont sign in to push origin

### Release version

3.2.1

### Operating system

ubuntu 22.04.2

### Steps to reproduce the behavior

simply attempt to sign in on a fresh install without upgrading packages (i cant, when i do so my video driver has issues and my system wont boot)

**Comment by zarosath** [comment]
So 3.1.1 had the same issue until i deleted the repository and authenticated through web address github.com when it prompted me for root access password.

**Comment by shiftkey** [comment]
@zarosath has this been resolved? 

I don't have much in the way of meaningful error messages or screenshots here so I'm not sure how to proceed...
