### ISSUE TITLE
githubdesktop doesn't recognize my vscode

### ISSUE THREAD

**Issue by Rafael-Machado01** [shiftkey/desktop#879]
### The problem

github desktop doesn't recognize my text editor which is Visual Studio Code only GNOME Text Editor

### Release version

Version 3.2.1-linux2 (x64)

### Operating system

Fedora 38

### Steps to reproduce the behavior

Select editor in Options
External editor
Non does not have vscode option

### Log files

[2023-05-27.desktop.production.log](https://github.com/shiftkey/desktop/files/11584749/2023-05-27.desktop.production.log)
[2023-05-28.desktop.production.log](https://github.com/shiftkey/desktop/files/11584750/2023-05-28.desktop.production.log)

### Screenshots

![Captura de tela de 2023-05-28 11-07-05](https://github.com/shiftkey/desktop/assets/70187787/de1901cf-ee74-48d4-a2dc-b5a843041f0e)

### Additional context

Thanks in advance!

**Comment by shiftkey** [comment]
Which path is your VSCode installed to on disk?

**Comment by worldofgeese** [comment]
@shiftkey if I'm using Nixpkgs to install VS Code, then it symlinks binary from the Nix store path to `$HOME/.nix-profile/bin/code`. Can I pass a custom path to GH Desktop? It's installed as an AppImage.
