### ISSUE TITLE
Failing to detect user Flatpak installs of VSCode and VSCodium

### ISSUE THREAD

**Issue by pascalrrr** [shiftkey/desktop#885]
### The problem

When installing VSCodium or VSCode as a _user installed_ Flatpak, neither installation appears as an available External Editor in the application. Could be related to #851 and #879.

It looks like an issue in https://github.com/shiftkey/desktop/blob/84aeb5d5f3fa392f067d75582332992d4d0caf4b/app/src/lib/editors/linux.ts#L53-L58 and https://github.com/shiftkey/desktop/blob/84aeb5d5f3fa392f067d75582332992d4d0caf4b/app/src/lib/editors/linux.ts#L40-L46 and I will probably submit a PR to fix this.

### Release version

Version 3.2.1-linux2 (x64) (Unofficial Flatpak)

### Operating system

VanillaOS

### Steps to reproduce the behavior

1. Install GitHub Desktop on Linux
2. Install VSCodium or VSCode as a user through Flatpak
3. ???
4. Profit

no wait
*3. Go to File > Integrations > No VSCode or VSCodium

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/53631550/146de1bc-3e1b-4f10-9ccc-70e5c30a755d)

### Additional context

I am running the (seemingly unofficial) Flatpak version of GitHub Desktop. I hate to direct issues here because the Flatpak could be introducing this issue, but I think this is an issue here as well. I haven't tried with a system install of GH Desktop Linux.

**Comment by shiftkey** [comment]
> and I will probably submit a PR to fix this.

Please do - I only have a limited context on setups and tools that folks use, so these sort of contributions do help to fill in the gaps.

> I hate to direct issues here because the Flatpak could be introducing this issue,

I believe this is the right place to submit the fix, so here is fine to report the issue.
