### ISSUE TITLE
Failing to install from Terminal

### ISSUE THREAD

**Issue by shoshta73** [shiftkey/desktop#888]
### Operating System/Distribution

Ubuntu 22.04

### Installer

Latest - CLI

### What happened?

`sudo apt install github-desktop fails with message`

Package github-desktop is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

I have tried both package feeds

**Comment by rahul0x00** [comment]
@Shoshta73 first you need to configure the feed 
Refer to this link: https://github.com/shiftkey/desktop#shiftkey-package-feed

**Comment by shiftkey** [comment]
> I have tried both package feeds

Please clarify which package feeds you have listed. I believe you are using the feed that is no longer supported.

**Comment by shoshta73** [comment]
I have tried installing with both package feeds listed in README, with instructions given in same, on 2 seperate ocassions 2 days ago

**Comment by shiftkey** [comment]
Please attach the output from these commands - I don't expect all these files to exist but it will help me to understand your configuration:

```
cat /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list
cat /etc/apt/sources.list.d/shiftkey-packages.list
cat /etc/apt/sources.list.d/mwt-desktop.list
```

**Comment by shiftkey** [comment]
> `Package github-desktop is not available, but is referred to by another package`

There's additional information here that would help - the state of your package cache. According to https://askubuntu.com/a/391186/1034907 this command may help us understand more - can you share what output this returns?

```
apt-cache search github-desktop
```

**Comment by shoshta73** [comment]
Sure. Will do when i get the chance later today, at the latest will do it tommorow

**Comment by shoshta73** [comment]
Local ubuntu update server was clogged up. Today it installed successfully.
