### ISSUE TITLE
Wrong menu color with Adwaita-dark

### ISSUE THREAD

**Issue by ziggy42** [shiftkey/desktop#9]
### Description

So, first of all, I'm reporting this but it's really not a big deal. I'm also almost sure the problem is with Electron.

Setting the default dark theme on Fedora 27 makes the menu look black, and I'm not sure you're okey with this color :smile: 

![screenshot from 2017-12-14 15-35-24](https://user-images.githubusercontent.com/4258550/33997577-262e9e9e-e0e5-11e7-82b0-b05ccaabc51a.png)

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Fedora 27 with GNOME

### Steps to Reproduce

1. Set the theme to Adwaita-dark using GNOME tweaks
1. Open the app
1. See the menu

**Expected behavior:** The menu should be gray, I guess?
**Actual behavior:** They're too dark

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
Yeah, this should be submitted to `electron/electron` - not really much we can do on the Desktop side about it. 

> Set the theme to Adwaita-dark using GNOME tweaks

I gather this is using `gnome-tweak-tool`, but you can also set the terminal to the dark variant under Preferences and see how the menu _should_ look:

<img width="376" src="https://user-images.githubusercontent.com/359239/34017135-5a9bdb62-e174-11e7-8e69-35960f829ae1.png">

@ziggy42 would you mind opening an issue on `electron/electron` with these details? It's reproducible using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) sample app, if you want to use something simpler than Desktop.

 - `Adwaita` (light) theme:

<img width="501"  src="https://user-images.githubusercontent.com/359239/34017370-6a16eab8-e175-11e7-9618-bee7a381bfa2.png">

 - `Awaita-dark` theme:

<img width="468"  src="https://user-images.githubusercontent.com/359239/34017362-65f00668-e175-11e7-9ebf-a6cc3f5215f7.png">

I also noticed that VSCode has the same issue as Desktop with the dark menus.

**Comment by ziggy42** [comment]
@shiftkey I will tomorrow, I don't have my Linux machine with me at the moment.

**Comment by ziggy42** [comment]
I reported the problem to `electron` [here](https://github.com/electron/electron/issues/11454).

Every electron app I'm using has this problem, I didn't notice it in vscode and slack because I don't have the menus visible.

**Comment by shiftkey** [comment]
@ziggy42 thanks for that. I'll keep an eye on the upstream issue in the meantime as there's not much more we can do here.
