### ISSUE TITLE
Subject: Authentication Failure Issue while Cloning Private Repository

### ISSUE THREAD

**Issue by jeyakumar-BTR** [shiftkey/desktop#902]
Dear GitHub Support,

I am writing to report an ongoing issue I am facing with authentication while attempting to clone a private repository using Git Desktop.

I have followed the recommended troubleshooting steps, including verifying my GitHub account credentials, regenerating the personal access token (PAT), and ensuring the correct URL formatting. Additionally, I have successfully tested the PAT using the cURL command and received the expected response, confirming its validity.

However, despite these efforts, I continue to receive an "authentication failed" error when attempting to clone the private repository. This issue persists even after multiple attempts and ensuring the correct authentication information.

I would greatly appreciate your assistance in resolving this matter. If there are any additional steps or configurations I should consider, please provide specific guidance. I have thoroughly reviewed the available documentation and support resources but have been unable to find a solution.

Attached to this email, you will find the relevant details, including the error message received, the clone URL used, and the response from the cURL command.

Thank you for your attention to this matter. I look forward to your prompt response and resolution of the authentication failure issue.

PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

git desktop version 3.7.1 

Sincerely,
Jey,
jeyakumar-BTR
mailtojeykmr@gmail.com

**Comment by shiftkey** [comment]
@jeyakumar-BTR

> Attached to this email, you will find the relevant details, including the error message received, the clone URL used, and the response from the cURL command.

These details don't seem to be present - please provide the error message and any extra information.

> git desktop version 3.7.1

The latest version of the app I've published is `3.2.5` so I'm not sure which version this corresponds to.
