### ISSUE TITLE
🆕 [ARM/ARM64 users] Feedback on new packages

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#903]
Please submit any feedback you have here about the new ARM and ARM64 installers.

Latest release: **[`3.2.7-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-3.2.7-linux2)**

**Comment by isuro** [comment]
I'm using it via X11 & Docker, so some limitations apply from not having any real desktop environment or browser, but generally working great.

(Ubuntu 20.04.5 LTS, installed via `.deb`, current XQuartz & Docker, Macbook Pro M1)

**Comment by md-shamim-ahmad** [comment]
I find a issue #906

**Comment by Lunarequest** [comment]
the flatpak now builds for aarch64 as well(flathub doesn't support arm so we haven't build it for it)

**Comment by isuro** [comment]
Launching from cli no longer works ☹️.
As of `3.2.7-linux2`, if I comment out the redirect to `/dev/null` in `/usr/lib/github-desktop/resources/app/static/github`, I get:
```
$ github
ERR! Desktop command line interface not currently supported on platform linux
Error: Desktop command line interface not currently supported on platform linux
    at t (/usr/lib/github-desktop/resources/app/cli.js:1:26473)
    at Object.handler (/usr/lib/github-desktop/resources/app/cli.js:1:26160)
    at h (/usr/lib/github-desktop/resources/app/cli.js:1:28549)
    at e (/usr/lib/github-desktop/resources/app/cli.js:1:28693)
    at /usr/lib/github-desktop/resources/app/cli.js:1:28764
    at /usr/lib/github-desktop/resources/app/cli.js:1:28783
    at Object.<anonymous> (/usr/lib/github-desktop/resources/app/cli.js:1:28808)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1296:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
```
(Ubuntu 20.04.5 LTS, installed via .deb, current XQuartz & Docker, Macbook Pro M1)

**Comment by shiftkey** [comment]
@isuro which architecture are you installing? That appears to be this error:

https://github.com/shiftkey/desktop/blob/18c585faddcd2c8587eef51ce13198e76add9ce3/app/src/cli/open-desktop.ts#L20-L22

But I'm puzzled about how it's reaching there because the `__LINUX__` global that we set when building also uses `process.platform`:

https://github.com/shiftkey/desktop/blob/18c585faddcd2c8587eef51ce13198e76add9ce3/app/app-info.ts#L37

**Comment by isuro** [comment]
Installed via [GitHubDesktop-linux-arm64-3.2.7-linux2.deb](https://github.com/shiftkey/desktop/releases/download/release-3.2.7-linux2/GitHubDesktop-linux-arm64-3.2.7-linux2.deb)

**Comment by isuro** [comment]
And indeed:
```
$ npx ts-node
> process.platform
'linux'
```

**Comment by isuro** [comment]
According to the source map, the case wasn't built in somehow: 
<img width="2372" alt="Screenshot 2023-08-08 at 14 16 05" src="https://github.com/shiftkey/desktop/assets/913380/f24494b6-3439-46b4-87e6-79c11df98374">

**Comment by shiftkey** [comment]
Cool, that gives me some context to dig into @isuro - thanks for poking at the package contents...

**Comment by isuro** [comment]
Ping me if you have a new `.deb` you'd like me to try out!

**Comment by Bezierr** [comment]
This is not about the ARM installer but about AMD64.deb .
Issue: Geany is not supported as external editor anymore. This worked up to and including 3.2.5.

(System: Mint 21.1 Mate)

**Comment by shiftkey** [comment]
@Bezierr 

> Issue: Geany is not supported as external editor anymore. This worked up to and including 3.2.5.

This was removed in https://github.com/shiftkey/desktop/pull/894 because it doesn't support opening a directory, and I was receiving bug reports about it https://github.com/shiftkey/desktop/issues/871

**Comment by Bezierr** [comment]
@shiftkey
Ok. I never tried opening a directory but only individual files, which works (worked) as it's supposed to. So I guess I'll have to stick with 3.2.5 .

Anyway, thanks a lot for providing this for Linux -- really much appreciated!

**Comment by shiftkey** [comment]
@isuro just letting you know that the newest release ([`3.2.8-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-3.2.8-linux1)) has fixed this issue with the `github` command line helper.

**Comment by sabrehagen** [comment]
My environment uses OpenGL 2.1. The UI renders without some elements. Screenshot for reference:

![image](https://github.com/shiftkey/desktop/assets/1094600/e6d6bc9e-c5c2-40ae-a7cb-696252a3df85)

Terminal log:

```
[1200283:1014/012916.918090:ERROR:shared_context_state.cc(77)] Skia shader compilation error
------------------------
#version 100

#extension GL_EXT_blend_func_extended : require
precision mediump float;
precision mediump sampler2D;
uniform sampler2D uTextureSampler_0_S0;
varying highp vec2 vTextureCoords_S0;
varying highp float vTexIndex_S0;
varying mediump vec4 vinColor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vinColor_S0;
    mediump vec4 texColor;
    {
        texColor = texture2D(uTextureSampler_0_S0, vTextureCoords_S0, -0.5);
    }
    mediump vec4 outputCoverage_S0 = texColor;
    {
        outputCoverage_S0.w = max(max(outputCoverage_S0.x, outputCoverage_S0.y), outputCoverage_S0.z);
        gl_SecondaryFragColorEXT = outputColor_S0.w * outputCoverage_S0;
        gl_FragColor = outputColor_S0 * outputCoverage_S0;
    }
}

Errors:
0:1(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
0:2(12): warning: extension `GL_EXT_gpu_shader5' unsupported in fragment shader
0:3(1): error: `out' qualifier in declaration of `webgl_SecondaryFragColor' only valid for function parameters in GLSL 1.10
0:0(0): error: fragment shader writes to both `gl_FragColor' and `webgl_SecondaryFragColor'
```

**Comment by Lunarequest** [comment]
I've had similar output when my nvidia driver updated. Maybe  its the same for you? You could try disabling gpu bug workarounds?

**Comment by sabrehagen** [comment]
> I've had similar output when my nvidia driver updated. Maybe its the same for you? You could try disabling gpu bug workarounds?

Yes, using `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1 github-desktop` worked. Thank you!

**Comment by shiftkey** [comment]
Closing this out as things appear to be stable, and I suspect folks are fine to open fresh issues for whatever support questions they have
