### ISSUE TITLE
 The file directory is opened behind the application when launched

### ISSUE THREAD

**Issue by md-shamim-ahmad** [shiftkey/desktop#906]
### The problem

When I click on the choose  button for add an existing repository 
![vlcsnap-2023-07-13-22h21m40s239](https://github.com/desktop/desktop/assets/56692841/34337c16-e923-4597-8b0b-69e59ded354f)
But the file directory was opened behind the ```github desktop``` like this
![vlcsnap-2023-07-13-22h21m48s873](https://github.com/desktop/desktop/assets/56692841/40a89958-1ef8-4401-92de-4e7a89d29457)

### Release version

GitHubDesktop-linux-3.2.5

### Operating system

Ubuntu 22.04.2

### Screenshots

Here I have added a video to further clarify

https://github.com/desktop/desktop/assets/56692841/6e530f2d-a2e3-4d7b-9fa3-d4e54ecbb0d8

**Comment by shiftkey** [comment]
I've been able to see this myself with the latest version, but I haven't tested the pre-release installer - there might be a fix in a newer version of Electron but it's a low-priority bug for me currently to dig into...

**Comment by shiftkey** [comment]
I've also been able to reproduce this on the upcoming release, so I suspect this is a regression with Electron that might have been fixed in an update. Will need to investigate further.

**Comment by shiftkey** [comment]
This is an upstream issue with Electron that is being tracked and discussed here https://github.com/electron/electron/issues/32857

**Comment by shiftkey** [comment]
Closing this out as this is not something that I believe can be fixed here. If an Electron release lands with a fix for this I'm happy to explore updating to that version in the future.
