### ISSUE TITLE
The same code is a github changes

### ISSUE THREAD

**Issue by nicitaacom** [shiftkey/desktop#908]
### The problem

I have the same code and it shows me it as chanhes
![image](https://github.com/shiftkey/desktop/assets/39565703/e4b747c8-c207-4e62-a9f2-2f6a89d72463)

### Release version

Version 3.2.5-linux1 (x64)

### Operating system

Kali linux

### Steps to reproduce the behavior

idk what causes this error

**Comment by sarim** [comment]
whitespace / line ending character issue probably. run `git diff` in terminal

**Comment by shiftkey** [comment]
Seconding @sarim here, this seems to be a line endings change to the file that Git is reporting

**Comment by nicitaacom** [comment]
I discarded all changes
