### ISSUE TITLE
.gitignore not working

### ISSUE THREAD

**Issue by tct123** [shiftkey/desktop#909]
### The problem

When i try to add something to .gitignore file it doesen't get ignored.

### Release version

3.2.5-linux1

### Operating system

Linux Mint

**Comment by shiftkey** [comment]
> When i try to add something to .gitignore file it doesen't get ignored.

Please provide more details:

 - What file are you trying to ignore?
 - What gitignore rule did you add?
 - Is the file was already committed to the repository?

I suspect the file was part of an existing commit to the repository, and `.gitignore` rules only apply to untracked files in the repository. Removing the file in a commit and then adding the `.gitignore` rule should do the trick here.
