### ISSUE TITLE
unable to discard untracked changes due to gettext dependency

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#91]
## Description

Discard changes silently fails with the latest Snap installer

## Version

* GitHub Desktop: `1.5.0-linux5`
* Operating system: Ubuntu Bionic 18.04

## Steps to Reproduce

1. Ensure you have the "Confirm Discard Changes" option set
2. Find a repository with valid submodules
3. Add a new file to the repository
4. Right-click and discard changes
5. Confirm the action

### Expected Behavior

File is moved to trash, the dialog closes

### Actual Behavior

Nothing happens, with clues in the Dev Tools console

## Additional Information

<img width="555" src="https://user-images.githubusercontent.com/359239/48791466-3022c700-ecc8-11e8-8eda-0bebeec40522.png">

```
`git submodule status --` exited with an unexpected code: 2.
/snap/github-desktop/37/app/resources/app/git/libexec/git-core/git-submodule: 46: .: Can't open /usr/bin/gettext.sh

Uncaught (in promise) d: /snap/github-desktop/37/app/resources/app/git/libexec/git-core/git-submodule: 46: .: Can't open /usr/bin/gettext.sh


    at Object.t.git (file:///snap/github-desktop/37/app/resources/app/renderer.js:5:7311)
    at <anonymous>
```

**Comment by ipkpjersi** [comment]
I was able to replicate this on Ubuntu 16.04.
