### ISSUE TITLE
Crash with parameter `enable-wayland-ime` on Linux

### ISSUE THREAD

**Issue by Bryan2333** [shiftkey/desktop#913]
### The problem

Github desktop crashes once I type using input method.

It was a bug from chromium, but the fix was introduce to electron 24.5.1. See https://releases.electronjs.org/release/v24.5.1 and https://github.com/electron/electron/pull/38711. The current electron version of Github desktop 3.2.7 is 24.4.0, which does not contain the fix. So it is possible to upgrade the electron version? I know it may be annoying for developer to upgrade framework shortly after a new release.

### Release version

3.2.7

### Operating system

Arch Linux

### Steps to reproduce the behavior

1. Open terminal
2. Run command `github-desktop --ozone-platform-hint=auto --enable-wayland-ime`

**Comment by shiftkey** [comment]
> So it is possible to upgrade the electron version? I know it may be annoying for developer to upgrade framework shortly after a new release.


It's fine, I just generally try and stay in sync with the upstream project and they're on that specific version of Electron. A new release with `24.6.5` is being prepared now...

**Comment by shiftkey** [comment]
Fixed in [`3.2.7-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-3.2.7-linux2)
