### ISSUE TITLE
Organization and repositories under organization  are not showing github Linux version

### ISSUE THREAD

**Issue by salmanomayer** [shiftkey/desktop#918]
### The problem

I have created two organization in the github website but is not showing in the linux desktop version. but in the windows version it has no problem. please help me to solve.

### Release version

github 3.2.5

### Operating system

Ubuntu 22

### Screenshots

![Screenshot from 2023-08-23 19-59-29](https://github.com/shiftkey/desktop/assets/13465462/fcb2b0e9-ac90-4668-9104-fa88ff19b475)
![Screenshot from 2023-08-23 20-00-41](https://github.com/shiftkey/desktop/assets/13465462/9ca7136a-751d-4995-a6e7-eef2a8ba37e1)
![image](https://github.com/shiftkey/desktop/assets/13465462/8dd94572-6ca2-44c9-a790-801717ccaa80)

**Comment by shiftkey** [comment]
This is related to the OAuth details currently shipped in the app https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547

There's a workaround available which might work here: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

**Comment by salmanomayer** [comment]
Thanks for your help.
