### ISSUE TITLE
Outline is visible without hovering

### ISSUE THREAD

**Issue by PadowYT2** [shiftkey/desktop#920]
### The problem

The outline is visible without hovering over. This is really painful to look at

### Release version

3.2.7-linux2 (x64)

### Operating system

Zorin OS 16.3 (equivalent to Ubuntu 22.04)

### Screenshots

![https://cdn.padow.ru/sKSeQ](https://cdn.padow.ru/sKSeQ)

### Additional context

I have recently updated GitHub Desktop and it looks like this now

**Comment by shiftkey** [comment]
> The outline is visible without hovering over. 

Are you able to elaborate on which parts of this need to be investigated?

**Comment by PadowYT2** [comment]
> > The outline is visible without hovering over.
> 
> Are you able to elaborate on which parts of this need to be investigated?

![https://cdn.padow.ru/oF74W](https://cdn.padow.ru/oF74W)

I guess every single Button and Input fields

**Comment by PadowYT2** [comment]
@shiftkey?

**Comment by shiftkey** [comment]
This is part of the dark-mode design that is the same on the other platforms, so I'm hesitant to accept changes here without better understanding what we should be doing here. Here's an equivalent screenshot from the latest macOS build:

<img width="980" src="https://github.com/shiftkey/desktop/assets/359239/457c1635-e17a-4515-94a9-9c160776d4e4">

This is a question better asked on the upstream project, but understanding not just a bug report but what we should do here (as well as design suggestions for the look and feel here) would be essential as actionable feedback...

**Comment by PadowYT2** [comment]
> This is part of the dark-mode design that is the same on the other platforms, so I'm hesitant to accept changes here without better understanding what we should be doing here. Here's an equivalent screenshot from the latest macOS build:
> 
> <img alt="" width="980" src="https://user-images.githubusercontent.com/359239/265292501-457c1635-e17a-4515-94a9-9c160776d4e4.png">
> This is a question better asked on the upstream project, but understanding not just a bug report but what we should do here (as well as design suggestions for the look and feel here) would be essential as actionable feedback...

Thought it wasn't intentional as it looked better on older updates, but alright, thanks
