### ISSUE TITLE
System Theme always light

### ISSUE THREAD

**Issue by moritztim** [shiftkey/desktop#932]
### The problem

No matter what theme I set, when I select `System` in appearance, it's always light.

### Release version

Version 3.3.1-linux1 (x64)

### Operating system

Arch Linux GNOME Shell

### Steps to reproduce the behavior

1. Open Settings
2. click `Appearance`
3. select `System`
4. get flashbanged

### Log files

*idk where the log files are and have made another issue cause the show logs button doesn't work (#931)*

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/90388353/5f147e43-540e-44de-a13d-f64f169d44b1)
![image](https://github.com/shiftkey/desktop/assets/90388353/6f45b70d-b713-4737-8ac2-8b860d881929)

**Comment by shiftkey** [comment]
> Arch Linux GNOME Shell

 What version of GNOME are you running? Based on the About dialog I'm on 42.9 which seems to be working as expected:



![Image](https://github.com/shiftkey/desktop/assets/359239/2a2d12f4-8d87-4bc9-8363-a8b24954ca90)



Initially I was able to test this in a different way, with explicit themes - the app detects this and updates while open:

![](https://github.com/shiftkey/desktop/assets/359239/0f7ead6c-2be4-4b60-bb50-3d513268d5ed)

![](https://github.com/shiftkey/desktop/assets/359239/c2e87e84-5c53-4412-820a-0c7b0f729d48)

But this also works for me while I'm on this Appearance menu:

![](https://github.com/shiftkey/desktop/assets/359239/cf212a9a-f0b0-40f8-9749-2c1b73648575)

![Image](https://github.com/shiftkey/desktop/assets/359239/e17b8221-caff-4ca2-a0ec-7700b835aa9c)


I'd have to find the relevant Chromium source again to explain what's happening, but being able to narrow on differences between your setup and mine would be a good first step.

**Comment by moritztim** [comment]
Sorry for my late response, this slipped past me.
![image](https://github.com/shiftkey/desktop/assets/90388353/7889c32a-d90f-4ec7-91b9-8f74d32705dd)

**Comment by shiftkey** [comment]
@shiftkey it looks like https://github.com/electron/electron/pull/38977 might be the necessary fix, which will be in the next releases of the app - this should be in Electron [`v26.2.4`](https://releases.electronjs.org/release/v26.2.4)

**Comment by shiftkey** [comment]
Please re-test with [`3.3.5-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux1) and confirm the PR mentioned above fixes the issue for you.

**Comment by moritztim** [comment]
I'm currently sick but I'll do it when I get back to work

**Comment by moritztim** [comment]
Works!
