### ISSUE TITLE
unable to syncing my git account

### ISSUE THREAD

**Issue by Divya-780** [shiftkey/desktop#933]

**Comment by shiftkey** [comment]
Please provide more details about what you're seeing

**Comment by JustaDeathKnight** [comment]
![image](https://github.com/shiftkey/desktop/assets/15114630/8596632e-bfb3-4b8d-a405-7f580b6e467d)

I can't loggin in my github account, only stay there

**Comment by l3clelVl** [comment]
I am having the same issue. I start by attempting to "Clone a repository" with the "GitHub.com" option. I click "Sign in" 

> ![image](https://github.com/shiftkey/desktop/assets/57275418/b30479d4-0457-4930-8f43-f874ae954388)

then I'm met with a "Sign in using your browser" prompt. I click "Continue with browser"

> ![image](https://github.com/shiftkey/desktop/assets/57275418/8836f90d-b960-452f-a2de-6a3c8ccddd61)

My Browser window opens, I sign in, then it gives me a prompt

> ![image](https://github.com/shiftkey/desktop/assets/57275418/9541718d-a4e4-4e24-85aa-b1bf46b81872)

I check the "Always..." box and click "Open Link", then I'm routed back to the application, but I'm met with a 2 second spinning arrows, then it starts back at the "Sign in" where I'm now in a loop of "Sign in", "Continue with browser", Firefox opens a new tab, then auto routes back to the app, the "Continue with browser" spinning arrows, then back to "Sign in"

> ![image](https://github.com/shiftkey/desktop/assets/57275418/17c9f13d-0118-423a-98dc-12cb036b1cdf)

**Comment by l3clelVl** [comment]
I provided snippets of everything I see. What more detail do you want?
