### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by rs8077259** [shiftkey/desktop#935]
### The feature request

i am unable to find dark mode for the app in my Linux machine 

### Proposed solution

It would be helpful to see a dark theme in app as it feel comfortable on eyes

**Comment by shiftkey** [comment]
This has been available for many releases under **File** | **Options...** and the **Appearance** menu



![](https://github.com/shiftkey/desktop/assets/359239/6a93ae36-afb6-45ed-b67f-178b0eedc9bb)
