### ISSUE TITLE
About GitHub Desktop button is grayed out when not logged in to account

### ISSUE THREAD

**Issue by K0-RR** [shiftkey/desktop#941]
### The problem

I feel like this button should always be available in case someone needs the version number for a bug report.

### Release version

3.3.3

### Operating system

openSUSE Leap 15.4

### Screenshots

![Screenshot_20231011_235222](https://github.com/shiftkey/desktop/assets/43277609/56265608-2e1e-413c-a124-dfb10624727c)

**Comment by shiftkey** [comment]
I can't remember exactly why but I think it's because the welcome wizard is open at the time that this menu item is disabled. If you were to cancel that the menu item would be available.
