### ISSUE TITLE
Terminal and Atom cannot be opened when strict confinement is enabled

### ISSUE THREAD

**Issue by zypA13510** [shiftkey/desktop#95]
## Description
1. "Open in terminal" does not detect `git` installation, and gives an error when selecting "open without git"
![image](https://user-images.githubusercontent.com/8077540/48814864-6c613080-ed77-11e8-8dc8-d2cf78e6d9bb.png)
![image](https://user-images.githubusercontent.com/8077540/48814941-a4687380-ed77-11e8-886c-16578f35f3db.png)

2. "Open in Atom" becomes "open in external editor" and gives an error when clicked:
![image](https://user-images.githubusercontent.com/8077540/48815025-f4dfd100-ed77-11e8-910e-f6d550df67c9.png)

3. This is also evident in File -> Options -> Advanced:
![image](https://user-images.githubusercontent.com/8077540/48815133-49834c00-ed78-11e8-808f-509526a8ebab.png)

## Version
* GitHub Desktop: 1.5.0-linux5 (from snapcraft edge channel)
* Operating system: Ubuntu 18.04.1 LTS

## Steps to Reproduce
1. Install from command line: `snap install --edge github-desktop`
2. Fix #59 : `sudo snap connect github-desktop:password-manager-service`
3. Launch Github Desktop from GNOME
4. Try "open in terminal" and "open in external editor"

### Expected Behavior
Open git project folder in terminal / Open git project folder in Atom

### Actual Behavior
See description above.

**Comment by zypA13510** [comment]
Using 1.5.0-linux3 snap package installed with `--classic --dangerous` switch does not have this issue.

**Comment by shiftkey** [comment]
@zypA13510 this suggests to me that there's some permission missing that we need to request - does anything from [this list](https://forum.snapcraft.io/t/supported-interfaces/7744) stand out to you about launching processes?

**Comment by shiftkey** [comment]
> "Open in terminal" does not detect git installation, and gives an error when selecting "open without git"

This check is running `which git` to see if `git` is available on your PATH. What's interesting about this is I was able to run `which which` to find itself, but `git` would error: 

<img width="867" src="https://user-images.githubusercontent.com/359239/48914480-f67dc780-ee51-11e8-8969-34c33acd71bc.png">

I see that `process.env.PATH` (that should be inherited when you run `which`) does contain `/usr/bin`, which is where it should be:

<img width="831" src="https://user-images.githubusercontent.com/359239/48914883-16fa5180-ee53-11e8-8306-287bb4ac0ecc.png">

And when you try to continue on we try to use the default shell, which uses the same technique, we can't find any, which is this message appears:

![](https://user-images.githubusercontent.com/8077540/48814941-a4687380-ed77-11e8-886c-16578f35f3db.png)

And lastly, we do the same checks for the editor integration on Linux, so if we fix that we'll be able to support this completely. I'm just puzzled whether some sort of isolation is to blame here for hiding the details from the app.

**Comment by zypA13510** [comment]
FYI, I have built a version with all known interfaces enabled (except `content` and `dbus`, both of which requires another snap to provide a slot), and connected them to slots the snap core provides. This issue still exists, so does #98.

After a bit of Googling, I've also come across this question, could be related to this issue: **[/usr/bin/fold got permission denied but /usr/bin/fmt is working fine?](https://forum.snapcraft.io/t/usr-bin-fold-got-permission-denied-but-usr-bin-fmt-is-working-fine-whats-happened/6559)** The consensus seems to be that we shouldn't rely on `/usr/bin` but ship it with the snap if the app requires the binary.

I also wondered why Atom snap doesn't have such issue. Turns out that it isn't using strict confinement: [snapcrafters/atom/master/snap/snapcraft.yaml#L10](https://github.com/snapcrafters/atom/blob/977606321c7e76b6cc94a36e3739c7459ffca218/snap/snapcraft.yaml#L10). Maybe we need to solve this by switching desktop back to classic confinement?

Btw, I'm no expert on snap, so I may be wrong.

**Comment by zypA13510** [comment]
VSCode is also using classic confinement: [Microsoft/vscode/master/resources/linux/snap/snapcraft.yaml#L10](https://github.com/Microsoft/vscode/blob/85f805acf9436381b878cab5ab6c5146beec7893/resources/linux/snap/snapcraft.yaml#L10)

@shiftkey may I open a PR to switch it back to classic confinement?

**Comment by shiftkey** [comment]
With the help of the Snapcraft team, I've now been able to publicize the app again on the Snapcraft store now the enclosures are migrated. It is recommended to install the `beta` channel currently if you are working from a fresh install.

For existing installs the `edge` channel will remain using the `strict` enclosure for the moment, and refreshing to the latest version there will ask you to install the `beta` channel, which is using the `classic` enclosure and requires a manual upgrade:

<img width="929" src="https://user-images.githubusercontent.com/359239/55685440-adc03a00-592c-11e9-830e-32b6f429831d.png">
