### ISSUE TITLE
Does't see files in the dir a symbolic link

### ISSUE THREAD

**Issue by punkochel** [shiftkey/desktop#950]
If I have dir:
`~/MyFiles`
And I have a directory that stores a clone of a repository from github:
`~/Repository`
Then after:
`ln -s ~/MyFiles ~/Repository`
Github Desktop will not see files contained in ~/MyFiles, but will see an empty MyFiles directory.

OS: Ubuntu 22.04.3 LTS 64-bit

**Comment by shiftkey** [comment]
I don't have the bandwidth currently to sit down and reproduce this, so any additional information you have about how this breaks the app would be great.

**Comment by punkochel** [comment]
@shiftkey 
This does not disrupt the operation of the application in any way. It’s just that most likely this point was not taken into account when porting the program to Linux.

**Comment by shiftkey** [comment]
> This does not disrupt the operation of the application in any way. It’s just that most likely this point was not taken into account when porting the program to Linux.

Understanding how this impacts you would be great, as there's a lot of complexity with how the app uses `git` that should work cross-platform.
