### ISSUE TITLE
making changes to theme always asks for restart

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#957]
Spotted while testing `3.3.5` but may be present in previous releases.

Repro steps:

 1. Launch app, open settings
 2. Without making any changes, press **Save**

Expected: no prompt to restart app
Actual: app seems to always ask for restart

Possibly related to https://github.com/shiftkey/desktop/pull/912 but I can't recall seeing this at the time so it might be a new regression.

**Comment by krushnaj** [comment]
I did downgrade to `3.3.3` and it happens on that version too. Will downgrade further to see if it happens on other versions or not.

Tested this on `3.3.1` and it just as you mentioned it happens due to that change.
