### ISSUE TITLE
Not using SSH key when pushing to SSH remote

### ISSUE THREAD

**Issue by zypA13510** [shiftkey/desktop#96]
## Description
In the latest snap package (1.5.0-linux5) from snapcraft edge channel, pushing to ssh repos (self-hosted / other) are rejected:
> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

In previous versions installed with `--classic` switch, GitHub Desktop recognizes ssh keys in `~/.ssh`.

## Version
* GitHub Desktop: 1.5.0-linux5 (from snapcraft edge channel)
* Operating system: Ubuntu 18.04.1 LTS

## Steps to Reproduce
1. Install from command line: `snap install --edge github-desktop`
2. Fix #59 : `sudo snap connect github-desktop:password-manager-service`
3. Launch Github Desktop from GNOME
4. Add a local repository which uses ssh remote and requires ssh key authentication
5. Fetch / push to remote.

### Expected Behavior
Operation completes without error.

### Actual Behavior
An authentication error dialog appears.

### Logs
```
2018-11-21T03:37:30.838Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.162s)
2018-11-21T03:37:30.841Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
```

**Comment by zypA13510** [comment]
Can confirm it is working in 1.5.0-linux3 snap installed with `--classic --dangerous` switch.

**Comment by zypA13510** [comment]
@shiftkey I suppose `ssh-keys` interface needs to be added according to [this list](https://forum.snapcraft.io/t/supported-interfaces/7744)?

**Comment by shiftkey** [comment]
@zypA13510 I guess so. Feel free to submit a PR change to [the electron-builder config](https://github.com/shiftkey/desktop/blob/linux/script/electron-builder-linux.yml) to add it and we can organize a fresh RC

**Comment by zypA13510** [comment]
sure, will try to build and test it tomorrow.

**Comment by zypA13510** [comment]
Nope, it is not as easy as adding `ssh-keys` to the list. It fails nonetheless.

**Comment by shiftkey** [comment]
@zypA13510 did you also `sudo snap connect github-desktop:ssh-keys`? That interface is similar to `password-manager-service` in that you need to connect the app to it explicitly...

**Comment by zypA13510** [comment]
No, I forgot about that. Sorry. Will try it next week, or meanwhile, if anyone interested in testing it, the build is here: https://gitlab.com/zypA13510/desktop/-/jobs/124416195/artifacts/file/dist/GitHubDesktop-linux-1.5.1-beta0.snap
Install with `snap install --dangerous GitHubDesktop-linux-1.5.1-beta0.snap`, connect both interfaces `sudo snap connect github-desktop:ssh-keys` and `sudo snap connect github-desktop:password-manager-service` and launch.

**Comment by zypA13510** [comment]
@shiftkey Yes, that is exactly what I missed. Now that I've connected the interface, SSH remotes are working.
