### ISSUE TITLE
Screen goes to white after loading

### ISSUE THREAD

**Issue by PiperKev** [shiftkey/desktop#960]
### The problem

After the most recent update, the app loads normally but, after a few seconds, the screen goes totally white, leaving only the titlebar visible.  This happens every time I start the program.

### Release version

3.3.5-linux1 (x64)

### Operating system

Linux Mint 21.2

### Steps to reproduce the behavior

Click on the menu button.
Click "Accessories"
Click "Github Desktop"

### Log files

[2023-11-27.desktop..log](https://github.com/shiftkey/desktop/files/13474791/2023-11-27.desktop.log)

### Screenshots

![Screenshot from 2023-11-27 08-16-41](https://github.com/shiftkey/desktop/assets/8465037/0dd68275-de9a-444a-b2dd-7830078f55cf)

**Comment by shiftkey** [comment]
Closing in favour of #958, please follow along with that issue
