### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by jsj19990602** [shiftkey/desktop#964]
### The problem

if i click the github desktop and after a few minutes, it's screen become white

### Release version

3.3.5 and 3.3.4

### Operating system

ubuntu 20.04

**Comment by shiftkey** [comment]
Duplicate of https://github.com/shiftkey/desktop/issues/958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.
