### ISSUE TITLE
Ui disappears shortly after opening

### ISSUE THREAD

**Issue by amarraff** [shiftkey/desktop#966]
### The problem

Today, after I worked on my project and went to commit/push, I noticed the app was blank white. I rebooted the app, and after a few seconds, same thing. I can click on everything in the app like normal until it suddenly goes away. I am using the Flathub version of the app. I tried installing the app package manually from the provided repository here on the github page, but the same thing happens. After a few seconds, blank ui. I tested this on both X11 and Wayland, and the issue persisted on both. Rebooting my pc also did not help. I think this may have been caused by the most recent update, because it was working fine before it.

### Release version

3.3.5-linux1 (x64)

### Operating system

Kubuntu 23.10 x86_64

### Steps to reproduce the behavior

1. Open the github desktop app
2. Wait a few seconds
3. Ui goes blank

### Screenshots

![Screenshot_20231129_165621](https://github.com/shiftkey/desktop/assets/35876526/1d6e1483-7b6a-4579-8e64-56a2cf07cc32)

**Comment by ErikMCM** [comment]
I second this, happening to me as well on Kubuntu 22.04. Using the AppImages provided in the releases, this error begins to occur in version 3.3.4 and up. 

 When launching `github-desktop` from the command line, it logs the following after going blank:
```js
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at B (/usr/lib/github-desktop/resources/app/main.js:2:211769)
    at BrowserWindow.<anonymous> (/usr/lib/github-desktop/resources/app/main.js:2:216310)
    at BrowserWindow.emit (node:events:525:35)
  ```

**Comment by cpknight** [comment]
Same issue here under Pop!_OS 22.04 (Ubuntu derivative) running X11 with Intel generic GPU (Intel Device a7a1). Latest flatpak 3.3.5-linux1. Seems like white screen in Electron apps is pretty common, but I haven't been able to dig into this much yet. 
![image](https://github.com/shiftkey/desktop/assets/1295408/aba17ee2-f4c3-4083-af78-4e0ac0fb5ed9)

**Comment by cpknight** [comment]
Same behaviour using the `.deb.` from [https://apt.packages.shiftkey.dev/](https://apt.packages.shiftkey.dev/) `3.3.5-linux1` **but** downloading the latest `.deb` release from [https://github.com/shiftkey/desktop/releases](https://github.com/shiftkey/desktop/releases) `3.3.5-linux2` and installing that seems to work fine on my system (AMD64). So, fixed once this is pushed out via the distro channels?

**Comment by amarraff** [comment]
Didn't realize this was a duplicate my bad, go here:
https://github.com/shiftkey/desktop/issues/958
