### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by rafikidota** [shiftkey/desktop#967]
### The problem

When I launch the application, the screen goes blank.

### Release version

3.3.5-linux1

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

Launch the app and try to do anything

### Log files

[2023-11-30.desktop..log](https://github.com/shiftkey/desktop/files/13514611/2023-11-30.desktop.log)

### Screenshots

![Captura desde 2023-11-30 10-14-17](https://github.com/shiftkey/desktop/assets/71207415/47f3af69-b501-459d-bd2b-5c9ac417af85)

**Comment by cpknight** [comment]
@rafikidota - This seems to be a duplicate issue to [#967](https://github.com/shiftkey/desktop/issues/966) and may be limited to the `3.3.5-linux1` release - try downloading and installing `3.3.5-linux2` directly from the [releases](https://github.com/shiftkey/desktop/releases) page for now (as the distro networks seem to be still on `3.3.5-linux1`). It worked for me, anyhow.

**Comment by rafikidota** [comment]
@cpknight 3.3.5-linux2 worked for me too, Thanks bro
