### ISSUE TITLE
Screen Goes white after 2 to 3 secs

### ISSUE THREAD

**Issue by mujtabaaliawan** [shiftkey/desktop#970]
### The problem

When i open it, it goes to a blank white screen after two to three secs. I am using linux ubuntu 22.04

### Release version

the latest version available for ubuntu

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

Open github Desktop

### Screenshots

![Screenshot from 2023-12-01 19-25-15](https://github.com/shiftkey/desktop/assets/117171332/7a744396-fda1-4689-8ba9-ad8c2282c775)

**Comment by shiftkey** [comment]
Duplicate of https://github.com/shiftkey/desktop/issues/958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.
