### ISSUE TITLE
IntelliJ Idea Ultimate not supported by editor integration

### ISSUE THREAD

**Issue by Madeindreams** [shiftkey/desktop#978]
### The problem

I am unable to see my IDE in the options.
Under Linux. Using InteliJ Idea Ultimate

### Release version

3.3.5

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

go to file
options
integrations

![image](https://github.com/shiftkey/desktop/assets/17243647/ae0c475d-e046-42af-9036-0c41744e0148)

**Comment by shiftkey** [comment]
> Using InteliJ Idea Ultimate

These are the paths that we know to lookup to find this program

https://github.com/shiftkey/desktop/blob/12668bfca547601d4223d514b096525eff5f592c/app/src/lib/editors/linux.ts#L115

My guess here is that yours is installed somewhere else

**Comment by Madeindreams** [comment]
Humm.

I do not have the idea folder or executable

![image](https://github.com/shiftkey/desktop/assets/17243647/2ca5ad0b-dbcb-4a5c-a0e3-66b64dc1375f)
This is all the file i have in my snap/bin folder

**Comment by shiftkey** [comment]
I gather this `/snap/bin/intellij-idea-ultimate` shortcut is the one that you're using? I'm gonna need more information about your program to understand whether this is just a different version of `/snap/bin/idea` or if it's something different...

**Comment by Madeindreams** [comment]
Is it because it's the ultimate edition?

IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023
Licensed to **********
Subscription is active until November 24, 2024.
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-39-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.copilot (1.4.5.4049)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
Kotlin: 233.11799.300-IJ
Current Desktop: ubuntu:GNOME

**Comment by shiftkey** [comment]
Probably - please read the docs for how this editor integration works https://github.com/shiftkey/desktop/blob/linux/docs/technical/editor-integration.md#linux as we rely on community contributions to get these working

**Comment by Madeindreams** [comment]
OK il make a PR! Thank you for your help.

**Comment by Madeindreams** [comment]
https://github.com/shiftkey/desktop/pull/982

**Comment by shiftkey** [comment]
This is now published in [`3.3.6-linux3`](https://github.com/shiftkey/desktop/releases/tag/release-3.3.6-linux3).
