### ISSUE TITLE
Icon and button style issues with file explorer

### ISSUE THREAD

**Issue by zypA13510** [shiftkey/desktop#98]
## Description
The open dialog in 1.5.0-linux3:
![capture.png](https://user-images.githubusercontent.com/8077540/48930906-63ff2600-ef2e-11e8-8558-7bb4839b24f4.PNG)

The same dialog in 1.5.0-linux5:
![capture](https://user-images.githubusercontent.com/8077540/48930943-91e46a80-ef2e-11e8-9da1-8799b1206630.PNG)

Actually, both have some issues:
1. In RC5, all icons are missing, including file/folder icons, the home icon in the address bar, the magnifying glass on the search button, and those in the left navigation pane.
2. In RC3, the outline of buttons (ok / cancel / search) are missing, and UI elements, e.g. navigation on the left pane, are narrower (height) than they usually are.

## Version
* GitHub Desktop: 1.5.0-linux3 / 1.5.0-linux5 (both using snap installer)
* Operating system: Ubuntu 18.04.1 LTS

## Steps to Reproduce
1. Install GitHub Desktop
2. File -> Add local repository, in the resulting dialog, select "choose" beside the textbox
3. Observe the difference in style of the file explorer dialog.

**Comment by zypA13510** [comment]
Maybe related: snapcrafters/atom#41

**Comment by shiftkey** [comment]
With the help of the Snapcraft team, I've now been able to publicize the app again on the Snapcraft store now the enclosures are migrated. It is recommended to install the `beta` channel currently if you are working from a fresh install.

For existing installs the `edge` channel will remain using the `strict` enclosure for the moment, and refreshing to the latest version there will ask you to install the `beta` channel, which is using the `classic` enclosure and requires a manual upgrade:

<img width="929" src="https://user-images.githubusercontent.com/359239/55685440-adc03a00-592c-11e9-830e-32b6f429831d.png">
