### ISSUE TITLE
Cannot sign into Git

### ISSUE THREAD

**Issue by wingitman** [shiftkey/desktop#986]
### The problem

Whenever I try to login to git, I am taken to a browser, log in sucessfully on the browser, and recieve a popup to open Git Desktop to complete to login there.

However I get this error:
org.freedesktop.secrets was not provided

### Release version

Version 3.3.6-linux3 (x64)

### Operating system

SteamOS 3.5.7 (KDE Plasma version 5.27.5)

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/48458390/4d02ab86-53d1-4c29-9feb-b1d2de870b12)

**Comment by VratislavCZ** [comment]
I can't log in either. User interaction failed, on Linux Mint

**Comment by dragon3025** [comment]
I'm also having this issue.

**Comment by nicolasduarterj** [comment]
Was having the same issue. It's because you don't have anything that implements the Secret Service API. For that you can use GNOME Keyring, Keepassxc or [secret-service](https://github.com/yousefvand/secret-service), which I personally use.

**Comment by shiftkey** [comment]
> Was having the same issue. It's because you don't have anything that implements the Secret Service API. For that you can use GNOME Keyring, Keepassxc or [secret-service](https://github.com/yousefvand/secret-service), which I personally use.

This is the issue. Closing this out as KDE users need to look at an alternative (or install GNOME keyring).

**Comment by sawyermade** [comment]
How do you do that?

**Comment by dragon3025** [comment]
> > Was having the same issue. It's because you don't have anything that implements the Secret Service API. For that you can use GNOME Keyring, Keepassxc or [secret-service](https://github.com/yousefvand/secret-service), which I personally use.
> 
> This is the issue. Closing this out as KDE users need to look at an alternative (or install GNOME keyring).

Hello, could you explain how you do this? I've looked everywhere online and asked in 3 different subs on Reddit, and but found no help, so far. I have Keepassxc and secret-service right now.

**Comment by sawyermade** [comment]
I installed Keepassxc from the package manager, it has a pretty easy to use GUI (check a YouTube video for a Keepassxc GitHub setup tutorial), then run it and minimize/go home and it will run in the background. Then you can open GitHub gui and login and everything. On the steam game mode you can add both apps and do it right from the game mode select screen. It’s a bit of a chore but it works really well once you get it setup in desktop mode. I ended up plugging in a keyboard and mouse to get it setup bc the on screen keyboard and touch controls are terrible for desktop mode.

**Comment by dragon3025** [comment]
> I installed Keepassxc from the package manager, it has a pretty easy to use GUI (check a YouTube video for a Keepassxc GitHub setup tutorial), then run it and minimize/go home and it will run in the background. Then you can open GitHub gui and login and everything. On the steam game mode you can add both apps and do it right from the game mode select screen. It’s a bit of a chore but it works really well once you get it setup in desktop mode. I ended up plugging in a keyboard and mouse to get it setup bc the on screen keyboard and touch controls are terrible for desktop mode.

I tried this and it didn't work. I'll attach some screenshots.

**In Github with Keepassxc minimized:**
![Screenshot_20240921_132054](https://github.com/user-attachments/assets/e0e9889e-411e-46d5-b5e7-8d26fd205b96)
![Screenshot_20240921_132103](https://github.com/user-attachments/assets/97d15ba2-744f-4350-b121-7382f4d69cf2)

**It opened in Google Chrome, I don't know if it would do better in Firefox or how to make it open with Firefox:**
![Screenshot_20240921_132119](https://github.com/user-attachments/assets/9b1453b6-15ac-48f3-9579-8b54dbcf962c)

**Back in Github:**
![Screenshot_20240921_132133](https://github.com/user-attachments/assets/5055f838-7328-448c-885e-1f903666f664)

**Comment by sawyermade** [comment]
Did you create a database and everything in keypass?

**Comment by dragon3025** [comment]
> Did you create a database and everything in keypass?

I created a Database. I don't know what to do after that. I tried making an entry with my Github username and Password in it, but that didn't work.

**Comment by sawyermade** [comment]
I don’t remember exactly what I did, but keypassxc being setup properly was key. I watched a YouTube tutorial about how to set it up in arch Linux and then it worked after. Sorry bud, but I don’t remember all the steps I went through :(

Edit: If it’s working correctly a keypassxc window will pop up and ask if you authorize its use. That’s how you know it’s working.

**Comment by Awooku** [comment]
> > Did you create a database and everything in keypass?
> 
> I created a Database. I don't know what to do after that. I tried making an entry with my Github username and Password in it, but that didn't work.

I don't know if you found a solution yet, but what worked for me was:

- Click the "Settings" icon
- Click on "Secret Service Integration"
- Check the "Enable KeepassXC Freedesktop.org Secret Service Integration"

Next time I went through the sign-in process KeypassXC opened and I followed it's instructions. Everything seems to work for me now.

**Comment by dragon3025** [comment]
> > > Did you create a database and everything in keypass?
> > 
> > 
> > I created a Database. I don't know what to do after that. I tried making an entry with my Github username and Password in it, but that didn't work.
> 
> I don't know if you found a solution yet, but what worked for me was:
> 
> * Click the "Settings" icon
> * Click on "Secret Service Integration"
> * Check the "Enable KeepassXC Freedesktop.org Secret Service Integration"
> 
> Next time I went through the sign-in process KeypassXC opened and I followed it's instructions. Everything seems to work for me now.

Ah thank you, this worked for me.

EDIT: I had to leave Keypassxc running before trying to sign into GitHub in order for it to work.
