### ISSUE TITLE
Can't clone new repositories since i got 2FA

### ISSUE THREAD

**Issue by NitramO-YT** [shiftkey/desktop#988]
### The problem

Can't clone repositories since i got 2FA enabled on my account, it ask me to enter my username and password but when i do it it doesn't work, and ask me again, i tried to sign out and sign in again in options but it still not works!

### Release version

Version 3.3.6-linux3 (x64)

### Operating system

Linux KDE Neon Plasma

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/61696199/a744e05d-84c0-43b8-9aa0-f4e73b6319d1)

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by NitramO-YT** [comment]
> I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

Hi, i looked but i have no logs from around that time :/

```shell
nitramo@nitramo-laptop:~$ ls ~/.config/GitHub\ Desktop/logs/
2024-01-09.desktop..log  2024-01-11.desktop..log  2024-01-15.desktop..log  2024-01-17.desktop..log  2024-01-19.desktop..log  2024-01-30.desktop..log  2024-02-01.desktop..log  2024-02-05.desktop..log
2024-01-10.desktop..log  2024-01-12.desktop..log  2024-01-16.desktop..log  2024-01-18.desktop..log  2024-01-25.desktop..log  2024-01-31.desktop..log  2024-02-02.desktop..log
``` 

I'll try to redo this issue when i can and then send the logs here!

**Comment by shiftkey** [comment]
Please reopen when you have more information
