### ISSUE TITLE
Build dependency missing: g++

### ISSUE THREAD

**Issue by zypA13510** [shiftkey/desktop#99]
## Description
Following the instructions in [docs/contributing/setup.md](https://github.com/shiftkey/desktop/blob/linux/docs/contributing/setup.md#ubuntu-1604), if the dependencies are installed with `--no-install-recommends` switch, `g++` will be missing and the build would fail.

Build log: https://gitlab.com/zypA13510/desktop/-/jobs/124062902

If `gcc` is changed to `g++`, the error would not occur. And since `gcc` is a dependency of `g++`, `gcc` would be installed too.

## Version
[git-9614442f](https://github.com/shiftkey/desktop/blob/9614442fb3b307877c2177e5348a92051ecaec74/docs/contributing/setup.md)

## Steps to Reproduce
1. Pull docker image `ubuntu:xenial`
2. Run inside docker:
```
apt-get update > /dev/null
apt-get install -y --no-install-recommends ca-certificates curl git gnupg > /dev/null
curl -sLS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb http://deb.nodesource.com/node_8.x xenial main' > /etc/apt/sources.list.d/nodesource.list
curl -sLS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb http://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
apt-get update > /dev/null
apt-get install -y --no-install-recommends nodejs gcc make libsecret-1-dev yarn > /dev/null
yarn install --force
```

### Expected Behavior
`yarn install` finish without error

### Actual Behavior
`make: g++: Command not found`

### Logs
```
$ yarn install --force
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Rebuilding all packages...
success Saved lockfile.
$ ts-node -P script/tsconfig.json script/post-install.ts
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
error /builds/zypA13510/desktop/app/node_modules/registry-js: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /builds/zypA13510/desktop/app/node_modules/registry-js
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | linux | x64
gyp http GET https://atom.io/download/electron/v2.0.13/iojs-v2.0.13.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.13/iojs-v2.0.13.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.13/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.13/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/builds/zypA13510/desktop/app/node_modules/registry-js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/iojs-2.0.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/iojs-2.0.13',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/iojs-2.0.13/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/builds/zypA13510/desktop/app/node_modules/registry-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/builds/zypA13510/desktop/app/node_modules/registry-js/build'
  SOLINK_MODULE(target) Release/obj.target/registry.node
make: g++: Command not found
registry.target.mk:22: recipe for target 'Release/obj.target/registry.node' failed
make: Leaving directory '/builds/zypA13510/desktop/app/node_modules/registry-js/build'
make: *** [Release/obj.target/registry.node] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.48-coreos-r2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /builds/zypA13510/desktop/app/node_modules/registry-js
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by zypA13510** [comment]
Also, `git` with version 2.8.0 or above seems to be required for running `yarn test:setup`. Otherwise, an error will be thrown:
```
Error: Command failed: git config -l --show-origin
error: unknown option `show-origin'
```

However, both xenial (Ubuntu 16.04) and jessie (Debian 8) does not offer official `git` package versioned higher than 2.8.0 (including backports).

I'm not sure if the test script is intended to be part of the test process, because otherwise, we cannot run it on Ubuntu 16.04.

**Comment by shiftkey** [comment]
@zypA13510 thanks for digging into this. I was just [refreshing this doc](https://github.com/desktop/desktop/blob/update-setup-guides/docs/contributing/setup-linux.md) yesterday, so this is a great help to remember some things I overlooked.

I've updated the Node instructions to defer to the [Nodesource repository](https://github.com/nodesource/distributions/) rather than include the explicit commands to run, and from memory the last time I did this I also had to do this:

```shellsession
# use `sudo` on Ubuntu or run this as root on debian
apt-get install -y build-essential
```

Could you try testing that package instead of an explicit `gcc` or `g++` and see if that fixes the issue for you? I'm going to re-run through the new setup guide on some flavour of Ubuntu today and confirm that is all I need to do, and add something to our new section about needing to build native modules too.

> However, both xenial (Ubuntu 16.04) and jessie (Debian 8) does not offer official git package versioned higher than 2.8.0 (including backports).

This is a great point. I guess we need to link to the [`git-core` PPA](https://launchpad.net/~git-core/+archive/ubuntu/ppa) in the docs as they ship an up-to-date Git for everything after Trusty:

```shellsession
$ sudo add-apt-repository ppa:git-core/ppa
$ sudo apt-get update
```

**Comment by shiftkey** [comment]
I think https://github.com/desktop/desktop/pull/6269 should address the Node native module issue.

The Git PPA thing isn't required for typical Desktop contributions (it was designed for helping troubleshoot some CI environments in the past) so I'm going to leave it as is - most contributors will typically run `yarn test`.

**Comment by zypA13510** [comment]
> ```
> # use `sudo` on Ubuntu or run this as root on debian
> apt-get install -y build-essential
> ```
> 
> Could you try testing that package instead of an explicit `gcc` or `g++` and see if that fixes the issue for you? I'm going to re-run through the new setup guide on some flavour of Ubuntu today and confirm that is all I need to do, and add something to our new section about needing to build native modules too.

Confirm it works. According to apt, installing `build-essential` package will install a combination of `gcc`, `g++` and `make`
```
$ apt-cache depends build-essential
build-essential
 |Depends: libc6-dev
  Depends: <libc-dev>
    libc6-dev
  Depends: gcc
  Depends: g++
  Depends: make
    make-guile
  Depends: dpkg-dev
```

`rpm` seems to be missing from the new doc. Is this intentional? Because the package script does not fail and terminate but output an error, I'm guessing that your reason is people who doesn't have `rpm` installed probably doesn't want the rpm package anyway.
