### ISSUE TITLE
Can't clone repositories from my organisation

### ISSUE THREAD

**Issue by BulletStormXT** [shiftkey/desktop#991]
### The problem

If I want to clone a repository from an organisation, I get prompted to type in my Username and Password. When filled and comfirmed, the window pops up again.

### Release version

3.3.6-linux3 x64

### Operating system

ZorinOS 17 Pro (Ubuntu)

### Screenshots

![Bildschirmfoto vom 2024-01-11 23-42-25](https://github.com/shiftkey/desktop/assets/65316643/f6697fa7-4680-4614-b1cc-517081cf6064)

### Additional context

In the Windows-Version of Github Desktop is that window never popped up.
Sorry for my bad english :laughing:

**Comment by MingTheNoob** [comment]
I have been experiencing the same issue when trying to use it with another GitHub account that has access to other repos. With this current account that I write this with, the desktop app works perfectly fine with no issues. Any other accounts I try with will have access to private organisation repos disabled, giving the same auth error you show here.

The only thing that makes sense is this account was connected properly to GitHub and permissions were given properly as well. On any new account the permissions are not given properly to the organisation and you therefore cannot clone private organisation repos. I am able to clone a private personal repo as the permissions for access to my personal account work fine. 

I have only found one solution, which is not ideal at all but the only thing that worked for me is to disable "Third Party Application Access Restrictions" under the OAuth section of the settings of the organisation in question. With this off, the GitHub desktop app seems able again to work with private repos in an organisation. 

This solution will work fine for me for now as I am the only one in the organisation, but as other members join and restriction needs to be reenabled, I will need another solution.

**Comment by BulletStormXT** [comment]
Also. This Github-Destop version is made by shiftkey, also not from GitHub itself. So it is a third-party-App.
