### ISSUE TITLE
Select folder window shows up under the main window

### ISSUE THREAD

**Issue by masecla22** [shiftkey/desktop#992]
### The problem

When clicking on a file browser button the file picker shows up under the main window.

![image](https://github.com/shiftkey/desktop/assets/21177004/12f8cd59-f6ef-4e4b-be38-fea79f5ef0a5)
![image](https://github.com/shiftkey/desktop/assets/21177004/6e6cb869-594a-4354-9170-f19f98447bf5)
^ this shows up under the main window. 

I've also gone ahead and compiled and ran a dev build from the official Desktop repository, and the issue is not present. 

### Release version

Version 3.3.6-linux3 (x64)

### Operating system

Kubuntu 22.04.3 LTS x86_64 - 6.2.0-39-generic

### Steps to reproduce the behavior

1. Click on Add (inside of repository list)
2. Click on "Add Existing Repository" 
3. Click on "Choose" 
4. Window shows up under Main Window

### Log files

[2024-01-14.desktop..log](https://github.com/shiftkey/desktop/files/13931299/2024-01-14.desktop.log)
[2024-01-14.desktop.production.log](https://github.com/shiftkey/desktop/files/13931300/2024-01-14.desktop.production.log)

Nothing in the logs shows up regarding this, though I have uploaded them anyways.

**Comment by shiftkey** [comment]
Unfortunately this is an upstream Electron issue. #906 has more context but https://github.com/electron/electron/issues/32857 is the one that we need to follow.
