### ISSUE TITLE
Creating a branch while `Open branch with GitHub Desktop` is selected does not work as expected

### ISSUE THREAD

**Issue by J43fura** [shiftkey/desktop#994]
### The problem

When creating a branch while `Open branch with GitHub Desktop` is selected, it does not work as expected, and asks the user to Clone instead of directly switching to that branch.
Update: This happens only while doing this from inside of a GitHub project.
![Github-Branch-Error](https://github.com/desktop/desktop/assets/73950268/26713fb4-d876-4f90-99e2-239f99e6d2ac)

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

1. On the browser in an issue inside of a Project, click on `Development` & click `create a branch`
2. Select `Open branch with GitHub Desktop`
3. Unexpected behavior
![Github-Branch-Error](https://github.com/desktop/desktop/assets/73950268/26713fb4-d876-4f90-99e2-239f99e6d2ac)

### Screenshots

![image](https://github.com/desktop/desktop/assets/73950268/f320eaf4-0f68-45a5-b75a-f4a328c883bd)
![image](https://github.com/desktop/desktop/assets/73950268/32c35c5f-4378-42d4-b025-348bfc63b4b5)
![Github-Branch-Error](https://github.com/desktop/desktop/assets/73950268/26713fb4-d876-4f90-99e2-239f99e6d2ac)

### Additional context

I started getting this today and this happens only while doing this inside of a GitHub project. 
I also noticed the UI has changed on the browser's Github in the right panel of a  Project's issue. Not sure if related

**Comment by shiftkey** [comment]
A couple of questions:

 - does the repository exist in GitHub Desktop? I wonder if it's showing this dialog because it can't find it locally
 - What are the remotes for this repository locally? I can see a double `https://https://` in the path which makes me wonder if there's a bug on the server which has caused the client to break.

**Comment by shiftkey** [comment]
Yeah, there's a bug here with the `https://https://` being duplicated here:

<img width="591" src="https://github.com/shiftkey/desktop/assets/359239/5ddfba57-244d-47ab-86b3-725c43dfd05b">

I don't want to workaround this on the client, so I need to find the team responsible for the server-side change and chase up a fix

**Comment by J43fura** [comment]
> * does the repository exist in GitHub Desktop? I wonder if it's showing this dialog because it can't find it locally

- Yes (It also was working fine yesterday)

> * What are the remotes for this repository locally? I can see a double `https://https://` in the path which makes me wonder if there's a bug on the server which has caused the client to break.
- Glad you quickly found the server-side bug because i didn't quite understand the question 🤣

**Comment by shiftkey** [comment]
Closing this out as a fix has been deployed which should resolve this. Thanks for the report @J43fura!

**Comment by J43fura** [comment]
Hello @shiftkey :wave:,
:cactus: Now it just opens the GitHub Desktop app window, but does not switch to the branch at all.
